### ISSUE TITLE
Actions Buttons Position & Rework

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/kestra#1003]
### Feature description

The buttons on the bottom right are not visible enough and can be hard to find. Those are the new UI/UX optimization to make them more visible for the user and to simplify actions in Kestra's interface

*- in the /ui/flows Add a bulk action to selected flow + Add the buttons:  
<img width="752" alt="image" src="https://user-images.githubusercontent.com/125883179/220370084-77342e4f-f027-4daa-9ecf-f30db5671076.png">

*- When sticky Only keep buttons not tabs: 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/125883179/220371605-0c74fed9-7859-4182-98de-86ad0e6762dd.png">

*- In the /ui/flows/edit/name-space/flow-id: Delete the execute Tab, add on every tab the buttons:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/125883179/220370929-a09f5c74-8407-40dd-890e-f8a49dcf2526.png">

- Rename HOME to Dashboard in the menu and breadcrumb.

-Change the picto used for Home with the new "Dashboard" Picto:
<img width="104" alt="image" src="https://user-images.githubusercontent.com/125883179/220373728-b2117dd4-1bd4-4462-bb93-e487703cd9a4.png">

Thanks!

**Comment by tchiotludo** [comment]
https://user-images.githubusercontent.com/2064609/220459203-0173fa15-2e56-455b-af58-168a080e6908.mp4


First try don't look so nice, seems to be worst than now, we need to properly think that

**Comment by Ben8t** [comment]
@Nico-Kestra - looking for some design/proposal here :)

**Comment by Ben8t** [comment]
splitted in two issues #1333 & #1334
