### ISSUE TITLE
Monaco editor failed to display tooltip that concern code on the top

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1018]
![image](https://user-images.githubusercontent.com/2064609/221300341-374f4dbd-b248-436b-82d0-23ef11cec7c1.png)

**Comment by anna-geller** [comment]
seems no longer an issue with the new tabs/editor design 

![image](https://github.com/kestra-io/kestra/assets/86264395/5d8d1975-c0c4-463a-933b-59b676faeac9)
