### ISSUE TITLE
Analyse Queue usage on JDBC 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1034]
The queue size can grow depending on the workload, specially when a lot of logs. 
The [purge](https://kestra.io/docs/administrator-guide/configuration/databases/#kestra-jdbc-cleaner)  can reduce the amount of data but can be a pain to manage since the purge is globally (all type have the same config), maybe we can do a fine grained purge

**Comment by anna-geller** [comment]
> maybe we can do a fine grained purge

it seems that in 0.18 this has been done. @tchiotludo please reopen if not https://kestra.io/blogs/2024-08-06-release-0-18#new-improved-purge-process
