### ISSUE TITLE
Provide a task to debug a flow

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1054]
### Feature description

Provide a task to debug the flow by logging the current execution context.

```yaml
id: debug
type: io.kestra.core.task.debug.Debug
```

This will log all execution context variables.
We can propose multiple format like a full JSON or a hierarchical _ascii_ view.

Example of a hierarchical view:
 ```
 value1
   - subvalue 1
      - subsubvalue1
 value2
   - subvalue2
 ```

**Comment by anna-geller** [comment]
great idea! for the naming - perhaps something more explicit: `LogExecutionContext`?

**Comment by anna-geller** [comment]
closing in favor of a more generic `{{ context }}` expression that will be done as part of https://github.com/kestra-io/kestra/issues/1279 and will also be available in python script tasks via context object https://github.com/kestra-io/libs/issues/4 (to avoid having 2 features that do the same - the pebble context expression and the task)

background discussion:
![image](https://github.com/kestra-io/kestra/assets/86264395/27c7b2e2-e49e-4bfa-8f88-10c29db781ee)
