### ISSUE TITLE
Flow list : allow to filter execution based on status directly on flow list

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#107]
we are displaying usefull stats on flow list page. 

![image](https://user-images.githubusercontent.com/2064609/79745786-3546d400-8309-11ea-84f6-389730e897bf.png)

It can be really useful to have a link directly on execution from this charts.
* The lowest effort will be to go to execution filter for current date.
* The best one will be to allow to go on execution filter for current date **and** status.

**Comment by eregnier** [comment]
@tchiotludo it's good for this version.
Going a step beyond will be done in issue https://github.com/kestra-io/kestra/issues/124
