### ISSUE TITLE
Execution sort error

### ISSUE THREAD

**Issue by cuiweining** [kestra-io/kestra#1072]
### Expected Behavior

![image](https://user-images.githubusercontent.com/44800439/225796256-234a2625-bd77-414d-9cb5-271bd4360cd0.png)
Internal server error: SQL [select *, count(*) over () as "total_count" from (select "value" from executions where "deleted" = ? order by "id" desc) as "page" where true offset ? rows fetch next ? rows only]; ERROR: column "id" does not exist Position: 112

### Actual Behaviour

Create a pause Executions and check whether the executions are restarted after being deleted. After the executions are deleted, an error is reported when the executions list is sorted by ID.

### Steps To Reproduce

1, create pause flow
2, delete pause Executions
3, create pause Executions
4, Executions page id sort

### Environment Information

- Kestra Version: 0.8.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes): Kubernetes
- Java Version (If not docker): 1.8

**Comment by loicmathieu** [comment]
Hi @cuiweining thanks for reporting.
I tested it and in fact it is not linked to the pause task or an execution deletion but sorting on the `id` field didn't work at all.
I'll look at it.

**Comment by loicmathieu** [comment]
@cuiweining the bug is fixed and is available on the new 0.8.0-SNAPSHOT that was published minutes ago and should be available if you use our `develop-full` Docker image.
You can try it and provides feedback if any.
