### ISSUE TITLE
Can't trigger autocompletion modal on MacOS

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1080]
### Expected Behavior

Hit ⌘ + Space when the suggestion modal is off should trigger the modal back and get autocompletion back again

### Actual Behaviour

Hitting the given shortcut is not working on my side and it does nothing

### Steps To Reproduce

- Start typing a task
- When it comes to writing the type, just write "type: " then hit escape to put the autocomplete modal OFF
- Try to hit ⌘ + Space => Nothing is happening

### Environment Information

- Kestra Version: 0.8.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes): MacOS

### Example flow

Any flow

**Comment by brian-mulier-p** [comment]
I don't know if it's related to my own MAC shortcut (although I couldn't find any shortcut conflicting).
I managed to get something working using this

monaco.editor.addKeybindingRule(
    {
        keybinding:  monaco.KeyMod.CtrlCmd | monaco.KeyCode.Space,
        command: "editor.action.triggerSuggest"
    }
)

Going to make a PR, feel free to challenge it if you think it is related to my environment but I can't get why it isn't working.
Also, I checked Monaco Editor for any clue but didn't manage to find anything related

**Comment by tchiotludo** [comment]
you can create a PR, you are not the only one I think, I already have some report about that in the past :rocket:

**Comment by brian-mulier-p** [comment]
Done !
