### ISSUE TITLE
Cannot add cases in Switch task if no cases are defined

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1090]
### Expected Behavior

When I am in a Switch task and have only one case,
If I click on the minus button to delete this case, I should be able to create a new one.

### Actual Behaviour

When I am in a Switch task and have only one case,
If I click on the minus button to delete this case, I can not create new cases.

### Environment Information

- Kestra Version: 0.8.0-SNAPSHOT

### Example flow

![image](https://user-images.githubusercontent.com/37600690/226626063-3b9411d8-aa1a-4a0d-b713-2ec775e15df3.png)

**Comment by MilosPaunovic** [comment]
This seems fixed, as per attached video. Can you try it out again @Skraye and close if it's good, or point me in the right direction if I went in the wrong one?

[Screencast from 2024-09-05 12-14-34.webm](https://github.com/user-attachments/assets/a474d3ad-47fb-4dd8-9a66-245779a888a8)

**Comment by Skraye** [comment]
Work on my side, can be closed !
