### ISSUE TITLE
Error message when saving a flow is not clear

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1097]
### Expected Behavior

When I save a flow containing a task with missing required properties, the error should send me back the task's ID in the error message.

### Actual Behaviour

When I save a flow containing a task with missing required properties, I get a path that can be complicated to understand.

Nested tasks make the message worst : 
![image](https://user-images.githubusercontent.com/37600690/226948536-01638983-d7f4-457e-82fc-f8b3f441070d.png)

### Environment Information

- Kestra Version: 0.8.0-SNAPSHOT

**Comment by anna-geller** [comment]
this is an old issue and @tchiotludo improved the error messages in 0.17.0 - I'll close for now
