### ISSUE TITLE
Better display on namespace select

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1124]
for now the select namespace is fixed width, if the namespace is long, only the beginning is displayed :
![image](https://user-images.githubusercontent.com/2064609/229378460-dcdcb8da-943d-4da2-9107-f6a1e074c4b0.png)

but in fact the most important part is at end most of the time, we need to find a proper way to handle that

**Comment by loicmathieu** [comment]
Align right seems odd to me.
Mayeb we can increase the size ?
Byt the way, we use a lot "package-like" namespace as we are dev but not everyone does this so maybe it's not a very common issue to have long namespaces.

**Comment by Ben8t** [comment]
Agree on the "package-like" naming - very Java like
As you mention, maybe just increasing the size could do the trick 🤔

**Comment by tchiotludo** [comment]
increase size is not responsive ;) this is how it was done before and break on every small screen

**Comment by Skraye** [comment]
@tchiotludo Using flex must be responsive as the size will adapt to the screen ?

**Comment by anna-geller** [comment]
it seems we are able to display super long namespace names just fine after recent UI changes 

![image](https://github.com/kestra-io/kestra/assets/86264395/563b2e01-311b-4039-95aa-98f97b404751)

![image](https://github.com/kestra-io/kestra/assets/86264395/bde652e6-9c64-4e09-8284-a93e7fe28603)

@tchiotludo please reopen if you think this is still relevant
