### ISSUE TITLE
Add/Improve error message while changing a flow namespace

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1152]
### Feature description

As a **non-developer**

I created a **first flow with my first idea**

But I wanted to **change the namespace**

As a result, **I encountered multiple “Page not found” before understanding that it wasn’t possible**

So I end up **duplicating the flow and deleting the initial one**

*What would have helped?*

→ An error notification.

**Comment by Ben8t** [comment]
Would it be better to add the possibility to change a flow's namespace ? @tchiotludo

**Comment by Ben8t** [comment]
https://github.com/kestra-io/kestra/issues/60

**Comment by tchiotludo** [comment]
Reopen it to avoid the not found right now, that will be easy to fix
