### ISSUE TITLE
Not friendly error message while saving a wrong flow

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1154]
### Feature description

As a beginner

When I tried to save my first flow, it failed.

But I couldn't understand the error message to solve my problem (the message shows some Java artifacts).

So I must copy/paste a code snippet from the documentation and compare line by line where are the differences.

For example, the following error message could be shorter or more straighforward (hard to understand for a beginner, more over if not used to Java)

![image](https://user-images.githubusercontent.com/46634684/231512125-4a09b438-27c0-4036-a602-2bc3383f9014.png)

**Comment by Skraye** [comment]
Could you share a screen of the error message which does not seems clear enough?

**Comment by Ben8t** [comment]
On this one, maybe we could still keep the Java exception ("Message" part in the screenshot above) and just put a generic error as the main message if possible.

**Comment by loicmathieu** [comment]
Or hide the complex message / stacktrace in a detail pane hidden by default with a  caret to show it
