### ISSUE TITLE
⭐ Add a flow metrics dashboard tab

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1155]
### Feature description

Kestra 0.8.0 brings a separate metric storage, thanks to this we can now query metrics on a flow basis and not only on an execution basis.

This allows to provides a metrics dashboard for a Flow for ex to graph a metric value for a period of time.

The idea is to:
- Add a new **Metrics** tab on the **Flow page**
- Allow to select a metric by its name
- Graph the metric value

If a metric is emitted by one of the __Each__ task, we should add multiple metric series in the same graph.

**Comment by Ben8t** [comment]
Very nice feature idea !!!
Definitely a lot of use cases (first one in my mind is for data scientists/ml engineers who need to track experiments, model performances, etc... like [MLFlow features](https://mlflow.org/) for instance)
