### ISSUE TITLE
Get dbt models granularity in topology

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1164]
### Feature description

In topology : in a dbt run we can't get a model granularity view
We see some metadata after an execution in the Gantt chart, but we can't do anything with it. 

Could it be possible to get a broader view of all dbt models ? (examples [1](https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/part-four), [2](https://www.astronomer.io/blog/airflow-dbt-2/))

![image](https://user-images.githubusercontent.com/46634684/231775520-3962cdca-a9cd-4fd6-82d8-dc103f7f240e.png)

**Comment by anna-geller** [comment]
issue in the wrong repo (should be on the dbt plugin repo)

Follow for updates on this issue: https://github.com/kestra-io/plugin-dbt/issues/38
