### ISSUE TITLE
Bad namespace hyphenation (in table)

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1167]
### Issue description

Namespace should be clearer in table - break line at each point ?

![image](https://user-images.githubusercontent.com/46634684/231785604-f479b6e0-a2e2-492d-adfe-83bc0b202b3b.png)

**Comment by tchiotludo** [comment]
@brian-mulier-p if you replace the . with that white space unicode I think it will do the trick
```js
text.replaceAll('.' '&#x200B;.')
```

**Comment by brian-mulier-p** [comment]
Imma try that, thanks :)
