### ISSUE TITLE
Add a search bar to the Error logs on the main Dashboard to search for specific logs (it might be EE-only feature if it needs Elastic)

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1168]
### Feature description

Maybe adding more filters capabilities ?

![image](https://user-images.githubusercontent.com/46634684/231787983-20ebf880-cbaa-41f2-b457-f83a507909d7.png)

**Comment by anna-geller** [comment]
closing as this chart is no longer present in the new dashboard (due to performance on JDBC), going to the Logs page and filtering for ERROR gives the same view
