### ISSUE TITLE
Improve default documentation page in Editor view

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1178]
### Feature description

When opening the editor the right panel with documentation is empty - we should display at least a text and list available plugins (+ their doc)
UPDATE : see figma link below

**Comment by Ben8t** [comment]
https://www.figma.com/file/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?type=design&node-id=829-4038&t=E5LIrpsasZeTriSK-0

**Comment by anna-geller** [comment]
now handled with the flow/task properties documentation

![image](https://github.com/kestra-io/kestra/assets/86264395/28037d96-4572-4361-be70-2057dae895fb)
