### ISSUE TITLE
Display new version on the ui

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1188]
### Feature description

It would be interesting to have the visible version number and especially a visible link to update it if it was not up to date.

Ideally at the top right of the UI !

<img width="249" alt="Screenshot 2023-04-24 at 12 01 25" src="https://user-images.githubusercontent.com/46634684/233964965-09b9de0f-1dc7-4e5a-a5a2-d7a13688c10b.png">

**Comment by Nico-Kestra** [comment]
<img width="1718" alt="Capture d’écran 2023-05-19 à 10 19 57" src="https://github.com/kestra-io/kestra/assets/125994028/a341c7fa-2492-41d3-913e-fc1f78437953">
[Figma link](https://www.figma.com/file/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?type=design&node-id=829%3A4038&t=LkChqhww36cq4mBn-1)
