### ISSUE TITLE
Add Databricks plugin integration

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1215]
### Feature description

A lot of users and companies are using Databrick platform, we should definitely provide such plugin !

**Comment by loicmathieu** [comment]
There is also a JDBC driver so query Databricks via an SQL request.
@anna-geller do you think it's worth creating a task for it ?
https://www.databricks.com/spark/jdbc-drivers-download

**Comment by loicmathieu** [comment]
The Java SDK is experimental but we may be able to create a Job easily with it, see https://docs.databricks.com/dev-tools/sdk-java.html

**Comment by anna-geller** [comment]
for sure, great idea @loicmathieu!
