### ISSUE TITLE
Low code failed to open subobject

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1236]
![image](https://user-images.githubusercontent.com/2064609/236322787-d5c002ee-30e3-4d7e-a130-53d38685c3e1.png)

**Comment by Skraye** [comment]
@tchiotludo precise the flow pls

**Comment by tchiotludo** [comment]
https://demo.kestra.io/ui/flows/edit/io.kestra.demo.scripts/bash-docker-with-files/editor
