### ISSUE TITLE
Bug in Guided Tour

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1238]
### Expected Behavior

Guided tour should be straightforward without any bugs

### Actual Behaviour

There is a bug on Step 8 in the Guided Tour, the modal window goes on bottom left, the user can't access it

![image](https://user-images.githubusercontent.com/46634684/236453828-47bdab89-614c-48fa-8821-49fe1ca1b816.png)

Browser : chrome, macOS

### Environment Information

- Kestra Version: 0.8.1
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

**Comment by Skraye** [comment]
Link to https://github.com/kestra-io/kestra/issues/1249

**Comment by anna-geller** [comment]
done in https://github.com/kestra-io/kestra/pull/2472
