### ISSUE TITLE
Add flow selection in execution list

### ISSUE THREAD

**Issue by eregnier** [kestra-io/kestra#124]
Using a "select 2" component the flow selection should
* display all flows when no namespace is selected
* display only flows for selected namespace
* autocompletion ?

It is a complementary tool to free search field.

any other suggestions @tchiotludo

**Comment by eregnier** [comment]
do we still want this @tchiotludo ? this is also a bit unclear now to me.

**Comment by tchiotludo** [comment]
I think we can close this one and think a proper way to have a lot of filters
