### ISSUE TITLE
Deleted flow led to a 404 on execution page

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1243]
And it's seems that revision is not passed on call from this page

**Comment by Ben8t** [comment]
Can't reproduce on my side (either from Flow page or Revision tab 🤔). Do you have any steps to reproduce ?

**Comment by tchiotludo** [comment]
on the execution page, execute a flow, delete the flow and go back on the execution page of this deleted flow.

**Comment by Ben8t** [comment]
indeed

![image](https://github.com/kestra-io/kestra/assets/46634684/8c567b39-e21c-424e-a362-0442b75f57ce)
![image](https://github.com/kestra-io/kestra/assets/46634684/edf8af5c-33be-426a-9bcf-6f1a9e6b9b15)
