### ISSUE TITLE
Variables rendering escaping 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1244]
We have some documentation to [allow espace](http://localhost:3001/docs/developer-guide/variables/tag/verbatim) of `{{` if you have a templating engine behind the scene on the properties.

This one don't work since we have a recursive rendering that would inhibit the [variable rendering](https://github.com/kestra-io/kestra/blob/fea0e56715b8c76b67d319a479344592c067771e/core/src/main/java/io/kestra/core/runners/VariableRenderer.java#L91). 

We need to introduce a proper ways to allow escaping `{{`
We could choose: 
- `{ { Location } }`
- `{% raw %}{{ Location }}{% endraw %}`: don't think we are able since the verbatim tag is implemented on the raw parser
- `{\{ Location }}`

**Comment by loicmathieu** [comment]
Usually escape caracter comes first so can we have `\{{ Location }}` instead ?

Note that `{{ "{{" }}Location{{ "}}" }}` should also work or we should fix our Verbatim support https://pebbletemplates.io/wiki/tag/verbatim/

**Comment by tchiotludo** [comment]
@loicmathieu I don't think `\{{ Location }}` can be used since the parser will see the `{{` and we are done.

**Comment by loicmathieu** [comment]
@tchiotludo unfortunately yes, not possible. I propose this before I discover that we recursively render the expression so we cannot do anything to avoid rendering. See my proposed fix after I try everything I can think of.
