### ISSUE TITLE
Topology Dependancies - expand to task level

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1251]
### Feature description

For now the dependancies view is only at the flow level. It would great to be able to expand the view to the task level (of each flow).

![image](https://github.com/kestra-io/kestra/assets/46634684/86814975-073e-4243-8439-49cdfc42ef70)

![image](https://github.com/kestra-io/kestra/assets/46634684/25edb4ea-31f3-4185-aa8d-a2afa698e22d)

Probably linked to https://github.com/kestra-io/kestra/issues/774

**Comment by anna-geller** [comment]
as far as I remember, we discussed in the team and there was a consensus that:
1. for subflow, it's already possible to expand/collapse tasks of a child flow
2. for flow dependencies via triggers, this might not be desirable, as in theory, a flow event trigger is meant for decoupled work (exchanging events), so it might not always be desirable to allow other consumers to see the internals of the flow (only to trigger it)

no strong preference here, if you see a customer request to add this, please reopen and we'll add it 👍
