### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1257]
### Expected Behavior

Tests should be stable and should either pass or fail all the time on a given commit

### Actual Behaviour

Some tests are flaky and result in a non-stable build and having to relaunch these all over.

### Steps To Reproduce

Run any test

### Environment Information

CI

### Example flow

Flaky tests (non-exhaustive) :
io.kestra.core.serializers.JacksonMapperTest ✘ json()
io.kestra.core.tasks.DockerBashTest ✘ useInputFiles()
io.kestra.runner.h2.H2FlowListenersTest ✘ all()
io.kestra.runner.mysql.MysqlMultipleConditionStorageTest ✘ expiration()
io.kestra.runner.postgres.PostgresRunnerTest ✘ pauseRun()
io.kestra.runner.mysql.MysqlRunnerTest ✘ pauseRun()

See this build for eg.
[logs_5800.zip](https://github.com/kestra-io/kestra/files/11442065/logs_5800.zip)

**Comment by loicmathieu** [comment]
Another one:
io.kestra.webserver.controllers.ExecutionControllerTest ✘ restartFromLastFailed()

**Comment by moadibfr** [comment]
I had several failure with:
io.kestra.ee.runner.kafka.KafkaRunnerTest ✘ skipExecution()

**Comment by loicmathieu** [comment]
io.kestra.core.tasks.flows.WorkingDirectoryTest ✘ initializationError

**Comment by brian-mulier-p** [comment]
Closing as I grouped everything [here](https://github.com/kestra-io/kestra/issues/2722)
