### ISSUE TITLE
⭐ Flow Gallery

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1274]
# Feature description

**Feature Description**: having a “Flow Gallery” section within Kestra UI and website. This gallery will provide several Blueprints to users willing to get inspiration and know what’s possible with Kestra.

After several discussions, the MVP is : 

- A new section on the left side
- A new icon on the right side of the editor where users can search/apply blueprints
- Update the Create button to a dropdown button with the ability to "Create from gallery" where users are redirected to empty flow with right side panel focused on Flow Gallery
- A "apply" button in blueprint pages - when a user click on it, it adds the blueprints to the last element of tasks Flow properties.
- Blueprint Tags : `Database`, `Schedule & Trigger`, `Cloud`, `Script`, `ETL/ELT`, `Kestra Core`, `Alerting` (first list version, we could add tags in next releases, depending of the needs)
- Search : 
    - search bar on title, tags and task
    - tags filtering
    - dropdown by tasks (not in prototypes yet)

## Blueprint Specification

A blueprint has : 
- title
- description
- tags
- yaml code
- topology preview
- links to corresponding plugin documentation

## Anticipation

At some point we would like to let any user create and propose Blueprints (via a form for example)

---

See comments for prototypes

**Comment by Ben8t** [comment]
Flow Gallery Homepage



![Image](https://github.com/kestra-io/kestra/assets/46634684/a71d8145-ed82-4ebe-aadc-6f419c7f2dad)

**Comment by Ben8t** [comment]
Blueprint page

![Image](https://github.com/kestra-io/kestra/assets/46634684/8bc73d1d-8b2b-4714-9b3e-4902a194b36f)

**Comment by anna-geller** [comment]
Suggestion to the subheader - thousands of blueprints might be misleading - there'll be just tens of blueprints at first :) 

how about: "First step is always the hardest. Explore blueprints to kickstart your next flow." - WDYT @Ben8t?

**Comment by Ben8t** [comment]
100 agree with Anna's comment above

**Comment by Nico-Kestra** [comment]
<img width="1609" alt="Capture d’écran 2023-05-22 à 09 37 07" src="https://github.com/kestra-io/kestra/assets/125994028/2b00d5a6-8dbc-487c-b947-5d6a65ebfa74">

**Comment by Ben8t** [comment]
![image](https://github.com/kestra-io/kestra/assets/46634684/ec67bc57-be5e-4c97-af8d-21d55a6f44f5)

**Comment by Ben8t** [comment]
![image](https://github.com/kestra-io/kestra/assets/46634684/46384f68-8c64-4088-b84b-6df8f940912e)


![image](https://github.com/kestra-io/kestra/assets/46634684/73bb4922-9e9f-4ce0-8fb4-6d92eb3e4096)

**Comment by Nico-Kestra** [comment]
For button https://www.figma.com/file/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?type=design&node-id=866%3A3663&t=xoepqF8rWAsFC91c-1

**Comment by brian-mulier-p** [comment]
@Ben8t, do the "apply" button in the editor replace all the editor content with the selected blueprint ? I'm wondering if this button has any use, I feel like users will mostly want to take the source code of the blueprint and paste it where they want if they went inside the editor and not through the Flow Gallery ?

Or maybe it should copy everything except the id and namespace ? WDYT ?

**Comment by brian-mulier-p** [comment]
Also, what about having a hover effect and show details on click instead of having a specific button ?

**Comment by Ben8t** [comment]
> @Ben8t, do the "apply" button in the editor replace all the editor content with the selected blueprint ? I'm wondering if this button has any use, I feel like users will mostly want to take the source code of the blueprint and paste it where they want if they went inside the editor and not through the Flow Gallery ?
> 
> Or maybe it should copy everything except the id and namespace ? WDYT ?

👉 the idea in the description was "when a user click on it, it adds the blueprints to the last element of `tasks` Flow properties." (without taking the id and namespace yes) + copy/paste possibility - if all of these is possible technically possible 😅

**Comment by Ben8t** [comment]
> Also, what about having a hover effect and show details on click instead of having a specific button ?

don't really understand what you means by this 🤔 Hover on the bluerprint code ?

**Comment by brian-mulier-p** [comment]
> > @Ben8t, do the "apply" button in the editor replace all the editor content with the selected blueprint ? I'm wondering if this button has any use, I feel like users will mostly want to take the source code of the blueprint and paste it where they want if they went inside the editor and not through the Flow Gallery ?
> > Or maybe it should copy everything except the id and namespace ? WDYT ?
> 
> point_right the idea in the description was "when a user click on it, it adds the blueprints to the last element of `tasks` Flow properties." (without taking the id and namespace yes) + copy/paste possibility - if all of these is technically possible sweat_smile

What if there is more than simple tasks ? What about triggers or inputs for eg. ? Should we parse the blueprint and extract things and append them to the right section ?



> > Also, what about having a hover effect and show details on click instead of having a specific button ?
> 
> don't really understand what you means by this thinking Hover on the bluerprint code ?

What I mean is that I think it might be overkill to add a "Details" button, maybe we can simply open details on click anywhere on a blueprint in the list view with some "hover effects" to show that it is a clickable element ?
