### ISSUE TITLE
Evaluate expression should allow us to see all the context (with outputs, inputs, vars, ...)

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1279]
### Feature description

It would be great to facilitate discovery of inner working of Kestra and what tools I have at disposal in my flow to allow (through a button next to eval) viewing the whole context of Kestra, meaning outputs, inputs, variables, taskrun, ...

**Comment by anna-geller** [comment]
almost the same request https://github.com/kestra-io/kestra/issues/3537
