### ISSUE TITLE
Language modification should update the left navbar instantly

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1282]
### Expected Behavior

As the middle view does, the left navbar should also change language instantly on modification (refresh view)

### Actual Behaviour

You have to refresh / switch tab in order for the language to switch (looks unprofessional)

### Steps To Reproduce

Switch language
Left navbar is still in the old language while you don't refresh / switch tab

### Environment Information

- Kestra Version: 0.9.0-SNAPSHOT

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/kestra/commit/c593951483068a1d2b5e4b0236fc8bc821ccc196
