### ISSUE TITLE
Draft workspace

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1290]
### Feature description

Since `0.9.0` it's possible to save a flow as draft. However, it's not possible to create many drafts from not already saved flows, for different flows. Also it's not possible to see al draft in one central place.

The idea would be to create a place in the app where users can find their drafts.

**Comment by Ben8t** [comment]
maybe adding a "draft" label automatically ?

**Comment by anna-geller** [comment]
added to the list of ideas in notion
