### ISSUE TITLE
Flow Detail : breadcrumb is wrong on second click

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#13]
Seems to be have an context scope that don't work on `routeInfo()`, since on the `FlowRoot.Vue` we include the `Executions.Vue`, the execution replace the breadcrumb.

**Comment by eregnier** [comment]
fixed 4028dc994e907943072b1ee87cfc846fc6410b9e

**Comment by eregnier** [comment]
fixed c83c51856efa40d6a4fa2c00f52dc11a37c5ea0c
