### ISSUE TITLE
CREATED issue is not killable

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1306]
Right Now, we have a control on the `RUNNING` [state](https://github.com/kestra-io/kestra/blob/6e6c3334be5405807a547e42b5306a049c35ada9/webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java#L822) that prevent killing an execution in `CREATED`. Created must be killable as running on each king of killing (for one, for ids, and for search)

**Comment by loicmathieu** [comment]
In fact only killByQuery (search) filter on running execution on the backend side.
