### ISSUE TITLE
Boolean inputs not displayed correctly

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1310]
### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/37600690/3013e7f4-5467-4deb-8f2a-88ce1e696070)

### Environment Information

- Kestra Version: 0.8.1

**Comment by tchiotludo** [comment]
What do you expect ? @Skraye

**Comment by Skraye** [comment]
Does not looks natural to me.
What do you think @Nico-Kestra ?

**Comment by Nico-Kestra** [comment]
https://www.figma.com/file/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?type=design&node-id=1100%3A7303&t=oTbZMn2N0k2MDyDk-1

I think it's important to provide context for why Kestra triggers this pop-up. This text needs to be revised.

Also, having checkboxes under the label with nothing next to them looks really ugly, so I suggest placing them next to the label.

**Comment by Ben8t** [comment]
"To run this flow you have to fill the following inputs:" 🤔 
@anna-geller for a better english formulation ?
