### ISSUE TITLE
Button Rework - "Mass Action"

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1333]
### Feature description

Following #1003 issue, we want to change the positions of "mass action" buttons.

👉 Move them in the top of tables. When the user selects multiple elements, buttons should appear on the headers

See @Nico-Kestra prototypes in comment

**Comment by Nico-Kestra** [comment]
When I do mass actions the buttons replace the content of the first line. This saves space for positioning the buttons, like on Notion or crowd.
<img width="1668" alt="Capture d’écran 2023-05-19 à 09 35 24" src="https://github.com/kestra-io/kestra/assets/125994028/efb7c723-b1ce-4732-b93e-c65bed62bbc9">
[Figma link](https://www.figma.com/file/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?type=design&node-id=843%3A3633&t=LkChqhww36cq4mBn-1)
