### ISSUE TITLE
Button Rework - Actions at the top right

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1334]
### Feature description

Following https://github.com/kestra-io/kestra/issues/1003 issue, we want to change the positions of actions buttons.

👉 Move them at the top right.
👉 Change "New Execution" by "Run"

See @Nico-Kestra prototypes in comment

**Comment by Nico-Kestra** [comment]
All buttons actions on the top : 
<img width="1521" alt="Capture d’écran 2023-05-19 à 09 59 25" src="https://github.com/kestra-io/kestra/assets/125994028/04d0299e-fece-4025-b1f5-164b34eaf78b">
<img width="1576" alt="Capture d’écran 2023-05-19 à 10 03 45" src="https://github.com/kestra-io/kestra/assets/125994028/7f2e87f3-b248-4f35-8362-7ff3ea73c87e">
<img width="1526" alt="Capture d’écran 2023-05-19 à 10 04 53" src="https://github.com/kestra-io/kestra/assets/125994028/5f66871f-5f45-4b23-b04b-24d08a56ded5">
[Figma link](https://www.figma.com/file/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?type=design&node-id=866%3A3879&t=LkChqhww36cq4mBn-1)

**Comment by brian-mulier-p** [comment]
Moving it back to ready as it won't be tackled this release and needs a major refactoring on what was done as we changed a lot of things on figma
