### ISSUE TITLE
Vue-Flow : upgrading to 1.15.X break topology

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1361]
### Actual Behaviour

Upgrading to 0.15.0 break the low code, probably due to the rework that has been done: https://github.com/bcakmakoglu/vue-flow/releases/tag/v1.15.0

This makes the method `fitView` not work except with the button from the Controls components.
Note that when we upgraded to the latest (1.20 at times of writing), another issue occurred where the node could not be dragged anymore, and the view could not be moved.

### Environment Information

Kestra 0.9.0

**Comment by anna-geller** [comment]
it's been over a year, is this still relevant @Skraye?

@MilosPaunovic feel free to jump in to validate whether the issue persists

**Comment by MilosPaunovic** [comment]
I'll assign this one to me and give it a through check during cooldown deps update.
