### ISSUE TITLE
Monaco Yaml: Upgrading to 4.0.4 break suggestion

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1372]
### Actual Behaviour

Issue created here:
https://github.com/remcohaszing/monaco-yaml/issues/207

Opening this issue to have follow-up on our side

**Comment by anna-geller** [comment]
It's been over a year. I assume that by suggestion, you mean autocompletion? Currently, autocompletion seems to work without problems, so I'll close

Please reopen if this issue is still relevant
