### ISSUE TITLE
Bad namespace shown in template list

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1381]
### Expected Behavior

I should see all my namespace where I have template

### Actual Behaviour

Only flows template are listed in the select filter : 
List displayed
![image](https://github.com/kestra-io/kestra/assets/37600690/16d5a4ba-299b-45a8-be81-71fec009dfe9)
My template : 
![image](https://github.com/kestra-io/kestra/assets/37600690/d12c611e-a3cc-4d20-b46e-0e51c91590ed)

### Steps To Reproduce

- Create template(s)
- try to filter by namespace

### Environment Information

- Kestra Version: 0.9.0

**Comment by tchiotludo** [comment]
close in favor of kestra-io/kestra#1907
