### ISSUE TITLE
Restart any flow, even in SUCCESS state

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1384]
### Feature description

Since `0.9.0` it's possible to restart a failed flows with previous inputs (#1208)

It would be nice to be able to restart a Flow, even when in SUCCESS state

**Comment by tchiotludo** [comment]
@brian-mulier-p it's already done with the new replay button, no ?

**Comment by Ben8t** [comment]
nope, it was only for failed execs

**Comment by tchiotludo** [comment]
@brian-mulier-p I think you add a PR on the current release ;)

**Comment by brian-mulier-p** [comment]
Hmm I have to double check but I think it is still based on the control that the replay used to do

**Comment by brian-mulier-p** [comment]
@Ben8t Idk if it fits the need but you can click on new execution from an existing one and you will be able get all fields prefilled

**Comment by brian-mulier-p** [comment]
Hmm after checking the replay button is also available on success state so I think the feature is covered
