### ISSUE TITLE
Saved search filters

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#1397]
### Feature description

The UI already features rich ways of filtering the displayed content - mainly the Executions and Task Runs UI views. Additionally, there are more filtering capabilities, like the #1308, to be added in the future.

Setting the desired filters manually can be tiresome for repeated tasks.

Operations teams using those UI views would likely need to use several _pre-set filters_ to perform their tasks effectively. Common use cases include:

- List Executions being in the Failed/Warning state in the past 1 hour.
- List Executions being in any state filtered by a Execution Label (eg. only Executions labeled as "pre-production").
- List Executions of a selected Flow being in the Paused state in the past 24 hours.

This could be achieved by treating the filters as a first class object.

1. The **initial version** of this functionality might treat the filters as _user-specific_ and save them to a _local storage_.
1. A follow-up **advanced version** would allow _sharing the filters_ via a _shared storage_ - effectively allowing the whole operations team to share common filters and still allow defining the user-specific ones.

**Comment by Skraye** [comment]
I think we should first rework the way our date filter works.
As you said, relative times ranges wont work because we put absolute time ranges, and this is an issue.

So I suggest doing this one before : https://github.com/kestra-io/kestra/issues/2211
WDYT @anna-geller ?

**Comment by anna-geller** [comment]
Good catch, you're right 👍
