### ISSUE TITLE
Python env files are created as root

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1403]
### Expected Behavior

When my python task is done, I expect the env files to be cleanup

### Actual Behaviour

Files are created from root so Kestra cannot delete them

![image](https://github.com/kestra-io/kestra/assets/37600690/3f627799-022b-4f34-a474-1e05b227bc1e)
![image](https://github.com/kestra-io/kestra/assets/37600690/368257de-3efd-4422-a780-4dc12f9b8dd3)

### Steps To Reproduce

id: "a"
namespace: "b"
tasks:
  - id: python
    type: io.kestra.core.tasks.scripts.Python  
    runner: DOCKER
    dockerOptions:
      image: python
      pullImage: true
    inputFiles:
      main.py: |
        print("crash")

### Environment Information

- Kestra Version: 0.9.0

**Comment by loicmathieu** [comment]
This is because they are created by the Docker engine which, in your setup, runs as root.

Now that we move from host binding to a Docker volume, this issue no longer exists.

Fixed by https://github.com/kestra-io/kestra/pull/4349
