### ISSUE TITLE
Don't duplication error toast on topology 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1424]
https://github.com/kestra-io/kestra/blob/83c7bffcfe668c8f5e45b1ea0136be976731d731/ui/src/components/graph/Topology.vue#L587-L612

We duplicate the whole notification because flow validation don't return a standard error and return a 200 with not a standard exception here: 
https://github.com/kestra-io/kestra/blob/fbc80d07406b6ac3386a7ff54cd394c67b8687b5/webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java#L444

We should rely on standard exception handling on that route to keep the standard ErrorHandler with a proper formatting of the execption

**Comment by brian-mulier-p** [comment]
Done in 02457530a918b6d173e2d6ff15f6eeeb95921fc6
