### ISSUE TITLE
Improve revisions API endpoints and response

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1432]
### Feature description

Kestra has a concept of flow revisions.

API has a method GET /api/v1/flows/{namespace}/{id}/revisions which returns the list of flow revisions. With the large flow and many versions of it, the response might be huge.

So, several concerns here:
* Could there be a tracking section which would contain info about who modified the revision and when? This would allow to trace changes in the flow more effectively. 👉 available in Enterprise Edition

* Could we have an option to return just the tracking info of the flow in GET /api/v1/flows/{namespace}/{id}/revisions? This would limit the traffic and not return information which is not really needed all the time. Then user could select the specific revision of interest.

**Comment by anna-geller** [comment]
You're right that for the first issue, we have it in EE (and it will improve with Audit Logs enhancements) 

for the tracking info, you would need to provide a bit more details, not sure what is meant here

I'd close given it's an old issue (over 1 year), please reopen with more details and examples if this is still relevant 👍
