### ISSUE TITLE
Deprecated properties are not shown as deprecated in the UI editor

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1441]
Expected Behavior
The editor should display a warning when a deprecated property is used.

Actual Behaviour
The editor didn't display any warning when a deprecated property is used.

Steps To Reproduce
No response

Environment Information
Kestra Version: 0.9.0
Operating System (OS / Docker / Kubernetes):
Java Version (If not docker):
Example flow
No response

**Comment by Skraye** [comment]
Seems not possible yet due to library limitation : 
https://github.com/remcohaszing/monaco-yaml/issues/192
related to this issue : https://github.com/microsoft/vscode-json-languageservice/issues/87

**Comment by loicmathieu** [comment]
Fixed by [#1713](https://github.com/kestra-io/kestra/issues/1713)
