### ISSUE TITLE
[UI] Blueprints - add blueprints to favorite

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1445]
### Feature description

Add a favorite feature to the Flow Gallery so users can save most used blueprints

**Comment by anna-geller** [comment]
could be a bookmark as e.g. here https://developer.hashicorp.com/terraform/tutorials/providers

**Comment by MilosPaunovic** [comment]
Maybe we can do something like we have with community/custom blueprints, to have another tab, `Favorites` and to save everything locally, without involving BE @Ben8t, like we do for bookmarked pages now?

![image](https://github.com/user-attachments/assets/fd3658dd-9764-4068-8a3b-1208f02931d9)

**Comment by anna-geller** [comment]
good callout, using Bookmarks is totally enough, no need for any extra feature now! 👍 

![image](https://github.com/user-attachments/assets/0052639a-4501-4e9e-b672-8a6da192dde8)
