### ISSUE TITLE
UI - Flow dashboard missing a refresh button

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1447]
### Feature description

On the flow dashboard page, we have a list of flows with some execution charts. It would be great to have a refresh button as in the execution dashboard to avoid using browser refresh if we want to have updated charts.

**Comment by Ben8t** [comment]
@Nico-Kestra , we will probably need a design here

**Comment by anna-geller** [comment]
already available 

![image](https://github.com/kestra-io/kestra/assets/86264395/628449ae-180a-4b55-b51d-6cead59806c5)
