### ISSUE TITLE
Autopause debug execution

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#1449]
### Feature description

During flow development/debugging phase it is often handy to pause the execution before reaching a _critical task_ (an immutable action, sending to a 3rd party system, etc.). This way you can debug/verify the execution's correctness before "committing" it by resuming the execution.

Currently, it is possible to insert an explicit `io.kestra.core.tasks.flows.Pause` task to the flow, although specifying the "autopausing" task during the creation of execution.

**Comment by anna-geller** [comment]
Closing as it will be possible once we add https://github.com/kestra-io/kestra/issues/1937 -- @yuri1969 please reopen if you believe the manual Pause from the UI won't solve the problem here
