### ISSUE TITLE
Iceberg

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1450]
https://iceberg.apache.org/

**Comment by anna-geller** [comment]
Iceberg has a REST API - it seems that this will be the best getting started point for the plugin implementation:
- https://registry.hub.docker.com/r/tabulario/iceberg-rest
- https://github.com/tabular-io/iceberg-rest-image

**Comment by anna-geller** [comment]
adding Athena plugin first will be helpful as a first step -- Athena is one of the easiest setups to use Iceberg since it doesn't require Spark: https://github.com/kestra-io/plugin-jdbc/issues/147

**Comment by anna-geller** [comment]
we support it via Spark and Athena plugin

we can add it later on if there is demand for it from the community
