### ISSUE TITLE
Revision in Topology

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1455]
### Feature description

Being able to view a selected Revision at the Topology level

**Comment by anna-geller** [comment]
some questions:
1. what is meant by selected revision? the current version of the flow? 
2. why is this important? it seems you can always see the current version in the Revision tab

**Comment by Ben8t** [comment]
1. some users reach out to get the revision in the topology view to have a graphical representation of past revisions. Being able to choose between revisions and seeing the corresponding Topology.
2. agree that it's not that important IMO, just sometimes Flow can be complex and having a graphical view is easier to understand
