### ISSUE TITLE
Math operations on 'numeric' variables

### ISSUE THREAD

**Issue by vivane** [kestra-io/kestra#1459]
### Expected Behavior

It is expected to perform math operations with variables having numeric values.

### Actual Behaviour

Trying to perform math operation leads to the error. See example flows for more details.

### Steps To Reproduce

Create and run the flow as mentioned in the example. Observe errors.

### Environment Information

- Kestra Version: latest-dev
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

id: "math-variables"
namespace: "local.kestra.tests"
description: "This reproduces the issue with math operations on the 'numeric' variable"

variables:
  # This has to be declared as string as for YAML specifications.
  nowTime: "{{now() | timestamp}}"

tasks:
    #This prints the variable as is.
  - id: task-log-1
    type: io.kestra.core.tasks.log.Log
    message: "{{vars.nowTime}}"

    # This tries to perform math operation on 'numeric' variable.
  - id: task-log-2
    type: io.kestra.core.tasks.log.Log
    message: "{{ (vars.nowTime | number) - 100}}"

**Comment by loicmathieu** [comment]
@vivane this is the same issue as https://github.com/kestra-io/kestra/issues/1659 the `number` filter is not capable of rendering a template so it can't be used like this.
I'm closing it.
