### ISSUE TITLE
Minor bug: the onboarding tour window doesn't close after "Save" flow step

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1464]
### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/86264395/2f91a86f-9e1d-495a-aad8-6af878cf15ed)

could be just window placement, after clicking Execute now, the window is back

![image](https://github.com/kestra-io/kestra/assets/86264395/2ebaee89-b62f-4f6e-ad82-6f4ff731e995)

An easy fix would be to finish the tour after the Save step - instead of "Save" it could be "Save and execute the flow" maybe? @Ben8t  

### Environment Information

- Kestra Version: latest 0.9.3

**Comment by Ben8t** [comment]
Agree, linked to #1399

**Comment by Skraye** [comment]
It seems that your page miss the title, that's the root of the issue
