### ISSUE TITLE
Mass Reset scheduler execution locking

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1466]
In case of panic, executor may have not clean properly the scheduler trigger, and the locking could lead to infinite locking with this message : 

```
WARN  pool-5-thread-1 i.k.c.schedulers.AbstractScheduler Execution '1pgRuDH9gIrDuFzkuASUCH' for flow 'xxxxxx' is not found, schedule is blocked since 2023-04-27T07:06:45.459082Z   
```

If the admin want to recover the schedule, the only way is to remove the trigger, and readd them, that lead to a lots of burden, very long task, that will create some revision. 

Provide a proper interface to it properly and in mass

**Comment by brian-mulier-p** [comment]
How is this case happenning ? Because unless a manual delete of the execution in database / elastic I can't see how it is possible ?

**Comment by Ben8t** [comment]
@brian-mulier-p is it linked to the trigger locking thing ?

**Comment by brian-mulier-p** [comment]
Yes I think it is handled with the new admin trigger view
