### ISSUE TITLE
Template format should be kept in the same way as the Flow one

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#1469]
### Expected Behavior

Template YAML code should behave in the same way as the Flow one - keep the indentation, comments, etc. The Flows were corrected as a part of #748.

### Steps To Reproduce

1. Create a Template
2. Add a comment
3. Save
4. The comment is gone

### Environment Information

- Kestra Version: 0.9

**Comment by tchiotludo** [comment]
close in favor of kestra-io/kestra#1907
