### ISSUE TITLE
Have a graphical representation of all flows of a namespace

### ISSUE THREAD

**Issue by aurelienWls** [kestra-io/kestra#1484]
### Feature description

It could be usefull to have a graphical representation of all flows of a namespace.
A page like the "Dependencies" tab in flow section but at the namespace level.

I want to see the dependencies between all my flows in this page.

**Comment by Ben8t** [comment]
@Skraye already moved forward on this

![image](https://github.com/kestra-io/kestra/assets/46634684/8642e5cc-8828-4101-a67e-8149d0f622a8)


@Skraye can you link your PR here pls :) ?

**Comment by Skraye** [comment]
Done in the 0.10 release

**Comment by Ben8t** [comment]
This feature has been done in `0.10.0` (quick implementation with no tracking issue). @aurelienWls let us know when you'll hit this version if you need other details in this view
