### ISSUE TITLE
Expose an API endpoint to programmatically resume a paused Execution

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1492]
## Problem
At the moment, the Pause task can only be resumed from the UI. 

It would be great to expose an endpoint allowing external systems (e.g., Dbt Cloud webhook) to resume the flow execution.

This is particularly useful for saving compute when orchestrating long-running jobs (thereby potentially saving money for end-users). 

## Use cases
Imagine that you trigger a long-running job on AWS Batch, Azure Batch, Vertex AI, Spark job or Dbt Cloud. Instead of continuously polling for completion of that long-running task, the user can instead trigger it in a fire-and-forget manner. Then, a subsequent Pause task can pause the Flow execution until the actual job (e.g., Dbt Cloud webhook or a Spark job) triggers the Resume endpoint when the job is finished. Once Resumed, the Execution can continue running any downstream tasks.

**Comment by Ben8t** [comment]
Closing this one and move some part of your description in #1037
