### ISSUE TITLE
Add information about the next scheduled executions on the flow details page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1495]
### Feature description

Currently, the flow execution page shows only current and past executions. However, if a flow runs on a schedule, it would be helpful to show information about the next scheduled dates. 

![image](https://github.com/kestra-io/kestra/assets/86264395/44aa4ac0-605f-44e3-9081-d1404a36a0d7)

**Comment by Ben8t** [comment]
@Nico-Kestra, we would need a quick design here :)

**Comment by anna-geller** [comment]
will be done as part of https://github.com/kestra-io/kestra/issues/3822

![image](https://github.com/user-attachments/assets/6fa04224-54cc-41d9-b3f9-54a9e4e58de6)
