### ISSUE TITLE
Add a kill method on Runnable Task

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#1498]
### Expected Behavior

When I click "Kill", the execution should stop, and I should be able to replay some tasks.

### Actual Behaviour

When I attempt to kill an execution that has a running job on Azure Batch, nothing happens.
I believe Kestra is waiting for a signal from Azure Batch that never comes 😨

Any idea how we should handle the kill procedure ?

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by tchiotludo** [comment]
Add a `void kill()` method on `RunnableTask` that will be implemented on each task

**Comment by loicmathieu** [comment]
Script tasks must kill the process/container that they launched inside this kill method.
See https://github.com/kestra-io/kestra/issues/2653 for ex.
