### ISSUE TITLE
Extend the `Fail` task by `executionId` attribute

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1501]
### Feature description

Currently, the Fail task can only fail an execution based on a condition: https://kestra.io/plugins/core/tasks/executions/io.kestra.core.tasks.executions.fail 

It would be great to allow failing an execution explicitly by providing an Execution ID - useful with Triggers such as https://github.com/kestra-io/kestra/issues/1246#issuecomment-1587686367

**Comment by loicmathieu** [comment]
This may be dangerous, and there can be security implications.
Should we allow it cross-namespace?

You cite #1246 which would be better implemented by a SLA define in the flow itself with an action to kill itself if some SLA are not respected.

**Comment by loicmathieu** [comment]
The `Fail` task is implemented by genrating an exception and failing a task so it cannot fail another execution.
In fact, failing an execution is not something that exist today, it's always failing a task.

Maybe what we need is a tasks to Kill a target execution, it seems more accurate.

**Comment by anna-geller** [comment]
good catch, in that case I'll close this issue as we already have this one to add a task to kill an Execution https://github.com/kestra-io/kestra/issues/3352
