### ISSUE TITLE
Blueprints adjustements

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1511]
### Issue description

- [x] Markdown not rendered in blueprint description
- [x] Use purple for "Use" button (dark theme)
- [x] keep the breadcrumb on main blueprint page (from left side section)
- [x] move the Flow Gallery section above the Documentation section in the left bar menu
~- [ ]  Move "About this blueprint" text at the top of blueprint page~
- [x] Rename Flow Gallery by Blueprints

**Comment by anna-geller** [comment]
- [ ] separate tags by spaces rather than dots

atm this looks like a hierarchy, but all tags seem equally important, right?

![image](https://github.com/kestra-io/kestra/assets/86264395/c8420b87-8af7-4b93-933d-ed278909746f)

**Comment by anna-geller** [comment]
one easy item checked :) https://github.com/kestra-io/kestra/pull/1518

**Comment by anna-geller** [comment]
Regarding `Move "About this blueprint" text at the top of blueprint page`

After using blueprints, it actually seems more convenient to have the source code first and a description below

**Comment by brian-mulier-p** [comment]
WDYT @Ben8t ? This would lead to lesser visibility of topology but I'm okay with that

**Comment by anna-geller** [comment]
to add: the description is usually just a summary of what's already visible in the topology and source code (i.e. less important), so the way it's currently presented seems intuitive

Atm you can see the blueprint's source code directly in the editor. However, if the description moves to the top, the source code, which is the most important part, won't be visible  

![image](https://github.com/kestra-io/kestra/assets/86264395/de4c69b0-988f-418e-aa02-6f99d6f268cb)

**Comment by Ben8t** [comment]
Don't have a opinion, it was asked by Manu. But kinda agree with both of you, so let it keep things as they are
