### ISSUE TITLE
New consumer group break performance on postgres 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1516]
The cols added [here](https://github.com/kestra-io/kestra/blob/3945de00b65aa8b4f4d8ba2ab29298d0f8bf45ee/jdbc-postgres/src/main/resources/migrations/postgres/V14__queues_consumer_group.sql#L1) seems to prevent postgres to use index and do a full table scan for every query on the queue tables

**Comment by loicmathieu** [comment]
This is the same issue as #1121 so closing it as duplicate
