### ISSUE TITLE
Home Dashboard: unresponsive display of tiles displaying the number of Successful, Failed and Running Executions

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1563]
### Actual Behaviour

Display is not responsive for digits in dashboard
![image](https://github.com/kestra-io/kestra/assets/46634684/83a11b25-5420-4989-8011-08a38ecce9d5)
![image](https://github.com/kestra-io/kestra/assets/46634684/741f3631-6c3e-4067-9206-4a10bae6999e)

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
@Ben8t can you say more? would be lovely if you could share a quick screen share video showing which components are not responsive

**Comment by anna-geller** [comment]
Video showing the issue: https://share.descript.com/view/bgxZPEqDn55 

The entire tile displaying those numbers would need to be adjusted based on the screen resolution
