### ISSUE TITLE
Cancelling leaving editor still change the selected tab displayed

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1571]
### Expected Behavior

![lowcode-leave-bug](https://github.com/kestra-io/kestra/assets/37600690/d5ee71ca-ffef-411b-be93-9537ae6096ed)

### Environment Information

- Kestra Version: 0.10.0-snapshot

**Comment by anna-geller** [comment]
just a comment that the issue still persists on the 0.14.0 version

**Comment by MilosPaunovic** [comment]
Great work as always @sachinks07! 🚀
