### ISSUE TITLE
Add a setting for log collapsing 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1572]
### Expected Behavior

![image](https://github.com/kestra-io/kestra/assets/86264395/142ea710-6a5e-4956-99b0-e7f74f1530e8)

I need to manually click on each task to expand and show the logs -- this seems like a regression bug

![image](https://github.com/kestra-io/kestra/assets/86264395/ec209dc1-59a1-46a3-8b5e-2a648b3c4285)

### Environment Information

- Kestra Version: 0.10.0

**Comment by tchiotludo** [comment]
it was an intended feature and flow will expand only on failed tasks now (like GHA), WDYT ?

**Comment by anna-geller** [comment]
I want to see my logs, this is the most important aspect 

Having to expand/collapse is extremely inconvenient. Imagine you want to quickly scan the logs from the entire workflow that has 20 tasks. You would need to click on expand 20 times...

**Comment by Ben8t** [comment]
I think we should keep the collapsed by default (new intended feature) as it definitely keep things tidy. Logs are mostly a debugging feature (in any tools) - when you flow works you don't look at the logs, it's mostly for debugging error (and so you want to quickly find the ERROR log, hence the new behavior)

But agree with a settings where you can we set "Expand all logs" = true | false (false by default)

**Comment by anna-geller** [comment]
but I don't see the progress... this makes iterating on building workflows way more difficult. Troubleshooting is not only if something failed, but also the flow may succeed but the log shows something unexpected, or not showing some logs

this seems like a big regression in developer productivity

to see a tidy view of task structure, I would go to the topology or Gantt view. Logs tab is to see the logs.

**Comment by anna-geller** [comment]
to find a middle ground, perhaps we may consider adding a button allowing users to expand all @Ben8t?

![image](https://github.com/kestra-io/kestra/assets/86264395/4d4a1564-69fe-489f-9e45-18a54cf702ce)

**Comment by Ben8t** [comment]
Yes I think it's good compromise !
Changing the issue title to be clearer

**Comment by loicmathieu** [comment]
I too prefer logs to be openned by default, easier when building a workflow.
My opinion is that the logs tab should display ... logs, today it displays tasks status with call to action, one of these call to action is to show the task log.

**Comment by tchiotludo** [comment]
Add a settings with : 
- Expands logs (default one)
- Collapse logs
- Expands only error 

Add a collapse all / expand all on the logs page (that will not affect the settings)
