### ISSUE TITLE
Unsaved popup even If I just save the content

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1578]
https://github.com/kestra-io/kestra/assets/2064609/6f94a6ce-1c65-4381-83bf-6eaf13409ae4

- type somethings
- hit ctrl + s
- hit f5 
- say the unsaved popup

**Comment by brian-mulier-p** [comment]
Can't reproduce, if anyone else manage to feel free to take it

**Comment by Skraye** [comment]
done with : https://github.com/kestra-io/kestra/pull/1614
