### ISSUE TITLE
Dockerfile doesn't contain executable file

### ISSUE THREAD

**Issue by jnupeter** [kestra-io/kestra#1599]
### Expected Behavior

in the kestra checkout directory, run `./gradlew executableJar` then run `docker build -f Dockerfile . -t mykestra` then an image should be build. The docker image should be usable when run `docker run --rm mykestra:latest`.

### Actual Behaviour

Run `./gradlew executableJar` then run `docker build -f Dockerfile . -t mykestra`
The newly build image will fail with command not found when run `docker run --rm mykestra:latest`

### Steps To Reproduce

1, in the kestra project checkout directory;
2, run `./gradlew executableJar`;
3, run `docker build -f Dockerfile . -t mykestra`
4, run `docker run --rm mykestra:latest`

### Environment Information

- Kestra Version:0.10.0-snapshot (the head of `develop` branch)
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by Ben8t** [comment]
Not sure this one is still relevant - since Jun 23', Dockerfile changed several times and users are able to build their own Kestra images 🤔 
@Skraye do you confirm ? I'm closing right now, let's reopen if needed
