### ISSUE TITLE
Add a vision by TaskRun

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#164]
For now, we have only a view by executions. 
If a task is a long running task (that will raise the whole execution), there is no way to find this taskRun in order to dig the reason (except looking all executions one by one).
We need to create a new list like Executions but for TaskRun (displaying duration for each TaskRun and sortable). 
When we click on a taskRun, we must go to execution page (on gantt page) with all expanded for this taskRun (metrics, logs, ...)

**Comment by eregnier** [comment]
https://github.com/kestra-io/kestra/commit/25d25d60dcd40c9e73b6683a878a30d5ea011d4e
