### ISSUE TITLE
Selector problem in editor

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1640]
### Expected Behavior

Cursor select well but isnt displayed correctly : 
![image](https://github.com/kestra-io/kestra/assets/37600690/cc6e6b98-54ad-44ff-b326-ed8c742cfa0c)

Maybe a problem between Chromium & MonacoEditor, but not sure

### Environment Information

- Kestra Version: 0.9.5

**Comment by moadibfr** [comment]
Hey there 👋 
I experienced the same issue, also I'm not sure this is related but when this happened my cursor was also shifted from the "real" cursor position. What this mean is inserting and deleting resulted in modification in a place where my cursor isn't displaying.
I made a small video if this can help.
Also refreshing the editor does not fix so I'm able to reproduce and give more information if needed.

https://github.com/kestra-io/kestra/assets/4931174/450adfe6-cfd6-45d3-a88e-92accf1ddae4

Please tell me if I should open another issue 🙏
