### ISSUE TITLE
Double click on blueprint tag to reset tag filter

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1644]
### Feature description

Could it possible to allow a double click on tags to reset the filters ?

It's a common pattern in tag filtering in UI

**Comment by MilosPaunovic** [comment]
This is added via https://github.com/kestra-io/kestra/commit/7bcceffa484b9b752e03d58d22fdebf14dc743c2, could you give it a test to see if that's what you've meant @Ben8t, once CI is completed?
