### ISSUE TITLE
Use the proper design for slider in editor view

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1647]
### Feature description

Replace the purple bar by the proper design in Figma

https://www.figma.com/file/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?type=design&node-id=147-784&mode=design&t=TgTTJLsjdEEj5a26-0

**Comment by brian-mulier-p** [comment]
Is it the tiny gray bar ? (those links never work and I never fall on the right widget).
If so it misses something to show that it is slidable imo, wdyt ?

**Comment by Ben8t** [comment]
yes it's the tiny gray bar 
![image](https://github.com/kestra-io/kestra/assets/46634684/c6b0c4c5-3ffc-4580-986b-48ed91165e4f)

Nico thinks the actual bar is way too big, I kind of agree, let's try with this smaller one
cc @Nico-Kestra
