### ISSUE TITLE
Add logos to `models.conditions` tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1664]
### Feature description

Blueprints make it more visible that some logos are missing on core tasks such as Conditions:

![image](https://github.com/kestra-io/kestra/assets/86264395/2cc23f31-3c88-4857-8ce6-2bd11986daa1)

It would be great to add those. @Nico-Kestra do you have some logo examples in mind that could be used? https://kestra.io/plugins/core/conditions/io.kestra.core.models.conditions.types.executionnamespacecondition

**Comment by Nico-Kestra** [comment]
Hello @anna-geller,
We can use [this icon](https://www.figma.com/file/uUvt0RQ9DWiBTweX6oT4Qp/Library-Icons-Plugins?type=design&node-id=104%3A524&mode=design&t=Cgr0elzcgnzWmL8C-1) for all conditions
