### ISSUE TITLE
Plugin Hot Reload

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1671]
Integrating a new plugin need a Kestra server restart. Being to load at runtime new plugins will allow better deployment experience.

- https://www.toptal.com/java/java-wizardry-101-a-guide-to-java-class-reloading
- https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/plugins/UberModuleClassLoader.java#L83
- https://github.com/quanla/classreloading/blob/master/src/main/java/qj/util/lang/AggressiveClassLoader.java
- https://github.com/quarkusio/quarkus/blob/main/extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusHttpFunction.java#L21

**Comment by Ben8t** [comment]
Next idea : if user try to insert a plugin in his flow but the plugin is not in instance, then show a pop up to let user install the plugin.

**Comment by brian-mulier-p** [comment]
@Ben8t I don't see myself as a user adding a full task name (qualified name) before getting the popup. I think it would work only if we also have autocompletion on plugins not in our instance so I guess providing such feature requires autocompletion revamp.

Regarding this autocompletion revamp, how to handle simple users which do not have the ability to add new plugin to their instance ? 😔 For those users we probably want the current autocompletion and not the full one :/

**Comment by anna-geller** [comment]
tracked in https://github.com/kestra-io/kestra-ee/issues/1173
