### ISSUE TITLE
Typos on links to Plugins' documentation.

### ISSUE THREAD

**Issue by npranav10** [kestra-io/kestra#1682]
### Issue description

I found two types of typos on the links in README which redirect the user to the respective plugin's documentation on https://kestra.io/plugins/ .

1) Type 1 - Affected Plugins: Bash, Node and Python.

The README file has the type name starting with an uppercase character i.e. `https://kestra.io/plugins/core/tasks/scripts/io.kestra.core.tasks.scripts.Python` but the actual link has the type name in lower case i.e. `https://kestra.io/plugins/core/tasks/scripts/io.kestra.core.tasks.scripts.python`

Following are the lines where the issue is present:

https://github.com/kestra-io/kestra/blob/97fbc93655fc333232b2c9b1947b97c431cf84f9/README.md?plain=1#L221
https://github.com/kestra-io/kestra/blob/97fbc93655fc333232b2c9b1947b97c431cf84f9/README.md?plain=1#L270
https://github.com/kestra-io/kestra/blob/97fbc93655fc333232b2c9b1947b97c431cf84f9/README.md?plain=1#L282

2) Type 2: Affected Plugins: Groovy, Jython and Nashorn.

The links on the README file is of the pattern `https://kestra.io/plugins/plugin-scripts-xxx`, where xxx is the plugin name in lower case, but the actual links are of the pattern `https://kestra.io/plugins/plugin-script-xxx` where the word script is singular.

Following are the lines where the issue is present:

https://github.com/kestra-io/kestra/blob/97fbc93655fc333232b2c9b1947b97c431cf84f9/README.md?plain=1#L251
https://github.com/kestra-io/kestra/blob/97fbc93655fc333232b2c9b1947b97c431cf84f9/README.md?plain=1#L256
https://github.com/kestra-io/kestra/blob/97fbc93655fc333232b2c9b1947b97c431cf84f9/README.md?plain=1#L267

I am not sure they are really typos, perhaps you would actually want the documentation to be available on `https://kestra.io/plugins/core/tasks/scripts/io.kestra.core.tasks.scripts.python` instead of `https://kestra.io/plugins/core/tasks/scripts/io.kestra.core.tasks.scripts.Python` etc. So I just wanted to raise the issue before attempting to make any pull request.

Let me know if I have to make a pull request after correcting the changes.

**Comment by loicmathieu** [comment]
Hi,
We totally revamped our website a few weeks ago and it's possible that some links changed.
The README should be updated, if you would like to make a pull request it would be great!
