### ISSUE TITLE
Swagger UI uses the old Kestra logo

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1683]
### Expected Behavior

Swagger UI should use the new Kestra logo

### Actual Behaviour

Swagger UI uses the old Kestra logo

![Capture d’écran du 2023-07-03 11-57-50](https://github.com/kestra-io/kestra/assets/1819009/3f3ee6cc-0ba5-4a92-9259-eac46a41bfc6)

### Environment Information

- Kestra Version: 0.10.0
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
design can be definitely adjusted but the icon is fixed now 
![image](https://github.com/kestra-io/kestra/assets/86264395/be08daee-b001-47f9-b9ed-4b94854a2a11)
