### ISSUE TITLE
Google Palm Plugin

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1688]
### Feature description

https://ai.google/discover/palm2/

**Comment by anna-geller** [comment]
API docs https://developers.generativeai.google/api/rest/generativelanguage

**Comment by anna-geller** [comment]
closing as implemented in 0.11.0:

[ChatCompletion](https://kestra.io/plugins/plugin-gcp/tasks/vertexai/io.kestra.plugin.gcp.vertexai.chatcompletion)
[CustomJob](https://kestra.io/plugins/plugin-gcp/tasks/vertexai/io.kestra.plugin.gcp.vertexai.customjob)
[TextCompletion](https://kestra.io/plugins/plugin-gcp/tasks/vertexai/io.kestra.plugin.gcp.vertexai.textcompletion)
