### ISSUE TITLE
[UI] The restore button should be greyed out if no change was made

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1698]
### Actual Behaviour

Not a big deal but the restore button on the latest revision is not grayed out when coming from editor tab even if there is no change
![image](https://github.com/kestra-io/kestra/assets/37618489/55912002-a941-4529-bde1-f08f10974c9a)

### Environment Information

- Kestra Version: 0.10.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
@brian-mulier-p I believe we no longer show a diff if no change is made:

![image](https://github.com/kestra-io/kestra/assets/86264395/4596dd8b-7508-4eb2-bf59-b5d818dbfa21)

please reopen if I'm mistaken

**Comment by brian-mulier-p** [comment]
I think what I meant is that you need to have multiple revisions but then if you didn't change anything from the editor compared to the latest revision, the restore button can still be clicked next to the latest revision

**Comment by anna-geller** [comment]
Can you add some screenshots? I couldn't reproduce

**Comment by brian-mulier-p** [comment]
Closing as I don't remember what it was about, maybe a fix was provided in-between
