### ISSUE TITLE
Click on any taskrun should expand the logs for this taskrun

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1702]
### Feature description

I find it inconvenient to have to click on the small expand button.
It would be great if a click anywhere on the taskrun would also expand logs (and perhaps the button is no longer a button but a simple state display to know if logs are expanded or not), WDYT @Ben8t ?

**Comment by Ben8t** [comment]
Agree with you, small thing but in term of UX it makes sense. I would keep the expand/collapse button on taskruns anyway, keeping things explicit
