### ISSUE TITLE
Full image needed when deploying from GitLab: See Slack discussion attached

### ISSUE THREAD

**Issue by petrroda** [kestra-io/kestra#1703]
### Expected Behavior

![image](https://github.com/kestra-io/kestra/assets/12616511/c413f6c6-0359-4bba-8d07-e860ef0c0c28)

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by loicmathieu** [comment]
A full image is needed when updating a template from the CLI via `kestra template namespace update <template>`.

As templates are deprecated and will be removed soon I'm not sure we will take the time to fix that, WDYT @anna-geller

**Comment by anna-geller** [comment]
yup, that's correct. they have been deprecated since ~ a year, could you check this migration guide? https://kestra.io/docs/migration-guide/templates and feel free to ping us via Slack if you need some assistance while migrating to subflows
