### ISSUE TITLE
Triggers do not display conditions attribute in doc

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1704]
### Actual Behaviour

I think it is related to the inherited attributes not being displayed, didn't you do something around it @loicmathieu recently ?

### Environment Information

- Kestra Version: 0.10.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by loicmathieu** [comment]
Yes, attributes from the AbstractTrigger are filtered as with attributes from the abstract Task class for all tasks.

**Comment by brian-mulier-p** [comment]
I think this conditions attribute is really important in doc and should be an exception for this rule 🤔
