### ISSUE TITLE
Add a Papermill CLI plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1707]
### Feature description

Given how simple this CLI is, not sure whether we would need a plugin or only a blueprint.

beforeCommands:
```
pip install papermill
```

commands:
```yaml
papermill example.ipynb output.ipynb
```
optionally allowing to output to S3

It should take only jupyter notebook path as input and generate a new Jupyter notebook as output, allowing to also be parameterized -- all doable from `io.kestra.plugin.scripts.python.Commands`  https://papermill.readthedocs.io/en/latest/usage-execute.html#execute-via-cli

**Comment by Ben8t** [comment]
Created this small blueprint https://strapi.kestra.io/admin/content-manager/collectionType/api::blueprint.blueprint/200

**Comment by anna-geller** [comment]
thanks so much for the blueprint Ben!
