### ISSUE TITLE
Easily build a web-app from a Kestra flow

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#1709]
### Feature description

Hey !

Kestra shows amazing capabilities in data-management and BPMN domains.
But currently, its UI is not customer-facing in the sense that people creating and managing flows are not necessarily the end-user for the functions a flow provides.

It would be interesting to allow developers to easily transform a Kestra flow into a webapp.

The developer would have access to a Kestra API in Python/TypeScript/anything with functions and classes to:
- Sanitize inputs
- Trigger an execution with above inputs
- Watch the execution on Kestra
- Get and expose the outputs

The end-user would be able to:
- Login
- Upload some inputs (e.g. an image)
- Start the process
- Get outputs

That SDK could come with some skeleton example for authentication and authorization management, rate-limiting, security features, etc.

Please share your thoughts :)

**Comment by anna-geller** [comment]
hey @Melkaz, we plan to support that use case in the EE version https://github.com/kestra-io/kestra-ee/issues/1429 

The issue is internal so if you are curious about the details, ping us via Slack 👍
