### ISSUE TITLE
Display a warning when a deprecated feature is used in a Flow

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1713]
### Feature description

Whenever a flow uses a "deprecated" feature, we should display a warning in the editor

![image](https://github.com/kestra-io/kestra/assets/46634684/f30debb6-927f-4827-b149-331beecfe7d6)

**Comment by Ben8t** [comment]
related to #1441

**Comment by brian-mulier-p** [comment]
@Nico-Kestra do we put warning and error next to each other if there is a deprecation usage and an error at the same time ?
Also I guess we use #FCB37C for warning ?
