### ISSUE TITLE
Handle Trigger on ui 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#173]
## Normal 
if the flow only contains a normal trigger or a [flow trigger](https://kestra.io/docs/developer-guide/triggers/flow.html) : 
```
triggers:
  - id: watch
    type: org.kestra.task.gcp.gcs.Trigger
```
We don't allow to trigger the flow since it will not be working properly

## Schedule
If the flow contains only Schedule Flow, we allow to trigger the flow at a specific date for `schedule.date`; we need to calculate all the variables needed (previous, next, ...) and add a control of the date is valid for the specified cron expression

**Comment by eregnier** [comment]
this is solved with the new warning message I guess

**Comment by tchiotludo** [comment]
we don't have handle for now the schedule part

**Comment by anna-geller** [comment]
seems like the same as https://github.com/kestra-io/kestra/issues/2126
