### ISSUE TITLE
v0.9.7 image on docker hub is broken

### ISSUE THREAD

**Issue by acidumirae** [kestra-io/kestra#1731]
### Issue description

v0.9.7 image on docker hub is broken
https://hub.docker.com/r/kestra/kestra

There are 23 plugins v0.10.0 bundled in the said image
Plugins that reference io.kestra.core.models.tasks.WorkerGroup are crashing.
Since Worker Group was added in 0.10.0 and is not available in 0.9.x

For example redis plugin:

`kestra       | 2023-07-11 01:16:22,344 ERROR io-executor-thread-7 i.k.w.controllers.ErrorController Error loading BeanIntrospection for type [class io.kestra.plugin.redis.ListPush]: Could not initialize class io.kestra.plugin.redis.$ListPush$Introspection
kestra       | io.micronaut.core.beans.exceptions.IntrospectionException: Error loading BeanIntrospection for type [class io.kestra.plugin.redis.ListPush]: Could not initialize class io.kestra.plugin.redis.$ListPush$Introspection
kestra       |  at io.kestra.core.contexts.KestraValidator.findIntrospection(KestraValidator.java:74)
kestra       |  at io.kestra.core.contexts.KestraValidator.getBeanIntrospection(KestraValidator.java:45)
kestra       |  at io.micronaut.validation.validator.DefaultValidator.cascadeToOne(DefaultValidator.java:1347)
kestra       |  at io.micronaut.validation.validator.DefaultValidator.cascadeToIterableValue(DefaultValidator.java:1268)
kestra       |  at io.micronaut.validation.validator.DefaultValidator.access$800(DefaultValidator.java:98)
kestra       |  at io.micronaut.validation.validator.DefaultValidator$3.indexedValue(DefaultValidator.java:1166)
kestra       |  at io.micronaut.validation.validator.extractors.DefaultValueExtractors.lambda$new$4(DefaultValueExtractors.java:62)
kestra       |  at io.micronaut.validation.validator.DefaultValidator.lambda$doValidate$9(DefaultValidator.java:1137)
kestra       |  at java.base/java.util.Optional.ifPresent(Unknown Source)
kestra       |  at io.micronaut.validation.validator.DefaultValidator.doValidate(DefaultValidator.java:1137)
kestra       |  at io.micronaut.validation.validator.DefaultValidator.validate(DefaultValidator.java:166)
kestra       |  at io.micronaut.validation.validator.DefaultValidator.validate(DefaultValidator.java:133)
kestra       |  at io.kestra.core.models.validations.ModelValidator.isValid(ModelValidator.java:25)
kestra       |  at io.kestra.core.models.validations.ModelValidator.validate(ModelValidator.java:18)
kestra       |  at io.kestra.webserver.controllers.FlowController.lambda$validateFlows$8(FlowController.java:460)
kestra       |  at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
kestra       |  at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
kestra       |  at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
kestra       |  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
kestra       |  at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
kestra       |  at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
kestra       |  at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
kestra       |  at io.kestra.webserver.controllers.FlowController.validateFlows(FlowController.java:467)
kestra       |  at io.kestra.webserver.controllers.$FlowController$Definition$Intercepted.$$access$$validateFlows(Unknown Source)
kestra       |  at io.kestra.webserver.controllers.$FlowController$Definition$Exec.dispatch(Unknown Source)
kestra       |  at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
kestra       |  at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
kestra       |  at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:143)
kestra       |  at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
kestra       |  at io.kestra.webserver.controllers.$FlowController$Definition$Intercepted.validateFlows(Unknown Source)
kestra       |  at io.kestra.webserver.controllers.$FlowController$Definition$Exec.dispatch(Unknown Source)
kestra       |  at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
kestra       |  at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
kestra       |  at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
kestra       |  at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
kestra       |  at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
kestra       |  at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
kestra       |  at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
kestra       |  at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
kestra       |  at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
kestra       |  at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
kestra       |  at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
kestra       |  at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
kestra       |  at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
kestra       |  at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:206)
kestra       |  at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
kestra       |  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
kestra       |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
kestra       |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
kestra       |  at java.base/java.lang.Thread.run(Unknown Source)
kestra       | Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.kestra.plugin.redis.$ListPush$Introspection
kestra       |  at io.kestra.plugin.redis.$ListPush$IntrospectionRef.load(Unknown Source)
kestra       |  at io.kestra.core.contexts.KestraValidator.lambda$findIntrospection$0(KestraValidator.java:64)
kestra       |  at java.base/java.util.Optional.map(Unknown Source)
kestra       |  at io.kestra.core.contexts.KestraValidator.findIntrospection(KestraValidator.java:59)
kestra       |  ... 49 common frames omitted
kestra       | Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: io/kestra/core/models/tasks/WorkerGroup [in thread "io-executor-thread-6"]
kestra       |  at io.kestra.plugin.redis.$ListPush$Introspection.<clinit>(Unknown Source)
kestra       |  ... 53 common frames omitted`

**Comment by Skraye** [comment]
Hello @acidumirae, thank you for noticing! This should be fixed with the new 0.9.8.

**Comment by loicmathieu** [comment]
@acidumirae can you try the new version and confirm that it is now working fine?

**Comment by acidumirae** [comment]
Docker image v0.9.8 is not crashing (minus bugs fixed on v0.10.0), so it is working fine. Thank you!
