### ISSUE TITLE
Blueprint could have a version attached to it to match Kestra/Plugins version

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1735]
### Feature description

User working on the X.1 version will see any blueprints released with plugin available on X.2 but couldn't use it.

How do we deal with that ?

adding a blueprint version ?
filtering blueprints?

**Comment by anna-geller** [comment]
Blueprints currently always match the latest version:
- if some blueprints are outdated and we didn't catch up keeping them up to date, users should open an issue 
- if some tasks, such as e.g. WorkingDirectory are available only with a specific Kestra version e.g. >= 0.9.0, we set that in the plugin/task docs directly

once we introduce plugin versioning on the workflow (this is planned afaik), we'll be able to set the used plugin version directly within the workflow

closing with a comment, please reopen if sth still needs discussion
