### ISSUE TITLE
When using LocalFiles task in blueprints, there is an error: `Unprocessable Entity: Invalid entity: Invalid type: io.kestra.core.tasks.storages.LocalFiles`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1738]
### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/86264395/7ef99457-c0f4-4802-9a66-83aa21c03742)

### Environment Information

- Kestra Version: develop-full, EE demo, 0.10.1 snapshot

**Comment by brian-mulier-p** [comment]
Due to lack of API rebuild after release, it missed the new Kestra core version which includes the new task.
A rebuild + restart fixed the issue
