### ISSUE TITLE
Windows executable is not working in 0.10.0

### ISSUE THREAD

**Issue by vivane** [kestra-io/kestra#1750]
### Expected Behavior

Server should run with no issues.

### Actual Behaviour

Starting server gives the following output and fails.
`
'PK♥♦¶∟│▓╬jü2Θ╔' is not recognized as an internal or external command,                              operable program or batch file.                                                                     '┘O)¼╫↓Σ▌DEÇ─m▲' is not recognized as an internal or external command,                              operable program or batch file.                                                                     '¬█¢S‼' is not recognized as an internal or external command,                                       operable program or batch file.                                                                     
`

### Steps To Reproduce

1. Download the server JAR-file as instructed at https://kestra.io/docs/administrator-guide/deployment/manual.
2. Ran following command:
`kestra-0.10.0.cmd server standalone --config config.yml`
3. Server start fails.
4. Server runs OK with 0.9.5.

Here is the configuration file:
`
datasources:
  postgres:
    url: jdbc:postgresql://localhost:5432/kestra
    driverClassName: org.postgresql.Driver
    username: kestra
    password: k3str4
kestra:
  repository:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"
  queue:
    type: postgres
  tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
  url: http://localhost:8080/
`

### Environment Information

- Kestra Version: 0.10.0
- Operating System (OS / Docker / Kubernetes): Windows 10, no docker
- Java Version (If not docker): 17.0.7

**Comment by loicmathieu** [comment]
Hi @vivane,
This issue has been fixed already, we will release a new version soon (probably today) with the fix.
