### ISSUE TITLE
Add optional `end` date to backfills

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1762]
### Feature description

Currently, backfills trigger runs between the start date and the current date. Often users want to backfill only specific periods between the start and end date as in this Taxi Trip data example backfilling data only between January and April https://github.com/kestra-io/kestra/issues/1733. 

![image](https://github.com/kestra-io/kestra/assets/86264395/d28e0c0b-1d8f-4a83-943c-10d9f59076d9)

**Comment by loicmathieu** [comment]
Does this means that the trigger will stop to run after it hit the end date?

As currently, backfil allow to trigger old dates, then the trigger will work infinitely.

**Comment by anna-geller** [comment]
Extra: only add backfill to the UI when Schedule trigger is present in the flow definition

**Comment by anna-geller** [comment]
Closing this issue as we will likely deprecate the option to configure backfills via code entirely. Backfills will now be supported only via UI/API calls, not via making changes to the source code. This has several benefits:
1. No Terraform state conflicts -- requiring making changes to code from the UI to backfill past Executions wreaks havoc to the Terraform state.
2.  No need to bump up Flow Revision or commit code via CI/CD only to backfill a (potentially single) run backfilling some data.
