### ISSUE TITLE
New Plugin - Tableau

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1778]
### Feature description

MVP : refresh (https://medium.com/snake-charmer-python-and-analytics/triggering-extract-refreshes-for-tableau-server-workbooks-and-data-sources-using-the-rest-api-d4a8b8c001bf)

**Comment by anna-geller** [comment]
Closing as not in scope for now -- added it to a list of possible ideas for the future. We can revisit it if a customer or community member requests that integration.
