### ISSUE TITLE
Blueprint page feedback

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#1780]
### Expected Behavior

Little feedback on dark mode with light mode editor :

the first line must be white 
<img width="1191" alt="Capture d’écran 2023-07-19 à 20 41 14" src="https://github.com/kestra-io/kestra/assets/125994028/1052c97f-6366-48f7-b2c0-51839fa65e0b">

Thanks

### Environment Information

- Kestra Version: 0.11.0
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by MilosPaunovic** [comment]
This has been completed in the meantime, so closing it.
