### ISSUE TITLE
New plugin - HTTP

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1785]
### Feature description

- [ ] Move http to a new specific plugin
- [ ] let users choose to put requests response into internal storage (request body for example)
- [ ] create a new `Upload` task (basic POST) + keep the `Download` task (basic GET)
- [ ] Remove the hard limit of 10mb
- [x] https://github.com/kestra-io/plugin-fs/issues/63

**Comment by tchiotludo** [comment]
take care that the 10mb limit is voluntary on the `Request` plugins. 
We keep all the data in the outputs and we don't expect people to have largest data on theses outputs, I will even more tend to use a lower value like 1mb

**Comment by loicmathieu** [comment]
The idea can be to allow to store the response for the Request task, or at least allow configuration of this limit.
A lot of users complain about this one.

**Comment by tchiotludo** [comment]
you can already configure based on this [options](https://github.com/kestra-io/plugin-fs/blob/208ca5787e9ae2589a96343fd4ad3627a1b5240d/src/main/java/io/kestra/plugin/fs/http/AbstractHttp.java#L304)

**Comment by anna-geller** [comment]
related https://github.com/kestra-io/kestra/issues/2299

**Comment by anna-geller** [comment]
for now closing in favor of this https://github.com/kestra-io/kestra/issues/2304 + added to the discussion board to decide whether the sub-plugin must be moved 

(HTTP trigger has a separate issue already)
