### ISSUE TITLE
UI: Timeout exceeded

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1810]
### Issue description

![image](https://github.com/kestra-io/kestra/assets/86264395/80b22006-a33a-45f8-a86c-93f40a5d435a)

![image](https://github.com/kestra-io/kestra/assets/86264395/22d9a756-0d32-4ad7-8e91-faa87a21b6e2)

![image](https://github.com/kestra-io/kestra/assets/86264395/2d1b84f3-c7af-447d-9325-39fe1ee120ef)

jump dumping it all as I have no idea what can be helpful here 😅

**Comment by brian-mulier-p** [comment]
As we can see the /logs/search is causing the timeout, I guess it has to do with what we talked about this morning @loicmathieu with index on Postgres. Still I don't know why it has loaded on Blueprint page, did you come from another page before ?

**Comment by anna-geller** [comment]
yup, it's very likely that I can from another page 👍
