### ISSUE TITLE
Add the VS Code Extension to Extension Marketplace

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1818]
### Feature description

Following the creation of the [VS Code extension](https://github.com/kestra-io/vscode-kestra/tree/main), publishing it to the VS Code Extension marketplace

https://marketplace.visualstudio.com/vscode

**Comment by brian-mulier-p** [comment]
Note that it will be shipped for the V0.11.0 but it requires the core and API to be released first

**Comment by brian-mulier-p** [comment]
https://marketplace.visualstudio.com/items?itemName=kestra-io.kestra
