### ISSUE TITLE
Blueprint cause issues in Editor

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1847]
### Actual Behaviour

There are different cases:

- sometimes the UI raise 503 errors (probably the API is down)
- I got the following screen while accessing the editor view (while topology, exeuction and other Flow view were working)

![image](https://github.com/kestra-io/kestra/assets/46634684/27d65300-eec4-444b-a26d-0fdf4d48bfcb)

[Slack thread for reference](https://kestra-io.slack.com/archives/C04HTFM3VL6/p1690983912027399)

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by brian-mulier-p** [comment]
Tried to reproduce even with the 503 thing I couldn't manage to do it

**Comment by loicmathieu** [comment]
The issue is that blueprints are loaded in the editor even if the blueprint tab is not displayed.
This will also creates un-needed API calls that will overload the blueprint API.

@brian-mulier-p we should load blueprint only if the tab is selected in the editor, not always!
