### ISSUE TITLE
Add keyboard shortcut to comment lines

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1867]
### Feature description

Like in VS Code, I could be nice to add a shortcut in the editor to comment lines. CTRL+SHIFT+/

**Comment by anna-geller** [comment]
it already exists:

command + K + C = comment
command + K + U = uncomment

or do you mean changing those or renaming those? I also use them quite a lot!

**Comment by Ben8t** [comment]
Ohh, I wasnt aware of this ! Very nice ! Maybe we should create a documentation about available shortcuts then

**Comment by Ben8t** [comment]
Closing this one anyway
