### ISSUE TITLE
Logs page freeze / lag when dbt plugin generates a lot of models results

### ISSUE THREAD

**Issue by aballiet** [kestra-io/kestra#1885]
### Expected Behavior

We expect the `logs` section of dbt cloud trigger run to load in a reasonable amount of time.

### Actual Behaviour

A lot of timeout and laggy page / blocked / crashing.

![image](https://github.com/kestra-io/kestra/assets/25565600/26e8a829-9495-45f7-8f2c-2475a3746e1c)

### Steps To Reproduce

Run large project dbt cloud trigger run from Kestra

### Environment Information

- Kestra Version: 0.11.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes): Kubernetes
- Java Version (If not docker):

**Comment by anna-geller** [comment]
trying to understand the issue better: when you say logs, do you mean the parsing of the manifest to display model names is what generates some extra lag, correct @aballiet? 

Is this a feature that is required in your use case? I wonder whether we should provide a property to allow skipping model parsing. WDYT?

We also have that open issue to allow rendering those in the topology view, which could be friendlier than displaying those at the end of the logs https://github.com/kestra-io/plugin-dbt/issues/38

**Comment by aballiet** [comment]
Yes I think displaying just the logs like we can have in the Gantt is fine. No need to display one block per model.

Did a quick Loom video to show the bug

<img width="1264" alt="image" src="https://github.com/kestra-io/kestra/assets/25565600/fccd6128-0fa8-4099-b56b-2a64f2778c44">

Yes a fix is required because currently clicking on "logs" freezes the web browser :(

**Comment by Skraye** [comment]
Hi @aballiet ! Could you show us your browser console? That could leverage if the issue is coming from the front or from the back

**Comment by aballiet** [comment]
Nothing in console :/

**Comment by anna-geller** [comment]
Note from the team: It seems to be a frontend issue -- we create so many dynamic tasks for DBT that it can be challenging to handle that in the UI with thousands of models.

**Comment by brian-mulier-p** [comment]
Hello @aballiet can you try again with the latest SNAPSHOT version which includes [this](https://github.com/kestra-io/kestra/issues/1869) ?
I think it will fix the issue :+1:

**Comment by brian-mulier-p** [comment]
Also maybe it's because you have the "expand all" settings for logs which make the page display everything at once, might help with FAILED only or collapse all at first.
Still you can try it as-is with the new version I made a lot of improvement on the page

**Comment by aballiet** [comment]
Same problem 👎 

I changed to : 

![image](https://github.com/kestra-io/kestra/assets/25565600/2eb140f1-24b4-4594-9f28-5cf0d7c50d97)


![image](https://github.com/kestra-io/kestra/assets/25565600/61240a34-2888-4499-a089-5eb335376993)

**Comment by aballiet** [comment]
Frozen / buggy

**Comment by aballiet** [comment]
![image](https://github.com/kestra-io/kestra/assets/25565600/927c1d0a-311c-45cb-bf1f-d59fb950fcc2)

Log count increases 🚀 💥

**Comment by aballiet** [comment]
![image](https://github.com/kestra-io/kestra/assets/25565600/22daa331-a9e9-4ff6-ae8b-b99612172948)

**Comment by anna-geller** [comment]
@aballiet can you try setting `parseRunResult` to false? (you need the latest plugin with this https://github.com/kestra-io/plugin-dbt/commit/1ba6aa721d7e758caa4fea37343e8cf675469451)

**Comment by aballiet** [comment]
> @aballiet can you try setting `parseRunResult` to false? (you need the latest plugin with this https://github.com/kestra-io/plugin-dbt/commit/1ba6aa721d7e758caa4fea37343e8cf675469451)

Nice! Now we bundle our custom docker image to have more control on upgrades. I can try by EOW 😊

**Comment by brian-mulier-p** [comment]
Those 3 issues will also provide a smoother log explore experience:
- https://github.com/kestra-io/kestra/issues/2187
- https://github.com/kestra-io/kestra/issues/2188
- https://github.com/kestra-io/kestra/issues/2189

**Comment by aballiet** [comment]
> Those 3 issues will also provide a smoother log explore experience:
> 
> * [Debounce execution follow to prevent too much rerendering #2187](https://github.com/kestra-io/kestra/issues/2187)
> * [Long Logs tab loading time for too many taskruns #2188](https://github.com/kestra-io/kestra/issues/2188)
> * [Scrolling is not smooth when dealing with large amount of logs #2189](https://github.com/kestra-io/kestra/issues/2189)

Thanks a lot @brian-mulier-p 🔥
