### ISSUE TITLE
Uniformise version number in the whole app 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#19]
Actually, some files have version hardcoded : 
* org/kestra/webserver/Application.java
* org/kestra/cli/App.java
* package.json

We need to find a way to only rely on gradle.properties

**Comment by eregnier** [comment]
```groovy

import groovy.json.JsonSlurper
import groovy.json.JsonOutput

data = new JsonSlurper().parse(new File("package.json"))
data["version"] = "0.1.1"
def fileContent = JsonOutput.prettyPrint(JsonOutput.toJson(data))
new File("package.json").write(fileContent)

```

This is a working solution to update **package.json** version
