### ISSUE TITLE
Display some file preview based on plugin 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1908]
following this https://github.com/kestra-io/kestra/issues/1767. 
Now display file preview for custom extensions (csv, avro, ...).
Each plugin will be able to expose a file preview for a specific task: 
```java
public FileRenderer filepreview(String uri) 
```
(maybe based on the Output of the plugin)

**Comment by anna-geller** [comment]
not specific enough, we can reopen when a specific format is needed and isn't available yet like with e.g.:
- https://github.com/kestra-io/kestra/issues/5332
- https://github.com/kestra-io/kestra/issues/2926
