### ISSUE TITLE
New Storage - S3

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1911]
Create a true s3 storage that will allow to inherited AWS credentials (removing access key and secret keys)

**Comment by anna-geller** [comment]
big +1

would be great to allow S3 storage to work with IAM roles for folks deploying Kestra to AWS EKS

**Comment by iNikitaGricenko** [comment]
I will do it

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/storage-s3/pull/5
