### ISSUE TITLE
Add disable or remove trigger on the Admin triggers page

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1912]
### Feature description

A user reported a case when a flow is still triggered from a schedule whereas the flow has been deleted.

Even if this case should normally never occurs, this can be helpful to have some options on the new admin triggers page to disable a trigger (or remove it ... or check it ... or whatever will work around this kind of issue).

**Comment by jeremycopinlm** [comment]
Being able to remove some triggers on this screen could be great
Sometimes we see there remaining triggers for deleted flows
