### ISSUE TITLE
Change the preview icon to make the preview feature more visible

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1919]
### Feature description

maybe it's just me but I wasn't even aware that the Preview feature has already been merged because the 👁️ icon is so small

![image](https://github.com/kestra-io/kestra/assets/86264395/e21d8c98-7fc0-4b21-8500-edc2003cd5f1)

it's worth considering making it more prominent - maybe in purple and with a similar icon to "Show task logs" icon - perhaps even with the text "Result preview" next to it? 

![image](https://github.com/kestra-io/kestra/assets/86264395/e2a71217-fbb2-43df-a50f-c3a3e0afc945)

it seems suitable to indicate it's a clickable button providing Preview functionality

cc @Nico-Kestra

**Comment by Ben8t** [comment]
💯 - it was planned in the original issue https://github.com/kestra-io/kestra/issues/1769

don't know it was not implemented (more over I remember a discussion with @Skraye isn't 🤔 ?)

**Comment by tchiotludo** [comment]
I changed to that: 
![Image](https://github.com/kestra-io/kestra/assets/2064609/5d1889f0-2e06-40dd-8ec0-1ca2f2b19f94)


is this better?

**Comment by anna-geller** [comment]
so. much. better!
