### ISSUE TITLE
Pause a running execution manually

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1937]
- Add in the ui / api a wait to pause a running execution 
- The pause at the execution level will prevent creation of new tasks 
- But will not stop the running one (Runnable only) 
- The running one status must be correctly reported on the taskrun 
- a failed task will failed the execution even if the flow is paused

## Customer request

They would like the ability to ad-hoc pause flow execution. The use case would be if a new flow was rolled out to production while someone is inspecting it if they noticed something was wrong, they could pause while investigations take place.

Our current waitFor solution wouldn't cover this as they wouldn't know when they would need/want to pause an execution.

The implementation, however would be similar to what we have already, when a pause request is sent, Kestra will pause after the execution of the current task. This must be exposed as an API as well.

**Comment by Ben8t** [comment]
linked to #1449 and #1041

**Comment by anna-geller** [comment]
Estimate of difficulty: not very hard (so a few hours), but if linked to the Pause task, it might take more time to handle edge cases 

changed to P1
