### ISSUE TITLE
Date sort on Triggers administration

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1943]
### Feature description

Sort for dates have been disabled in #1942 since it requires to populate date columns from value in triggers table to be able to sort on it.
Add these columns and readd the sort option

**Comment by brian-mulier-p** [comment]
I'm wondering about the usage of it so I add triage. IMO the best thing would be to have another column with the "delay" between the last trigger occurrence and the last occurrence which should have occured based on the cron. This way you could easily identify the most delayed triggers which are probably interesting and safe to unlock

**Comment by MilosPaunovic** [comment]
Added back sorting on `nextExecutionDate` filed, closing this issue for now.

Relates to https://github.com/kestra-io/kestra/issues/6317.

**Comment by brian-mulier-p** [comment]
@anna-geller WDYT about the delay thing? Maybe worth another issue?

**Comment by anna-geller** [comment]
great idea! I think seeing which Scheduled Executions are delayed seems to be super valuable info to the user ❤️  since you know the context best, can you open an issue Brian? (just to make sure I don't miss important details)
