### ISSUE TITLE
Improve Settings page display

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1947]
Provide more structured/organized settings:

- Group settings per topics, e.g., Language & Appearance, Editor, Environment, Execution.
- Reduce the size of unnecessarily large inputs

https://www.figma.com/file/ew0uXk0NRXJ2NBBJTNe2n1/UI?type=design&node-id=647%3A4752&mode=design&t=7So8q4uLoBLC3djL-1

![Settings (1)](https://github.com/kestra-io/kestra/assets/86264395/e642d52e-d750-4ac5-9a51-46f2e7f1318c)

**Comment by Nico-Kestra** [comment]
<img width="1432" alt="Capture d’écran 2023-08-24 à 18 06 32" src="https://github.com/kestra-io/kestra/assets/125994028/f4ea4650-8e67-45ee-af07-f4a5a77fe99c">
[Figma](https://www.figma.com/file/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?type=design&node-id=2654%3A69358&mode=design&t=47O6AFhLt29YOd2a-1)

**Comment by Nico-Kestra** [comment]
I think it was interesting to have a third option for the theme mode: "Sync with system."
Is it difficult to implement?

**Comment by tchiotludo** [comment]
@Nico-Kestra, no, please create a separate issue :+1:

**Comment by anna-geller** [comment]
![image](https://github.com/kestra-io/kestra/assets/86264395/8618f6d2-1a70-40e5-86ae-d77440c9afb1)
