### ISSUE TITLE
Allow disabling schedule after a failed execution

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1951]
## Problem

Often, when a scheduled data pipeline is broken and fails, a user may want to disable the schedule after the failed execution and manually re-enabling the scheduled trigger after validating and fixing the issue.

This might be useful for several reasons:
1. Avoid rerunning subsequent scheduled workflows if it's known that a pipeline is broken (might be due to reasons outside of the flow's control e.g. issues in upstream source systems) 
2. Avoid unnecessary compute e.g. rerunning the next scheduled dbt runs if it's clear that there is some issue in the pipeline

## Possible solution

Add a boolean property to the Schedule trigger named `dependsOnPast`

Using this name of the property will be useful to folks familiar with Airflow's [depends_on_past](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html#concepts-depends-on-past) property.

- `dependsOnPast` should be by default set to false
- If set to true, the status of the trigger will be set as `disabled: true` when the flow fails.
- we should make sure to log that information: when the `disabled` toggle is set to `true` due to a previous failure, this should be visible in the logs

**Comment by tchiotludo** [comment]
take care, the design to disable didn't work, appending `disabled: true` will update the source and I don't think we want to update the source

**Comment by anna-geller** [comment]
fair point, Terraform would complain! :) 

what is an alternative way of handling this?

**Comment by tchiotludo** [comment]
I think we will handle that one on the same way we will handle backfill (with previous & end date), so on the ui, we will have a modal for removing the disabled flagged. 
Just need to design this modal

**Comment by anna-geller** [comment]
closing as this will be doable after adding stopAfter trigger property https://github.com/kestra-io/kestra/issues/2964
