### ISSUE TITLE
Issue with css Border color 

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#1975]
### Expected Behavior

In both dark and light modes, we have an issue with the border color.

<img width="1750" alt="Capture d’écran 2023-08-28 à 11 44 54" src="https://github.com/kestra-io/kestra/assets/125994028/88697991-5986-40bb-b8f5-f945e4c18ee2">
<img width="1639" alt="Capture d’écran 2023-08-28 à 11 45 06" src="https://github.com/kestra-io/kestra/assets/125994028/68f0374a-d2a4-4e4b-beb4-a55e6ef9922c">
The color is #2F3342 on dark mode and #E5E4F7 on light mode

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by Skraye** [comment]
This has been fixed by @tchiotludo
