### ISSUE TITLE
Error on click on documentation page

### ISSUE THREAD

**Issue by eregnier** [kestra-io/kestra#199]
![image](https://user-images.githubusercontent.com/5399780/98002533-0ea44280-1dee-11eb-9d16-6dcbefe63ed4.png)

**Comment by eregnier** [comment]
Is it something only for me ?

**Comment by tchiotludo** [comment]
I think, you need to rebuild the project to get ride of this error. 
or all the out directory of intellijidea

**Comment by eregnier** [comment]
That was it indeed.
