### ISSUE TITLE
Better error / warning display on flow validation

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1993]
### Feature description

Right now the errors display on flow validation is a bit rude to read as they are on a single line separated by ',' (see below)
![image](https://github.com/kestra-io/kestra/assets/37618489/74749c68-d861-4980-942c-b022205f9a7b)

Would be great to have line-separated errors.

Also for a more user-friendly display, would be great to replace errors / warnings path from the "type" property if available at given path to easily know which task / condition / trigger is having issue.

First implementation thought would be to try to get "type" property starting from the exact path and going backward till we eventually find a value which we replace.

ex.

Bash task deprecated => "tasks[0] is deprecated"
==> take tasks[0] starting from flow and get the type property
=> "Bash is deprecated"

MyTask.deprecatedProp is deprecated => "tasks[0].deprecatedProp is deprecated"
==> take tasks[0].deprecatedProp => value don't have a "type" property so we go backward
==> take tasks[0].type => MyTask
=> "MyTask.deprecatedProp is deprecated"

Still need to figure out if this replacement should be done at backend level (which would remove any path-related information) or if it should be done at front level to keep this information if needed for future features

**Comment by anna-geller** [comment]
seems no longer relevant after moving the wearing to the new editor design 

![image](https://github.com/kestra-io/kestra/assets/86264395/ecc6474d-fe01-4cb0-9d17-fb0ccf9af2b8)

if still relevant, feel free to reopen
