### ISSUE TITLE
Improve the release process (incl. docker builds)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1996]
### Notes from “2023 in Review” retro

- [x]  improve the link between OSS and EE
- [x]  the way we release plugins is too difficult
- [ ]  bugfix releases can include the wrong plugins
- [ ]  publish plugins independent of Maven central (private registry) - 40 min delay can be saved or use the [snapshot release Maven central](https://s01.oss.sonatype.org/content/repositories/releases/io/kestra/)

## Problem 

To build *-full images, we need the core to be built first. However, the core will try to build an image with all plugins that can't be released with the base/core image.

## Possible solutions

Split the main release action into smaller jobs that depend on each other: first core, then the one with plugins https://github.com/kestra-io/kestra/blob/develop/.github/workflows/main.yml

**Comment by loicmathieu** [comment]
We now improve our release process and split building and publishing to Maven, and publishing images so we no longer have issues with our release process.
We can now close this issue, as we're happy with this new release process.
