### ISSUE TITLE
Icons issue blueprints

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#1997]
### Expected Behavior

The parallel icon is not the same in the topology and in the list of used blueprints.
The one in the topology is the correct one.

<img width="1331" alt="Capture d’écran 2023-08-30 à 15 18 14" src="https://github.com/kestra-io/kestra/assets/125994028/710bff75-e070-42b7-8f16-4fcc242b3892">

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
done 

![image](https://github.com/kestra-io/kestra/assets/86264395/94294f81-db3b-41ca-be5e-bb5a678870d3)
