### ISSUE TITLE
Issue with Zoom Option Colors in Dark Mode

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#1998]
### Expected Behavior

<img width="291" alt="Capture d’écran 2023-08-30 à 15 20 13" src="https://github.com/kestra-io/kestra/assets/125994028/a6b65b4e-5630-4d51-8673-200832bae1c5">

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
![image](https://github.com/kestra-io/kestra/assets/86264395/62a76dd4-0d45-4be5-80c2-3d13a9c61cd3)

done
