### ISSUE TITLE
New Topology: Issue color failed

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#1999]
### Expected Behavior

The arrowhead should be red.
<img width="375" alt="Capture d’écran 2023-08-30 à 15 20 59" src="https://github.com/kestra-io/kestra/assets/125994028/a1ca3676-70ac-42d0-91f5-55df54f5cd53">

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
done
![image](https://github.com/kestra-io/kestra/assets/86264395/c2d3148e-4aa2-4ac5-9e47-9f557a2a2256)
