### ISSUE TITLE
[UI] Make the Executions tab configurable via Settings

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2010]
### Feature description

Currently, the Gantt view is the default view after creating a new flow.

While the Gantt view might be helpful for troubleshooting the duration of tasks in very complex workflows, the Logs tab seems more important to be displayed at first. 

After you create a new workflow, it would be great to display the logs tab by default. Especially after the recent changes and planned additions (such as including logs from subflows), this view becomes the most useful and most commonly used one:

![image](https://github.com/kestra-io/kestra/assets/86264395/c0108379-a581-4f34-9b1f-6c706b47ae14)

## Alternative 

An alternative might be adding a Setting section with a dropdown menu that allows users to set the default Executions tab:
1. Logs (default)
2. Gantt
3. Topology
4. Overview
5. Outputs
6. Metrics
7. Audit Logs (EE only)

**Comment by tchiotludo** [comment]
I will opt to a setting that will match oss at first with only:
1. Gantt
2. Topology
3. Overview

Don't really think the others one is useful. 
I think to kept gantt as default one for now?

**Comment by anna-geller** [comment]
It would be great to have the possibility of seeing the logs tab by default as it gives real-time updates on the progress of the tasks in terms of application logic, not only task run duration

FWIW I find the log view so information-rich that I rarely need the Gantt view

If you want to keep Gantt by default, perhaps this order in the Settings would be a good compromise: 

1. Gantt (default)
2. Logs
3. Topology
4. Overview

I'd still vote for Logs as the default but understand why you'd prefer to keep Gantt as the default, It looks nice in the demos when parallel bars start moving :)

**Comment by tchiotludo** [comment]
It's mostly for whaou effect for first run in kestra but maybe we can make Gantt the default one after the getting started  ?

**Comment by anna-geller** [comment]
yes that works, all options work for me as long as there is a setting allowing configuring Logs as the default tab 👍  

it seems we can:
1. Keep the Gantt view as the default view, as today (no changes here) 
2. Provide a dropdown in the Settings allowing to set the default Executions tab to be Gantt (default), Overview, Logs or Topology

if it sounds good, I'll ask Nico to add it to the new Settings design https://github.com/kestra-io/kestra/issues/1947#issuecomment-1693197834

**Comment by anna-geller** [comment]
@Nico-Kestra let's talk about the design for this :)

**Comment by Nico-Kestra** [comment]
<img width="1742" alt="Capture d’écran 2023-09-04 à 18 52 49" src="https://github.com/kestra-io/kestra/assets/125994028/a58e225f-1728-4a89-8c2d-7b6747d08d76">

**Comment by anna-geller** [comment]
@Nico-Kestra 2 small requests 
![image](https://github.com/kestra-io/kestra/assets/86264395/b16bb032-22e4-4160-9271-68bd1744e657)

**Comment by MilosPaunovic** [comment]
Would say this is done via https://github.com/kestra-io/kestra/issues/5775, waiting for @anna-geller to confirm and close if it is.
