### ISSUE TITLE
Documentation query schema issue.

### ISSUE THREAD

**Issue by eregnier** [kestra-io/kestra#202]
![image](https://user-images.githubusercontent.com/5399780/98013282-795b7b00-1dfa-11eb-8fe4-be770846142a.png)
![image](https://user-images.githubusercontent.com/5399780/98013381-9a23d080-1dfa-11eb-8c5d-6e1a358b190a.png)

**Comment by tchiotludo** [comment]
Your plugin must not be on last version so we can't generate the schema

**Comment by eregnier** [comment]
Ok, i'll remember.
