### ISSUE TITLE
Add a configuration flag to mark a flow using listeners in the Editor as invalid 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2024]
### Issue description

If a user includes `listeners` in a flow on Kestra 0.12.0 and higher, the Editor should display a warning that the flow is invalid due to that deprecated feature. The goal is to prevent new flows with listeners. 

Such a warning should be displayed in both the UI and in the VS Code extension.

**Comment by tchiotludo** [comment]
it's done like this : 

![Image](https://github.com/kestra-io/kestra/assets/2064609/aacaa00c-b689-43e8-b19c-997f2b011929)

seems to be sufficient? We don't have a way for now on the code editor (not supported by vscode as I know)
