### ISSUE TITLE
[UI] Allow jumping to the next log of a specific log level type

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2045]
## Problem

Currently, Kestra allows filtering for specific log levels. This allows users to filter only for WARN or ERROR level logs, as shown in the image below. 

![image](https://github.com/kestra-io/kestra/assets/86264395/91405999-b717-4042-bcb1-a632113a6381)

The problem with this approach is that it often lacks context. Seeing the WARN-level logs only (without the logs that came before or after), sometimes doesn't provide enough information necessary for troubleshooting. Some users would instead like to see a couple of logs that came before or after that specific WARN or ERROR log.

## Recommendations from the community

One possible solution could be an option to set a higher log level e.g. DEBUG or INFO level, and allow users to "jump" to a specific lower-level log message. One user recommended this solution from dbt Cloud:

![image](https://github.com/kestra-io/kestra/assets/86264395/4a422ef9-6f12-458d-969e-7ccfef3b4a91)

This lists a lower log level than the one selected in the dropdown and allows users to jump to the next log of a specific level.

**Comment by aballiet** [comment]
Would be awesome, thanks @anna-geller !

**Comment by anna-geller** [comment]
![Executions](https://github.com/kestra-io/kestra/assets/86264395/2a979c2b-735e-41dc-a150-e21c29f3461d)

**Comment by aballiet** [comment]
Looks amazing @anna-geller

**Comment by Nico-Kestra** [comment]
Hello, I've cleaned up the file!

<img width="1604" alt="Executions_Logs" src="https://github.com/kestra-io/kestra/assets/125994028/50355b4d-e517-4d3b-88af-e4df2336b241">

[Figma](https://www.figma.com/file/ew0uXk0NRXJ2NBBJTNe2n1/UI?type=design&node-id=645%3A4590&mode=design&t=7So8q4uLoBLC3djL-1)

**Comment by aballiet** [comment]
> Hello, I've cleaned up the file!
> 
> <img alt="Executions_Logs" width="1604" src="https://private-user-images.githubusercontent.com/125994028/316467315-50355b4d-e517-4d3b-88af-e4df2336b241.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjMyOTMsIm5iZiI6MTcxMTM2Mjk5MywicGF0aCI6Ii8xMjU5OTQwMjgvMzE2NDY3MzE1LTUwMzU1YjRkLWU1MTctNGQzYi04OGFmLWU0ZGYyMzM2YjI0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxMDM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDFiYTY0NTY1ODljNTJlOWZiYzE0ZjZmMzYwOTY2Y2Q5MjkwNDlmZTFlZjdjZWFiMzVlYjk1MDhhODVmOWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7p0G3ImqEXP6XphxbH0aNkyvw71IxVdfWw_uOqVT_fM">
> [Figma](https://www.figma.com/file/ew0uXk0NRXJ2NBBJTNe2n1/UI?type=design&node-id=645%3A4590&mode=design&t=7So8q4uLoBLC3djL-1)

AMAZING !!!

**Comment by anna-geller** [comment]
update, we synced with Brian that:
1. the filter must be kept and then we only show the levels below that so e.g. if you select INFO from the dropdown, trace and debug won't  be shown, you can only jump to the next logs starting from info
2. cursor must be implemented and needs to be highlighted so that user knows on which log level they currently are

![image](https://github.com/user-attachments/assets/79e09025-0cb9-4068-b58c-66e518432d27)

**Comment by brian-mulier-p** [comment]
So... after coding a bit, found out it's a really complex subject especially due to the fact that we're handling subflows transparently for the user leading to recursive components.
The draft (or reminder due to how poorly it's redacted) looks like this:
```
INFO[0-0]
WARN[0-1]

    // second taskrun, first taskrun
    WARN[1-0-0] > => @cursor=0-0 => cursor@0 = [1-0-0]
    DEBUG[1-0-1]
    INFO[1-0-2]
    // second taskrun, second taskrun, first taskrun
    INFO[1-1-0-0]
    ERROR[1-1-0-1]

WARN[2-0]

next(warn)
cursor@0 = [2-0]
==> [2-0] doesn't start with 1 so cursor@1 = undefined


next(error)
cursor@0 = [1-1-0-1]
==> [1-1-0-1] starts with 1 so cursor@1 = [1-0-1]
cursor@1 = [1-0-1]
cursor@1-1 = [0-1]

the top-level component is the only one with "handle-cursor=true"
```

a bit technical but it helps digging out further the subject.

I just saw that the issue got moved to 0.20.0. Maybe this subject can be postponed (I think it was in the current backlog when I took the issue). I can also go till the end but it can get complex quickly.
