### ISSUE TITLE
Investigate connection issue when multiple workers

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#2047]
Actually, we have some report that multiple worker increase the amount of thread globally. 
Normally we expect that all the workers thread use the global pool

**Comment by loicmathieu** [comment]
Do we have more information? 
Without more information I really have no idea what to look for.

**Comment by tchiotludo** [comment]
Just look at the amount of connection on the database and change the worker thread count to see if the number of connection increase

**Comment by loicmathieu** [comment]
OK, understood, so it's not multiple worker but multiple worker threads ;)

**Comment by loicmathieu** [comment]
I started Kestra with 1 worker thread => 10 connections (which is normal as it's the size of the pool)
I started Kestra with 128 worker threads and add load so all threads are used => 10 connections

So everything seems to be working as expected.
