### ISSUE TITLE
Zombie Worker Task Detection & Automatic Resubmission

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2055]
## Motivating user problems

We’ve seen some issues from the community struggling with Zombie tasks, e.g. [here](https://kestra-io.slack.com/archives/C03FQKXRK3K/p1693291677993079?thread_ts=1693213886.903819&cid=C03FQKXRK3K) — task runs for dbt Cloud jobs and Airbyte syncs get stuck in a `Running` state due to K8s pod restarts.

Kestra currently does not check whether the current execution still has task runs in progress running on a worker, i.e., there’s no heartbeat-like system for Zombie tasks on the JDBC backend. As a result, long-running processes such as a dbt Cloud job (or Airbyte sync) may have finished 30 min ago, yet they are still marked as “running” due to a pod restart that happened in between due to an Autoscaling event.

## Technical implementation

Currently, on the OSS edition, we have no auto-restart of tasks killed in case of pod restart/eviction — this is available only on EE. The only troubleshooting we provide for now is an [endpoint](https://kestra.io/docs/administrator-guide/monitoring#kestra-endpoints) that allows *seeing* the tasks running on the worker → the  `/worker` route will expose all currently running tasks on this worker.

On EE, we rely on internal Kafka heartbeats to detect unhealthy workers and worker tasks. However, this works only for EE and only with EE deployed with the Kafka backend.

## Required solution

JDBC setup needs to be able to detect unhealthy worker tasks and resubmit them.

Internal [Notion doc with implementation proposal](https://www.notion.so/kestra-io/JDBC-worker-heartbeat-and-job-resubmit-bac72558b9294674b7f126359f5f5253?pvs=4)

**Comment by aballiet** [comment]
🙏
