### ISSUE TITLE
Add System Labels incl. user and correlationId (an execution reference field)

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#2059]
see discussion [here](https://kestra-io.slack.com/archives/C03FEC452NQ/p1694106094726859?thread_ts=1694094495.975719&cid=C03FEC452NQ)

> There is a common notion of a key bound to execution instance. Existing flow processing tools refer to this key as business key or reference key. Such key is set at execution invocation and eventually gets copied to spawned child-processes/sub-flows. The key can be used for effective search based on the data being processed.
> 
> Such reference can be set via a combination of input & label, although having a dedicated property of execution might bring some benefits.
> 
> You have a data set which is characterized by a single ID - let's say a batch number. After you process that data, you receive a question regarding processing of that particular piece of data.
> It's like: "Show me the logs from processing of batch XYZ" or "When did we process the batch XYZ?"
> So you need to query the processing history and obtain all related executions.

We could add a simple reference on the execution, each subflow, trigger that start from that flow will copy the reference, and we need to have this field visible on the list and to allow search on that one.

**Comment by loicmathieu** [comment]
In the integration world (EAI/ESB/SOA) we refere at this by the name of correlation identifier (correlationId) as it allows to correlate multiple messages (here executions) together.

**Comment by anna-geller** [comment]
**More context:** The user's main problem that this issue is aimed to solve is the heavy reliance on `labels`. To analyze the state of workflows and task run metrics, users currently need to be able to filter the metrics based on Execution labels, which introduces a lot of complexity.

The idea of this reference field is to create a surrogate key comprised of multiple fields for easier filtering of relevant operational data to answer questions such as "What are top 10 failing executions in the past 1h containing label env:prod grouped by label x and flowId => Which PROD flows of a "type" specified by the given label x are most troublesome?"

**Comment by anna-geller** [comment]
@tchiotludo out of curiosity: If we were to add this reference/business field, could it be used to guarantee idempotency and concurrency limiting? e.g., if there is a business key that uniquely identifies a specific task run that relates to a specific business process/transaction and the user has declared in the workflow configuration that at any time, there can be only one instance of that task/trigger running at all times, I wonder if this could be used to ensure idempotency and sort of global concurrency limit.

**Comment by damienkilgannon** [comment]
Since, this is been pushed back in priorities ... anybody have an example work around they use to achieve similar for the time been?

**Comment by anna-geller** [comment]
@damienkilgannon you can leverage the label task and filter executions by that label, e.g.:

```yaml
  - id: label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      url: "{{ outputs.some_task.value }}"
```

**Comment by anna-geller** [comment]
Discussed with Ludo, and we will solve it by introducing System Labels and one of them will be `system_correlationId`.

System Labels are all labels that have keys starting with `system_`.  Those labels will be by default hidden in the UI and will only be displayed if you explicitly search for them in the `labels` key-value field. 

The `system_correlationId` will be by default set to the `executionId` of the first flow in the chain and it will be propagated to all subflow executions downstream of the first flow in the chain. This will be implemented for `Subflow` and `ForEachItem` tasks but not for Flow triggers (at least for now, as it's more complex for flow triggers).

If some users would like to set a custom correlation ID, it's possible by defining a custom `system_correlationId` label in the flow e.g.:

```yaml
id: flow
namespace: company.team
labels:
  system_correlationId: myCustomKey

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ labels.system_correlationId }}
```

The System Labels listed below will be automatically added to relevant executions and wil be hidden in the UI:
- `system_correlationId`
- `system_username`
- `system_app` - pointing to the app ID in the format `{"system_app": "myAppId"}` - https://github.com/kestra-io/kestra-ee/issues/1429 

IMPORTANT NOTE: those **should be read-only** (not possible to overwrite those).

---

What about custom labels that users may want to hide in the UI? As an extra scope (if we have time), we can add `internal labels` set from the configuration file. 


```yaml
kestra:
  internal-labels:
    prefixes:
      - internal_
      - admin_
```

**Comment by anna-geller** [comment]
TBD we likely will not allow user's custom system labels

**Comment by loicmathieu** [comment]
Two labels have been added as system labels: `system_username` and `system_correlationId`.
System labels has been made read only and writable only by Kestra itself.
Hidden labels has been implemented for `system_` and `internal_` prefix.

Only `system_appId` still needs to be added, this needs to be part of the Apps feature, closing this issue.
