### ISSUE TITLE
add an execute bouton on flow list

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#206]
The bouton will open the same form than execute tab.
When the execution is created, redirect to the execution page

**Comment by aurelienWls** [comment]
It could be interesting to also add this button on source editor tab

**Comment by tchiotludo** [comment]
replace by this one : https://github.com/kestra-io/kestra/commit/b42d4013ac8c69625910a2e1f9fc2a47f9576cfc, on the source code the button is also here
