### ISSUE TITLE
[UI] Rename the Value column in the Outputs tab to "Iteration Value"

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2066]
### Issue description

The name "Value" is confusing as this value is only used in tasks that iterate over values - "Each" tasks.

Changing that column name will make it clearer why this value is only available in those mapped tasks.

**Comment by H3m4N-14** [comment]
@anna-geller I'm interested in working on this issue. Could you please assign it to me? I believe I can make the necessary changes to clarify the "Value" column as described in the issue description. Thanks!
