### ISSUE TITLE
Upgrade DuckDB driver to 0.9

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2085]
### Feature description

DuckDB is going to release a new version (0.9) on September 20th. To continue supporting MotherDuck, the driver must be updated as it is currently not backward compatible.

Users will upgrade starting Sept 27th. As a MotherDuck partner, we need to upgrade to 0.9 soon after the release to facilitate a smooth transition.

**Comment by armetiz** [comment]
I create the following PR : https://github.com/kestra-io/plugin-jdbc/pull/158

**Comment by anna-geller** [comment]
closing in favor of https://github.com/kestra-io/plugin-jdbc/issues/165
