### ISSUE TITLE
Shorten long subflow and namespace names in the topology once expanded

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2118]
### Feature description

When using a subflow that has an exceptionally long nested namespace and a long flow name, the expand/collapse functionality on subflows breaks:

https://share.descript.com/view/HoXFM9gTAQn 

would be great to e.g. show three dots "longName..." and show full name only when hovering over it

**Comment by tchiotludo** [comment]
fix here https://github.com/kestra-io/ui-libs/commit/68e3797eba64532b873c50fc0ccc2ced390298b3 for long name but I was not able to reproduce the disappear of the node 



![Image](https://github.com/kestra-io/kestra/assets/2064609/0da44678-7104-47e4-a512-22094c977817)
