### ISSUE TITLE
Show warning when manually executing a flow containing a `{{ trigger.uri }}` variable

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2126]
### Feature description

When a user attempts to execute a flow that has a trigger variable such as `{{ trigger.uri }}`, show a warning in the UI explaining that such a variable cannot be resolved in a manual execution:

"The trigger variable used in this flow cannot be parsed in a manual execution."

Ideally (if possible), point to the trigger variable used:

"The trigger variable XXX used in this flow cannot be parsed in manually triggered executions." e.g.:
"The trigger variable `{{ trigger.uri }}` used in this flow cannot be parsed in manually triggered executions."

We can consider adding this as a question in the logs:

"Are you trying to manually execute a flow with trigger variables?"
- risk of FP and FN

**Comment by MilosPaunovic** [comment]
I believe that the best approach here would be to add this message in the `validate` endpoint, which would be generated on the BE side, to uniform all the error/warning messages passed to users.

**Comment by anna-geller** [comment]
just discussed with Ludo: we can use RegEx and if `{{ trigger }}` is used anywhere in the flow code and you try to hit "Execute", we can display a simple warning
