### ISSUE TITLE
Properties with default value should not be displayed as error on the editor 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2129]
### Feature description

These two properties are optional, so the warning shouldn't pop up:

![image](https://github.com/kestra-io/plugin-scripts/assets/86264395/83e80d55-4907-4482-88e7-8179986eb55a)

**Comment by loicmathieu** [comment]
This has been fixed.
![image](https://github.com/kestra-io/kestra/assets/1819009/d1339789-206f-4cc2-a2c4-98fe8a2c6485)
