### ISSUE TITLE
Dynamically generated webhook key doesn't work as expected

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2138]
In the last 0.11.0 release, we added the feature to fetch the webhook key from secrets. However, it didn't work for me. See in the video that when using the webhook key from the Secret, no Execution was triggered. After hardcoding the key, the event from EventBridge got passed to the webhook without any issues:

https://share.descript.com/view/kytVX5bnfp5 

### Environment Information

- Kestra Version: 0.12.0

**Comment by loicmathieu** [comment]
This is an issue due to the secret function that adds a new line at the end of the rendered value.
