### ISSUE TITLE
SurrealDB plugin with `Query` and Batch insert task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2142]
### Feature description

This will be a new plugin, not a JDBC sub-plugin

Live query only in the future, not now: https://surrealdb.com/lq

**Comment by loicmathieu** [comment]
@anna-geller Query and Trigger has been done. Batch is not planed yet.
Should we close this issue and open a new one for Batch or just close it and wait to see if there is any interest for a Batch task?

**Comment by anna-geller** [comment]
We can add Batch insert later on if there's demand for it
