### ISSUE TITLE
[UI] Simplify Environment name and color to be visible even when the sidebar is collapsed

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#2160]
### Feature description

I think the current integration could be revised. 
<img width="515" alt="Capture d’écran 2023-09-21 à 14 02 08" src="https://github.com/kestra-io/kestra/assets/125994028/9b109d3e-a8e0-465e-84f8-407f7156be93">

I suggest:

- The label surrounded by a border of the chosen color.
- A 15% opacity glow of the same color on the top of the menu.

Like this: 
![Enregistrement-de-l’écran-2023-09-21-à-13 58 34](https://github.com/kestra-io/kestra/assets/125994028/c4e8a002-3a7b-4664-a0bb-5556a611f485)

<img width="510" alt="Capture d’écran 2023-09-21 à 14 04 08" src="https://github.com/kestra-io/kestra/assets/125994028/1ffb968c-5e38-4bcd-939c-0c045a109f17">

WDYT?

**Comment by anna-geller** [comment]
already done in 0.16.0
