### ISSUE TITLE
[UI] Change icons and their position for the sidebar menu

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#2161]
We have a new sidebar design. In particular, it includes:

1. new icons in the sidebar
2. settings icon is now at the bottom
3. expand-collapse is improved for more visibility

![Menu_left](https://github.com/kestra-io/kestra/assets/86264395/c4d20a8c-c969-43e6-98bb-2213706e6fb4)

![Enregistrement-de-l’écran-2023-09-21-à-14 24 21](https://github.com/kestra-io/kestra/assets/125994028/0f76ec97-b60a-4f5f-96ec-080095524ec1)

[Figma](https://www.figma.com/proto/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?page-id=147%3A784&type=design&node-id=3134-31966&viewport=8886%2C-20074%2C0.69&t=y7MoEmcwheVK3KDj-1&scaling=min-zoom&starting-point-node-id=1005%3A6841&mode=design)

**Comment by tchiotludo** [comment]
@Nico-Kestra I can't find the design in figma, seems that it was removed

**Comment by tchiotludo** [comment]
relate to https://github.com/kestra-io/kestra/issues/2092

**Comment by anna-geller** [comment]
let's clarify when @Nico-Kestra is back, this one is not urgent 👍

**Comment by Nico-Kestra** [comment]
https://www.figma.com/proto/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?page-id=147%3A784&type=design&node-id=2943-36499&viewport=5758%2C-13336%2C0.43&t=vLloi9KcCrupYEy1-1&scaling=min-zoom&starting-point-node-id=1005%3A6841&mode=design
