### ISSUE TITLE
[UI] Cannot copy logs as they auto-collapse by clicking anywhere within the logs window

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2168]
### Explain the bug

See the issue in a video:

https://share.descript.com/view/PXDPtWVAF1O

Clicking anywhere on the expanded logs field shouldn't collapse. Collapsing the window should only happen when clicking on the collapse arrow.

![image](https://github.com/kestra-io/kestra/assets/86264395/7ac91c89-8c24-4a91-b4f1-479bb14f013c)

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by tchiotludo** [comment]
fix in #2180
