### ISSUE TITLE
[UI] Make the background color of the logs darker

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2170]
### Feature description

We should make the background color of the logs darker, as before (dark grey, close to black).

Here is how logs look like currently on the develop branch:

![image](https://github.com/kestra-io/kestra/assets/86264395/f88a8194-946b-4bac-982e-478092886ef8)

Previously, the contrast seemed to be more user-friendly (darker = stronger contrast = easier to read the log messages) + the logos were better highlighted when there was no box around them:

![image](https://github.com/kestra-io/kestra/assets/86264395/5b31eb4a-90e7-49be-8637-acfeb1a9caa4)

Related to this issue https://github.com/kestra-io/kestra/issues/2167 (request for alternate color between log messages, which would indeed be great to bring back)

cc @Nico-Kestra

**Comment by Nico-Kestra** [comment]
like this? 
<img width="1355" alt="Capture d’écran 2023-09-25 à 09 37 13" src="https://github.com/kestra-io/kestra/assets/125994028/ba80898d-072f-4c49-89dc-e54e6c00aeab">

**Comment by Nico-Kestra** [comment]
or this:
<img width="1489" alt="Capture d’écran 2023-09-25 à 09 38 55" src="https://github.com/kestra-io/kestra/assets/125994028/055e6e3f-7b0a-41fb-98a1-30ba81fb939d">
