### ISSUE TITLE
[UI] Make the navigation buttons darker

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2174]
### Feature description

The navigation buttons seem a little too bright and don't seem to match the design of the rest of the topology view:

![image](https://github.com/kestra-io/kestra/assets/86264395/1486521f-cd80-469d-b92e-105e63cf6230)

@Nico-Kestra will add a design

**Comment by Nico-Kestra** [comment]
It has existed forever, but since the topology update, we lost the style.
https://www.figma.com/file/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?type=design&node-id=1429%3A11864&mode=design&t=PSY3ILW4qJhvJ4In-1

**Comment by anna-geller** [comment]
thanks Nico, adding a screenshot for visibility:

![image](https://github.com/kestra-io/kestra/assets/86264395/c1479f32-d22f-4d56-8de7-d7886b26229b)

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/ui-libs/commit/b3c8d17a3eeb8aca01e4245985ea3a71ea155f5a
