### ISSUE TITLE
JDBC heartbeat followup

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2201]
### Issue description

- Remove the worker instance when the worker exits properly
- Add some WARNING logs of missing heartbeat, task resubmit, worker exiting because DEAD, ...
- Reduce duplication on the three queue implementations
- Display heartbeat information (date & status), note that for Kafka it will be missing

Note that when the worker is evicted by the executor, it may exit immediately as tasks will be resubmitted, we also may want to implement that as today it still wait for tasks to be ended so it will higher the risk of double execution.

**Comment by loicmathieu** [comment]
Maybe also display the heartbeat date and status in the worker page.

**Comment by tchiotludo** [comment]
all of theses are fixed in https://github.com/kestra-io/kestra/pull/2081
