### ISSUE TITLE
[UI] Add "Last 5 minutes" filter to Metrics

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2210]
### Feature description

It would be useful to allow a fine-granular overview of metrics from the last couple of runs. 

![image](https://github.com/kestra-io/kestra/assets/86264395/dacd0bd5-c3e7-46d0-bf0a-ebf42dcedec0)

see https://github.com/kestra-io/kestra/issues/1753#issuecomment-1705727664 

(the period is TBD, 5 min seems to make sense - it could be 15 min)

**Comment by chinmaym07** [comment]
Hey @anna-geller , 
Can I contribute to this ?

**Comment by tchiotludo** [comment]
@chinmaym07 for sure, the task is for you

**Comment by thefoxie** [comment]
@anna-geller @tchiotludo
Hey guys, hope you don't mind I've implemented it. Seemed like low hanging fruit.

**Comment by anna-geller** [comment]
for sure, thanks so much!
