### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#2218]
### Feature description

Hello,

It would be nice to think a bit deeper about error management in Kestra.
That feature already exist in order to catch:

- **flow-level** errors: https://kestra.io/docs/tutorial/errors#flow-level-error-handling-using-errors
- **namespace-level** errors: https://kestra.io/docs/tutorial/errors#namespace-level-error-handling-using-a-flow-trigger

What about **task-level** error where we'd like to set up a contingency plan ?
  
And what about executing a task regardless of having an error or not ? A basic example would be "I need to POST a status to another system to report that the execution finished with a failed/success state", that is similar to a `finally` statement in several languages.

We can probably tackle some of those needs with triggers, but I find it needlessly complicated for most cases.

Cheers 🦄

**Comment by anna-geller** [comment]
We'll work on improving error handling as part of this project https://github.com/kestra-io/kestra/issues/4701
