### ISSUE TITLE
Transmit kill to subflow

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#2220]
[Flow](https://kestra.io/plugins/core/tasks/flows/io.kestra.core.tasks.flows.flow) task may transmit the kill to child execution when they are killed, add a props `transmitStatus` for that (and maybe merge with `transmitFailed` to have a 2 way binding?  

---
EDIT: Figma link @fhussonnois @brian-mulier-p https://www.figma.com/file/ew0uXk0NRXJ2NBBJTNe2n1/UI?type=design&node-id=256%3A2517&mode=design&t=DsImwya9lbQyJwKx-1

**Comment by anna-geller** [comment]
Based on the meeting today, we want to have a cascading kill behavior by default. However, to enable edge cases, such as when the user wants to kill only the parent execution and keep the subflow executions running (e.g. ForEachItem use case with downstream tasks that might be killed without killing ForEachItem child executions), we want to provide a UI-based feature allowing to choose whether to kill all parent + children (the default cascading behavior) or only parent (second option) 

This may be implemented similarly to the Action button with 3 dots:

![image](https://github.com/kestra-io/kestra/assets/86264395/239560ed-594e-4be4-86ab-912f2a1749d8)

@Nico-Kestra might give some nice suggestions how to best handle it

On the backend side: we always cascade kill, not only with `wait: true` (for simplicity + `wait: false` triggering happens so fast that users wouldn't have the chance to kill it)

**Comment by brian-mulier-p** [comment]
I won't fight too much but I believe having checkboxes in the Kill confirmation popup is the best as it will allow further customization of the killing behaviour later on (combine kill subflow + graceful for eg.)

**Comment by anna-geller** [comment]
we clarified via Slack that Brian initially thought we could move this functionality to the confirmation dialog. We agreed it's important to show the options sooner so we can keep Nico's design and go with this for now
