### ISSUE TITLE
Allow user to define a callback when using the executions/trigger endpoint

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#2221]
### Feature description

Hey,

It would be nice if we could define a callback when triggering a flow.
For example, a HTTP GET request would be done on a given URL to alert that the execution has finished.

What is tricky is to be flexible enough while keeping in mind we are dealing with JSON here (some people may need to POST some content... for example the flow ID, others with HTTP headers, etc.)

Cheers 🦄

Y.

**Comment by anna-geller** [comment]
you mention 2 use cases - trigger some action when:
1. execution starts
2. execution finishes

both are possible with the Flow trigger already -- ping us on Slack in case you can't figure out how to do that with the Flow trigger 👍
