### ISSUE TITLE
Missing information for the request on a REST endpoint

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#2224]
### Explain the bug

There should be some documentation for the user regarding the request on the `executions/trigger/{namespace}/{id}`  endpoint.

In the documentation, it doesn't show: https://kestra.io/docs/api-guide#post-/api/v1/executions/trigger/-namespace-/-id-

Another user on Slack (thanks louj) identified an erroneous `- null` for the above endpoint in this file: https://kestra.io/kestra-ee.yml

Cheers,

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by yuri1969** [comment]
Reported to the upstream as https://github.com/micronaut-projects/micronaut-openapi/issues/1237

**Comment by Melkaz** [comment]
Is it fixed ?
The upstream issue looks closed but the issue remains in Kestra's API documentaiton

**Comment by yuri1969** [comment]
Well, the fix's merged but release is still pending.

**Comment by smunteankestra** [comment]
fixed 

![Image](https://github.com/kestra-io/kestra/assets/171780240/cd3e337d-4912-4819-87a8-3e75b7dd305d)
