### ISSUE TITLE
Running executions are not shown with default date filter

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2226]
### Explain the bug

Due to end date filter, we should remove it

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by aballiet** [comment]
Can I offer a PR ?

**Comment by Skraye** [comment]
@aballiet To fix that we need to remove the forced `endDate`, you can give it a try.
Later we plan on improving the way the date filter works.

**Comment by aballiet** [comment]
In the end, I will not have the time to do it. I let you @Skraye 👍
