### ISSUE TITLE
Task using WorkingDirectory cache ends with an error: `Unable to execute WorkingDirectory post actions`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2233]
### Explain the bug

Is cache only intended for use with Process runner - @loicmathieu? if so, we can close the issue

reproducer:
```yaml
id: python_cached_dependencies
namespace: dev

tasks:
  - id: working_dir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: python_script
        type: io.kestra.plugin.scripts.python.Script
        warningOnStdErr: false
        beforeCommands:
          - python -m venv venv
          - source venv/bin/activate
          - pip install pandas
        script: |
          import pandas as pd
          print(pd.__version__)
    cache:
      patterns:
        - venv/**
      ttl: PT1H
```

stack trace:

```Java
Command succeed with code 0
2023-10-04 12:04:29.766Cache files changed, we update the cache
2023-10-04 12:04:29.918Unable to execute WorkingDirectory post actions
2023-10-04 12:04:29.918java.io.IOException: Is a directory
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.read(Unknown Source)
	at java.base/sun.nio.ch.ChannelInputStream.read(Unknown Source)
	at java.base/sun.nio.ch.ChannelInputStream.read(Unknown Source)
	at java.base/sun.nio.ch.ChannelInputStream.read(Unknown Source)
	at java.base/java.nio.file.Files.read(Unknown Source)
	at java.base/java.nio.file.Files.readAllBytes(Unknown Source)
	at io.kestra.core.tasks.flows.WorkingDirectory.postExecuteTasks(WorkingDirectory.java:326)
	at io.kestra.core.runners.Worker.handleTask(Worker.java:173)
	at io.kestra.core.runners.Worker.lambda$run$2(Worker.java:137)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

changing to PROCESS runner works:

![image](https://github.com/kestra-io/kestra/assets/86264395/0e9fc7f0-694a-4129-8ffd-763658306f67)

### Environment Information

- Kestra Version: 0.13.0
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by tchiotludo** [comment]
We must support docker runner

**Comment by loicmathieu** [comment]
Does it work? I think it has something to do with file write access on some Docker installation so it can be ignored.

**Comment by anna-geller** [comment]
thanks. I shared a reproducer, can you try it? I ran it here on the preview https://preview-oss.kestra.io/ui/executions/dev/python_cached_dependencies/16dIqspaJWkf1eDO3s8i0o/logs?level=TRACE&page=1

**Comment by tchiotludo** [comment]
we don't display error if it's work for the end users, so if it work, hide the log

**Comment by loicmathieu** [comment]
I can confirm it didn't work

**Comment by loicmathieu** [comment]
I checked and this is caused by the container being run as root.
I can lower the message from ERROR to WARNING.
By the way, the same issue occurs for cleaning the temporary directory (which is not related to this task).

This is caused by the Docker daemon being run as root I think.
The python official image runs as root but I'm not sure changing that will make any difference.

**Comment by loicmathieu** [comment]
Unfortunately this is when creating the cache file so caching will not work.
The file has been created as root so it cannot be run with the user running Kestra.

**Comment by anna-geller** [comment]
I'd normally open a new issue, but we may consider deprecating the `WorkingDirectory`'s `cache` property entirely. 

I struggle using it with a local process, too, and it seems to be difficult to support across various edge cases.

Reproducer:

```yaml
id: dbt_cache_deps
namespace: blueprint

tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    cache:
      patterns:
        - venv/**
      ttl: PT24H
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main

    - id: dbt-build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      runner: PROCESS
      warningOnStdErr: false
      beforeCommands:
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install --upgrade pip
        - pip install dbt-duckdb > /dev/null
      commands:
        - dbt deps
        - dbt build
```

![image](https://github.com/kestra-io/kestra/assets/86264395/92a2f4c9-5ee1-437a-8fd6-14c9be9d2edc)

**Comment by walker-philips** [comment]
I am getting the same issue but have specified a PROCESS runner for all tasks. My overall Kestra deployment is using Docker with user as ROOT. Is the solution to have Kestra utilize a different system user in its docker compose to resolve the issue?

**Comment by anna-geller** [comment]
Hi @walker-philips, sorry for the late response — I think we don't know yet what's the right way to resolve the issue, that's why it's still open. We might solve it as part of the new script runner for Docker https://github.com/kestra-io/kestra/issues/3153

**Comment by loicmathieu** [comment]
@anna-geller I made a small adjustement by ignoring directories and files that cannot be read (like executables) and I can make it works. I'm not sure but depending on the system you may need to set the docker user to 1000 for ex to avoid permission issue.

See https://github.com/kestra-io/kestra/pull/3422

**Comment by anna-geller** [comment]
nice! let's keep the issue open to QA your change thoroughly first on the develop image

**Comment by loicmathieu** [comment]
@anna-geller did you had a change to have a look at this? Can we close it?

**Comment by anna-geller** [comment]
overall it works, I only don't understand the second line here "Cache files changed, we update the cache" -- I didn't update anything so the cache should be the same for 1 hour

![image](https://github.com/kestra-io/kestra/assets/86264395/b0773e49-18c9-41d9-af73-8d57cc4891c7)

**Comment by anna-geller** [comment]
also:

![image](https://github.com/kestra-io/kestra/assets/86264395/6ae56ff7-fd41-48f0-83b8-83b90511da41)

looking at not significantly reduced execution times, something doesn't seem to be working entirely as expected 

hard to judge by execution times whether dependencies were properly cached and/or retrieved from the cache:

![image](https://github.com/kestra-io/kestra/assets/86264395/999e0e48-bd7c-4686-8f3e-cf4a1822f5d5)


Worth QAing a bit more, can you cross-check on your end?

**Comment by loicmathieu** [comment]
>  I only don't understand the second line here "Cache files changed, we update the cache"

You didn't change anything, but the pip install changed it (the same goes for npm).
There are usually some files that change even when the same dependencies are fetched, this can be handled by the cache regex.

> looking at not significantly reduced execution times, something doesn't seem to be working entirely as expected

There is two things here:
- I think venv creates a random directory, so I'm not sure caching would work with venv.
- Even if caching exist, sometimes it's not significantly faster than downloading each library, it depends ...

> Worth QAing a bit more, can you cross-check on your end?

I did cross check and the caching functionality works, wether or not it applies to a specific use case (like Python venv) is not dependent of the caching feature.

**Comment by anna-geller** [comment]
gotcha, in that case let's close it. thanks so much!
