### ISSUE TITLE
Refacto JDBC persist throw exception

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#2242]
### Explain the bug

Actually a RunTime exception is thrown making the app crash.

### Environment Information

- Kestra Version: 0.13.0-SNAPSHOT

**Comment by anna-geller** [comment]
@Skraye can you clarify a bit more? alternatively, you can self-assign for 0.14

**Comment by anna-geller** [comment]
very old issue, closing. Please reopen with more context if the issue is still relevant
