### ISSUE TITLE
Add `logLevel` Enum property on the core task

### ISSUE THREAD

**Issue by aurelienWls** [kestra-io/kestra#2245]
### Feature description

Hi,

Usually, all tasks are generating logs. These logs are collected by Kestra to be display in the UI. By default, this is the ideal behavior
But sometimes we don't want that logs are collected for example when we have

- huge log size (that use a lot of space in the Kestra DB for nothing and  that are not readable in Kestra UI)
- sensible information in the logs

So it would be interesting if we should be able to disable the collect of the log by Kestra.

**Comment by tchiotludo** [comment]
You could add a `logLevel` on task and trigger that will limit the output of every log emitted by the task, by default, we will keep the `TRACE` level
