### ISSUE TITLE
Newlines break secrets

### ISSUE THREAD

**Issue by mgmorcos** [kestra-io/kestra#2249]
### Explain the bug

Base64 encoding can introduce newline characters, e.g.,

```sh
$ echo -n "y0Dqk9Zg17IuRbYrWtEJFFCtILvmdKeHEefr1IEYpFAQq6Crtb4wVVZ3hEVcGsRgmGbKWfQn8ZgPwUo5ocn0B5VRONCJwwvS" | base64
eTBEcWs5WmcxN0l1UmJZcld0RUpGRkN0SUx2bWRLZUhFZWZyMUlFWXBGQVFxNkNydGI0d1ZWWjNo
RVZjR3NSZ21HYktXZlFuOFpnUHdVbzVvY24wQjVWUk9OQ0p3d3ZT
```

These decode fine in the command line

```sh
$ export foo="$(echo -n 'y0Dqk9Zg17IuRbYrWtEJFFCtILvmdKeHEefr1IEYpFAQq6Crtb4wVVZ3hEVcGsRgmGbKWfQn8ZgPwUo5ocn0B5VRONCJwwvS' | base64)"
$ echo "$foo" | base64 -d
y0Dqk9Zg17IuRbYrWtEJFFCtILvmdKeHEefr1IEYpFAQq6Crtb4wVVZ3hEVcGsRgmGbKWfQn8ZgPwUo5ocn0B5VRONCJwwvS
```

But Kestra is not able to decode newline-containing encoded secrets.

As workarounds, `-w 0` option can be appended to `base64` command during encoding, or the newline characters can be manually removed from the encoded base64 string.

Kestra should probably not break when newlines are encountered in encoded secrets.

### Environment Information

- Kestra Version: 0.12.1
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by loicmathieu** [comment]
Can you give us more information about the issue.

- How do you set this env variable that includes a new line? Newline on itself is cumbersome in the shell.
- What is the error in Kestra? Do you have any logs?
