### ISSUE TITLE
[UI] Add a new Info icon in the top menu and move Live help and Documentation links there

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2278]
### Feature description

Currently, there is a sprawl of links within the UI

![image](https://github.com/kestra-io/kestra/assets/86264395/51c86faa-a8d6-450e-969c-036c5c07d813)

Additionally, when new version is available, that's also visible in the top navigation bar as an extra button. This is a little distracting.

## Proposal

Add a new Question-mark like icon to the top-right menu with links to the relevant help information. 

The items required in that list are:
- Live help - with a hammer-wrench icon and a link to Slack in OSS - in the SaaS or EE we can link to other support channels e.g. chatbot
- Documentation - link to the Developer Guide
- Plugins - link to the plugins list
- Open a GitHub issue - with GitHub icon and a link to https://github.com/kestra-io/kestra 
- Join the Community - this can have a Slack icon and point to Slack
- New version available! - dynamically added only when new version is available

![image](https://github.com/kestra-io/kestra/assets/86264395/edf47ca7-f1df-42f8-a7b9-be0448a51724)

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/kestra/commit/69a23fc1ca8be6388978801153254f96956001ff
