### ISSUE TITLE
Dropdowns have a small margin before first (or after last) item

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2324]
I think the `gap-2` create the weird space here
![image](https://github.com/kestra-io/kestra/assets/37600690/53ed4e59-65d8-4297-919c-5345d96a1d61)

_Originally posted by @Skraye in https://github.com/kestra-io/kestra/pull/2286#discussion_r1362373598_

Should be handled with element plus overriden styling

**Comment by Skraye** [comment]
@Niravdas Sure ! Go for it :)

**Comment by Niravdas** [comment]
Should I try removing that small margin before the first (or after the last) item?

**Comment by brian-mulier-p** [comment]
Yes :+1:

**Comment by Niravdas** [comment]
Hi @brian-mulier-p 
can anyone please review [PR ](https://github.com/kestra-io/kestra/pull/2354) I raised.
