### ISSUE TITLE
Mark FlowCondition as deprecated.

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2327]
### Feature description

Deprecate https://kestra.io/plugins/core/conditions/io.kestra.core.models.conditions.types.flowcondition

preferred option: https://kestra.io/plugins/core/conditions/io.kestra.core.models.conditions.types.executionflowcondition

**Comment by loicmathieu** [comment]
It is already deprecated and displayed as it inside the Kestra UI, see https://preview-oss.kestra.io/ui/plugins/io.kestra.core.models.conditions.types.FlowCondition



![Image](https://github.com/kestra-io/kestra/assets/1819009/84bccd8e-1621-4bf3-a016-aca9459e03d3)



But for an unknown reason, on the website the deprecated icon is not shown, see https://kestra.io/plugins/core/conditions/io.kestra.core.models.conditions.types.flowcondition



![Image](https://github.com/kestra-io/kestra/assets/1819009/7f08e0a0-e371-4258-8c79-55623f7374a8)

**Comment by rldorado** [comment]
Ey! So far in my findings I see that the website FE is taking the title `.md` tag value so in this example it'll only show "FlowCondition" instead of "FlowCondition- 🔒 Deprecated".

```
---
title: FlowCondition
editLink: false

description: "Condition for a specific flow. Note that this condition is deprecated, use `ExecutionFlowCondition` instead."

icon: PHN2Zy...
---


<h1>
    <img width="25" src="..." alt="FlowCondition" /> FlowCondition- 🔒 Deprecated
</h1>
```

So title should have the same content as the h1.

**Comment by loicmathieu** [comment]
Thanks, it explains the behavior, on our side, we didn't add the 'deprecated' flag on the MD title.
I'll have a look.
