### ISSUE TITLE
Add the Python Kestra library to the Kestra full image

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2357]
### Feature description

The Kestra full image installs binaries (python3 python3-venv python-is-python3 nodejs npm curl zip unzip) and all plugins but not the Kestra library.
User that wanted to use the Python tasks with the PROCESS runner will need to install it (or use a custom Kestra image).

If possible, we should install the Kestra Python library inside the Kestra full image.

**Comment by romangoldberg** [comment]
Hi,
we have very simple Python scripts, like for example parsing the date or creating an s3 bucket path from different variables and we are trying to do that in python script and run it as a PROCESS. The only thing that we are missing is the Kestra library on our runtime environment and we would expect that Kestra will have Kestra in it environment.
