### ISSUE TITLE
Configuration to disable code editor

### ISSUE THREAD

**Issue by fritzwijaya** [kestra-io/kestra#2363]
Hi Kestra Community,

Is thereany way to completely disable the web editor for flow? I want to limit the flow deployment only through CI/CD and disable the creation and editing for production cluster.

Many thanks

**Comment by anna-geller** [comment]
hey, we support disabling editing flows based on the user role (RBAC) to allow e.g. admins and CI/CD service accounts to edit flows, while others can have them read-only. To be transparent, this is a paid feature that you can discuss with sales@kestra.io 

feel free to ping me on kestra.io/slack to discuss the reasons for that more
