### ISSUE TITLE
Allow to search across all Namespace Files (rather than only across currently-open files)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2368]
1. Search by file name
2. Search by flow source

Search by file's content is out of scope for now for several reasons (performance, privacy)

**Comment by brian-mulier-p** [comment]
After discussing with @tchiotludo it was chosen not to include search by flow source for now as it requires some rework around matches retrieval (we need more info on matches' index in flow for VSCode to highlight / show proper preview). Moreover, as we're limited by storages which prevent us from having search by content over Namespace Files (not flows) which in the end leads to incomplete and confusing feature (why my search by content is scoped to flows ?).

I'll only introduce search by file (& flows) name for now.
