### ISSUE TITLE
[JDBC] Errors logs widget is long to fetch on the Homepage

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2376]
### Explain the bug

See https://preview-oss.kestra.io/ui/dashboard

The "Errors logs" widget is long to fetch on the Homepage

### Environment Information

- Kestra Version: 0.13.0-SNAPSHOT
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by aballiet** [comment]
Change default time range to 1H instead of 30 days 👍

**Comment by loicmathieu** [comment]
Let's wait for some analysis ;) 

But we use 7 days for some pages, we might decide to align this page also.

**Comment by loicmathieu** [comment]
Locally, it correctly uses the `logs_namespace_flow` index.

As we switch from 30 days to 7 days in other places I advise to do the same here.

For the record the SQL query is:

```sql
select "value" from logs where ("tenant_id" is null and "deleted" = false and (level in ('ERROR'::log_level, 'WARN'::log_level)) and "timestamp" >= cast('2023-09-24 15:30:39.253+02:00' as timestamp with time zone) and "timestamp" <= cast('2023-10-24 15:30:39.253+02:00' as timestamp with time zone)) order by "timestamp" desc fetch next 10 rows only
```

**Comment by loicmathieu** [comment]
> As we switch from 30 days to 7 days in other places I advise to do the same here.

I was wrong, apparently we use 30 days by default in all dashboards (homepage, flows, executions, namespaces, ...)
