### ISSUE TITLE
Dashboard for today / yesterday are not relevant

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#2383]
![image](https://github.com/kestra-io/kestra/assets/2064609/3f49ddbe-211f-4eb5-95c3-22de1ecfe6fa)

In that case, the running is today and flagged on "the last 30 days"

**Comment by loicmathieu** [comment]
I'm not sure I understand the issue but it may be fixed by https://github.com/kestra-io/kestra/pull/2411

**Comment by anna-geller** [comment]
@tchiotludo is this perhaps already done?

**Comment by loicmathieu** [comment]
Dashboards will be rewritten soon, closing it.
