### ISSUE TITLE
Issue with null-coalescing operator

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#2396]
### Explain the bug

According to this (and others):
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

If you have `X = null` and `Y = "1"`
X being an String input not defined
Y an output of a task

Doing `X ?? Y` you should have `"1"`, but the X is rendered as an empty string (maybe because the input is defined as a String ?) and then the coalesce return X instead of Y

Using the ternary syntax (`X ? X : Y`) can be use as a workaround for now.

### Environment Information

- Kestra Version: 0.13
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by EdwardLi-coder** [comment]
<img width="805" alt="image" src="https://github.com/kestra-io/kestra/assets/29945767/8fee92cf-c05b-4bc6-ab2f-dd9044f62182">
The X maybe is empty string.So the result is x.What place you find the result isn't Desired result.May be we can look it to resolve it.
