### ISSUE TITLE
[UI] Improve the plugin overview with tiles per subplugin and search

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2399]
Currently, the embedded plugin overview is difficult to use. There is no search to validate if a given plugin is already supported. Some subplugins, such as notification subplugins or subplugins for specific AWS, Azure, or GCP services, are also hidden behind one large plugin. 

![Image](https://github.com/kestra-io/kestra/assets/86264395/0c0e6836-6ca7-4d4e-b254-8cbe04824b04)

It would be more user-friendly to offer an overview with a tile per service/subplugin, showing all integrations at a glance. 

## To do

1. New UI navigation menu called "Plugins" below the "Blueprints" section
2. Within the "Plugins" page, there should be a plugin overview with a search bar
3. The search bar should allow searching for specific plugins, tasks and triggers
4. Add a preview when hovering over a plugin to avoid having to open each plugin separately 

https://www.figma.com/file/4tLhsoCsh9yVzYRY1N70kS/App-Kestra?type=design&node-id=3695%3A13259&mode=design&t=qWr3YxCPWwCFeCsd-1 

## Preview

When hovering over a plugin, it should display a list of tasks and triggers with a short explanation:

![Plugins App](https://github.com/kestra-io/kestra/assets/86264395/a181b7af-6415-41e1-8750-6036dfacc069)

Showing the same plugin overview on the website and in the UI would also help navigate plugins.
```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/1147
```

**Comment by anna-geller** [comment]
@Nico-Kestra I assigned this one to you so you can cross-check the design for both the website and the UI

**Comment by Nico-Kestra** [comment]
Do you mean integration into the UI? Because I've already done it for the website. Unless you want me to check the front end, and if so, where?
