### ISSUE TITLE
Parallel with failure don't save successful tasks

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#240]
If I run some parallel flow, if one task failed, the currently running task will not be marked as failed / success and keep running indefinitely.

We need at least to let the executor update the WorkerTaskResult for running task to have true feedback of this execution

**Comment by Ben8t** [comment]
This one seems to be fixed since then
![Image](https://github.com/user-attachments/assets/80485186-9b77-456d-9fe4-7e3804675317)
