### ISSUE TITLE
Add VS Code command "Sync local files to kestra" allowing to keep an entire local directory in sync with a specific namespace

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2403]
The user requirement is to keep a specific local directory in sync with a specific kestra namespace.

User needs to therefore provide the following:
- local directory path
- kestra namespace

That's all that is required from the user.

On the kestra side, there might be a VS Code command to trigger a manual sync:

![image](https://github.com/kestra-io/kestra/assets/86264395/05efcc39-bc6b-475d-9c5c-d103f1f952be)

Or kestra might automatically keep that specified local directory in sync with namespace files in the form of some background process. 

## Advantages

- Easy way to get started
- Easy way to "just" deploy local files

## Drawbacks

- Syncing files without Git is nice for local development, but likely not what people would do in prod

**Comment by MilosPaunovic** [comment]
We're long away from using VSCode anymore, this should either be closed or adapted to `monaco-editor` implementation @anna-geller, @Ben8t.

**Comment by anna-geller** [comment]
agree that no action is needed as we now fully support syncing both code and flows:
- Bind mount scripts and custom files https://www.youtube.com/watch?v=aWvUtbu8FAo 
- Sync local flows with kestra bidirectionally https://youtu.be/C_aLyXBysN8
