### ISSUE TITLE
Links in the S3 documentation are broken

### ISSUE THREAD

**Issue by bastien-k** [kestra-io/kestra#2404]
Hello,
Links under https://kestra.io/plugins/plugin-aws#s3 are broken.
For example, we see:
https://kestra.io/plugins/plugin-aws/triggers/s3/io.kestra.plugin.aws.strigger
But we should see:
https://kestra.io/plugins/plugin-aws/triggers/s3/io.kestra.plugin.aws.s3.trigger

**Comment by anna-geller** [comment]
thanks so much for flagging this, done in https://github.com/kestra-io/docs/pull/623
