### ISSUE TITLE
Better display of skip tasks on topology for execution

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#241]
![image](https://user-images.githubusercontent.com/2064609/101085843-4c90b400-35b0-11eb-8fd0-214c0d7fe08b.png)

When you run a switch and some task are not execute (normally). We don't see clearly that this tasks are skipped. 

Maybe just add some opacity on skipped tasks ?

**Comment by Ben8t** [comment]
Enhanced since recent versions (cf screenshots), but still agree about changing the opacity for non executed tasks





![Image](https://user-images.githubusercontent.com/46634684/231497247-6b6a845c-ed6e-42a6-b714-71a4a7b6cd34.png)

**Comment by yuri1969** [comment]
Here is a bit of feedback obtained during an internal UI presentation: The topology view should convey the _taken path_ of the execution. This means it must be easy to tell which nodes and edges took a part in the execution.

Crude example:
![path](https://github.com/kestra-io/kestra/assets/13468636/abc89a28-b036-4437-b06a-d1f75a94c5fe)

**Comment by Ben8t** [comment]
epic at #1670

**Comment by tchiotludo** [comment]
@Nico-Kestra : we don't have a design on that one

**Comment by tchiotludo** [comment]
I think about using opacity to hide the unused edge, it's not complex but we need to forward the taskId to the edge to be able to know if the target edge is visible or not
