### ISSUE TITLE
Allow marking executions as Success, Acknowledged or Resolved with a comment about the reason for the state change

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#2423]
### Feature description

The UI currently lacks a possibility to provide an execution feedback from a user. Failed production executions are usually treated as incidents. There are usually error notifications channels triggering an incident response from an operations/support team. The notification channels are _direct_ (Slack/Teams/email/etc.) or _indirect_ (an incident tool receiving incident events & supporting the whole incident life-cycle).

Configuring and running a full fledged incident tool can be a bit time consuming and complex. Using a direct way solely brings a new set of problems in multi-team environments (sharing channels, etc.).

Having a possibility to provide feedback directly in the Kestra Executions UI would help to resolve some of the problems. The minimal feature set would be:

1. define a set of execution "feedback states": `default`, `To Do`, `In Progress`, `Resolved`
2. allow to assign one of "feedback states" to execution & with an optional comment
3. log the user and time stamp to the audit log
4. allow users to further filter executions based on the "feedback state"

This feature would surely not replace a dedicated incident/ticket tool, although it, IMO, should greatly help to improve the out-of-the-box experience for support/operations teams.

**Comment by yuri1969** [comment]
The current use case supports following incident flow:

1. an execution gets to the ERROR state
2. the support team gets notified
3. a member of the support team marks the execution as `To Do` and passes the incident further to the operations team
4. a member of the operations team marks the execution as `In progress` while resolving the issue
5. finally, the execution can be marked as `Resolved`

This way it is possible to track status of incident resolution.

**Comment by anna-geller** [comment]
we'll tackle in in EE as we have no way to assign users to incidents + track resolution status in OSS https://github.com/kestra-io/kestra-ee/issues/1560
