### ISSUE TITLE
Optimize Execution.outputs() methods

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#244]
https://github.com/kestra-io/kestra/blob/3096d57d6cccf23fdb0d611ecfa3e7140284fc73/core/src/main/java/org/kestra/core/models/executions/Execution.java#L517

![image](https://user-images.githubusercontent.com/2064609/101155690-c4e68c00-3627-11eb-85ef-b8a21e46bf3a.png)

This methods use almost 30% of all Executor process for now. seems that the findChilds can be optimized because we parse it for each taskrun, maybe we can make only 1 pass on this.

**Comment by loicmathieu** [comment]
Closing it as very old, and multiple improvements have been made in this area.

If we want to continue optimizing the Executor, we need to profile it again to find what are the current hotspots.
