### ISSUE TITLE
[UI] Lower the toast about "Successfully saved", otherwise the "Execute in a new tab" dropdown menu is not reachable

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2440]
### Explain the bug

![image](https://github.com/kestra-io/kestra/assets/86264395/6d42f2c4-a37d-4ecb-b3b1-1113ffc6a5f0)

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by tchiotludo** [comment]
I think we should keep the preference in local storage that will prevent to have this need: 
- save the last choice (blank or not) in local storage
- change the execute button to execute ⤴ if it's the blank

**Comment by anna-geller** [comment]
replaced by https://github.com/kestra-io/kestra/issues/2448
