### ISSUE TITLE
Fix documentation for Unit Testing a plugin

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#2449]
### Explain the bug

[This page](https://kestra.io/docs/plugin-developer-guide/unit-test#unit-test-with-a-full-flow) needs to be updated as this line is invalid: 
```java
Execution execution = runnerUtils.runOne("io.kestra.templates", "example");
```

It seems the signature of `RunnerUtils.runOne` changed recently, here how it should be:
```java
Execution execution = runnerUtils.runOne(null, "io.kestra.templates", "example");
```

Maybe we could add back the previous signature instead of setting `null` for the `tenantId` ?

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by loicmathieu** [comment]
The plugin development guide will be updated for the next release to take into account the changes on the Java API due to the new multi-tenancy feature.

**Comment by loicmathieu** [comment]
Fixed by https://github.com/kestra-io/docs/pull/1632
