### ISSUE TITLE
Namespace File Editor should keep track of the previously selected namespace if there was one

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2476]
### Explain the bug

Currently it always select the first namespace available unless we have a default namespace setting set up.
It can be annoying when you try to debug as you may need to reload the page sometimes and it fails to retrieve the previously selected namespace.
I think if we have a RestoreUrl saved for editor it should take it instead of selecting the first namespace.

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by prajwalgh** [comment]
Hello, if issue #2476is currently unassigned or available, please consider assigning it to me.

**Comment by brian-mulier-p** [comment]
Hello @prajwalgh, thank's for contributing, I assigned you :)

**Comment by brian-mulier-p** [comment]
Hello @prajwalgh do you manage to do it or do you need any help ?
