### ISSUE TITLE
Log the full child execution URLs in the `ForEachItem` task logs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2481]
Log full child execution URLs to make troubleshooting easier:

![image](https://github.com/kestra-io/kestra/assets/86264395/7c9db094-ff29-493f-b86a-97de4df1303d)

**Comment by Skraye** [comment]
Should we use markdown when generating the logs with some things like 
`[{execId}](ui/executions/{flow}/{namespace}/{execId}/logs)`
and interpret it in the front end (**only for tasks like forEach or Subflows as logs are always the same**, as other tasks/customs plugin could generate fraudulent markdown)

**Comment by anna-geller** [comment]
plain text already solves the problem to have a link for troubleshooting 👍 thx for flagging this

**Comment by brian-mulier-p** [comment]
@anna-geller we talked about that with devs the other day and I think we want to introduce a more complex instance-referencing-URLs mechanism and not a raw plaintext URL. Idk if we want to tackle it this release but it may not be a quick win :+1:

**Comment by anna-geller** [comment]
no worries, we have some other work planned for ForEachItem anyway, so moved to 0.18

**Comment by Skraye** [comment]
Now every subflow creation log in a custom format that allows us to interpret it and create link in logs in the UI
![image](https://github.com/user-attachments/assets/87427b37-90ad-4e5b-b754-26bf2abbbf40)
