### ISSUE TITLE
[UI] Adjust the log message in the `ForEachItem` task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2486]
### Feature description

This log line that appears in both `ForEachItem` and `Flow` task:

```
Create new execution for flow 'qa'.'subflow' with id 'QrsDEw8tgGjlA5r5RXgSO' from task 'each' and taskrun '2MA5A1J9xFI8LWV6MZ27yK (2)'
```

should be shortened to just:

```
Created a new execution for flow qa.subflow with id QrsDEw8tgGjlA5r5RXgSO (2)
```

No quotes and no info about the task and taskrun needed.

**Comment by Skraye** [comment]
https://github.com/kestra-io/kestra/pull/2498
