### ISSUE TITLE
[UI] Accessing any blueprint with a script task results in an error: `Unprocessable Entity: Invalid entity: Invalid type: io.kestra.plugin.scripts.python.Script`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2493]
### Explain the bu

![image](https://github.com/kestra-io/kestra/assets/86264395/4ef21a90-8f7d-4f60-94a9-dd457127be78)

![image](https://github.com/kestra-io/kestra/assets/86264395/909a15b4-d94c-43fb-bab8-ac4c6ed78e2d)

Response:

```json
{
    "message": "Unprocessable Entity: Invalid entity: Invalid type: io.kestra.plugin.scripts.python.Script",
    "_links": {
        "self": {
            "href": "/api/v1/blueprints/community/148/graph"
        }
    }
}
```

**Comment by tchiotludo** [comment]
Fixed, just need to rebuild the api to bring a new class from kestra core
