### ISSUE TITLE
Add minimum threshold for cpu/memory value in DockerOptions

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#2509]
### Feature description

[cpu limits](https://kestra.io/plugins/plugin-script-python/tasks/io.kestra.core.tasks.scripts.python#cpu) and [memory limits](https://kestra.io/plugins/plugin-script-python/tasks/io.kestra.core.tasks.scripts.python#memory-2) can be bounded to a maximum value but not to minimum ones.

Would it be possible to add minimum cpu and minium memory requirements options for Docker containers (in DockerOptions) ?

**Comment by loicmathieu** [comment]
It's possible if you tell me which minimum I should put (ideally backed by proof that this is the right minimum) ...

According to me, it's not possible as it depends on what you execute inside your Docker container, so it's highly user-dependent. We can add recommendations inside our documentation to set limits as taskdefaults, but we cannot choose those limits on behalf of the user.

**Comment by Ben8t** [comment]
Sorry, was not clear: the issue is about letting users set minimum requirements as an option (like the max already possible). Updating the issue

**Comment by Ben8t** [comment]
Oh I missed that one ! Thanks :) 
Probably closing the issue then; do you know about any CPU limit options ?

**Comment by loicmathieu** [comment]
Closing it.

There is a lot of options that can be passed to the docker runner, almost anything that is documented for the docker command line can be passed to the docker runner if needed.
