### ISSUE TITLE
Allow filtering executions by specific input values

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2511]
### Feature description

The request came up a couple of times already. Users expect to be able to filter executions based on a specific string/numeric/date property, or based on a specific element in the JSON input.  

Certain types of inputs such as the FILE input type will not be possible. Also, if this is only possible to do with Elastic, we can add it only to the EE version.

Slightly related to https://github.com/kestra-io/kestra/issues/1760

**Comment by loicmathieu** [comment]
We can filter on more columns but each time we need to add an index for that which has a storage and a write cost.
Moreover, index on complex JSON structure is only possible on Elasticsearch and Postgres so MySQL will have a performance impact (H2 is on memory so the index is less needed).
