### ISSUE TITLE
Validate possible improvements to load time for VS Code editor, especially with namespace files stored in cloud object storage (S3, GCS, Azure)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2523]
Currently, the load time is not optimized, as in 0.13.0 we focused on delivering the minimal viable Editor version. Next, we should consider various caching options and ways to optimize the speed of the Editor.

I think even if we don't manage to do this one, it's OK as I imagine: most folks will likely use a local file system for local development (which is fast) and the cloud storage bucket is mostly for production. And for production, you would typically have read-only view. Just a note to show this is great to add, but not a blocker.

**Comment by tchiotludo** [comment]
It's a must have to have a better experience for people willing to work only on the browser

**Comment by anna-geller** [comment]
no longer relevant in 0.17
