### ISSUE TITLE
Missing actions buttons on Topology Only view

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#2553]
### Explain the bug

Topology view does not have the action button displayed anymore

This prevent from doing a flow from 100% low code on this view

![image](https://github.com/kestra-io/kestra/assets/37600690/7328e98e-f1f2-4b14-8638-94919032cbba)

### Environment Information

- Kestra Version: 0.13.0
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by anna-geller** [comment]
can you explain more? how did it look like before?

it seems you can edit tasks + add new ones directly from the UI forms

![image](https://github.com/kestra-io/kestra/assets/86264395/a77053d8-26e5-4173-aa90-2efa192b3a7f)

**Comment by Skraye** [comment]
When you're in full topology view, the "Actions" button I highlighted above isn't show, so you can edit your flow metadata for example
