### ISSUE TITLE
Infinite loop when variables call each other

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#2592]
### Explain the bug

id: hello-world
namespace: my.namespace

inputs:
  - name: test
    type: STRING
    required: false
    defaults: "{{ vars.dv_test }}"

variables:
  dv_test: "{{ inputs.test }}"

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "Kestra team wishes you a great day! 👋 {{ inputs.test }}"

### Environment Information

- Kestra Version: 0.13.0 (and probably previous versions)

**Comment by anna-geller** [comment]
should no longer happen with render()
