### ISSUE TITLE
Fix docs issue for rendering code fragments like `{{ trigger.body }}`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2625]
### Explain the bug

on the website: https://kestra.io/plugins/core/triggers/io.kestra.core.models.triggers.types.webhook

![image](https://github.com/kestra-io/kestra/assets/86264395/7d127440-36a7-44ba-b0eb-ecdd33d2b507)

works in the app:

![image](https://github.com/kestra-io/kestra/assets/86264395/3bdfbf3e-73f7-4e15-9cb6-82fddeeacd18)

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by Skraye** [comment]
Done in https://github.com/kestra-io/docs/commit/b38b8beef09ebef0725a7d0b1a8ee094a3b7ff6b
will be available when develop is rebased in main
