### ISSUE TITLE
NamespaceFiles should be put in proper space in internal storage

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#2635]
### Feature description

Namespace file are stored inside the internal storage in the same bucket/directory as for flow data.
Best practices for flow data stored in cloud storage advise configuring policy to remove old data to avoid infinite storage growth.
However, applying such a policy will also remove namespace files that may still be used.

**Comment by Ben8t** [comment]
2 ideas:
* Have another bucket in the internal storage configuration dedicated to Namespace files
* Create a folder automatically so at least users can know where files are arranged

**Comment by anna-geller** [comment]
done as blueprint https://strapi.kestra.io/admin/content-manager/collectionType/api::blueprint.blueprint/202
