### ISSUE TITLE
[Reevaluate if needed after adding KV Store] Add support for purging state store files 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2639]
### Feature description

from @loicmathieu "The purge task only purges execution data, not state and cache."

**Comment by anna-geller** [comment]
closing for now as it's possible for both wdir and state store to delete those:
- https://kestra.io/plugins/core/tasks/states/io.kestra.core.tasks.states.delete
- cache - set expiration

**Comment by anna-geller** [comment]
Reason to reopen: the Delete task must be called from the flow that uses the state. So when you delete the flow or remove the State task, the state will stay forever (and some tasks like the Singer plugin use it under the hood).

**Comment by loicmathieu** [comment]
Now that State store is a KV under the cover it can be deleted manually from the UI so I think we can close this one.
