### ISSUE TITLE
[UI] The Trigger name column is too small with large webhook trigger values

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2644]
### Explain the bug

See: https://demo.kestra.io/ui/prod/executions/product/github/6fl9t1Yq7FtfMmDbY2j9JN

![image](https://github.com/kestra-io/kestra/assets/86264395/560085f4-f061-4b17-b07d-bd6dcd5f055d)

### Environment Information

- Kestra Version: 0.14.0 snapshot

**Comment by brian-mulier-p** [comment]
Closing as I believe it got fixed by recent UI overhauls
