### ISSUE TITLE
Protect against deleting running execution 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#2651]
Some people delete the execution before killing it. Leading to execution on the worker to continue with no way to kill the running task. 
We should: 
- on simple delete, we should add a confirmation before deleting a running execution 
- on mass delete, we should skip running execution, and add a check box on the confirmation modal, [] I want to delete also running executions

**Comment by loicmathieu** [comment]
@tchiotludo should we really ask if they want to delete running or just restrict? I vote for restrict and sau that the execution must be killed first. No that killing always works it is the good way to do it.

**Comment by tchiotludo** [comment]
I vote for ask for, for edge case (when there is massive crash), killed will be impossible, so at first it's a warning on the ui for now
