### ISSUE TITLE
(jdbc) flow execution with OOM task can end up as zombie RUNNING

### ISSUE THREAD

**Issue by aballiet** [kestra-io/kestra#2653]
### Explain the bug

While running flows with a dbt step (docker image based plugin). If the execution experiences OOM error (code 137).
Task is still considered as RUNNING instead of FAILED.

<img width="1235" alt="image" src="https://github.com/kestra-io/kestra/assets/25565600/aba2dd79-9e63-402b-83da-2897c8ffd1da">

Task re-submit is not working and blocks the pipeline in a IDLE state (no concurrent executions in Kestra with trigger schedule)

My understanding : 
-> Worker crashes because of OOM (pod restart)
-> Task is not attached anymore to an existing worker
-> heartbeat fails at detecting it

DB dump :
[oom_worker_job_running.json](https://github.com/kestra-io/kestra/files/13612535/oom_worker_job_running.json)
<img width="1237" alt="image" src="https://github.com/kestra-io/kestra/assets/25565600/990e46d9-d398-4195-8538-877252439c65">

### Environment Information

- Kestra Version: 0.13.2
- Operating System and Java Version (if not using Kestra Docker image): k8s, official helm chart

**Comment by Ben8t** [comment]
Adding some details here after a discussion with @aballiet and Anas:

They have created a flow to automatically call Kestra's API to DELETE those executions. **While the DELETE flag in the database is correctly set to true, the executions are still in a RUNNING state.**

👉 Clicking on KILLING/DELETE (and on API call) should work as intended. That's maybe a broader issue (see https://github.com/kestra-io/kestra/issues/2531 too)

This seems to appear only on `dbt.CLI` task. Gorgias's team is looking to find a reproducer - one idea is to kill explicitly the worker when the task is running and restart it to see what happens.


> Some solutions & workaround explored:
> 1. Query the DB directly to remove those executions: that seems dangerous and not respecting Kestra's API
> 2. Using `shell.Commands` task with customer Docker. The issue might be caused by some middleware in the `dbt.CLI` task.
> They use `dbt.CLI` with a custom docker image, but after inspection it's a very simple Dockerfile


@aballiet do not hesitate to add more information here :)

**Comment by loicmathieu** [comment]
Hi,
If you update an execution to DELETED directly in the database that will not have any effect on the execution on itself. I think it's not a good idea, killing an execution is the right thing to do here.

Currently, if you kill a tasks that runs in a Docker container, it will not kill the container which is something we should do. We have plans for that.
