### ISSUE TITLE
Wrong timezone in Schedule task leads to Scheduler failure and Kestra crashing

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2655]
### Explain the bug

[myFile1.log](https://github.com/kestra-io/kestra/files/13614477/myFile1.log)

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by tchiotludo** [comment]
0fa696465b3506cbecd5fd72d8119aad9c6112ca and be383eb6d97161788b51a783f76794873a400b6d prevent the crash, now we need to add a proper validation on flow save
