### ISSUE TITLE
Create & Edit flow lose tracks of tenant in route.params

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2702]
### Explain the bug

If you go on a non-default tenant, clicking on edit flow or create flow doesn't keep the tenant id in the URL since we don't ...route.params when pushing a new route
Remember to CTRL + SHIFT + F 'router.push' to make sure to fix all these issues

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by anna-geller** [comment]
closing in favor of https://github.com/kestra-io/kestra-ee/issues/662
