### ISSUE TITLE
[CI] Prevent develop CI from running concurrently (latest build should abort any preceding build)

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2747]
### Explain the bug

See https://docs.github.com/en/actions/using-jobs/using-concurrency
If we don't do that, we're openned to issues like triggering two builds (two merge), if the last-merged-PR-triggered build is faster, it will result in the previous build being the one pushed last and would not include the very last PR

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by Skraye** [comment]
fix by  https://github.com/kestra-io/kestra/pull/2766 and https://github.com/kestra-io/kestra-ee/pull/707
