### ISSUE TITLE
Alignment of logs tabs is not centered

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#2798]
![image](https://github.com/kestra-io/kestra/assets/2064609/5cf27d44-cfb0-4dd2-b9ad-83acf4b56445)

**Comment by anna-geller** [comment]
interesting. Can you say more about why it is helpful if logs are centered?

**Comment by tchiotludo** [comment]
just a ui / layout issue, the state and duration should be align vertically to looks better

**Comment by shawnfrost69** [comment]
Hi @anna-geller, I can work on this issue, could you please provide a video demonstrating this issue? It would help me to reproduce the steps.

**Comment by MilosPaunovic** [comment]
@shawnfrost69 Execute one of the flows, you can use, for example, `tutorial.business_processes`, open`Logs` tab on `Execution` page, and you'll see the misalignment shown in the description of this issue.

**Comment by shawnfrost69** [comment]
Hi @MilosPaunovic, please take a look at the attached video and confirm if these changes look good or not so that I can push my updates. Thanks..
https://github.com/user-attachments/assets/b56f223f-12d5-40e3-bac3-699a8aab4ef3

**Comment by MilosPaunovic** [comment]
On video looks fine, but you'll need to open a PR for it to be tested properly.

**Comment by shawnfrost69** [comment]
Thanks for your feedback! I’m glad to hear that the changes look fine in the video. I’ll go ahead and open a pull request so that it can be tested properly.

**Comment by shawnfrost69** [comment]
Hi @MilosPaunovic https://github.com/kestra-io/kestra/pull/5774
I hope these changes will fix this issue, even though i tested it locally.

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @shawnfrost69! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/5774.
