### ISSUE TITLE
Dynamic inputs from kestra UI (get data from KV Store) 

### ISSUE THREAD

**Issue by eregnier** [kestra-io/kestra#283]
is it out of scope of kestra ?
it looks like it is plugin input like feature said @tchiotludo

**Comment by tchiotludo** [comment]
This can be done with plugins systems that allow to define a some custom Inputs type and where able to return a list of values based on ui search. 
Imagine for example a plugin that will add github repository input type, the plugins will declare an input type 'org.kestra.inputs.github` for example, each plugins will implement an interface like that : 
```java
import org.kestra.webserver.responses.PagedResults;

public interface InputType {
    PagedResults<String> search(String query);
    Boolean isValid(String query);
}
```
That will return the possible values and validate incoming values. 
 Seems a lot of works be seems possible like that

**Comment by anna-geller** [comment]
closing as we now aligned on the implementation in a separate issue
