### ISSUE TITLE
Allow to disable worker task running resubmit

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2836]
### Feature description

If a Worker fail on a task that cannot be process, it will fail after restart due to worker task running resubmit.

This can happen for ex for such bug: #2835 

Using `--skip-executions` can skip the execution but it would be good to also have a switch at the worker side, this can be convenient when there is multiple potential problematic tasks.

**Comment by fhussonnois** [comment]
Duplicate with #3351 and part of the PR https://github.com/kestra-io/kestra/pull/3376
