### ISSUE TITLE
Execution pop-up could be placed better

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#2843]
### Feature description

When navigating in the UI quickly and running manual executions, the execution popup goes sometimes over UI elements/buttons (attached screenshots show replay button being hidden by the execution pop-up)

Would be nice to place the popup elsewhere, in a blank space

<img width="456" alt="Screenshot 2024-01-12 at 15 51 51" src="https://github.com/kestra-io/kestra/assets/46634684/8b631bac-b814-49d2-951f-e404d5f1ded7">
<img width="456" alt="Screenshot 2024-01-12 at 15 51 25" src="https://github.com/kestra-io/kestra/assets/46634684/88ee8d59-5c4b-4973-bbcd-87dba264261d">

**Comment by anna-geller** [comment]
done

![image](https://github.com/kestra-io/kestra/assets/86264395/d43902c8-b6ab-4baf-9952-4ccde2c46a8c)
