### ISSUE TITLE
Slow web interface loading (AdBlock)

### ISSUE THREAD

**Issue by drakylar** [kestra-io/kestra#2845]
### Explain the bug

AdBlock (Chrome) makes page loading slower up to 15-20 seconds. The problem has appeared after 1 week of using Kestra.

To solve this problem, I've disabled AdBlock Chrome Addon for Kestra website.

Pending requests:
![image](https://github.com/kestra-io/kestra/assets/11704054/0c5fe6d1-692d-4a1a-aef6-39a9c6bd789d)

15 sec loading waterfall:
![image](https://github.com/kestra-io/kestra/assets/11704054/a8a22f96-035f-4b3a-87b3-05ecd1323549)

Console errors:
```
Mo {message: 'timeout of 15000ms exceeded', name: 'AxiosError', code: 'ECONNABORTED', config: {…}, request: XMLHttpRequest, …}
```

Time for https://api.kestra.io/v1/reports/events :
![image](https://github.com/kestra-io/kestra/assets/11704054/667c9a42-1ab6-45cc-840e-c91ad0c071e2)

### Environment Information

- Kestra Version: 0.13.8 (but also was at 0.9)

AdBlock plugin URL: https://chromewebstore.google.com/detail/adblock-%E2%80%94-%D0%BB%D1%83%D1%87%D1%88%D0%B8%D0%B9-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2/gighmmpiobklfepjocnamgkkbiglidom

**Comment by smunteankestra** [comment]
tested, works fine with AdBlock on version 0.17.3, closing, if issue will reproduce please open another incident
