### ISSUE TITLE
Add a property "id" as alias to "name" on inputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2861]
### Feature description

Every kestra property has "id", only inputs have "name". This is inconsistent and makes it more difficult to use the product.

**Comment by loicmathieu** [comment]
Should it be an alias or should we deprecate name in favor of id?

**Comment by anna-geller** [comment]
deprecating would be ideal, I agree

if too destructive, alias would already help 👍

**Comment by anna-geller** [comment]
when implementing, worth checking whether renaming fixes this issue as well https://github.com/kestra-io/kestra/issues/2533
