### ISSUE TITLE
Add alias "storage" to "storages"

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2862]
### Feature description

We have a concept of internal storage. Seeing storage in the plural form is unusual. We can start by adding an alias/copy "storage" and deprecating "storages" in 1.0.

**Comment by loicmathieu** [comment]
Just to be sure, you mean relocating all storage related tasks from `io.kestra.core.tasks.storages` to `io.kestra.core.tasks.storage`?

I have a WIP for task alias and there is an issue to move core task to a different package so it can be done at the same time.

**Comment by anna-geller** [comment]
sounds great. To explain more: I found the word "storages" in plural a bit unexpected/uncommon (usually you just say "storage"). If you find `storages` OK, let's keep as is and close the issue (not critical to rename this one)

**Comment by loicmathieu** [comment]
All task packages (subgroup) will be singular after the big renaming.
