### ISSUE TITLE
Editing from the split editor/topology mandates double save  

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2869]
### Explain the bug

When you edit a flow in the split editor/topology few using the topology, for ex by adding a new task, you need to save the flow both in the topology view and in the editor.
If you only save it in the topology view, when executing the flow you will have the following popup and the flow is not saved.
![image](https://github.com/kestra-io/kestra/assets/1819009/c7fa3327-dc15-4c2d-9088-ec1179765925)

To reproduce:
- Edit an existing flow with the split editor/topology view
- Add a new task using the topology view
- Save the task using the topology save button
- Execute the flow

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by Skraye** [comment]
There is only one button to save, but maybe you mean the button "save" in a task editor ? 
![image](https://github.com/kestra-io/kestra/assets/37600690/21e83e2a-66ab-45ae-9c66-c691b90f0b0a)
This one does not save the flow but only a task (as we wont save anytime a task is updated)

**Comment by brian-mulier-p** [comment]
@loicmathieu agree with above so I'm not sure it's a bug and if we should do anything about it :thinking:

**Comment by loicmathieu** [comment]
In this case, maybe the name should be changed as it's misleading.

- Save Task
- Update Task
- Apply
- ...
