### ISSUE TITLE
Add a enter shortcut on toast with confirmation

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#287]
for example, the execute flow popup don't have any shortcut, we can use ctrl + enter to see the popup but we need to take the mouse for the confirmation

**Comment by eregnier** [comment]
Yes, it is a great feature. you meant we want autofocus on modal submit button to trigger flow from keyboard only.
That will be a cool feature :)

**Comment by anna-geller** [comment]
old issue, not enough value created by saving 1 click so closing
