### ISSUE TITLE
Remove the expand button from the flow dependencies view

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2873]
When you are in the dependency view of a flow that has dependencies, you see an expand button even if there is nothing to expand. Clicking on it does nothing.

![image](https://github.com/kestra-io/kestra/assets/86264395/efa7036a-d81c-4d7f-91f5-539cf69dfd82)

**Comment by Skraye** [comment]
fix in https://github.com/kestra-io/kestra/commit/45d3e8c7993f9ef7c91b81e0865677abe9b729c9
