### ISSUE TITLE
Tooltip "Settings have been saved" shown when navigating to the Settings page

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2878]
### Explain the bug

Tooltip "Settings have been saved" shown when navigating to the Settings page.

This tooltip must only be shown when the settings are saved not when we arrived in the page.

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by anna-geller** [comment]
looks like this has been fixed as I couldn't reproduce any more, reopen if you still see it
