### ISSUE TITLE
Topology isn't generated until we type something when clicking on "Use" on a blueprint

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2884]
### Explain the bug

Reproducer:
- Click 'Use' button on a blueprint
- Go to Topology tab
- The warning "error while generating..." is there and there is no topology displayed
- Upon writing anything, the topology succeeds to be displayed

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by MilosPaunovic** [comment]
Closing this as it does not seem to be relevant anymore.

https://github.com/kestra-io/kestra/assets/62475782/d0455bef-4124-4d4d-a8cd-193bdb870ae2

Will be reopened if necessary.
