### ISSUE TITLE
Inefficient icon management for topology frontend side

### ISSUE THREAD

**Issue by eregnier** [kestra-io/kestra#289]
It appears that each topology node trigger an http query to get icons from api. 
However, the api returns all icon definition in one document. this is a bloated behavior that we have to centralize in a store
![image](https://user-images.githubusercontent.com/5399780/107669073-a937db80-6c91-11eb-96d1-2c6858948022.png)

**Comment by tchiotludo** [comment]
in fact, it's in the store, but the first request display all the component at the same time when the store is not ready. 
I don't find a quick way for this case (only the first load)

**Comment by eregnier** [comment]
I'll do it :)
I will just do one query at topology load store result  in a vuex store and use something like :img="store['icon']" which lasyloads image if value change from undefined to a string

**Comment by tchiotludo** [comment]
👍 just think the image is not used only on this page, and it will be fined not duplicate the behaviour on each page 😁

**Comment by eregnier** [comment]
it's ok now (PR update)
