### ISSUE TITLE
Auto-complete in VS Code Editor

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#2925]
### Feature description

[After the Python auto-complete issue](https://github.com/kestra-io/kestra/issues/2514), one user asked for Groovy script auto-completion.
Generally speaking, it would be nice to allow auto-complete on all (most used) programming languages

**Comment by anna-geller** [comment]
closing given the planned move to https://github.com/kestra-io/kestra-ee/issues/829

**Comment by brian-mulier-p** [comment]
Still @MilosPaunovic can you check if it's embed in the new editor ?

**Comment by anna-geller** [comment]
autocompletion for programming languages is out of scope for now (too complex + we assume most people code their app logic in their preferred editor and mostly read/make small adjustments in kestra)

**Comment by brian-mulier-p** [comment]
That's not true as Python is a programming language and we still want to provide autocompletion for it :P
Anyway I checked on Monaco's doc and it's not natively supported for groovy. Still @MilosPaunovic idk if there is already something in the Monaco's API to map an extension to the right language but if it's not maybe you can create an external file which holds mappings between extension and the lang to give to Monaco editor :+1: 
It's easy to do and I believe you can base yourself off [this language dropdown](https://microsoft.github.io/monaco-editor/)

**Comment by brian-mulier-p** [comment]
Just for reference, there is also this [groovy language adapter](https://gist.github.com/Ruminat/42364312e90ba5d71875697ede66990e) just in case. I believe if there is a user asking for something and there's things to do it in < 1 hour we should provide it but that's my opinion :+1:

**Comment by MilosPaunovic** [comment]
By default, `Monaco` supports only `css`, `html`, `json` and `typescript`, but it can be definitely be extended to what we need.
