### ISSUE TITLE
state.duration is not properly computed

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2951]
### Explain the bug

See the below report where it says executions have been running for less than a minute while I executed two shell.Commands with a sleep 70 in it
![image](https://github.com/kestra-io/kestra/assets/37618489/7b206c97-fad2-4c53-83d4-241b1bf6937a)
![image](https://github.com/kestra-io/kestra/assets/37618489/69172f1a-2927-483c-a86e-dbf8fedd685d)

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by anna-geller** [comment]
@brian-mulier-p can you still reproduce after Scheduler refactor?

**Comment by brian-mulier-p** [comment]
No I don't :+1:
