### ISSUE TITLE
[Docs] Improve documentation on how Pebble templating is handled in Python scripts – inline script vs. Namespace Files

### ISSUE THREAD

**Issue by tdragon6** [kestra-io/kestra#2969]
### Describe the issue

In the new version, when using `io.kestra.plugin.scripts.python.Script` to run a task, reading a python script file from a namespace file does not recognize the template syntax in the python code.

For example:

```
import os

os.system("cat {{ outputs['node1'].outputs.['file'] }}")
```

An error occurs when the above python script is read from the namespace and executed. It doesn't recognize template syntax `{{ outputs['node1'].outputs.['file'] }}`.

### Environment

- Kestra Version: v0.14.4-full
- Operating System (OS/Docker/Kubernetes): docker
- Java Version (if you don't run kestra in Docker): docker

**Comment by anna-geller** [comment]
This is an intended behavior. You have two options:
1. Paste the script inline in YAML
2. Use argparse, fire or any other CLI library to pass the templates variables
3. (Recommended) don't specify outputs or inputs with Pebble templating, instead use outputFiles and inputFiles properties -- this way you can keep your python code clean (same as local) and only add kestra specific syntax in kestra YAML flow spec.

I agree though we should document it better

**Comment by anna-geller** [comment]
added here https://github.com/kestra-io/docs/commit/1b8c4c6394fef284f674f1349761d59cc1ac87e4
