### ISSUE TITLE
[UI] Add a new welcome page 🎉

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2996]
### Feature description

[Link to figma](https://www.figma.com/file/ew0uXk0NRXJ2NBBJTNe2n1/UI?type=design&node-id=0-1&mode=design&t=TtjBKrrj2UCLCuGC-0)

![image](https://github.com/kestra-io/kestra/assets/86264395/f4d4b700-79ed-4ac7-a195-8fba529bc10c)

light mode:

![image](https://github.com/kestra-io/kestra/assets/86264395/b1674551-c893-464d-8e91-19509b285c59)

for comparison, here is the current page :)

![image](https://github.com/kestra-io/kestra/assets/86264395/6814e19c-3d8f-4d48-8a99-320a8f661fa3)

**Comment by Skraye** [comment]
close in https://github.com/kestra-io/kestra/commit/abb1aab64148605d1e043a3f4d16e596341a437c
