### ISSUE TITLE
Reserve the "system" namespace for kestra and raise a warning when using that namespace name + add a global setting for the name of that namespace

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3004]
### Feature description

We want to introduce system flows in 0.16 or 0.17 https://github.com/kestra-io/kestra/issues/3003 

To do that, we need to reserve the namespace name "system" for kestra 

For this release (0.15.0), we should show a warning in the UI when a user tries to create a flow with a system namespace saying: `"The system namespace is reserved for background workflows intended to perform routine tasks such as sending alerts and purging logs. Please use another namespace name."`

**Comment by loicmathieu** [comment]
There is a high risk that users already used `system` for their system flows.

What we can do however, is to use as _system_ namespace a namespace name that users cannot use as it's not valid (this may require some work on our side) like `*system*`. If those flows will not be editable from users the name of the namespace will not be that important so we may also generate it and register the generated name somewhere.

**Comment by anna-geller** [comment]
There is no risk, we won't delete the namespace for the user. The idea is that if they have a system namespace in 0.15.0, they will see a warning asking to change the name because this namespace will be reserved for system flows. Even if they have some of them, they will not be gone, they will just be hidden behind system flow so they will need to then move if they don't want to always click on the dropdown to find those flows and executions

I think this issue will clarify https://github.com/kestra-io/kestra/issues/3003 

For now, we only need a warning, that's all

**Comment by loicmathieu** [comment]
There is no way to 'move' a flow so they will need to delete the flow and re-create it.

**Comment by anna-geller** [comment]
yes you're right, that's a tradeoff we have to make

**Comment by yuri1969** [comment]
The idea of hiding an _internal functionality_ performed by _utility flows_ is interesting. Could the name be configurable like the [env-vars-prefix](https://kestra.io/docs/administrator-guide/configuration/others#kestravariablesenv-vars-prefix) is?

**Comment by yuri1969** [comment]
@anna-geller No particular use case here beyond flexibility.

**Comment by anna-geller** [comment]
ok, let's do it:

```yaml
kestra:
  system-flows:
    namespace: system
```
