### ISSUE TITLE
[UI] When user hits "Tab", we should navigate to the next field in the UI form rather than creating a long space

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3007]
### Feature description

This already works on checkbox fields, but on text or select fields, kestra adds a long space rather than navigating to the next field in the UI form https://share.descript.com/view/oX72PxSxMCR 

![image](https://github.com/kestra-io/kestra/assets/86264395/c5e73b3f-fd76-4d74-9683-4e50356060af)

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/kestra/commit/075ab7d95cbcbf2ee6b56a4befa373340dd5d31c
