### ISSUE TITLE
[UI] Change the Save and Actions buttons to be in the top right corner of the editor and without the "Actions" and "Save" text — only icons

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3008]
The expected change:
1. Move the buttons to the top right corner of the Editor
2. Change the buttons so that those are only icons without text as shown in the second image below

![image](https://github.com/kestra-io/kestra/assets/86264395/22fc459b-a096-4a5a-b06e-93dd6bfb5430)

![image](https://github.com/kestra-io/kestra/assets/86264395/e09ee6e1-aab8-46c0-bab6-f0e153da0beb)

https://www.figma.com/file/ew0uXk0NRXJ2NBBJTNe2n1/UI?type=design&node-id=144%3A2708&mode=design&t=bTHNOPWLGgwEna8S-1

**Comment by Nico-Kestra** [comment]
Example for responsive, only icon button
<img width="1743" alt="Capture d’écran 2024-02-08 à 10 42 36" src="https://github.com/kestra-io/kestra/assets/125994028/ffee88af-210e-4c49-8f9e-946378081b94">
