### ISSUE TITLE
[Plugin docs] Deprecated properties lack a deprecation sign in the plugin/task documentation

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3012]
### Feature description

![image](https://github.com/kestra-io/kestra/assets/86264395/c4a73d49-431d-44e3-b50c-ca5d41e42b27)

You can see that the UI correctly displays a warning for a deprecated property, but the task docs don't show any info that it's deprecated. We should directly show a deprecation icon next to deprecated properties in the plugin documentation.

**Comment by loicmathieu** [comment]
This has been fixed in 0.16 on the website
![image](https://github.com/kestra-io/kestra/assets/1819009/bb57d452-58b3-4c03-9f6a-041456997550)

On the application, deprecated properties are no longer shown so even if they will be displayed the same, they are hidden.
