### ISSUE TITLE
[UI] Add a dropdown to filter Flows by specific criteria (disabled/enabled, parent/child, with/without any trigger)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3029]
### Feature description

In a similar way to how we added a dropdown to filter executions:

![image](https://github.com/kestra-io/kestra/assets/86264395/cb74c6bd-773b-4fdd-8098-3c0eff81859f)

We need a filter to filter flows by the following criteria:
1. All flows
2. Enabled flows
3. Disabled flows
4. Parent flows
5. Child flows
6. Flows with a trigger 
7. Flows without a trigger

We could filter by trigger type but for now, it seems enough to only allow filtering by flows with and without triggers, as there is a dedicated Trigger tab on each flow and a Trigger page under administration.

**Comment by Kishorecoder96** [comment]
is this issue still open ? can i contribute for this ?

**Comment by MilosPaunovic** [comment]
Yes, go for it @Kishorecoder96! 🚀

**Comment by Ben8t** [comment]
@Kishorecoder96 did you succeed to make any progress on this :) ?

**Comment by Kishorecoder96** [comment]
> @Kishorecoder96 did you succeed to make any progress on this :) ?

No I will work from Sunday

**Comment by Kishorecoder96** [comment]
@Ben8t i setup kestra in my local environment and cant find the code for filters in execution .can you help me with this provide me the path or some references.

**Comment by MilosPaunovic** [comment]
@Kishorecoder96  Execution filters are located in `kestra/ui/src/components/executions/Executions.vue` file.

**Comment by Kishorecoder96** [comment]
@MilosPaunovic I can't add the filter ,bcoz i am not good at vue. So I will learn and do this ,unassign me now so if anybody knows contribute now if no one contribute i will come back and contribute

**Comment by anna-geller** [comment]
sure, no problem @Kishorecoder96 :)
