### ISSUE TITLE
Enable output encryption to all tasks or just specifically HTTP request

### ISSUE THREAD

**Issue by kriko** [kestra-io/kestra#3032]
### Feature description

**Using Oauth2 or similar authentication flows and HTTP request with the new features regarding encryption of secrets**

For some [HTTP requests](https://kestra.io/plugins/plugin-fs/tasks/http/io.kestra.plugin.fs.http.request) authentication should be done before the main request, one of these scenarios involves authenticating against an Oauth2 or an OpenID Connect endpoint, then using the generated token for sequential requests. These tokens typically have a lifetime between hours to even a month and thus should be considered as sensitive.

In an authentication flow, one could have a HTTP request task carrying out the authentication, however when the token is returned as the output of the HTTP request task, the token would be logged and stored unencrypted.

In regards to the following issues in GitHub: #2046  and #2143

Would it be possible to enforce the HTTP request task to encrypt it's outputs?

A more general approach would be to have a generic attribute for each task (or even a flow that produces outputs), to define the required JSON paths either statically or [dynamically (using JsonPath)](https://github.com/json-path/JsonPath) and these outputs would be encrypted on the fly, before they are passed along?

Iterating over the idea - inputs to (sub)flows or tasks could be decrypted in a similar way - defining an array of static or dynamic JSON paths, carried in an input, to be decrypted on the fly.

**Use cases**

1. Oauth2 or similar authentication flows in http requests.
2. A more generic solution would also support compliance with delicate (such as personally identifiable) data in extract-load type of flows.

Discussed with @loicmathieu in [Slack](https://kestra-io.slack.com/archives/C03FEC452NQ/p1707438030794029).

**Comment by loicmathieu** [comment]
Decision has been done to only add encryption to the HTTP Request task as done in GCP and AWS Auth token tasks.
