### ISSUE TITLE
Unable to save the default flow without any modification

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3047]
### Describe the issue

When you create a flow, there is a default flow in the editor.
It is not possible to save it without any modification.

### Environment

- Kestra Version: 0.15-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
indeed, quite an urgent bug https://share.descript.com/view/cxaYIAZcOAd
