### ISSUE TITLE
Make the relative/absolute filter on Executions page + Flows Executions tab less prominent (perhaps grey color?)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3061]
### Feature description

It works well, but it's a bit distracting - perhaps just changing the color of this to grey? 

![image](https://github.com/kestra-io/kestra/assets/86264395/6db29217-d63b-4966-910f-80401a1784d6)

https://share.descript.com/view/7ZrOS02JG0W

**Comment by loicmathieu** [comment]
Another solution would be instead to have radio button to select Relative / Absolute.
Have an entry in the relative select that switch to absolute (this is how Kibana does for ex).

**Comment by anna-geller** [comment]
yup totally, same thoughts by Nico, he's working on a toggle
