### ISSUE TITLE
Backfill is still running even if ended

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#3069]
![image](https://github.com/kestra-io/kestra/assets/2064609/8bcdc536-2ca2-4357-8210-ee859db22cba)
If I fill a backfill end date that could not be reach, the backfill will never end and will be kept in running state. 
We need to consider the backfill as ended as soon as the end date is the same the normal one.

**Comment by loicmathieu** [comment]
It now impossible to create a backfill with an end date in the future.
And if we create a backfill that ends now, it is correctly ended when now is reached.
