### ISSUE TITLE
Kestra shutdown after some time

### ISSUE THREAD

**Issue by drakylar** [kestra-io/kestra#3107]
### Describe the issue

Kestra triggers a shutdown after some time (12-24 hours), log fragment:

```
INFO    scheduled-executor-thread-1   io.kestra.jdbc.runner.JdbcCleaner  Cleaned 329492 records from queues
ERROR   scheduled-executor-thread-1   io.kestra.jdbc.runner.JdbcHeartbeat  heartbeatCheckUp failed, unable to find current instance '6347ba98-a70b-4dc8-b034-a773ae4f75cf', Shutting down now!
WARN    command-shutdown   io.kestra.cli.AbstractCommand  Receiving shutdown ! Try to graceful exit
WARN    command-shutdown   io.kestra.core.runners.Worker  Worker still has 4 thread(s) running, waiting all threads to terminate before shutdown!
...
INFO    command-shutdown   io.kestra.core.runners.Worker  No more worker threads busy, shutting down!
```

### Environment

- Kestra Version: 0.15.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes): docker-compose

**Comment by anna-geller** [comment]
hey, the 0.15.0 has not been released yet; the `develop` image/branch may be a little flaky; sorry about that!

I'll forward the issue to our engineers, and meanwhile, you can use the latest stable version, 0.14.4 (the `kestra/kestra:latest-full` image)

Thanks so much for reporting this!
