### ISSUE TITLE
[UI] ForEachItem taskrun Gantt disaplay is broken

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3108]
### Describe the issue

See

![image](https://github.com/kestra-io/kestra/assets/1819009/828ec46f-a497-40cb-8ea5-a32386a3a53f)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Skraye** [comment]
closes in #3120
