### ISSUE TITLE
[UI] When you arrive to the settting page you have a Setting updated toast

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3150]
### Describe the issue

When you arrive to the settting page you have a Setting updated toast.
But you just read the settings!
Settings should be saved only when changed, not when read to display the settings page.

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
I can't reproduce https://share.descript.com/view/k5ZrMJI717m

if you still see the issue, please share a screen capture or screenshot image
