### ISSUE TITLE
[UI] 'Open' and 'Expand' flow in the dependencies tab didn't work anymore

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3160]
### Describe the issue

'Open' and 'Expand' flow in the dependencies tab didn't work anymore.
Clicking on any of these button didn't do anything (there is no error in the console neither).

### Environment

- Kestra Version: 0.15
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
moved to 0.16 due to time constraint and not enough info, if this is a critical issue, please move to 0.15 and add a reproducer + maybe some video or screenshot of the UI issue
