### ISSUE TITLE
Extend the `secret()` function to return null if the secret cannot be found 

### ISSUE THREAD

**Issue by M-E-Rademaker** [kestra-io/kestra#3162]
## Motivation

At one point in a flow we pass/set a password as an env variable via the `env` property of the `io.kestra.plugin.scripts.python.Commands` task.

Now I want to switch between passwords and i want to use `secret()`. Depending on where the flow is run (locally or in producation), the first password (defined as an env variable called `SECRETS_PASSWORD_A`) may not exist. 

In this case I want to use the second (which is some default). I tried: 

`USER_PASSWORD: {{ secret('password_a') ?? 'default_password'}}` 

This does not work because `secret()` complains that 'password_a' is not defined (which is correct in this case). I guess my question is: Can I somehow wrap this in an if-statement that does somehting like1. if password_a exists, use secret() on it and set this to be USER_PASSWORD

2. if `password_a` does not exist use `default_password` and skip using `secrets()`

## Suggested solution 

In the slack #help channel Ludovic suggested to add an argument `failedOnMissing=false`

See: [the conversation on the slack #help channel](https://app.slack.com/client/T01JX6XH5KN/activity)

**Comment by anna-geller** [comment]
I believe failing will not help here. The secret function will need to return null if the secret is not found
