### ISSUE TITLE
Add HTTP core plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3188]
### Feature description

Simple HTTP calls should be feasible in the core library without having to require a dedicated plugin + Ludo mentioned HTTP doesn't have many dependencies so should be feasible

**Comment by loicmathieu** [comment]
Yes, the current HTTP tasks can be moved to the core without needed any additional library.
We can also move them to a dedicated plugin for better visibility.

**Comment by anna-geller** [comment]
moving to core would be fantastic
