### ISSUE TITLE
Kestra VS Code Editor keeps defaulting to the 'getting-started.md' file.

### ISSUE THREAD

**Issue by JumaX** [kestra-io/kestra#3194]
### Describe the issue

**Task:**

Moving from different interface elements back to the Kestra VS Code editor to edit code.

**Problem:**

When moving between different interface elements, for example viewing the logs of a failed/completed task, back to the embedded VS Code editor, the `getting-started.md` file is always re-opened and set to the default file that is loaded.  This is very frustrating if you are moving back and forth between the editor and logs to test items.  

Ideally, the 'getting-started.md' should be opened the first time a user logs in, and then never again.  Additionally, having the ability to remove this file from the editor would be helpful as well.

![Screenshot 2024-03-01 at 10 46 55 (2)](https://github.com/kestra-io/kestra/assets/1376580/37984d4c-d8cd-4446-b8d9-3e8271738087)

### Environment

- Kestra Version: 0.15.0
- Operating System (OS/Docker/Kubernetes): Mac OS/Docker Desktop
- Java Version (if you don't run kestra in Docker): N/A.

**Comment by anna-geller** [comment]
The getting_started.md file was removed as part of Editor redesign https://github.com/kestra-io/kestra/pull/3568 

![image](https://github.com/kestra-io/kestra/assets/86264395/7780d0de-2b01-469a-bb4f-4a096798fee3)
