### ISSUE TITLE
[UI] Trigger toggle need a double click

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3195]
### Describe the issue

On the trigger admin page, you need to click twice on the trigger toggle to unable/disable it, which seems odd as usually a toggle uses a single click.

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Skraye** [comment]
Could not reproduce
