### ISSUE TITLE
For Each Item displays 5 task in the topology but not in the code

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#3206]
### Describe the issue

Will it have been designed to be a feature (still not clear to me 🤔), the introduction of for each item tasks in the topology/logs is not explicitly declared in the YAML syntax, which seems to be a discrepancy to Kestra's semantic isn't?

cc @anna-geller for discussing this as it's very unclear from a user perspective

![image](https://github.com/kestra-io/kestra/assets/46634684/9d087a63-b4b9-4a5b-86f9-c2b80018a14f)

**Comment by Ben8t** [comment]
related issue: https://github.com/kestra-io/kestra/issues/3208

**Comment by anna-geller** [comment]
@Ben8t, We did it to solve technical issues (not intended to be user-facing), but it was not fully finished yet other than fixing a critical bug. The icons were not addressed yet 

let me consolidate that into one issue, thx for the report
