### ISSUE TITLE
[UI] Flows > Create editor turns blank on new flow with problematic YAML

### ISSUE THREAD

**Issue by kriko** [kestra-io/kestra#3217]
### Describe the issue

Open Kestra. Go to Flows.
Create a new flow.
With the prefilled template, delete the first 3 lines or copy paste this code:
```
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
```
Editor will disappear.
![kestra-editor-bug](https://github.com/kestra-io/kestra/assets/169998/c83274fe-55db-481c-a15f-e1fb4eb66090)

### Environment

- Kestra Version: 0.15.0

**Comment by anna-geller** [comment]
on 0.17 it turns completely grey. thx for reporting! 👍 

![image](https://github.com/kestra-io/kestra/assets/86264395/022701ae-053c-4f48-a2cf-17799c2f5bd5)

**Comment by MilosPaunovic** [comment]
@kriko This is now completely amended with the latest commit https://github.com/kestra-io/kestra/commit/57230b07a9ce9d61cf670a3067da885e48dd633e on the `develop` branch.

Thank you for pointing us to it, much appreciated!
