### ISSUE TITLE
Failed executions on Flow detail page is not filtered for that flow

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3240]
### Describe the issue

On the flow detail page, failed executions are not filtered by the selected flow, and hence, shows up failed executions of other flows. Ideally, we should have failed executions only for the flow selected.

I have attached the screenshot showing the failed execution on the flow detail page that belongs to other flow.
<img width="1728" alt="flow_detail_page_issue" src="https://github.com/kestra-io/kestra/assets/6594483/9f6e373b-2d18-48c8-a522-09c6a8b6f6b7">

### Environment

- Kestra Version: 0.15.0
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker): N/A

**Comment by anna-geller** [comment]
I can reproduce

![image](https://github.com/kestra-io/kestra/assets/86264395/4283cd9a-19c2-4331-8138-36ba738b0289)

```yaml
id: hello1
namespace: myteam

tasks:
  - id: fail
    type: io.kestra.core.tasks.executions.Fail
```

it will show other flow's failed executions too
