### ISSUE TITLE
Redesign `ForEachItem` task — add the store boolean property

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3271]
Due to recent changes made to address the Executor issues, [you can no longer use](https://share.descript.com/view/AIpTlTxOdv0) the `read(taskrun.items)` as it gives (see video): `The 'read' function can only be used in the Worker as it accesses the internal storage. ({{ read(taskrun.items) }}:1)`

To address it, we'll need to:
- add `store: bool` property by default set to `true`
- figure out how to handle the split without storing the data (`store: false`)

**Comment by loicmathieu** [comment]
This has been abandoned as we revert the restriction of the `read()` method to the Worker.
A redesign of the task will be done on the next release.
