### ISSUE TITLE
[UI/Settings]  add a 'Save'' button to save all the modifications once

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#3285]
### Describe the issue

Currently, the settings are saved on each field modification. However, this may lead to unexpected behaviors. 

- For dropdown lists the save confirmation message is displayed even if no change was made. 
- For `Editor font size`: a confirmation message is displayed each time we click on top/down arrows (the user is spammed)

### Environment

- Kestra Version: 0.15.x
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by RashmitTopG** [comment]
I would like to work on this

**Comment by Skraye** [comment]
Hello @RashmitTopG , I've just assigned you to the following : https://github.com/kestra-io/kestra/issues/2177

Please pick one task at a time, I can remove you from the other one if you'd rather work on this one!

**Comment by CGaneshKumar2002** [comment]
Hi @fhussonnois I wish to work on this issue. I have a basic idea on how Settings page work as I worked on #1949. I suppose I have some solution in my mind regarding this one, but before getting started on this one, the #1949 issue-tagged pr (#5554) should be merged inorder to avoid conflicts as I think it involves working on the same file. Kindly let me know if that's not the case

**Comment by syedfardeenjeelani** [comment]
@anna-geller  i would like to work on this issue

**Comment by MilosPaunovic** [comment]
@CGaneshKumar2002 You can start working on this and I'll take a look at the #1949 Monday, and if we merge it in the meantime, you can just rebase your branch for this issue.

**Comment by CGaneshKumar2002** [comment]
Hi @MilosPaunovic I've raised a PR for this one. Kindly check and let me know your feedback if any. Thanks

**Comment by MilosPaunovic** [comment]
Thanks @CGaneshKumar2002, looking forward to more of your PRs! 🚀
