### ISSUE TITLE
[UI/Stats] French translations are missing for the Stats page

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#3287]
### Describe the issue

French translations are missing for the Stats page

### Environment

- Kestra Version: 0.15.x
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
All french translations are there.
![image](https://github.com/kestra-io/kestra/assets/1819009/3a94b6ad-26f5-4b33-82f7-325518054c44)
