### ISSUE TITLE
Execution > outputs can't freeze if too many ouputs

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#329]
1000 rows with 15 cols on the execution can lead to a browser freeze on the outputs tabs

**Comment by Ben8t** [comment]
@Skraye or @brian-mulier-p 
Could you provide some kind of pre-analyse to see what's possible pls ?

Is it a problem with json deserialization or just the table viewer (cf. [Virtualized table in Element framework](https://element-plus.org/en-US/component/table-v2.html) )?
