### ISSUE TITLE
[UI] Display a warning when Flow has a plain text password or token

### ISSUE THREAD

**Issue by kriko** [kestra-io/kestra#3291]
### Feature description

Many flows enable users to authenticate against services and it might be convinient for a developer to save their flow with hard-coded credentials, but when we take into account that Kestra itself versions the flows and flows may also be synced to Git, then these credentials can leak. The correct usage for credentials should be through the secret() function.

Thus a feature proposal (or idea): in order to help developers avoid these mistakes, display a warning message when credentials are inserted in plain text.

**Comment by anna-geller** [comment]
interesting idea

at first, it's easier to get started locally with credentials in the code so the warning could be potentially annoying, but I agree there is a benefit that it forces users not to forget to add credentials

we could enable this in the configuration

let's keep the issue open and see the interest in the community, we can definitely add it as an opt-in feature

**Comment by anna-geller** [comment]
possible way to tackle it: 
1. Flag sensitive properties within the plugin
2. Regex on those properties to verify user leverages some Pebble here e.g. awsSecretKey: "{{  }}" -- this meansthey use env variables, namespace variables, inputs or secrets

**Comment by shawnfrost69** [comment]
Hi @anna-geller, could you please provide a video demonstrating this issue? It would help me gain a clearer understanding of the problem. Thank you!

**Comment by MilosPaunovic** [comment]
@shawnfrost69 I've assigned you to another issue. Why don't we take one by one, and after closing that one, you can choose another one.

**Comment by anna-geller** [comment]
we currently mask all sensitive values (secret-type inputs, secrets etc), closing for now
