### ISSUE TITLE
Add saved search filters shared across the instance or custom Execution dashboards

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#3311]
### Feature description

As a continuation of #1397 it would be great to implement a some form of _shared search filters_.

Being able to store personal (local) _search filters_ is great. However, having an instant access to a set of centrally stored common queries would also support efficient collaboration within a team. Additionally, having such ready-to-use filters could make day-to-day operations less error prone.

---

Typical use cases:
* Common filters for the support team - "List Executions featuring a label `state: production` and being in the Failed/Warning state in the past 1 hour" + the same for 24h
* Instantly available filters for members of a particular project - "List Executions featuring labels `project: FOO` in the past 24 hours"

---

It would help to be able to CRUD the stored queries without restarting the cluster - maybe a similar approach to [EE's Custom Blueprints](https://kestra.io/docs/enterprise/custom-blueprints).

**Comment by anna-geller** [comment]
I think this issue is mostly intended for the Enterprise Edition, can you confirm? Because OSS is a single-player instance so the saved search there is saved for that single user, unless the search will not survive instance restart? 

FWIW we have an open issue to start saving Settings in the DB (instead of just locally) but moving saved search filters to Settings wouldn't address the use case for those filters to be shared across the team.

Do you want those filters to be shared across namespaces or should they be tied to a namespace?

**Comment by yuri1969** [comment]
> I think this issue is mostly intended for the Enterprise Edition, can you confirm? Because OSS is a single-player instance so the saved search there is saved for that single user, unless the search will not survive instance restart?

Having the search filters saved to a DB (instead of locally) would benefit even the single-user OSS edition - different browsers, browser storage flushes, etc.

But yes, it feels like it would mostly benefit the multi-user EE with a potential to tie the searches to roles and/or namespaces.

> FWIW we have an open issue to start saving Settings in the DB (instead of just locally) but moving saved search filters to Settings wouldn't address the use case for those filters to be shared across the team.

Settings represent a single personalized user config. OTOH the Saved searches are intended to be defined and shared among multiple users.

> Do you want those filters to be shared across namespaces or should they be tied to a namespace?

Right now, we don't have a real use case for introducing a fine granularity of the Saved searches - per namespace, per user role, etc. However, there might be a potential to effectively filter irrelevant Saved searchers out from a group of users (e.g. support don't need to see test-related filters).

**Comment by anna-geller** [comment]
https://www.figma.com/file/ew0uXk0NRXJ2NBBJTNe2n1/UI?type=design&node-id=660-5610&mode=design&t=pPFw3QuxFOjDCIoa-0

![Flow-Executions](https://github.com/kestra-io/kestra/assets/86264395/b0ef7059-99a3-4c30-a269-0b65c42ca91c)

**Comment by MilosPaunovic** [comment]
As we've introduced `Custom Dashboards`, this issue seems like it needs a bit of triage.

**Comment by anna-geller** [comment]
thanks for bringing this up Milos — you're right, the main request from Yuri has been shipped in the last release through the combination of custom dashboards, bookmarks and saved search filters. We can keep iterating by opening dedicated issues as follow up to Custom Dashboards on EE repo for now
