### ISSUE TITLE
The concurrency limit is marked as mandatory in the low code editor

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3333]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/528d5cd4-21df-462d-bf16-2ae96bfa474a)

### Environment

develop

**Comment by MilosPaunovic** [comment]
Regarding this - it's determined by the backend, which returns this segment as part of the response:

`{
    "type": "object",
    "properties": {
        "behavior": {
            "type": "string",
            "enum": [
                "QUEUE",
                "CANCEL",
                "FAIL"
            ],
            "default": "QUEUE",
            "markdownDescription": "Default value is : `QUEUE`"
        },
        "limit": {
            "type": "integer",
            "exclusiveMinimum": 0
        }
    },
    "required": [
        "limit"
    ]
}`

So potentially this should not be handled on the FE, if I'm not wrong @anna-geller ?

**Comment by anna-geller** [comment]
I don't know about the implementation, but `concurrency` has to be an optional property.

**Comment by Skraye** [comment]
close by https://github.com/kestra-io/kestra/commit/70a0b67548b15c6613ea19c09f411abdd1f43e9e
