### ISSUE TITLE
Beta plugins

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3344]
### Feature description

When a plugin is annotated with `com.google.common.annotations.Beta`, add a `$beta` property in the JSON Schema and document it as beta.

The following snippet should be added with an alert of type info:

> This plugin is currently in beta. While it is considered safe for use, please be aware that its API could change in ways that are not compatible with earlier versions in future releases, or it might become unsupported.

~@anna-geller please advise for the snippet documentation, I'll update the description accordingly~ => updated

**Comment by anna-geller** [comment]
how about this?

> This plugin is currently in beta. While it is considered safe for use, please be aware that its API could change in ways that are not compatible with earlier versions in future releases, or it might become unsupported.
