### ISSUE TITLE
[UI] Boolean is not displayed correctly (the true, false, none labels are gone)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3362]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/1de178c8-d06f-49b3-87e5-9297330323e4)

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Skraye** [comment]
close in https://github.com/kestra-io/kestra/commit/34a74fb2218408e4d172d51b2e23ee3e3f32200c
