### ISSUE TITLE
Can’t push to github

### ISSUE THREAD

**Issue by rupisaini123** [kestra-io/kestra#3377]
### Describe the issue

I am created a github branch and try to oush the flows using io.kestra.plugin.git.Push and followed the instructions from https://kestra.io/plugins/plugin-git/tasks/io.kestra.plugin.git.push.

But when i execute the flow, it keeps on giving the error “ Ref HEAD cannot be resolved”

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
can you share a reproducer?
