### ISSUE TITLE
Flow failed from executor don't purge scheduler & don't trigger listeners

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#338]
If I have a flow with a Flow failed from executor (for any reason), it : 
- don't trigger the listeners at least (maybe Flow Trigger also) 
- don't purge the scheduler and the flow will be blocked (because of this [condition](https://github.com/kestra-io/kestra/blob/b55ac08ba9661b7803cfd7ac4116f4c93c9f29ec/runner-kafka/src/main/java/io/kestra/runner/kafka/KafkaScheduler.java#L108))

**Comment by anna-geller** [comment]
@tchiotludo is it still relevant? it's open for over 3 years, I'm gonna close it unless you say it's still worth looking at
