### ISSUE TITLE
[Front] Strange toggle for boolean input

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3380]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/1819009/565eb9bf-5122-4e5e-9544-b8904d06b03c)

There is a strange three-value toggle for boolean input without any labels and specific coloring.

### Environment

- Kestra Version: 0.16.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
duplicate https://github.com/kestra-io/kestra/issues/3362
