### ISSUE TITLE
Import CSV >2GB with PostGreSQL CopyIn

### ISSUE THREAD

**Issue by thomas-depierre-ntico** [kestra-io/kestra#3386]
### Describe the issue

Unable to load CSV files larger than 2GB with the PostGreSQL.CopyIn plugin. The error message indicates missing data at the point where the file reaches 2GB
![image](https://github.com/kestra-io/kestra/assets/121309939/38eaae32-94a7-4728-9b1c-367c9161875a)

### Environment

- Kestra Version: 0.15.6
- Operating System: Docker

**Comment by loicmathieu** [comment]
Hi @thomas-depierre-ntico can you add a YAML flow example (with redacted secret if any) and tell us which Kestra internal storage you are using (the default is the local storage if you didn't configure anything and use our docker compose).

**Comment by thomas-depierre-ntico** [comment]
Hello Loïc,
Unfortunately I am no longer working on this project. I could therefore not
provide the corresponding flow. For storage, we were on internal storage
(we switched to S3 later).

**Comment by loicmathieu** [comment]
@thomas-depierre-ntico thank you, we will see what we can do without these information.

**Comment by loicmathieu** [comment]
For the record, this is known to not work on Windows, see https://www.postgresql.org/message-id/15654-bd233aae1c150270@postgresql.org

**Comment by thomas-depierre-ntico** [comment]
We have never installed our Kestra production on Windows, only Linux

**Comment by loicmathieu** [comment]
I tested it and it works with a 2.1GB file with the fix to file upload, see https://github.com/kestra-io/kestra/pull/3429
It should have been caused by an invalid file truncated to 2GB
