### ISSUE TITLE
Tasks from dependencies in plugins are transmitted in PluginDocumentation

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#3390]
### Describe the issue
Here AWS depends on plugin-script
![image](https://github.com/kestra-io/kestra/assets/37618489/4e2e55df-66a0-4093-a70d-a94daa6cb4dc)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
fixed

![image](https://github.com/kestra-io/kestra/assets/86264395/5df1599d-fe2d-4018-a5e6-1f588377390c)
