### ISSUE TITLE
Blueprint: Add a space between the header and the topology

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#3393]
### Describe the issue

The topology is stuck to the header, please add a space.
<img width="1926" alt="Capture d’écran 2024-03-26 à 10 51 07" src="https://github.com/kestra-io/kestra/assets/125994028/67808d0a-0e9f-41f6-8ebe-df6a61af3351">

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
no longer happening

![image](https://github.com/kestra-io/kestra/assets/86264395/50d3cf6c-4b3f-43bc-9683-e2a4b17cee3c)
