### ISSUE TITLE
Misleading UI warning about inputs name property

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3397]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/628c657b-3cb8-4f41-bb0c-9c3d74ef915d)

### Environment

- Kestra Version: develop

**Comment by brian-mulier-p** [comment]
@anna-geller this was fixed by https://github.com/kestra-io/kestra/commit/7c85c2eb52050984891d4d8941f1da2791dc4c2c
Please reopen if you still experience it but on preview I don't.
