### ISSUE TITLE
DockerScriptRunner autocompletion lists 5 runners instead of 1

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3399]
### Feature description

Overall, it works great! only the autocompletion issue:
![image](https://github.com/kestra-io/kestra/assets/86264395/de0491ca-2c84-4c9a-abf6-cdcec84a791c)

**Comment by brian-mulier-p** [comment]
Probably fixed by [this](https://github.com/kestra-io/kestra/commit/f564a463cef9bedad40b8bb2b1b1b373fb941960)
