### ISSUE TITLE
Stats page is blank on Kestra Cloud

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3408]
### Describe the issue

Stats page is blank on Kestra Cloud.

![Blank_Stats_Page](https://github.com/kestra-io/kestra/assets/6594483/a96b7146-efcf-4908-b3b3-68991fd31f94)

### Environment

- Kestra Version: 0.15.8
- Operating System (OS/Docker/Kubernetes): Cloud
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
I confirm:

0.15.8
![image](https://github.com/kestra-io/kestra/assets/86264395/ef668fc8-1c2e-47b5-9fc9-f28ad6eb3289)

The current 0.16.0 snapshot seems fixed

![image](https://github.com/kestra-io/kestra/assets/86264395/fe903109-70f4-4817-820b-12335529ba98)
