### ISSUE TITLE
Service Accounts landing page shows no service account even when there exists service account

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3409]
### Describe the issue

When I create service account, it gets created successfully.
After the successful creation of service account, no service account appears on the Service Accounts landing page.
![Empty_Service_Account_Page](https://github.com/kestra-io/kestra/assets/6594483/202017fa-cc57-4a64-b60c-d2703a0f621d)

Assuming that the service account might not have got created, when I try to create the same service account again, it rightly errors out stating that `Invalid entity: user.username: Duplicate username, already exists`

The error statement is incorrect, as it should have said duplicate service account. But it mentions it as "user.username". 

<img width="735" alt="Duplicate_Service_Account_Error" src="https://github.com/kestra-io/kestra/assets/6594483/9c83a5f1-e4bb-4cb0-b9eb-61a0bb3b6b2a">

### Environment

- Kestra Version: 0.15.8
- Operating System (OS/Docker/Kubernetes): Cloud
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
thx a lot, I can reproduce

https://share.descript.com/view/KDe0x8K3oPg

**Comment by fhussonnois** [comment]
I agree that this behavior is frustrating. Unfortunately, in Kestra service accounts and standard users are managed in the same way. If you try to create a new user with no access you'll get exactly the same behavior, i.e., users (in a broad sense) with no access are not visibile.

**Comment by Skraye** [comment]
close as it was done when I set a default empty access for new user created (including Service Account)
