### ISSUE TITLE
Grey out Namespace tabs other than "Create" for a namespace that hasn't been created yet

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3410]
![image](https://github.com/kestra-io/kestra/assets/86264395/75304acb-ad62-4943-80e1-a7516e4ceba5)

### Describe the issue

1. When I open an existing namespace, the header on the top says "Namespaces" instead of stating the namespace corresponding to that page. In this case, `io.kestra.tests`
2. The namespace that I had selected was `io.kestra.tests` as is correctly referenced in the URL, but the Failed Executions and Error logs are showing a different namespace: `io.kestra`. (I think thats the only namespace where I had failures, implying that Failed Executions and Error Logs are not filtered for the namespace under consideration.)
3. `Error Logs` title is incorrectly named as `Errors Logs`.

### Environment

- Kestra Version: 0.15.8
- Operating System (OS/Docker/Kubernetes): Cloud
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
# 1 it's just a section name, the namespace name is visible
![image](https://github.com/kestra-io/kestra/assets/86264395/2666d03b-937f-4d16-b94b-679c34a7f78c)

# 2 can you record a screen share showing it? also here I couldn't reproduce yet
# 3 could you add more info + screenshots, I don't see Errors Logs anywhere in the app yet

**Comment by shrutimantri** [comment]
Here is the link of the screen recording showcasing the issue: https://drive.google.com/file/d/1zJydIBzjHfRGy-5vPxJY1fxHiQ_W4WyO/view?usp=drive_link

**Comment by anna-geller** [comment]
The namespace has not been created yet, so only the Create tab should be visible until then (the other tabs should be greyed out). Thanks for the report, Shruti!

**Comment by anna-geller** [comment]
will no longer be needed as we'll automatically create namespaces for namespace names used in flows https://github.com/kestra-io/kestra-ee/issues/1038
