### ISSUE TITLE
Namespace Create button lands on Dependencies tab

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3412]
### Describe the issue

The "Create" button should land on "Create" tab, but instead lands on "Dependencies" page.

![Create_Namespace_Lands_Wrongly](https://github.com/kestra-io/kestra/assets/6594483/33319215-a6e5-4bac-a2bc-8a3f3f74ff91)

### Environment

- Kestra Version: 0.15.8
- Operating System (OS/Docker/Kubernetes): Cloud
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
yup, I can reproduce 👍 

https://share.descript.com/view/SmSy8IgSxun

**Comment by Skraye** [comment]
Done in https://github.com/kestra-io/kestra-ee/commit/4a281cb2e74ce3f170ac18d3380e8ddeea207b31
