### ISSUE TITLE
Improve handling of working directory and file inputs/outputs for remote Script Runners

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3415]
### Feature description

Example issue showing that things work so far but with an error-prone configuration https://github.com/kestra-io/plugin-aws/issues/405 

possible avenues to explore:
- expose the workingDir and ouputDir as env variables
- inject execution context into Script libs to allow retrieving `workingDir` or `outputDir` https://github.com/kestra-io/libs/issues/4

**Comment by loicmathieu** [comment]
We should definitely set an env variable for both directories (which are the same by the way), it can easily be done.
