### ISSUE TITLE
Adjust ProcessScriptRunner to better support Windows users

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3464]
issue just to keep track— for now, Process script runner doesn't accept any parameters, so we may want to adjust to make it work on Windows 

(e.g. the default interpreter /bin/bash won't work on Windows)

![image](https://github.com/kestra-io/kestra/assets/86264395/5e830d37-3965-4d0e-bdfe-543509d6c1b1)

**Comment by loicmathieu** [comment]
It creates a new process and send the existing command to it.

There is nothing to adapt for Windows, Java is agnostic of the OS so starting a new process will works on all OSes compatible with Java.

The task itself, however, needs to be updated to use another interpreter, not the task runner.

**Comment by anna-geller** [comment]
perfect, thanks for checking - let's add info in the docs https://github.com/kestra-io/kestra/pull/3583 and close then
