### ISSUE TITLE
Use the new FileSerde methods

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3475]
### Issue description

Thanks to https://github.com/kestra-io/kestra/pull/3472 we now have a more performant way to deal with multi-line reading/writting of ION files.

We should:
- Deprecate the existing methods (maybe not all)
- Use them in all plugins that reads/writes multiple rows
- Validate that a file written with the old mechanism is still readable with the new (imagine an update after a write of a file, the file should be readable by the updated code)
- Validate that the new format is still preview nicely in the UI

**Comment by loicmathieu** [comment]
Good task candidate: https://github.com/kestra-io/plugin-serdes/issues/102

**Comment by loicmathieu** [comment]
Result for the serdes plugin: https://github.com/kestra-io/plugin-serdes/pull/105

**Comment by anna-geller** [comment]
moved to 0.18 due to Jackson upstream issue

**Comment by loicmathieu** [comment]
Upstream issue: https://github.com/FasterXML/jackson-dataformats-binary/issues/493

**Comment by loicmathieu** [comment]
A workaround has been done, see https://github.com/kestra-io/kestra/commit/9911e2532fc6a8baddfe6f46f3be6a8 965ef26f2#diff-01b560e0a4b0dd166ea2841ec5a4887132f4c8d87c07134504cb0ab39b57e24dR152

All plugins has been updated to use `FileSerde.readAll()` and `writeAll()` where applicable and not too complex todo.
