### ISSUE TITLE
[UI] The call to the taskruns/search API is made twice from the taskruns page

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3510]
### Describe the issue

The call to the `taskruns/search` API is made twice from the taskruns page, when arriving in the page.
As this call can be costly, it should be done once.

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by brian-mulier-p** [comment]
I fixed a duplicate call but I think it was targetting more than only taskruns page. What I've found is that the duplicate call came whenever we load a page where there is the auto refresh that is already activated upon page load.
