### ISSUE TITLE
[UI] The new plugin page miss a light theme

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3515]
### Describe the issue

See 
![image](https://github.com/kestra-io/kestra/assets/1819009/4e89ed14-fe0c-4ce0-acb1-94eb735484aa)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Skraye** [comment]
done in : https://github.com/kestra-io/kestra/commit/3bc599f71d1124a3302dfa0c71fb079ad1c38b5e
