### ISSUE TITLE
feat(ui): provide URL to the child execution in UI when using io.kestra.core.tasks.flows.Flow

### ISSUE THREAD

**Issue by aballiet** [kestra-io/kestra#3519]
### Feature description

Allow users to jump to child execution from the option menu.

![image](https://github.com/kestra-io/kestra/assets/25565600/2f21cb61-50a0-4efd-baac-8e62e5321072)

Could be a URL embedded in logs or a dedicated option from menu. When Kestra UI detects the task type, it creates this option

**Comment by anna-geller** [comment]
We now log a clickable execution ID and flow ID + there is a Subflow menu item in the taskrun

![image](https://github.com/user-attachments/assets/3685467d-79d3-48c9-8b9a-142ee0cccc90)

**Comment by aballiet** [comment]
Amazing @anna-geller 🔥
