### ISSUE TITLE
Flow editor cursor issue

### ISSUE THREAD

**Issue by Naxora** [kestra-io/kestra#3532]
### Describe the issue

Sometimes when I go back to edit the flow I got this issue.
I click where the red dot on the image but the select cursor jump into the middle of the line.

Browser version: Brave v1.64.122
All extension disabled.

![Screenshot 2024-04-12 115614](https://github.com/kestra-io/kestra/assets/40932425/53b7bc91-cc20-4157-85d3-78b6db22ed6e)

### Environment

- Kestra Version: 0.16.0
- Operating System (OS/Docker/Kubernetes): Docker on linux server
- Java Version (if you don't run kestra in Docker): -

**Comment by MilosPaunovic** [comment]
Hi @Naxora, thanks for reporting this issue.

It is now fixed and merged to `develop` branch, so you can check it to verify.
