### ISSUE TITLE
Move KESTRA_CONFIGURATION from docker-compose.yml into file on the kestra-data ?

### ISSUE THREAD

**Issue by Naxora** [kestra-io/kestra#3534]
### Feature description

Just an idea.
'KESTRA_CONFIGURATION' It can be a setting file in the kestra data folder because every time when
I mondify the KESTRA_CONFIGURATION I need to stop and restart whole kestra container.
But this is my opinion.

**Comment by anna-geller** [comment]
can you share what issue are you trying to solve? 

even if we change the KESTRA_CONFIGURATION to be a YAML file instead of a YAML string in an environment variable, you would need to still restart the server for the changes to take effect (they are applied at start time)

**Comment by Naxora** [comment]
Ah okay, I understand now. Just Loïc mentioned this "we plan to use plugin configuration more often"
And the plugin configuration as I know is in the KESTRA_CONFIGURATION in docker-compose.yml so every time when I modify the plugin config kestra need to be restarted.

**Comment by anna-geller** [comment]
Unfortunately yes. We don't have any other way in the open-source version. In the EE version, there is a concept of centralized namespace-level configuration where you could add variables, task defaults and secrets directly from the UI any time without having to restart the server, but this is currently not available in the OSS version.

I'll close the issue then, feel free to ping me via Slack https://kestra.io/slack if you want to discuss this more, ok?

**Comment by anna-geller** [comment]
@loicmathieu mentioned it might be possible so reopening the issue

**Comment by loicmathieu** [comment]
This will soon be documented in our website, meanwhile you can check the PR: https://github.com/kestra-io/docs/pull/1415/files

> I mondify the KESTRA_CONFIGURATION I need to stop and restart whole kestra container.

One thing that worth noticing is that whereas it's using the environment variable or a configuration file, Kestra would need to be restarted for it to be taken into account.
