### ISSUE TITLE
Editor disappearing after copying and pasting code

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#3536]
### Describe the issue

1. I'm on the editor with the documentation open on the right.
2. copy and paste a flow, like [this one](https://kestra.io/plugins/plugin-aws/task-runners/runner/io.kestra.plugin.aws.runner.awsbatchtaskrunner#examples).
3. The editor disappears.
4. I can no longer move the bar to resize the editor.

https://youtu.be/Yxrsikaorwk

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by brian-mulier-p** [comment]
Urgent issue to be included in the next bugfix
