### ISSUE TITLE
Improve troubleshooting resolution by adding a "Dump Context" button or API endpoint to extract execution context

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#3537]
### Feature description

To improve troubleshooting resolution, it could be nice to add a button, API endpoint, or anything allowing users to dump the context of an execution. The goal is to streamline bug/questions troubleshooting and lighten the back and forth around logs, flows definition, backend, plugins, versions, etc.

**Comment by Ben8t** [comment]
Maybe broader scope that can be checked by the user before export:

```
flows
executions
logs
depending flows
depending executions
namespace configuration
instance configuration
instance versions
plugin versions
```

**Comment by loicmathieu** [comment]
> allowing users to dump the context of an execution

This is already the case via the API button on the execution page.
But there isn't a way to fetch execution data + logs + flow definition + config for ex.

Note that some information may be sensitive, if we provide a way to retrieve configuration we may restrict it to administrators.
