### ISSUE TITLE
Rename TaskDefault as PluginDefault

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3556]
### Issue description

As they can set defaults for more than just tasks but also trigger/condition/taskrunner.
Or flow default as they can set default as plugins only in a Flow (not storage or secret for ex).

**Comment by anna-geller** [comment]
do you mean renaming only internally or also a user-facing change of the core property? if user-facing change, let's discuss it via Slack as it seems like a big project

**Comment by loicmathieu** [comment]
Yes, also user facing.

**Comment by anna-geller** [comment]
I thought about it and think you're right, we should change it to `pluginDefaults`
