### ISSUE TITLE
DockerTaskRunner appears repeatedly in the editor autocompletion and docs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3564]
### Describe the issue

Docs:

![image](https://github.com/kestra-io/kestra/assets/86264395/5909885d-4d6b-4d94-9e6c-7dc7a25ce3bf)

UI:
![image](https://github.com/kestra-io/kestra/assets/86264395/d312e70b-f2b1-41c4-be2f-d052f8a398f1)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
Fixed by https://github.com/kestra-io/kestra/pull/3645
