### ISSUE TITLE
New onboarding flow

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3567]
See the last prototype (Onboarding with Editor interface): https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?m=dev 

All flows will be stored in the `tutorial` namespace when launching a new kestra instance. 

[The flows](https://kestra.io/blueprints?page=1&size=24&tags=50):

- Hello World → Log + Shell + Schedule (preselected by default)
    
- Data Engineering Pipelines → HTTP Download +  Python + DuckDB
    
- Microservices and APIs → HTTP Request +  Schedule + Slack
  
- Data Warehouse and Analytics → dbt + Git + Python
    
- Business Processes → HTTP Request +  Slack + Pause
    
- Infrastructure Automation → Terraform + Docker + Python
    
- Business Automation → Postgres + CSV + Excel
    
- File Processing → HTTP Download + ArchiveDecompress + Avro

**Comment by anna-geller** [comment]
Note: the design in Figma has 6 use cases, but we will have 8 use cases (as shown above) so there will be 4 on each side:

![image](https://github.com/kestra-io/kestra/assets/86264395/b3745f5d-d78b-468a-b2d2-502201b532e4)

**Comment by Skraye** [comment]
@anna-geller How do you plan to handle people that won't use the full kestra image, meaning they wont have all the plugins ?

**Comment by anna-geller** [comment]
good question, in that case I would only allow selecting the Hello World example (https://kestra.io/blueprints/224-getting-started-with-kestra-a-hello-world-example — atm this blueprint won't load on the web as it uses unreleased new OutputValues task)
