### ISSUE TITLE
Topology View doesn't let you delete a trigger

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#3571]
### Describe the issue

- Click the delete icon in the topology view
- Press confirm
- Nothing happens but should remove the trigger

https://github.com/kestra-io/kestra/assets/34094921/2405e8db-6cd9-4bc9-8e31-50c09e1ff3b9

### Environment

- Kestra Version: 0.16.0
- Operating System (OS/Docker/Kubernetes): macOS
- Java Version (if you don't run kestra in Docker):

**Comment by brian-mulier-p** [comment]
fixed by https://github.com/kestra-io/ui-libs/commit/b29b7229b565b46820997264920b419ba246c6b3 + https://github.com/kestra-io/kestra/commit/cb26406788fbd351cc96ea3426d01aa0fb30ae04 + https://github.com/kestra-io/kestra-ee/commit/b00da0a1371bedc73eaa86aa875f8523e023292b
