### ISSUE TITLE
Add pagination on log per task (gantt & logs tabs)

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#360]
Some task can have a lot of log, and will freeze the browser. 
We need to add some pagination and some filter (text at min)

**Comment by Ben8t** [comment]
On Gantt & Logs tabs :
* add pagination
* filter on text size ( > XXX characters)

**Comment by tchiotludo** [comment]
I mostly more think about the infinite scroll of github actions. 
We have log in realtime, so we will be not able to have proper pagination and I think infinite scroll is best on the UX side
