### ISSUE TITLE
Fix Executions display - logos are not visible in execution topology and logs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3617]
![image](https://github.com/kestra-io/kestra/assets/86264395/a7292d8d-849a-41db-b304-28be18769b82)

reproduce: pick any Getting Started blueprint

**Comment by Skraye** [comment]
Topology fixed in : https://github.com/kestra-io/kestra/commit/384b94df2629f53d1e39ed1a9f0b924853ddf5b0

**Comment by tchiotludo** [comment]
it's fixed also here: https://github.com/kestra-io/kestra/commit/dd885069a9c665c2d5bc1a00b73f8630c10eeb10
