### ISSUE TITLE
Start flow show error, but flow is finished successfully

### ISSUE THREAD

**Issue by zd-dalibor** [kestra-io/kestra#3628]
### Describe the issue

The flow finished successfully:
![image](https://github.com/kestra-io/kestra/assets/226822/0fb75855-ca26-4d9c-944f-cdfb59ae22db)

but every time when it is started I am getting this error
<img width="716" alt="image" src="https://github.com/kestra-io/kestra/assets/226822/85be30ba-b6f0-426b-8c85-336af1780388">
<img width="703" alt="image" src="https://github.com/kestra-io/kestra/assets/226822/9dca6074-13de-4cc2-8b98-e56dfb0c4e51">

### Environment

- Kestra Version: 0.16.4
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by zd-dalibor** [comment]
By the way, my kestra service is running behind traefik proxy.
It seems that kestra using server-side events.
Do we need some specific traefik configuration for kestra to work properly?

**Comment by tchiotludo** [comment]
Strange, we are also using Traefik (behind kubernetes) and we don't have a special configuration to make it work with SSE. 
You can try inside the container (with curl) on the same URL?

**Comment by zd-dalibor** [comment]
@tchiotludo 
I just updated the Traefik to latest version and now kestra is working fine, no more errors like this.
Thanks.

I am closing the issue.
