### ISSUE TITLE
Blueprints page in Kestra UI leads to 503 error code

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3653]
### Describe the issue

The Blueprint page is not opening in the Kestra UI. I tried it in the cloud, as well as on the docker setup.

cloud screenshot:
![Screenshot 2024-05-01 at 9 53 27 AM](https://github.com/kestra-io/kestra/assets/6594483/1de699ad-349a-4169-89fb-ab802ff332f9)

docker screenshot:
![Screenshot 2024-05-01 at 9 54 46 AM](https://github.com/kestra-io/kestra/assets/6594483/cbc52f66-3cb0-487b-91a9-d37aa6fec98f)

### Environment

- Kestra Version: 0.16.4
- Operating System (OS/Docker/Kubernetes): Cloud and Docker, both
- Java Version (if you don't run kestra in Docker):

I also tried older version 0.15.5 on Docker, still the same error.

**Comment by shrutimantri** [comment]
The Blueprint page on Kestra website: https://kestra.io/blueprints is also not working.

**Comment by wrussell1999** [comment]
Resolved. Issue was related to the API
