### ISSUE TITLE
Multiple pages on Kestra's website are breaking intermittently

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3654]
### Describe the issue

Multiple pages on Kestra's website are breaking intermittently including the home page: http://kestra.io

![Screenshot 2024-05-01 at 1 14 51 PM](https://github.com/kestra-io/kestra/assets/6594483/dbb201fe-2393-418a-8f22-59ae710cf021)

Other pages being Plugins page (https://kestra.io/plugins), any specific plugin page(https://kestra.io/plugins/plugin-aws), etc.

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by wrussell1999** [comment]
Seems to be API related. 503s when making requests to the API.

**Comment by wrussell1999** [comment]
Latest changes of the API weren't deployed. Resolved now.
