### ISSUE TITLE
AWS, GCP and Azure plugins are missing on the develop-full image

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3672]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/53b85409-4b51-4f3a-8144-103db33be210)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by fhussonnois** [comment]
The current develop image does contains some plugins in version 0.16.x which are not compatible with Kestra 0.17.0. This should be fixed when a new Docker image will be built from develop and latest SNAPSHOT versions of related plugins will be pickup.

![kestra-devfull-plugins](https://github.com/kestra-io/kestra/assets/1786576/a8e18234-4f0f-4e8f-b9d4-f66f46c68a53)
