### ISSUE TITLE
Warnings are displayed in plugins built on top of script plugins

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3673]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/0ca66ec6-a895-4683-9c5d-7155c5df42d8)

this warning is not needed

### Environment

- Kestra Version: 0.16.6 - last release

**Comment by loicmathieu** [comment]
This is OK in 0.16.6.
I think it whould have been a browser caching issue of the JSONSchema.

![image](https://github.com/kestra-io/kestra/assets/1819009/6d96cb03-9333-497d-9821-7fdb453483a1)
