### ISSUE TITLE
Subflow/lineage diagram if dbt/sqlmesh/dbt-like

### ISSUE THREAD

**Issue by 0xhanh** [kestra-io/kestra#3678]
### Feature description

Hi,

Are there any plugins that display Subflow or lineage diagram when we zoom-in/click on a task step like "dbt", "sqlmesh", or dbt-like?

Hopefully Kestra will support this UI feature

![image](https://github.com/kestra-io/kestra/assets/17973141/ab06425f-30e8-4bd5-977d-327477d1227f)

**Comment by anna-geller** [comment]
it's already possible! 🎉 just add a subflow and click on Expand button to see all tasks within the subflow https://kestra.io/docs/workflow-components/subflows
