### ISSUE TITLE
Follow up to the new Editor

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3685]
### Feature description

- [x] Bring back autocompletion https://share.descript.com/view/qzSqX2OpPcB 
- [x] Remove the VS Code Editor sidebar (and everything related to VS Code)
- [x] https://github.com/kestra-io/kestra/issues/3687 
- [x] https://github.com/kestra-io/kestra/issues/3686
- [x] https://github.com/kestra-io/kestra/issues/3691 
- [x] Auto-collapse the Namespace Files Editor sidebar -- it's cleaner and doesn't introduce extra complexity for users who don't use Namespace Files
![image](https://github.com/kestra-io/kestra/assets/86264395/c393b4eb-403f-4072-89dc-8beb7700ad42)
- [ ] Add a slider allowing to resize the sidebar https://share.descript.com/view/UYwAYEnQrCL  https://share.descript.com/view/oApRm9DKpcG 
- [ ] Regression on the main slider https://share.descript.com/view/srOiMLzdQRZ on the editor-follow-up branch
- [x] Reduce the width of the sidebar to provide enough space for the Editor and documentation
![image](https://github.com/kestra-io/kestra/assets/86264395/d0fee76c-0a25-4800-923a-20f617ec144f)
- [x] Remove the Getting Started markdown file. We can now implement a better UX to guide people through the editor 
![image](https://github.com/kestra-io/kestra/assets/86264395/185ce163-4938-4037-b32a-9b8f68960988)
- [ ] when using subflows, allow opening a subflow in a new editor https://github.com/kestra-io/kestra/issues/2473
- [ ] Add support for bulk-delete by holding a Shift-key -- when you select one file or folder, click on the Shift key and select other files, this should allow to bulk-select and bulk-delete multiple files or folders
![image](https://github.com/kestra-io/kestra/assets/86264395/f06335b6-303e-4384-84ab-e7ed1be9c0f0)
- [ ] Remove mandatory file extension "Missing file extension", people could add file without

**Comment by brian-mulier-p** [comment]
- [x] (maybe) add a placeholder value when there is no files created yet to show users it's not buggy

It wasn't needed before but since I removed the getting_started.md it looks weird to have an empty browser without saying anything idk WDYT @anna-geller ?
![image](https://github.com/kestra-io/kestra/assets/37618489/605c8c79-e315-4247-82a0-066a8d501bf8)

**Comment by anna-geller** [comment]
I would auto-collapse by default and make the expand icon more prominent (perhaps add a little color to it e.g. purple?)

**Comment by MilosPaunovic** [comment]
For now, added the placeholder value for the situation when there are no namespace files and also, the sidebar is collapsed by default, but the button is made more prominent.

And @brian-mulier-p removed the `getting-started.md` file in https://github.com/kestra-io/kestra/commit/9189cd678272d69eaa024feda70e1ecc804d015b yesterday.
