### ISSUE TITLE
Revision history throws a TypeError: this.editor.onDidFocusEditorText is not a function

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3691]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/7e4e4f00-f110-4279-82cd-76b14196ed6c)

### Environment

develop

**Comment by MilosPaunovic** [comment]
Closing as it was fixed with https://github.com/kestra-io/kestra/pull/3689
