### ISSUE TITLE
Alias and documentation

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3712]
### Issue description

- [x]  Check the behavior of documentation in the editor: which one is displayed?
- [x]  Add a redirect in the website

**Comment by loicmathieu** [comment]
The editor now correctly displays the aliase documentation with a deprecated alert on it.

**Comment by brian-mulier-p** [comment]
solved by https://github.com/kestra-io/api.kestra.io/commit/480f19e855d41f0174363ba7afdc4e97c616df92
