### ISSUE TITLE
Auto scroll Plugins list to the currently open page

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#3730]
### Feature description

When you go to the Plugins page on the left, and click on a plugin it will put you on the first sub page for that plugin but doesn't show you the others. The user needs to scroll down the list to find the other ones related to that plugin. It would be a nice quality of life thing to have the list scroll down to the active page.

https://github.com/kestra-io/kestra/assets/34094921/68c706e8-ee34-4aa5-81f7-b183f4ebf041

This also happens when you refresh the page, it doesn't remember where you were scrolled to. This means you have to scroll down the list to find the related pages to the plugin.

https://github.com/kestra-io/kestra/assets/34094921/55380d55-cca1-4ade-b847-9a4cb3bb27d7

**Comment by MRADUL9936** [comment]
@anna-geller  I would like to work on this issue .

**Comment by MilosPaunovic** [comment]
@MRADUL9936 Go for it! :rocket:

**Comment by MilosPaunovic** [comment]
Great job, @MRADUL9936, thanks for your contribution! 🚀 

Feel free to take another pick at the [curated list ](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=label%3A%22good+first+issue%22)of good first issues, if you're interested in contributing some more.
