### ISSUE TITLE
Editor resizing do a lot of API call

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#3737]
### Issue description

See video, when moving the file explorer, its like everything is reloaded :
![editor-size](https://github.com/kestra-io/kestra/assets/37600690/6d53a995-00e6-42a4-babe-53a4d1a5116a)

**Comment by brian-mulier-p** [comment]
@MilosPaunovic can you have a look ?

**Comment by MilosPaunovic** [comment]
Amended with https://github.com/kestra-io/kestra/pull/3746
