### ISSUE TITLE
Link to "Migrations section" on Templates page is broken

### ISSUE THREAD

**Issue by npranav10** [kestra-io/kestra#3738]
### Issue description

The link to templates' migrations section document is incorrect on the following lines:

https://github.com/kestra-io/kestra/blob/b2ea51da09feac4818e7f3d766fba824cc01473e/ui/src/translations/en.json#L281

https://github.com/kestra-io/kestra/blob/b2ea51da09feac4818e7f3d766fba824cc01473e/ui/src/translations/fr.json#L270

Incorrect Link: [https://kestra.io/docs/migrations/templates](https://kestra.io/docs/migrations/templates)
Correct Link: [https://kestra.io/docs/migration-guide/templates](https://kestra.io/docs/migration-guide/templates)

I will raise a pull request shortly with a fix.

**Comment by MilosPaunovic** [comment]
Thanks @npranav10!
