### ISSUE TITLE
Feature Request: Importing of Pebble Macros within Workflow YAMLs

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#3760]
### Feature description

I reuse Pebble expressions all over my Workflow YAMLs, and could benefit from making them macros in a single file, and importing them to Workflow YAMLs.

If this is possible, this is a nice-to-have, it is not blocking anything.

Related Docs:

[Kestra Macro](https://kestra.io/docs/concepts/expression/expression-usage#macros)

[Pebble Import statement that might be relevant](https://pebbletemplates.io/wiki/tag/import/)

Thank you 🙏

**Comment by anna-geller** [comment]
Asked the team to validate whether storing macros on a namespace level would be feasible:

```yaml
resource "kestra_namespace" "example" {
  namespace_id  = "io.kestra.mynamespace"
  description   = "Friendly description"
  variables     = <<EOT
k1: 1
k2:
    v1: 1
EOT
  task_defaults = <<EOT
- type: io.kestra.core.tasks.log.Log
  values:
    message: first {{flow.id}}
- type: io.kestra.core.tasks.debugs.Return
  values:
    format: first {{flow.id}}
EOT
  macros = <<EOT
{% macro input(type, name) %}
    <input type="{{ type }}" name="{{ name }}" />
{% endmacro %}
{% macro my_macro(column, table) %}
    SELECT {{ column }}
    FROM {{ table }}
{% endmacro %}
EOT
}
```

in OSS, this would need to be defined in the configuration the same way as for `taskDefaults`

**Comment by japerry911** [comment]
Hey @anna-geller, just reviewing my issues and catching up, this is good to close, I haven't really had a use case for a global macro yet in Pebble in Kestra.
