### ISSUE TITLE
Empty Inputs not NULL after typing in them/removing characters

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#3768]
### Describe the issue

I have a STRING type input, Property IDs.
It defaults to NULL since I have required: false , but if I accidentally type  in it, and delete what I type, it ends up going through as an empty string "".
I was curious, is there a way to make it NULL instead of empty string when you revert what's inputted? My use case is I use Pebble expression to remove --property_ids <property_ids_input from a Python script call if Property IDs is NULL. I could always remove if NULL or empty string, but I wanted to check before doing that.
 let me know if you need more details in responding to this, appreciate the help, thank you

Images:
1st image shows input as it appears after I delete text that accidentally inputted
2nd image shows input in execution overview tab showing Blank string and not NULL

![Screenshot 2024-05-17 at 1 22 12 PM](https://github.com/kestra-io/kestra/assets/21957238/4b87bdfa-275b-4e1b-be0d-6f8f0cc34296)

![Screenshot 2024-05-17 at 1 25 04 PM](https://github.com/kestra-io/kestra/assets/21957238/f1f5a25d-8fb4-475c-84e8-064f4cb1dbd6)

### Environment

- Kestra Version: v0.16.6
- Operating System (OS/Docker/Kubernetes): GCP VM Docker Compose
- Java Version (if you don't run kestra in Docker): n/a

**Comment by anna-geller** [comment]
You can close the window and reopening again will no longer have that empty string;) 

Alternatively, what if you explicitly type `null` without any quotes? AFK so hard to check atm

**Comment by japerry911** [comment]
I'll test typing 'null' when I get back.

I was thinking there could be a little null button or something like the checkboxes have above input box or something. I'll elaborate when I get on later.

Thanks @anna-geller !

**Comment by japerry911** [comment]
>Alternatively, what if you explicitly type null without any quotes?

This does not work, does "null" as string. 

I was envisioning something like this, where you could press None, or String and if String it gives input box.

<img width="273" alt="Screenshot 2024-05-18 at 1 37 38 PM" src="https://github.com/kestra-io/kestra/assets/21957238/3c619481-c201-469f-a808-6ff60d736aa7">


*This is not blocking anything for me, so nothing urgently needs to be done on it, just noticed it when I was 'deving' and rerunning runs frequently.

**Comment by loicmathieu** [comment]
@anna-geller it's not a bug and providing a specific UI for such thing may be a bit overkilled. Let's move this to 0.18 to have more time to think about it.

**Comment by anna-geller** [comment]
we discussed together that an input should never be an empty string so we'll replace the empty string input values with `null` on the UI-side — @MilosPaunovic ping me if you want more details/examples
