### ISSUE TITLE
Off-Centered Elements in the Demo Instance

### ISSUE THREAD

**Issue by quentin-py** [kestra-io/kestra#3812]
### Describe the issue

Welcome Page from https://us.kestra.cloud/ui/demo/welcome

<img width="1440" alt="Capture d’écran 2024-05-24 à 09 15 05" src="https://github.com/kestra-io/kestra/assets/46087775/5dfa97a8-91e4-408a-958d-788eb4a80a75">

### Environment

- Kestra Version: 0.16.6
- Browser: Arc, latest version

**Comment by anna-geller** [comment]
state on develop https://share.descript.com/view/OKbivLZRUwA

**Comment by anna-geller** [comment]
We can add a container in the same way we do it with video-container in the docs to fix it, Figma: https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=0%3A1&t=lYku1yT8bmVsS0j0-1
