### ISSUE TITLE
Provide a way to access flow and namespace states

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3814]
### Feature description

Flows can use a state store by flow or namespace.

This is very convenient to store state between two flow executions but there is no way to access this state other by a task.
As some task use a state transparently, there is certain circumstances where accessing the state would be great for debugging purpose, or resetting it.

We can for example add a new tab to the flow page (and the same to the namespace page) that would list all states of the flow and allow to download it and removing it (no need to allow to create a state for now).

**Comment by anna-geller** [comment]
You're totally right that we need to do it after we add KV Store: https://github.com/kestra-io/kestra/issues/3852
