### ISSUE TITLE
Revert the color of dark plugin icons in the UI

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3817]
### Describe the issue

The new onboarding UX looks bad when using light mode because the color of dark icons is not reverted. 

![image](https://github.com/kestra-io/kestra/assets/86264395/274591d7-b1df-4dbf-b719-cef83bd9a24e)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Amended with aea578adfaa13510ecb7f22ddfc273beb1bca2c3, can be checked and, if alright, closed

**Comment by anna-geller** [comment]
yup fixed on develop

![image](https://github.com/kestra-io/kestra/assets/86264395/5cb004cd-0ea2-45ed-84b3-29cca26d4e0b)
