### ISSUE TITLE
[Scheduling] Extend the Execute modal with "Schedule for later" option + extend the Subflow task with a `scheduledDate` argument + extend Schedule trigger with `dates` array property

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3818]
### Feature description

- [ ] In the Advanced configuration in the `Execute` modal, add an option to schedule an execution for later — provide a date picker in the UI to allow scheduling an execution for a specific date.
- [ ] Add `scheduledDate` argument to the Subflow task to create an execution of a Subflow for later. If the user adds a `scheduledDate` and has `wait` property set to `true`, log a warning in the console to warn that this will block the parent execution until the scheduled child execution finishes 
- [ ] Provide an example in the `Subflow` task that combines Subflow with `EachParallel` task to create multiple scheduled executions in the future (potentially with custom inputs) -- the parallel task can iterate over multiple dates or over multiple input values to create executions for the future 
- [ ] Extend the `Schedule` trigger with the `dates` array property, allowing users to provide a list of ISO-formatted dates (akin to `DATETIME` inputs)

```yaml
id: schedule
namespace: dev

tasks:
  - id: API
    type: io.kestra.plugin.core.http.Request
    uri: https://jsonplaceholder.typicode.com/posts/1
    method: GET

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    dates: 
      - "2024-06-04T14:00:00.000000+02:00"
      - "2024-08-06T14:00:00.000000+02:00"
      - "2024-10-01T14:00:00.000000+02:00"
```

**Comment by japerry911** [comment]
@anna-geller  I don't know if this is exactly related to this issue, but seems close. With this potential update, would it be possible to schedule execution for later with API or through a Kestra task?

**Comment by anna-geller** [comment]
@japerry911 via an API call seems feasible. Why via a task though? Schedule is a trigger... unless you mean the Subflow task - in that case, yes 👍

**Comment by japerry911** [comment]
@anna-geller , API call would be great. My use case is that we have something run at 12:00 PM, and if it fails to find necessary requirements, it reschedules for 60 minutes later.. up to 3 times/3 hours. So API call would solve this, as this previously (with other provider) happened with API call in Python code.

In terms of task, I see what you are saying, that would not make sense haha 😄

**Comment by johnsturgeon** [comment]
This would be a game changer for me.  I have jobs that need to be run whose schedule time / date can only be derived as a delta from a specific event.

This would allow me to calculate the runs for the week, and schedule the jobs that need to run!
