### ISSUE TITLE
New main dashboard — more welcoming, informative and faster

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3822]
Planned changes to the main dashboard:
- [x] Keep the top chart but label the axis + add a description of the legend on the top
- [x] Change the pie charts into a number/KPI with an upward/downward trend at the top
- [x] Change the colors and add labels
- [x] Clearly include information about currently running and scheduled executions -- closes https://github.com/kestra-io/kestra/issues/3011 
- [x] Remove the error logs per namespace and the large table
![image](https://github.com/kestra-io/kestra/assets/86264395/03f4a4be-3233-43e9-be2d-734f8e2158f1)

## Context
The main dashboard currently suffers from the following issues:
1. When new users get started, they tend to make mistakes, and seeing a red dashboard isn't encouraging. -> Change the colors to be on-brand and color-blind-friendly

![image](https://github.com/kestra-io/kestra/assets/86264395/6703d466-631e-4b5f-b990-6dc5d328a1f6)

2. The charts in the middle take too much space for the limited amount of information they provide -> change to numbers with a trend:

![image](https://github.com/kestra-io/kestra/assets/86264395/126554e5-f387-42af-895e-3abd6de90cc4)

3. Tables with error logs and recently failed executions are slow to load -> remove them:
![image](https://github.com/kestra-io/kestra/assets/86264395/0698d441-9bc8-454d-8070-e7008741115c)

4. There are two tree maps that display the same information -> remove them:
5. The colors are not color-blind friendly and "boring" :) We can enliven it with kestra-specific colors
6. Axis are missing labels and the legend is missing to explain what is meant by each color

**We want to redesign this main dashboard.**

Preferred visualization types:
- numbers with upward/downward trend
- line chart
- area chart
- (grouped) bar chart
- scatterplot
- if REALLY needed, a pie chart (best to avoid)

**Comment by anna-geller** [comment]
link to Figma 

https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=2194-27607&t=fEACqUmbBHoOqNPb-0

![Frame 15766](https://github.com/kestra-io/kestra/assets/86264395/88761324-83a1-45ce-b8f1-0d5462eb377c)

**Comment by anna-geller** [comment]
extra note from Nico to adjust the Flow Overview page as well 

![image](https://github.com/kestra-io/kestra/assets/86264395/4867ae41-0979-4a6d-bffa-bb870501fc42)

**Comment by tchiotludo** [comment]
an idea of relevant stat:
- a pie charts grouped by namespace, with duration as value (to see namespace longer than the others one)

**Comment by anna-geller** [comment]
when you hover over the state name, you'll see that the State name is clickable (a link) that will link to an Executions list filtered for that state

![image](https://github.com/user-attachments/assets/311db246-55d4-4d69-bb56-af4f9c19d466)

**Comment by anna-geller** [comment]
Extra info @MilosPaunovic as discussed today:
- backend might be missing some endpoints to display the required data, especially the bar chart -- displaying the execution stats per day, per week, per month, per hour (depending on the selected period) will require some changes on the backend side
- the Main Dashboard + Flow Overview Dashboard are the highest priority. Additionally, we should change also the Namespace Overview page, which will display the same charts as on the main dashboard but filtered only for that namespace
![image](https://github.com/user-attachments/assets/a8744f96-21c1-4acc-b354-16c64389f379)
- for the Success and Failure Ratio, we can compute it as the ratio of the number of Executions in the Success/Failed state divided by the total number of Executions (so: Success/Total + Failed/Total without including Warning)
![image](https://github.com/user-attachments/assets/7ce755f5-ffb5-4db5-b196-7225b33712bd)

**Comment by anna-geller** [comment]
we'll display the trendline only on Elastic backend

![Image](https://github.com/user-attachments/assets/04475add-30cd-4099-8f2d-26e83579cf1e)

**Comment by anna-geller** [comment]
only the endpoint to display trend in Elastic is missing

**Comment by MilosPaunovic** [comment]
Hey @fhussonnois, could you please list the all new endpoints which I can use on the UI for the new dashboard page?

**Comment by fhussonnois** [comment]
Hey @MilosPaunovic, here are the new endpoint API:

- POST `/api/v1/stats/summary` : Get total number of flows and triggers , e.g., `{"flows": 10, "triggers": 5}`
- POST `/api/v1/stats/executions/daily/group-by-namespace` : Get daily statistics for executions grouped by namespace, e.g. : 
```
{
  "io.kestra.dev" : {
      "RUNNING": 100
       "SUCCESS: 150,
       "FAILED: 0,
....
   }
}
```

**Comment by MilosPaunovic** [comment]
This is now merged to `develop` branches of both `OSS` and `EE`, and is deployed to their respective preview pages.

I've implemented improved look for the main dashboard page and for flow & namespace overview pages, so all three need to be checked.

What I know already that needs improving is the following:
- Empty states of charts and tables (there already is a design for it, [here](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=2194-28454&node-type=frame&t=XILzkbsqrZe4YFh7-0))
- On `EE`, there is an issue with `/v1/triggers/search` endpoint when I pass these parameters:
```js
sort: next_execution_date:asc
size: 5
page: 1
```

I get an error `"Internal server error: Request failed: [search_phase_execution_exception] all shards failed"` and the same exact endpoint works as expected on `OSS`.

**Comment by anna-geller** [comment]
@MilosPaunovic, the new color palette is not added yet https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=2194-26375&t=lBzrGL2eqd8X10wV-4 
![image](https://github.com/user-attachments/assets/e8901e58-19dd-4d43-aeed-c3ba626e7368)

Ideally, we wanted that new colorblind-friendly color palette to become the default, with the possibility of switching to a classic view for those who like the classic green-red style via Settings

**Comment by MilosPaunovic** [comment]
Hey @Nico-Kestra, could you please export the list of `HEX` colors for both regular and colorblind scheme - there are the necessary values we need to cover (bare in mind some of the colors might overlap)

These are options for Logs:
 ```
TRACE
DEBUG
INFO
WARN
ERROR
```

And these are options for Executions:

```
CREATED
RUNNING
PAUSED
RESTARTED
KILLING
SUCCESS
WARNING
FAILED
KILLED
CANCELLED
QUEUED
RETRYING
RETRIED
```

**Comment by Nico-Kestra** [comment]
Hey @MilosPaunovic 
I think you have all the information [here](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=1011-9373&t=HdaMFo6OZpbn3QQH-1), but feel free to ask if you need more details.

**Comment by MilosPaunovic** [comment]
@Nico-Kestra How is the progress on the coloring scheme, is it going to be ready for me to start working on it in the morning?

**Comment by anna-geller** [comment]
@MilosPaunovic Nico shared this with me, can you find it in figma?

![image](https://github.com/user-attachments/assets/84e2b268-8861-472a-a810-0d075d9accc8)

**Comment by Nico-Kestra** [comment]
<img width="985" alt="Capture d’écran 2024-09-23 à 19 30 48" src="https://github.com/user-attachments/assets/36548803-7697-4ac8-9756-c7fbd83158f2">
I'm a bit behind schedule, but it's coming along. This is the classic mode in dark and light mode. I'm fine-tuning a couple of things on it, and I'll start working on the other mode tomorrow.

**Comment by MilosPaunovic** [comment]
@Nico-Kestra Would it be possible, when you're done, to export the HEX color values for me, for the three modes? It would help me immensely.

**Comment by Nico-Kestra** [comment]
Yep, I could export a JSON for you.

**Comment by Nico-Kestra** [comment]
<img width="1702" alt="Capture d’écran 2024-09-24 à 10 16 02" src="https://github.com/user-attachments/assets/02ed7b57-838b-4323-96a2-aef40d20a595">

<img width="1726" alt="Capture d’écran 2024-09-24 à 10 15 57" src="https://github.com/user-attachments/assets/3425d71d-209f-4404-b0b4-436c726f12c3">

Can you update legend color ?
My grays are much lighter and more readable:

<img width="1410" alt="Capture d’écran 2024-09-24 à 10 17 38" src="https://github.com/user-attachments/assets/5fa20b83-8fa3-483d-adec-66f797faf372">

<img width="1399" alt="Capture d’écran 2024-09-24 à 10 17 44" src="https://github.com/user-attachments/assets/c99d9ff7-ab8c-478b-a0d4-3bd0ab3c063d">

**Comment by Nico-Kestra** [comment]
Also, the chart bars are thinner, with a small separation between each color.
<img width="352" alt="Capture d’écran 2024-09-24 à 10 19 48" src="https://github.com/user-attachments/assets/cef1b9eb-6ee3-4eca-94e9-36d449be9191">

**Comment by anna-geller** [comment]
> My grays are much lighter and more readable:

@Nico-Kestra I suggested in a separate issue to even make that entirely white to improve the contrast, the background is already grey, so grey on grey (even if lighter) will not have as big contrast as white, WDYT? https://github.com/kestra-io/kestra-ee/issues/1778

**Comment by Nico-Kestra** [comment]
<img width="1360" alt="Capture d’écran 2024-09-24 à 10 39 00" src="https://github.com/user-attachments/assets/9ccf1dfd-87ea-494c-91bc-f2c7c1545e58">
There are some typographies in white and others in gray because not everything has the same importance. However, it's a light gray close to white.

**Comment by Nico-Kestra** [comment]
Thank you, you changed the color for the 🔎 icon, but the icon to the left of the title was supposed to remain purple :-)
<img width="791" alt="Capture d’écran 2024-09-24 à 15 50 21" src="https://github.com/user-attachments/assets/f5974781-df14-4102-afb5-c7ef316770fc">


I also see that we have rounded corners on the charts in the EE version, we need to remove them. Thanks.
<img width="155" alt="Capture d’écran 2024-09-24 à 15 48 57" src="https://github.com/user-attachments/assets/1e651b06-ea34-4f89-8959-66345a42e58c">

**Comment by MilosPaunovic** [comment]
I am having trouble keeping track of all the issues and Slack treads where we have things for me to do regarding dashboard. Can we open single one and add all the remaining issues as tasks, so they can be checked once completed? It would be immense help if you could take on compiling that list @anna-geller.

**Comment by Nico-Kestra** [comment]
Sorry @MilosPaunovic it's a mistake. i add it [here](https://github.com/kestra-io/kestra-ee/issues/1778)

**Comment by MilosPaunovic** [comment]
No worries, it's just that I've completed a lot from that other, as well. But we'll manage.
