### ISSUE TITLE
Remove Beta flag annotation from Realtime Triggers and adjust the documentation

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3843]
### Feature description

As discussed yesterday @loicmathieu - the reason is that we don't anticipate any user-facing changes to the syntax (only internal implementation can be optimized for performance + observability features)

We should cross-check the docs, e.g. Postgres uses wording message and has duplicated id/type:
![image](https://github.com/kestra-io/kestra/assets/86264395/0dfdb52d-783b-4210-8d99-02d6f4997dbc)

**Comment by loicmathieu** [comment]
Done for all real time trigger
