### ISSUE TITLE
Editor 'Export Namespace Files' should export only namespace files

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3855]
### Describe the issue

Editor 'Export Namespace Files' should export only namespace files.

Today it export both files and flows as it is what the old editor was doing as it mixed the two, now that the new editor only edit namespace files we should update the endpoint to only return namespace files.

### Environment

- Kestra Version: 0.17.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
it's really really useful to get the flows in one go

I understand that technically you might expect only flows but it's really useful to include flows and soon we will revisit how to integrate other flows within the Editor
