### ISSUE TITLE
Expression autocomplete enhancement

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3856]
## Missing variables

The following variables are missing:
- flow.tenantId*
- task.id
- task.type
- taskrun.id
- taskrun.startDate
- taskrun.attemptsCount
- taskrun.parentId*
- taskrun.value*
- taskrun.iteration*

'*' Not always present, we may want to restrict them

The following also exist but I think they are too complex to add: envs, globals, parents

## Autocomplete improvements

- outputs autocompletion in an Each task is missing the `taskrun.value`
- outputs autocompletion includes the current task, which is misleading as it's not yet available
-  outputs autocompletion includes the next tasks, which is misleading as they are not yet available
- outputs autocompletion proposes tasks that didn't have any outputs

**Comment by anna-geller** [comment]
let's start with:

- task.id
- task.type
- taskrun.id
- taskrun.startDate
- taskrun.attemptsCount

**Comment by anna-geller** [comment]
prioritized here https://github.com/kestra-io/kestra/issues/3622
