### ISSUE TITLE
Make the blueprints view more compact

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3870]
### Feature description

We want to use the space more efficiently here.

1. We can move the search bar down to the same line as pagination under the tags
2. Move tags higher + change the font size to something smaller 

![image](https://github.com/kestra-io/kestra/assets/86264395/ca7e32f7-4e07-452a-80ee-41fe0eda93e3)

**Comment by MilosPaunovic** [comment]
Is this too compact now @anna-geller? The search bar is the same height as the pagination buttons on the right.

![image](https://github.com/kestra-io/kestra/assets/62475782/9951e704-ab4f-45df-b887-71fd23a3c784)

**Comment by anna-geller** [comment]
it's perfect 👍
