### ISSUE TITLE
No password length constraint

### ISSUE THREAD

**Issue by munteanstefan** [kestra-io/kestra#3871]
### Describe the issue

No password length constraint may lead blocking of the login functionality, and it cached a response: 
{"message":"Request Entity Too Large","_links":{"self":{"href":"/ui/admin/stats"}},"_embedded":{"errors":[{"message":"Request Entity Too Large"}]}}

Preconditions: 
kestra started up and at least one flow is saved in dashboard

Steps to reproduce

1 Activate basic authorization
2 insert a huge string in the email/password/confirm password field example : input a string of 2997 characters 
3 Save the credentials and try to login with the correct email and password

Note that the response is cached, so opening a new tab will result in the same response, check screenshot
<img width="962" alt="image" src="https://github.com/kestra-io/kestra/assets/32432117/4a3dd98a-0a30-4132-a107-2eb81c6d3d81">

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by frankzengjj** [comment]
hi I would like to take this issue. The PR is [here](https://github.com/kestra-io/kestra/pull/4261).

**Comment by MilosPaunovic** [comment]
Closed by https://github.com/kestra-io/kestra/pull/4261. Thanks @frankzengjj for the contribution! 🚀
