### ISSUE TITLE
Reviews Onboarding

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#3874]
### First page: intro
- [ ] Add animation to the gradient on the first page.
- [x] Title "Welcome to Kestra!" > font weight 500
- [x] I won't put a 'Next' button on this screen. Let's go is enough.

### Second page: choose a use-case

- [x] Add a button appearance animation like on the prototype.
- [x] Add a rollover effect to the buttons, background and border (prototype)
- [x] 2 icons docker, is it normal?
<img width="392" alt="Capture d’écran 2024-05-30 à 10 24 25" src="https://github.com/kestra-io/kestra/assets/125994028/9c1f9f3f-d345-4b43-b630-75c749bf63fb">

### Fifth page: Execute

- [x] Add a bottom-to-top repeating animation on the arrow, see prototype.
- [x] Add a glowing animation intensifying behind the "execute" button.
- [x] Hide the Kestra menu as on the previous pages.

### Sixth page: pop-up

- [x] I think it's a shame to have this extra screen in an onboarding process.
<img width="1131" alt="Capture d’écran 2024-05-30 à 10 33 28" src="https://github.com/kestra-io/kestra/assets/125994028/2c35d46f-bb87-417b-85f9-8eda9639d40d">

- [x] I closed the pop-up, and now I'm stuck trying to execute the flow.
<img width="1379" alt="Capture d’écran 2024-05-30 à 10 34 54" src="https://github.com/kestra-io/kestra/assets/125994028/e74e49eb-8a31-4b89-bce7-cedee2bff1ff">

### Seventh page: log

- [x] Move the 'You’re all set!' box downwards and to the right so that we can see the execution clearly.
- [x] Delete the 'skip the tutorial' button on this last page.
- [x] The "Explore other Flows" button should navigate back to the second page with the use case choices.

### General

- [x] Add roll over effect on all buttons (previous, skip, let's go, next...)
- [x] Delete the 'Next' button
- [x] Light mode, I thought the color change would be automatic; for example:
<img width="1878" alt="Capture d’écran 2024-05-30 à 10 42 07" src="https://github.com/kestra-io/kestra/assets/125994028/604c01e9-6d31-4be9-a9ae-7dcb07a9f36f">

<img width="1804" alt="Capture d’écran 2024-05-30 à 10 40 32" src="https://github.com/kestra-io/kestra/assets/125994028/397120be-c185-4dd8-8bd8-c35cdf1e79a0">

**Comment by MilosPaunovic** [comment]
For the two Docker icons it is a question for @anna-geller, because that flow has two tasks (`io.kestra.plugin.docker.Build` and `io.kestra.plugin.docker.Run` - for which the icons are the same. Do we want to keep them both?

**Comment by MilosPaunovic** [comment]
On the issues on `Sixth page` I had a discussion with @anna-geller about it and the decision was that we keep that extra step, as it shows the real flow of the execution. I suggest that we just disable the closing icon on the dialog there. @Nico-Kestra do you think that is a viable solution?

**Comment by Nico-Kestra** [comment]
> On the issues on `Sixth page` I had a discussion with @anna-geller about it and the decision was that we keep that extra step, as it shows the real flow of the execution. I suggest that we just disable the closing icon on the dialog there. @Nico-Kestra do you think that is a viable solution?

ok to disable the closing icon.

**Comment by anna-geller** [comment]
For the next and previous step, Nico we did that for consistency 

If it's not difficult, let's keep only one Docker icon. If it's difficult, no harm to have it twice

**Comment by anna-geller** [comment]
@Nico-Kestra that extra screen is important to teach users how to trigger flows with inputs. If this helps, you're right @MilosPaunovic that closing it can be disabled here to guarantee the full flow (if difficult/time consuming, you can skip this task, not a big issue)

**Comment by Nico-Kestra** [comment]
> For the next and previous step, Nico we did that for consistency
> 
> If it's not difficult, let's keep only one Docker icon. If it's difficult, no harm to have it twice

I find that having secondary "next" buttons serves no purpose when we already have the primary purple button to proceed to the next step.

**Comment by Nico-Kestra** [comment]
To avoid any misunderstanding, I am indeed referring to this button.
<img width="837" alt="Capture d’écran 2024-05-30 à 11 31 34" src="https://github.com/kestra-io/kestra/assets/125994028/1088b019-1f9d-481b-bb91-2390db63e57c">

**Comment by anna-geller** [comment]
Understandable. It's a bit unnatural to have `previous` step without `next`, I'd prefer keeping it as we implemented it, but if you feel strongly about it Nico, we can remove that `next` button 

Regarding:
> The "Explore other Flows" button should navigate back to the second page with the use case choices.

Please no, it makes no sense for the user to go through the entire tutorial again, all flows are already stored in the "tutorial" namespace so it's enough to point the user to the Flows page filtered by that namespace. Additional benefit to it is showing this important UI page instead of showing the same entire guide for the second time:)

**Comment by Nico-Kestra** [comment]
Originally, my need was this one: :-) at the bottom right.
<img width="344" alt="Capture d’écran 2024-05-30 à 14 27 58" src="https://github.com/kestra-io/kestra/assets/125994028/f28f52e7-2b95-4ef8-bab6-45da5d3669fc">

**Comment by MilosPaunovic** [comment]
We've changed that as it was too easy for users to abort the tour.

**Comment by anna-geller** [comment]
the skip tutorial on one side and the previous/next on the other feels quite natural, I think we're good to ship 🚀 

@Nico-Kestra I'll schedule 15 min next week to discuss if you'd like to suggest anything else (we can ship such a change in a bugfix release 1-2 weeks later, no rush)

**Comment by anna-geller** [comment]
@MilosPaunovic it seems there are no urgent changes left so I changed the milestone here to 0.18, we can discuss more on Wed what still left

**Comment by MilosPaunovic** [comment]
I'll just push what I have in next 10-15 mins, and then we can call it a wrap for `0.17.0`.

**Comment by MilosPaunovic** [comment]
Okay, just to sum it up, what is left to be done from all the tasks and comment of this issue is the following:

- [ ] **First page:** Add animation to the gradient on the first page
- [x] **Second page:** Add a button appearance animation like on the prototype.
- [x] Exclude the Docker task runner logo in the icons list https://github.com/kestra-io/kestra/issues/3925 
- [ ] Color for the flow code border on the light theme

@Nico-Kestra Could you do another pass of the onboarding (both light and dark modes) on the link I'll send you, and add anything else you find in the comment below, so the three of us can discuss together on Wednesday?

**Comment by anna-geller** [comment]
I'd consider the issue as done (the gradient thing is nothing major) 👍
