### ISSUE TITLE
Default image for Powershell should have WSMan installed by default

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#3877]
### Feature description

As a user, I'd like Kestra to orchestrate many remote calls out to my windows machines to execute scripts and other commands. 

The default powershell image today cannot do this as it is missing libraries. These cannot be installed with the beforeCommands as they require a restart of the powershell session. 

A minimal docker image with this support would look like the following

```
FROM mcr.microsoft.com/powershell:7.2.0-ubuntu-20.04

RUN apt-get update && \
    apt-get install -y openssh-client

pwsh -Command "Install-Module -Name PSWSMan -Force"
pwsh -Command "Install-WSMan"

CMD ["pwsh"]
```

**Comment by anna-geller** [comment]
done https://github.com/kestra-io/examples/blob/main/dockerfiles/powershell.Dockerfile
https://github.com/kestra-io/examples/pkgs/container/powershell

feel free to submit a PR if you'd like to change something (e.g. not sure if the base image is something we want to pin to a specific version, we tend to use `latest`, is there a way we can avoid pinning this to 7.2.0 and ubuntu 20.04 only?)
