### ISSUE TITLE
Review Welcome page

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#3884]
### Welcome box
<img width="1092" alt="Capture d’écran 2024-05-30 à 15 40 35" src="https://github.com/kestra-io/kestra/assets/125994028/92483fc2-db68-47a8-a588-6f70b0f8fe82">

- [x] Change color svg on light mode (the one online is not visible)
- [ ] Align the text 'Welcome to Kestra' to the left and align it with the button on the left.
- [ ] Shadows are missing on the boxe

### Help box
<img width="1128" alt="Capture d’écran 2024-05-30 à 15 32 30" src="https://github.com/kestra-io/kestra/assets/125994028/30da4d8a-8d82-4981-a75a-46a9c39ac72d">
<img width="1103" alt="Capture d’écran 2024-05-30 à 15 31 23" src="https://github.com/kestra-io/kestra/assets/125994028/0e1c6ee6-c2b7-44eb-95e7-4552d1699972">

- [ ] I have the overlapping of borders and different radii. It looks odd. The expected effect 👇
<img width="869" alt="Capture d’écran 2024-05-30 à 15 46 50" src="https://github.com/kestra-io/kestra/assets/125994028/68b9032f-b0fa-4cee-93f4-52b392c819d3">

- [ ] Shadows are missing on the boxe

**Comment by anna-geller** [comment]
superseded by https://github.com/kestra-io/kestra/issues/6056
