### ISSUE TITLE
Enable/Disable Realtime Triger from the UI should not be possible

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3886]
### Describe the issue

Currently, you can only disable a real time trigger from the YAML so the toggle to disable/enable it from the UI (both in the flow Triggers tab and the administration Triggers page) should be disabled.

### Environment

- Kestra Version: 0.17.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Is it related to this one https://github.com/kestra-io/kestra/issues/3236?

**Comment by loicmathieu** [comment]
No, it's very specific to the new real-time triggers that cannot be disabled via the API as classical triggers could be.

**Comment by Skraye** [comment]
As we can not differenciate realtime triggers reliably for now, at least a backend check has been added :
https://github.com/kestra-io/kestra/commit/2223265e60505b6eae3d82b490d55554d5e1f356

**Comment by loicmathieu** [comment]
We need a way from the UI to know the type of the trigger: schedule, polling, realtime, other so we can disable the enable/disable toggle when not used.
This issue is also there for Webhook trigger.
