### ISSUE TITLE
Provide a UI field allowing to copy a full Webhook URL e.g. on the Flow Overview page 

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#3891]
### Issue description

The webhook url example mentionned in doc + webhook trigger task doesn't work if tenant is part of the equation:

❌ curl https://{your_hostname}/api/v1/executions/webhook/{namespace}/{flowId}/{key}
✅ curl https://{your_hostname}/api/v1/{tenant_id}/executions/webhook/{namespace}/{flowId}/{key}

**Comment by anna-geller** [comment]
I think this might need to be a field that is masked but can be copied - like API token, given that webhook key is a sensitive info

**Comment by anna-geller** [comment]
@Nico-Kestra we need some help with the design here
