### ISSUE TITLE
executions filter by date failed for unfinished date will never be shown

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#390]
If the execution is not finished, the execution not finished will never be show. 
It's really annoying for running one

**Comment by smunteankestra** [comment]
reproducing in Absolute filter, in relative filter works fine

**Comment by MilosPaunovic** [comment]
Hi @smunteankestra, can you try to reproduce this with new filtering system, if able, please provide more details.

**Comment by smunteankestra** [comment]
Not reproducing
