### ISSUE TITLE
Sftp Plugin Missing

### ISSUE THREAD

**Issue by ankushgo** [kestra-io/kestra#3900]
### Describe the issue

After updating to version 0.17.0, the SFTP plugin (io.kestra.plugin.fs.sftp) is no longer available in flow task.
For reference:
<img width="1414" alt="Kestra Error" src="https://github.com/kestra-io/kestra/assets/27128056/4a5dc115-40f2-48d1-a9f1-e5ae42ce1082">

### Environment

- Kestra Version: 0.17
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
The task is present in our internal deployment that uses our latest release.
![image](https://github.com/kestra-io/kestra/assets/1819009/2ff62b96-68f8-47d4-86f4-a4640d37f1eb)

Can you re-pull the image?
Be careful that develop images are not stable images so this kind of issues can occur from time to time.

**Comment by anna-geller** [comment]
I can't reproduce, @ankushgo I'd also recommend repulling the image:

```bash
docker pull kestra/kestra:latest
```

![image](https://github.com/user-attachments/assets/1f65e19f-9208-4b58-9b70-55427f385a38)
