### ISSUE TITLE
Flows page does not display correctly list of flows

### ISSUE THREAD

**Issue by aballiet** [kestra-io/kestra#3902]
### Describe the issue

Sometimes => probably a race condition, when navigating on `Flows` page, list is displayed like this : 

<img width="1493" alt="image" src="https://github.com/kestra-io/kestra/assets/25565600/60b781aa-84e6-435a-8aa7-9a79ed257512">

Console does not seem to throw any error : 
<img width="1350" alt="image" src="https://github.com/kestra-io/kestra/assets/25565600/08e90140-81f8-4234-ad24-4d8280d9bd39">

> We notice that `Total 69` is correctly specified at the bottom right of the table

### Environment

- Kestra Version: 0.16.7
- Operating System (OS/Docker/Kubernetes): k8S
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
Can you reproduce also in 0.17 @aballiet?

**Comment by anna-geller** [comment]
I can't reproduce it currently. @aballiet, perhaps we close the issue and you can reopen it once you see the issue occurring again?

**Comment by aballiet** [comment]
> I can't reproduce it currently. @aballiet, perhaps we close the issue and you can reopen it once you see the issue occurring again?

Yes we will update soon to `0.18`, I will keep you updated if happening again.
For now we can close 👍
