### ISSUE TITLE
Kestra namespace file import does not update existing files with local storage

### ISSUE THREAD

**Issue by aucubin** [kestra-io/kestra#3908]
### Describe the issue

We have the namespace files locally stored in a git repository and use kestra cli `kestra namespace file update --delete` to update the namespace scripts on the local environments of the devs.

If we now run the command line argument and the file already existed in the editor it will not be updated and that will only work if the file is removed manually in the editor before running the CLI. The same behaviour is visible if we use the REST API /api/v1/namespaces/$namespace/files and run DELETE before adding the file again with HTTP POST.

Note this only seems to happen with the local storage backend, on our k8s installation with S3 backend the update works without needing to manually delete the files in the editor.

### Repro
1. Run import and check that all namespace files are imported
2. Edit random imported namespace file in editor
3. Run import again
4. The change made in step 2 will persist although I would expect it to be overwritten due to the --delete argument.

### Environment

- Kestra Version: 0.16.6
- Operating System (OS/Docker/Kubernetes): Docker (the docker-compose.yml from this repository)
- Java Version (if you don't run kestra in Docker):

**Comment by Ben8t** [comment]
@aucubin can you try on a more recent version of Kestra ?

I'm not able to reproduce on 0.18.7

https://github.com/user-attachments/assets/1dc98e03-cef6-4e26-bb21-af7011a0424d

**Comment by aucubin** [comment]
Hi. Yes, the issue seemed to fix itself with some version upgrade in the mean time. I can also not reproduce it anymore.
