### ISSUE TITLE
[Internal issue] Purge logs and increase the size of the database on the OSS preview environment

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3917]
### Describe the issue

It keeps loading and seems to be stuck: https://share.descript.com/view/mxHmwtoqIp7

![image](https://github.com/kestra-io/kestra/assets/86264395/956f3e2a-4550-4a72-b220-4babbdaf4e9d)

### Environment

- Kestra Version: develop

**Comment by loicmathieu** [comment]
Purge has been setup weeks ago.
Database instance has be scaled up today.
