### ISSUE TITLE
Show the EE popup when hovering over Namespace left sidebar menu only once 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3923]
### Feature description

Show this only once + when clicking on it otherwise it's pretty annoying

![image](https://github.com/kestra-io/kestra/assets/86264395/435cc70b-90a5-4cdc-be95-cbdc3a3e1ea3)

**Comment by tchiotludo** [comment]
the fix is not the good one, we should display the popup only on the click simply ;)

**Comment by MilosPaunovic** [comment]
Amended the functionality, now the tooltip is shown only on click, not on hover anymore.
