### ISSUE TITLE
Gantt: allow collapse of flowable 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#393]
* Allow to collapse gantt by parent flowable tasks
* stick flowable on scroll 
* stick global header with duration on scroll 

example from metaflow : 
![image](https://user-images.githubusercontent.com/2064609/139411817-6890b263-e7a8-47b0-9ba5-8041903b54e9.png)

https://demo.public.outerbounds.xyz/WhyIsThisFlowSlow/21?direction=asc&group=true&order=startTime&status

**Comment by anna-geller** [comment]
seems possible today :)
