### ISSUE TITLE
Gantt: add some filter & sort

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#394]
Add some filter on gantt : 
- by status 
- by taskId ? 

https://demo.public.outerbounds.xyz/DivideByZeroFlow/16?direction=asc&group=true&order=startTime&status

Add a sort : 
![image](https://user-images.githubusercontent.com/2064609/139412261-d0ef2dba-31b3-4aa2-9fdc-7bd6c628d9a5.png)

**Comment by Ben8t** [comment]
MVP : filter by status

**Comment by anna-geller** [comment]
seems like child executions of a subflow can handle this for now :) I added this to the Notion list of ideas https://www.notion.so/kestra-io/bluesky-idea-Gantt-add-filter-sort-760c2dee3cef475eb4158dfb87ee89ee?pvs=4
