### ISSUE TITLE
Please add support for standard unix cron expression with SECOND field.

### ISSUE THREAD

**Issue by lukedoomer** [kestra-io/kestra#3941]
### Feature description

In my use cases, I really need to specify the SECOND field. I hope cron element of kestra accepting 6 fields.
According to the document, `Internally, the Scheduler will keep checking every second whether some trigger must be evaluated.`

Should be an easy change for kestra?

**Comment by anna-geller** [comment]
to clarify, do you want to schedule something every x seconds?

**Comment by anna-geller** [comment]
I got a response from the team that it's possible without introducing a breaking change. We'll add that in the next release. Thanks for the isssue

**Comment by lukedoomer** [comment]
Nice, looking forward to see the update!
yes, I need to schedule something every x seconds or at every hh:00:58 something like that.
