### ISSUE TITLE
Creating block comment with CMD - / causes editor to vanish

### ISSUE THREAD

**Issue by stemarco** [kestra-io/kestra#3955]
### Describe the issue

After attempting to save and getting an error, selecting a block of code and commenting with CMD - / caused Flows editor to vanish.

### Environment

- Kestra Version: 0.17.1
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker): -

**Comment by brian-mulier-p** [comment]
Hello ! Can you please provide your original flow (which contains the error) and the block you tried to comment out ? I can't reproduce the issue

**Comment by anna-geller** [comment]
I'd recommend using this to comment out some code: 
- on Mac: Cmd + K + C
- on Windows: Ctrl + K + C
