### ISSUE TITLE
Add a note to the Timezone Settings that it only impacts the UI, not flows

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#3959]
The Date and Time Settings only impact the UI, not Flows. This seems to have caught a few users off guard as they expected it to set the timezone for their server, not just the UI. While the setting is correct, we should add a popup note or similar to explain to the user to manually set the timezone for the Schedule trigger if they want flows to be scheduled in another timezone than UTC

![Screenshot 2024-06-07 at 15 48 09](https://github.com/kestra-io/kestra/assets/34094921/8e959777-3fb7-4d25-b203-86d9b1959845)

**Comment by wrussell1999** [comment]
Related to the problem: https://github.com/kestra-io/kestra/pull/3960

**Comment by anna-geller** [comment]
Milos, you could add an Info icon with the text: "Note that this setting is used for displaying date and time properties in the UI. To schedule your flows in a timezone different than UTC, make sure to set the timezone property on the Schedule trigger in your flow code or your plugin defaults."
