### ISSUE TITLE
Add ability to parse JSON in io.kestra.plugin.scripts.groovy.FileTransform

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#3962]
### Feature description

Currently when I try to import json parser in groovy FileTransform task

```
import groovy.json.JsonSlurper
```

exception happens:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script10.groovy: 1: unable to resolve class groovy.json.JsonSlurper
 @ line 1, column 1.
   import groovy.json.JsonSlurper
```

It would be nice to know what modules are available to import

**Comment by anna-geller** [comment]
good catch, we'll get back to you on that on Monday

btw would this task be useful in your use case? we were thinking of adding support for JSONata https://github.com/kestra-io/kestra/issues/3148

**Comment by aku** [comment]
Built in support for JSON is certainly welcome. In my case I was disappointed with Jython performance (I do a simple transformation of array of data which includes parsing JSON string) so I've decided to try other FileTranform tasks/plugins.
Nashorn doesn't support returning multiple rows, Groovy can't parse JSON. So I stuck with Jython

**Comment by anna-geller** [comment]
Hey, I got the following response from the team: "In process (in JVM) script tasks will never be able to install any packages due to security reasons. They are more performant than scripts in external processes but with fewer features."

This means we are not able to install any external Groovy libraries including JSON. To use JSON packages, you will need to use Node.js or Python script task instead (or JSONata once we add it).

**Comment by loicmathieu** [comment]
@aku the Jackson library is in the classpath, you may be able to use it to process JSON.

**Comment by aku** [comment]
> @aku the Jackson library is in the classpath, you may be able to use it to process JSON.

Hi @loicmathieu 
Thanks! It took me a while to figure out how to use it but I managed to parse JSON objects using Jackson lib.
Here is a snippet:

```groovy
      import com.fasterxml.jackson.*

      def jsonStr = '{ "name": "John Doe", "age": 99, "embedded": {"foo": "bar"} }';

      def mapper = new databind.ObjectMapper();
      def typeRef = new core.type.TypeReference<HashMap<String,Object>>() {};

      data = mapper.readValue(jsonStr, typeRef);
      
      logger.info('json object: {}', data);
      logger.info('embedded field: {}', data.embedded.foo)
```

Maybe you can update plugin documentation to provide some examples for other users?
Also, it would be nice to know plugin's limitations
