### ISSUE TITLE
Browser Back Button Does Not Redirect to Settings Page

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#3972]
### Describe the issue

Steps:
1 Navigate to Settings: http://localhost:8080/ui/settings
2 In the top right corner click "Jump to" and select "Dashboard"
3 Hit back button in browser (Firefox developer or Chrome latest versions)

Expected : User is redirected to settings
Actual: User still on dashboard

### Environment

- Kestra Version: latest
- Operating System : docker
- Java Version : docker

**Comment by MilosPaunovic** [comment]
Closing this as it's working now.
