### ISSUE TITLE
Front end validation of format of file to import

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#3973]
### Describe the issue

User is allowed to upload formats others than  .zip, .yaml or .yml

Steps to reproduce:
1 Navigate to Flows
2 Click on import and select for instance a .dmg file

Expected result:
User not allowed to upload formats other than  .zip, .yaml or .yml

Actual result: Response code 422 

<img width="1528" alt="image" src="https://github.com/kestra-io/kestra/assets/171780240/024159c8-8630-4a2c-8ed5-2a973518ad09">

### Environment

- Kestra Version: latest
- Operating System (Docker):
- Java Version (Docker):

**Comment by MilosPaunovic** [comment]
Thanks for this @Piyush-r-bhaskar! 🚀 

And if you add a comment here, I can assign you to the issue.

**Comment by Piyush-r-bhaskar** [comment]
> Thanks for this @Piyush-r-bhaskar! 🚀 
> 
> And if you add a comment here, I can assign you to the issue.

Sure Milo. Thanks 

& I checked the PR didn't know it was that easy & i have chosen a complicated path.

Thank you for the review. New learning 😊

**Comment by MilosPaunovic** [comment]
Yeah, those native `HTML` attributes are industry standard, so we should always try to use them if possible or if it's not requested differently. Anyway, thanks for the work on this!
