### ISSUE TITLE
Flow Filters User can filter by space symbol

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#3974]
### Describe the issue

Steps to reproduce:

1 Navigate to flows
2 Add a filter name with space symbol " "

Expected: filtering by space not allowed since id requires: At id: must match "^[a-zA-Z0-9][a-zA-Z0-9._-]*"
<img width="1537" alt="image" src="https://github.com/kestra-io/kestra/assets/171780240/293f1d73-fd16-48a3-bd9d-962ba0e9cb44">

Actual: 
<img width="1703" alt="image" src="https://github.com/kestra-io/kestra/assets/171780240/8b9b3ab7-0089-45f7-a510-9bb83238b0f5">

<img width="1785" alt="image" src="https://github.com/kestra-io/kestra/assets/171780240/8158b412-929b-420f-bef5-69006c76bf88">

### Environment

- Kestra Version: latest
- Operating System (Docker):
- Java Version (Docker):

**Comment by MilosPaunovic** [comment]
Closing this as we've recently changed the entire filtering system.
