### ISSUE TITLE
No limit on environment name in Settings

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#3979]
### Describe the issue

Seems there is no limit to the environment name field

Steps:
1 Navigate to settings, and input in environment name field a very long string

Notes: Some constraints would be nice to have

<img width="1787" alt="image" src="https://github.com/kestra-io/kestra/assets/171780240/83616910-3042-4591-a6b7-c18917949b38">

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Thanks @Piyush-r-bhaskar! 🚀

P.S. If you comment here, I'll have the option to assign you to the issue.

**Comment by Piyush-r-bhaskar** [comment]
> Thanks @Piyush-r-bhaskar! 🚀
> 
> P.S. If you comment here, I'll have the option to assign you to the issue.

Sure @MilosPaunovic  you may assign it to me.
