### ISSUE TITLE
Add spacing to the bottom of the UI

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#3981]
### Describe the issue

In general, on the UI, the pagination or the elements at the bottom are too close to the edge. I would tend to add some space to avoid this.
For example, on blueprints, plugins, or even executions:

<img width="2048" alt="Capture d’écran 2024-06-10 à 14 51 05" src="https://github.com/kestra-io/kestra/assets/125994028/97d61d37-5d0e-460b-bc15-b9823ece8645">

<img width="2043" alt="Capture d’écran 2024-06-10 à 14 51 24" src="https://github.com/kestra-io/kestra/assets/125994028/0de62062-4299-452c-bc81-66f679830557">

<img width="2048" alt="Capture d’écran 2024-06-10 à 14 54 34" src="https://github.com/kestra-io/kestra/assets/125994028/d0a56d76-b169-406c-a6f6-1f29cd823d68">

Add 64px please.

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Padding added to bottom of `Executions`, `Blueprints` and `Plugins` pages.
