### ISSUE TITLE
Ensure that deleting an execution also deletes the logs related to that execution

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3987]
### Feature description

it will avoid issues when user deletes an execution and logs stick around https://github.com/kestra-io/kestra/issues/3961 

it will ensure that kestra executions + logs remain in a consistent state

**Comment by loicmathieu** [comment]
An execution can have:
- logs
- metrics
- internal storage data

When deleted, we should by default delete all related data, but we may offer a way to keep them as it can be useful for ex to keep logs for debugging or metrics for observability. So I propose to add the following parameters when deleting an execution which are true by default: `deleteLogs`, `deleteMetrics`, `deleteStorage`.

**Comment by loicmathieu** [comment]
@MilosPaunovic I made the necessary backend changes to delete logs, metrics, and internal storage when deleting an execution, see https://github.com/kestra-io/kestra/pull/4427

Can you include in the three places where we delete an execution, in the validation tooltip, checkboxes (checked by default) for "Delete logs", "Delete metrics", "Delete internal storage files".

In the Execution page
![image](https://github.com/user-attachments/assets/e99581e4-7829-4ee8-bcda-c3eae92d3c74)

In the Execution list pages (there should be two places, one that uses ids and another one that uses search filters)
![image](https://github.com/user-attachments/assets/38fef567-ebd3-4573-b050-497e53d279b7)

You can add a commit to my branch: https://github.com/kestra-io/kestra/pull/4427
