### ISSUE TITLE
Filtering executions with custom label does not work

### ISSUE THREAD

**Issue by SystemFuchs** [kestra-io/kestra#3995]
### Describe the issue

I'm labeling my executions with a custom label e.g. "hostname:meet". When I try to filter the execution list I'm getting an empty result set. The other filters like env: or project: do work:

![image](https://github.com/kestra-io/kestra/assets/3988026/e0ef162e-3aeb-45b0-99d8-2950f472b8d9)
![image](https://github.com/kestra-io/kestra/assets/3988026/48703070-5d7b-423e-9c62-45f4967707dc)

### Environment

- Kestra Version: 0.17.1
- Operating System (OS/Docker/Kubernetes):Linux/Docker
- Java Version (if you don't run kestra in Docker):

**Comment by SystemFuchs** [comment]
I think we can close this issue. Suddenly it is working.

**Comment by MilosPaunovic** [comment]
Closing, based on the comment above. @SystemFuchs if you notice it again, we can re-open and investigate more.
