### ISSUE TITLE
Dependencies tab doesn't show dependencies

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4002]
### Describe the issue

Flow dependencies created via the `ForEachItem` task are not displayed in EE even though it works fine in OSS on 0.17.2

![image](https://github.com/kestra-io/kestra/assets/86264395/759a59f0-ba5d-4ec1-ba44-e1a4c8cb3f7e)

![image](https://github.com/kestra-io/kestra/assets/86264395/fda9fab8-db07-4c5b-bd2f-06380584c6c5)

it starts to get a little frustrating that this bug keeps reappearing — should we add more tests to automatically test the behavior?

https://us.kestra.cloud/ui/kestra-tech/flows/edit/github/fetch_kestra_repositories/dependencies

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
After a quick check using the flow from cloud link, it turns out that the response from the endpoint for the OSS version is empty, and that is the reason why nothing is drawn in the flow graph, so I'm unassigning myself from this one.

**Comment by anna-geller** [comment]
sure no worries, I changed the label to backend then 👍

**Comment by Ben8t** [comment]
same behavior with explicit dependencies (flow trigger)


![Image](https://github.com/user-attachments/assets/8af66ab8-9304-4088-8cd5-07e6a3559056)



![Image](https://github.com/user-attachments/assets/e89e5fd6-f947-4d7b-b0a0-5063644cbeb7)

(version EE develop-full, pulled on 29/07/2024)

**Comment by MilosPaunovic** [comment]
@Ben8t I'm trying to reproduce this, but failing. 

https://us.kestra.cloud/ui/kestra-tech/flows/edit/data.posthog.export/organizations/dependencies this seems to show proper deps, so is the link Anna posted as an initial description of this task https://us.kestra.cloud/ui/kestra-tech/flows/edit/github/fetch_kestra_repositories/dependencies.

Can you provide a link to failing one for me to have closer look at it?

**Comment by Ben8t** [comment]
@MilosPaunovic here is one that doesn't work https://us.kestra.cloud/ui/demo/namespaces/edit/shiny_rocks/dependencies - I think the scope is Namespaces dependencies view - I can see dependancies at the flow level

**Comment by MilosPaunovic** [comment]
@Ben8t Clicking on the link from your last comment takes me to to working dependencies view. Could you re-check and close if it's alright now?

**Comment by anna-geller** [comment]
good catch Milos, the issue is fixed already

![image](https://github.com/user-attachments/assets/5fc45dbf-ae83-4359-81bb-5afadff59429)
