### ISSUE TITLE
Wrong password toast message improvement

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4012]
### Describe the issue

If user will input in password field space symbol example:
Login: "testtest" pasword: "      "
Actual : no toast message notifying  a wrong login/pass is shown
Expected: Incorrect username or password. message is present

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by mounikaperi** [comment]
@smunteankestra @MilosPaunovic - if no-one is working on this. can I contribute to this issue?

**Comment by smunteankestra** [comment]
Hi, go for it, thanks

**Comment by mounikaperi** [comment]
thank you @smunteankestra

**Comment by mounikaperi** [comment]
@smunteankestra can you please review https://github.com/kestra-io/kestra/pull/5206

**Comment by mounikaperi** [comment]
@smunteankestra one request- i am unable to assign this issue to my name. as pull request is merged, can you please assign this to me and close the issue?

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/kestra/pull/5206.

**Comment by mounikaperi** [comment]
Thank you @MilosPaunovic
