### ISSUE TITLE
After Language change, user needs to refresh to update left side 

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4021]
### Describe the issue

After Language change, user needs to refresh to update left side 

![image](https://github.com/kestra-io/kestra/assets/171780240/32fe2673-6e53-4c17-b862-68aec46f3bd3)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Behavior for this is changed, now the language does not switch automatically on selection, but when we click `Save` button, so this is now amended.

See https://github.com/kestra-io/kestra/pull/6520 and https://github.com/kestra-io/kestra/issues/6460 for more details.
