### ISSUE TITLE
[FeedBack] - How can you improve Kestra visual

### ISSUE THREAD

**Issue by Gadiffet** [kestra-io/kestra#403]
**Warning: * This feedback is not here to degrade the work of the designer and my feedback is based on my experience, it is probably not good***

You are using too much color

*Logo :*
![image](https://user-images.githubusercontent.com/56682141/143054904-1061459d-2d02-4a7e-bb4f-da3f1459df5f.png)
![image](https://user-images.githubusercontent.com/56682141/143055047-c20868ae-2740-4077-9326-a6a5c92517a6.png)
![image](https://user-images.githubusercontent.com/56682141/143055145-d493ae71-c214-44d4-8c3e-d2d15c66584b.png)

*Text :*
![image](https://user-images.githubusercontent.com/56682141/143055334-e4d70548-4108-41d2-b582-e0e458870b90.png)
![image](https://user-images.githubusercontent.com/56682141/143055680-e4442122-75f9-4b79-a1c5-ccd629937812.png)
![image](https://user-images.githubusercontent.com/56682141/143056258-4d0cc35a-02de-4ff0-9c3e-c0f3e9fd7747.png)
![image](https://user-images.githubusercontent.com/56682141/143056470-9d664423-86f6-453f-8de0-e2a4a67bf3ca.png)

And more ...

If you want to create a color blind friendly application, use [Contrast Ratio Checker](https://webaim.org/resources/contrastchecker/) to find your correct color combination.
And if you want to have a consistent application, use as little color as possible. Use your logo colors + warning / error color (red / orange / green)

# Exemple

### Currently
![image](https://user-images.githubusercontent.com/56682141/143051697-fc1717c1-9088-412f-aa79-35ff927b56c5.png)
![image](https://user-images.githubusercontent.com/56682141/143057168-f7d4afde-a014-4c46-96a1-4aad1dede4e0.png)

### Possible solution
![image](https://user-images.githubusercontent.com/56682141/143052129-25740a7f-8f8a-4778-99fa-3d8ff025fd75.png)
![image](https://user-images.githubusercontent.com/56682141/143058332-0ab6edb6-f2fc-451a-9fa2-f39e6acc882b.png)

Probably updating your logo with a new color to improve the consistency of your application.

### Currently
![image](https://user-images.githubusercontent.com/56682141/143059067-01d17ae3-3806-4155-ad60-9663a5ee2936.png)
![image](https://user-images.githubusercontent.com/56682141/143059261-0e328329-0542-44f0-b392-81cf32063752.png)

The color is great, but you are still using a new color.

### Possible Solution
![image](https://user-images.githubusercontent.com/56682141/143060377-173d8049-e10d-4364-a650-d2f9b07c6edb.png)
![image](https://user-images.githubusercontent.com/56682141/143061100-7fd7af96-ac02-4ff8-b387-3b8395495d47.png)

I tried to choose a lighter color, you do what you want, it's a test :D 

# Issues

## Logo padding when switching between black and white
![image](https://user-images.githubusercontent.com/56682141/143061663-ede92475-129e-46e4-b086-e5beae4ed631.png)
![image](https://user-images.githubusercontent.com/56682141/143061772-c48aa85e-56e1-4890-8064-0e30b2c8af54.png)

## Black Mod
![image](https://user-images.githubusercontent.com/56682141/143069057-7bb02f31-f9bd-4025-94a2-194fadaf93e9.png)

**Comment by tchiotludo** [comment]
- Logo padding when switching between black and white
- source Code 

done in 1f675f29bcbb28be0a385e826d87fedf867db511

For the contrast issue, we need to have a deeper look :eyes:
