### ISSUE TITLE
"interpreter" and "beforeCommands" fields not visible on python scripts but mandatory

### ISSUE THREAD

**Issue by jhetzel** [kestra-io/kestra#4042]
### Describe the issue

both fields should be available and are marked mandatory but are not shown
<img width="812" alt="Bildschirmfoto 2024-06-15 um 21 19 40" src="https://github.com/kestra-io/kestra/assets/76711604/69308d21-d13d-44ad-a316-50703ac5aa04">
<img width="674" alt="Bildschirmfoto 2024-06-15 um 21 20 00" src="https://github.com/kestra-io/kestra/assets/76711604/acea7568-6df4-44de-b283-45b7f84ffd84">

### Environment

- Kestra Version: 17.1
- Operating System (OS/Docker/Kubernetes): Unraid/Docker
- Java Version (if you don't run kestra in Docker):

**Comment by Ben8t** [comment]
Seems good on 0.20
![Image](https://github.com/user-attachments/assets/47a0aec8-caac-4c39-a541-bf8f4f526e86)

Probably change here with new no-code coming soon. Closing
