### ISSUE TITLE
[UI] The calls to the API for the logs widget on the dashboard are made twice

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#4060]
### Describe the issue

The calls to the API for the logs widget on the dashboard are made twice.
Goes to: http://localhost:8080/ui/dashboard
You'll notice that the calls to /logs/search and /stats/logs are made twice, those calls are costly as the logs table is the biggest table so it's important to not overload them.

![image](https://github.com/kestra-io/kestra/assets/1819009/63631e32-0228-44d2-ba71-13aa7040226c)

### Environment

- Kestra Version: 0.18.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Closing, as we've changed our main dashboard, so this is not relevant anymore.
