### ISSUE TITLE
Prefilling execution with `null` inputs fills with 'null' as string

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#4065]
### Describe the issue

Hello !
This is sorta related to [this issue](https://github.com/kestra-io/kestra/issues/3768). But when I run a workflow with blank inputs, it uses Null, but if I run a repeat execution with "Prefill" button in run execution menu, it fills in string "null". 

Should this be an empty string when you prefill? Otherwise it treats value as string and not null.

Here is image after Prefill is clicked on a previously nulled inputs run.
![image](https://github.com/kestra-io/kestra/assets/21957238/eba18932-9a34-4f97-bfcb-799fd4179275)

Thanks :pray:

### Environment

- Kestra Version: 0.17.3
- Operating System (OS/Docker/Kubernetes): Cloud
- Java Version (if you don't run kestra in Docker): n/a

**Comment by Skraye** [comment]
fixed by https://github.com/kestra-io/kestra/commit/0338f23e5b1791c01dbbe21a1cc40751515006a2
Now when executing without value, we will not send "null" as a string anymore, so prefill will not fill with null string
