### ISSUE TITLE
Dublication of Page title in Plugins 

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4069]
### Describe the issue

Plugins page title is duplicated, and a Href to the same path

<img width="1600" alt="image" src="https://github.com/kestra-io/kestra/assets/171780240/e9617cfb-6d5a-4bc4-a193-a00a8a81ff21">

### Environment

- Kestra Version: 0.17.3
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Closed with https://github.com/kestra-io/kestra/commit/53013379cdc6fa4effbf716f3018f1cbcc55f841.
