### ISSUE TITLE
Flow becomes unavailable after closing namespace file in editor

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4071]
### Describe the issue

From [Slack](https://kestra-io.slack.com/archives/C03FEC452NQ/p1718791797411269):
> Found a minor bug : when i select a file from my namespace then select my flow and finally trigger the cross buton of the hello.txt file (see screenshots) it make the flow unavailable (see near empty screen shot). (I can make my flow appear again just by switching to any other tab, like overview, and coming back to the editor.)
I'm on kestra 17.4 on a docker on a debian machine.
Not really bothering me anyway.

### Environment

- Kestra Version: 0.17.4
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):

**Comment by smunteankestra** [comment]
https://github.com/kestra-io/kestra/assets/171780240/6f3ab267-8a92-4424-900a-c934688a00d1

video to reproduce

**Comment by smunteankestra** [comment]
might be related to https://github.com/kestra-io/kestra/issues/4073
