### ISSUE TITLE
Can't view files when Editor is selected to Topology View

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4073]
### Describe the issue

When you open the Editor, and change the view to Topology only, namespace files will not open. They will appear as tabs at the top but it will not display them

https://github.com/kestra-io/kestra/assets/34094921/dcf9edaf-2026-4c52-acf9-9259e36f6650

### Environment

- Kestra Version: 0.18 Snapshot
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
@anna-geller What kind of behaviour do we want to have here?

My proposition would be this:

1. When view is changed to `topology` whatever tab the user has opened it will change to tab with the flow being opened.
2. If the user opens any other file from the sidebar or clicks on any tab for already opened namespace files, it will switch the view to `source-topology`.

Would that solution work?

**Comment by anna-geller** [comment]
@MilosPaunovic ideally, it should work as Will described i.e. when you click on another tab e.g. a tab with a Python script, then you should show that Python script rather than the topology of the flow. When you then switch back to the flow tab, it should show the flow's topology again. Does it make sense?

**Comment by MilosPaunovic** [comment]
Yup, makes perfect sense, will make it like so.

**Comment by MilosPaunovic** [comment]
@anna-geller But now when I've got my hands on this issue, it might be confusing as to what will happen is the user is on tab with some namespace file and clicks the Topology button?

**Comment by anna-geller** [comment]
no action needed for it, as there is no topology for a regular file ✅

**Comment by MilosPaunovic** [comment]
But right now, the Topology for Flow will be shown on whichever tab you're on.

**Comment by MilosPaunovic** [comment]
I have opened a PR #4138 which aims to solve this issue in a following manner:

- On `Flow` tab, the user can select what ever view it desires
- If a tab is changed from `Flow` to any namespace file, the view is automatically changed to code only. It also disables buttons on the top to change to another view and show a tooltip that other views are available only on `Flow` tab.
- When the user returns to `Flow` tab, the view is set to the one it was before, but can be easily changed using top buttons, just like before.

If this is alright approach, I can merge this one? @wrussell1999 @anna-geller

**Comment by anna-geller** [comment]
sounds great, LGTM!
