### ISSUE TITLE
Support for secret files

### ISSUE THREAD

**Issue by nidomiro** [kestra-io/kestra#4094]
### Feature description

It is a well known practice for using docker to map secrets as a file into the container.
This can increase security a lot, since environment variables can be introspected simply.
Another benefit is, that if you e.g. need several ssh-keys in your workflows, it does not bloat your .env file too much.

There could be a configuration entry, where the kestra operator could define where these folders are.
My suggestion is a config with the name `secrets-directory`  for the secrets, that points to `/run/secrets` by default for docker. The filename would directly map to the argument, given to `secret(FILENAME_IN_SECRETS)` , since the folder is indication for it being a secret.

I'm willing to start (and hopefully finish) the implementation on it, even tough it is some time since I last wrote java.
It would be great to get your comments on my proposed solution and naming, so I can incorporate it into the code right at the start.

**Comment by anna-geller** [comment]
can you say a bit more what benefit loading secrets from a file offer compared to loading them from env variables?

**Comment by anna-geller** [comment]
we are willing to review a PR that reads environment variables from `.env` file - would that be something that would make your use case easier?

**Comment by nidomiro** [comment]
Loading from a `.env` file is what I'm already doing via [the `env_file` definition of docker compose](https://github.com/compose-spec/compose-spec/blob/master/spec.md#env_file) so there is no benefit for me here.

My usecase would be to be able to store my ssh-keys as files and map them as files into the Kestra container. I would not have to base64 encode them and store them as a huge string that bloats my environment file and make it hard to read.

To my knowledge having secrets as files is fairly common, since there are multiple docker-images that support it, like [postgres](https://hub.docker.com/_/postgres#:~:text=POSTGRES_PASSWORD_FILE), [traefik](https://doc.traefik.io/traefik/user-guides/docker-compose/acme-dns/#:~:text=The%20environment%20variable%20within%20our%20traefik%20service%20are%20suffixed%20by%20_FILE), ...
I think this was introduced with [docker secrets](https://docs.docker.com/engine/swarm/secrets/).
The main benefit security wise is that it can be more difficult to get to the actual secrets, since something like `docker inspect` won't show them.

**Comment by Sneltrain** [comment]
This probably isn't quite what you are looking for @nidomiro, but in my Docker Compose I have mounted this volume: `/opt/Kestra/kestra/storage:/app/storage`. Now when I have a namespace `my.namespace` I can add files to `/opt/Kestra/kestra/storage/my/namespace/_files/` and they will appear in Kestra even without restarting the container.

This way I can easily add multiple files (secrets or not) but I have to do that for every namespace individually instead of adding them to the whole Kestra instance.

**Comment by anna-geller** [comment]
Kestra 0.18 is released, and you can try your use case by storing that file as a KV pair: https://kestra.io/docs/concepts/kv-store

Note that overall secure Secrets management is a paid feature, so you can reach out to us via Slack or kestra.io/demo to discuss that use case.
