### ISSUE TITLE
[EE] Refresh the auth token/cookie automatically if the user is still active

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4120]
### Describe the issue

Kestra currently time-outs the user based on a fixed interval (token expiry) instead of silently refreshing the token when the user is active. 
The user may be in the middle of editing a flow when the user token expires, which blocks the user from saving when pressing the "Save" button, and then ultimately kicks the user out into the login page without saving which causes the user to lose all the work they've done since they last saved with a valid token.

There needs to be some sort of silent refreshing of tokens periodically when the user is active in the editor or otherwise browsing the dashboard. 

Proposed solution : 
- When accessing any link on the Kestra dashboard, If the token expiry is within a certain threshold (2 min until expiry or something like that), silently refresh the token so it doesn't log out the user.
- When a user is editing in the Kestra flow editor, periodically check for the token expiry threshold and silently refresh the token so it doesn't log out the user.

I think this is a bit of a critical issue, I've lost work multiple times due to this, and because of this bug I'm forced to save more often than I'd like which creates a lot of revisions that I don't want. 

### Environment

- Kestra Version: 0.17.5
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by yuri1969** [comment]
As a workaround we have exended the validity interval of both cookie/JWT token to several hours instead of the default 1 hour using the [Micronaut Security guide](https://micronaut-projects.github.io/micronaut-security/latest/guide/#cookieToken).

**Comment by anna-geller** [comment]
Just this week we opened an [internal issue](https://github.com/kestra-io/kestra-ee/issues/1302) to refresh the cookie automatically (1h will be kept if not online, but refresh if online before the 1h) pretty much exactly as you suggested :) we'll take it as a high-priority item, thx for flagging

**Comment by anna-geller** [comment]
internal notes/extra context:
> currently, the session cookie has a limited duration (configuration is possible, but the default is very low, on the cloud it's set to 1h). We should auto-refresh the cookie when the user is still online before the expiration.

**Comment by anna-geller** [comment]
closes https://github.com/kestra-io/kestra-ee/issues/1303
