### ISSUE TITLE
Docker Task Runner Icon not displaying

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4122]
### Describe the issue

Not displaying in the plugin page or blueprints (website + kestra)

https://kestra.io/plugins/core/task-runners/io.kestra.plugin.scripts.runner.docker.docker

![Screenshot 2024-06-24 at 18 21 11](https://github.com/kestra-io/kestra/assets/34094921/227b10e7-04b4-4f86-be40-7b7fd3689dde)

Blueprint:
![Screenshot 2024-06-24 at 18 21 43](https://github.com/kestra-io/kestra/assets/34094921/06cb4bbc-77ff-41c3-9d17-fc6298b2fa99)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
this might fix it, not 100% though yet https://github.com/kestra-io/plugin-scripts/commit/297d241724d326764dc201cb38910c529534b66e
