### ISSUE TITLE
Execution charts don't honor start date & end date

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#413]
[This](http://kestra:8080/ui/executions?sort=state.startDate%3Adesc&start=2020-09-01T00%3A00%3A00.000%2B02%3A00&end=2020-09-30T00%3A00%3A00.000%2B02%3A00) have a date filter, the table honor the filter but not the charts on top

**Comment by MilosPaunovic** [comment]
Closing this as it's not relevant anymore, also, the new charts on executions listing are honoring date filters.
