### ISSUE TITLE
Find and Replace in Editor stops working sometimes after flow execution

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4130]
### Feature description

Add a Find (Control + F) and Replace feature to allow people to easily change multiple instances of a word in their flows and files.

**Comment by MilosPaunovic** [comment]
@wrussell1999 I'm kind of confused here, as that functionality already exists in the editor, or am I missing something?

https://github.com/kestra-io/kestra/assets/62475782/cfd9e738-f27b-4f63-83e6-edb70fbe78e5

**Comment by wrussell1999** [comment]
@MilosPaunovic Hmm odd. It wasn't working for me so I gave it a hard refresh and it now shows up. Trying to see if I can replicate this bug. If I can't, I will close the issue.

When I pressed Control + F (or in my case Cmd + F on Mac), no search box would display (none in Kestra or Chrome). Also no UI option to trigger it either. Maybe something we'd want to add for accessibility?

**Comment by wrussell1999** [comment]
@MilosPaunovic I've been able to re-create it. When I execute this [blueprint](https://kestra.io/blueprints/225-run-multiple-python-scripts-in-parallel-on-aws-ecs-fargate-with-aws-batch), when I go back to the editor, it no longer works.

https://github.com/kestra-io/kestra/assets/34094921/2a0e188c-9585-4ea0-8054-8f2afb555d83

**Comment by wrussell1999** [comment]
Same for namespace files and when I go between tabs in the flow 

https://github.com/kestra-io/kestra/assets/34094921/dff1a0e2-71a9-41fa-a29a-6116fbfee845

**Comment by wrussell1999** [comment]
Broken when I go between flows too

https://github.com/kestra-io/kestra/assets/34094921/dbff29b0-6750-42d9-bc68-f74609f1015b

**Comment by wrussell1999** [comment]
Refreshing seems to fix it

https://github.com/kestra-io/kestra/assets/34094921/6313e1aa-9f67-4598-bdc9-051173d2e515

**Comment by anna-geller** [comment]
@wrussell1999 do you still see this issue? I'm inclined to close it as I also can't reproduce it but if you still see it, we can keep it open and investigate more

**Comment by wrussell1999** [comment]
Can't reproduce so closing!
