### ISSUE TITLE
PR CI for kestra cannot succeed

### ISSUE THREAD

**Issue by eregnier** [kestra-io/kestra#416]
some secret are missing in PR context from a fork , so PR always fails
As there is no frontend tests https://github.com/kestra-io/kestra/pull/415 should not fail
As e2e code is not called at all, https://github.com/kestra-io/kestra/pull/411 should not fail
However there is slack things breaking CI at some point like :
![image](https://user-images.githubusercontent.com/5399780/145985272-635b1b54-13a4-4b3b-9284-7309d3e064e8.png)

**Comment by tchiotludo** [comment]
I've try a fix, can you rebase one of your PR to validate ? I can't myself :disappointed:

**Comment by tchiotludo** [comment]
don't work :cry: 
just try another way, can you rebase again please ?

**Comment by tchiotludo** [comment]
It works thanks :+1:
