### ISSUE TITLE
Add a few of the Namespace endpoints to OSS version

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#4162]
For this issue https://github.com/kestra-io/kestra/issues/3609 to be implemented successfully, we need to add a couple of NS endpoints to OSS version - one for loading all the namespaces, one for loading single one, and one for loading dependencies of the single namespace.

**Comment by loicmathieu** [comment]
@MilosPaunovic as OSS now have a Namespace page I suppose we can close this one right?

**Comment by MilosPaunovic** [comment]
Yup, @brian-mulier-p handled this one through the https://github.com/kestra-io/kestra/commit/da500b397e5cd9710d1518c45238be7b655e492f, so closing it.
