### ISSUE TITLE
avoid warnings on outdated pip when running io.kestra.plugin.scripts.python.Script

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4197]
### Feature description

I'm using io.kestra.plugin.scripts.python.Script to run some python scripts

My logs are flooded with following messages:

WARN [notice] A new release of pip is available: 24.0 -> 24.1.1
WARN [notice] To update, run: pip install --upgrade pip

Is it possible to get rid of this warning ('cause it marks the whole execution as one with problems) without suppressing the logs completely or changing log level for this particular task ('cause sometimes it logs something really important like S3 storage exhaustion)

**Comment by anna-geller** [comment]
fully agree we this shouldn't put the task run state in a warning state

let me fix it asap by ignoring this warning
