### ISSUE TITLE
Output of PurgeExecution task is too verbose and produces broken links in Output panel

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4208]
### Feature description

I'm using PurgeExecution to get rid of execution data to save space in S3.

The task can produces a lot of useless lines in the Output panel. Also, there are problems with Preview and Download buttons (which could probably be removed in this case 'cause there is nothing to show/download)

<img width="1219" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/02943d2e-f408-4291-826a-a2f25f211b35">

If you click on Preview button Kestra will display Page Not Found page

<img width="443" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/fa99b13f-804a-425d-9e99-ec60788a5091">

If you click on Download button Kestra will redirect to some page with JSON data

<img width="963" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/8b8ac6af-1c52-4689-bfb9-bf5ce97e7012">

Please consider optimizing the way PurgeExecution reports its result

**Comment by anna-geller** [comment]
thx for the extra context, I agree this task is not a good solution to remove outputs from the execution

we will tackle it in https://github.com/kestra-io/kestra/issues/4207
