### ISSUE TITLE
Add ability to provide a comment when submitting a new revision of a flow

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4209]
### Feature description

It would be nice to have git-like commit messages when editing a flow
Sometimes it is hard to remember why you did a certain change

**Comment by anna-geller** [comment]
you can add that information to the flow description and any change you make there will be tied to that version and displayed in the revision history

we would like to support custom versions, though, similar to what you suggested - you can follow along in this issue https://github.com/kestra-io/kestra/issues/1547
