### ISSUE TITLE
Add Kestra Pulumi package/resource provider

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4210]
### Feature description

We may be able to use https://github.com/pulumi/pulumi-tf-provider-boilerplate as a getting-started point

Requested a.o. by @japerry911

**Comment by japerry911** [comment]
Thanks Anna. Hey Team, please reach out if you need guinea pig tester, or want to discuss/brainstorm anything on it. Appreciate it, really excited about Pulumi-Kestra!

**Comment by anna-geller** [comment]
just realized I created a dup issue accidentally. Jack, let's keep this original one https://github.com/kestra-io/kestra/issues/3016 👍
