### ISSUE TITLE
Add ability to see resources consumptions by a flow

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4215]
### Feature description

I have a lot of flows based on Kafka and DB triggers.
These flows produce a ton of intermediate data in the storage.
I use Purge/PurgeExecution tasks but Purge is not very reliable (I've submitted a number of issues) and sometimes I want to keep the data for debugging.  Eventually, I run out of storage.

It would be super helpful to be able to see some resources consumption stats per flow.
I.e. I'd like to understand what is the cost behind some flow in terms of storage (total size of executions data) and other resources.

**Comment by anna-geller** [comment]
we provide info about resource consumption in the Cluster Monitor in the EE version

we will address the issue of being able to purge specific outputs by ID in https://github.com/kestra-io/kestra/issues/4207

**Comment by aku** [comment]
@anna-geller so, this feature will not be available in OSS version at all?

**Comment by anna-geller** [comment]
https://github.com/kestra-io/kestra/issues/4207 this one will be OSS

tracking resource consumption like CPU, memory, storage across workers is an existing EE feature
