### ISSUE TITLE
Topology editor panel cause saving problems.

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#4220]
### Describe the issue

Using Firefox, I did not tested it with other tools.

- When opening a flow (or refreshing it with or without cache) I'm getting, in the console (opened by pressing F12), two warnings [logs1.txt](https://github.com/user-attachments/files/16085150/logs1.txt).

**Using the topology panel** of the edit tab (task referred here are : io.kestra.plugin.airbyte.cloud.jobs.Reset and io.kestra.plugin.core.log.Log as well as custom task from my plug-in ) :
- deleting a task has no effect (absolutely none)
- adding a task doesn't make it appear in the topology (still appear in the yaml) until the flow is saved, it produce the following error [logs2.txt](https://github.com/user-attachments/files/16085284/logs2.txt).
- changments made through the topology on existing tasks like adding a description or specifying the logLevel produce the same type of error as adding task but doesn't appear (even after save) in the yaml (and only appear in the topology this time). From this point writing anything in the yaml erase (even before saving) those shadow values in the topology.
- when uncollapsing the enum menu of the loglevel I got "Empty string passed to getElementById()." in the console and am now unable to save the flow no matter what (CTRL-s, clicking the save button, through the topology or the yaml).

Side note : There's no specific logging by the docker container when those action are performed.

### Environment

- Kestra Version: 0.17.8 (full)
- Operating System (OS/Docker/Kubernetes): Docker on a debian machine
- Java Version (if you don't run kestra in Docker):

**Comment by smunteankestra** [comment]
not reproducing on kestra latest
