### ISSUE TITLE
Empty role (Null Role or Null namespace) is successfully saved despite (correctly) throwing errors

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4222]
### Describe the issue

Null Role or Null namespace returns uscess message in user group creation
Check video
https://github.com/kestra-io/kestra/assets/171780240/8ad6a361-0a82-4cf1-a33b-6163dc656d7b

### Environment

- Kestra Version: latest
- Operating System (Mac/Docker/):
- Java Version (Docker):

**Comment by anna-geller** [comment]
duplicate of https://github.com/kestra-io/kestra-ee/issues/1548
