### ISSUE TITLE
Dashboard blueprints link needs to be adjusted

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4224]
### Describe the issue

Fresh lunched Kestra instance has GET STARTED IN 3 EASY STEPS
link needs to be adjusted to href="/ui/blueprints/community"

https://github.com/kestra-io/kestra/assets/171780240/65a0332f-d0b1-4654-b9d2-451c4ffe3c2c

### Environment

- Kestra Version: latest
- Operating System (/Docker/):
- Java Version (Docker):

**Comment by MilosPaunovic** [comment]
Closed with https://github.com/kestra-io/kestra-ee/pull/1331
