### ISSUE TITLE
Examples displaying in documentation

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#4226]
### Feature description

A useful addition to increase the easiness of use for end users may be to allow tasks to display examples for specific properties.

Especially for tasks that takes and outputs URI(s), since the contents of such files isn't showed in the example field (and should not in my opinion) of the task itself it may be good to let such properties, that use a Schema annotation example field, to display this field.

And to reduce the heaviness of the documentation for more used-to-the-task users : having the documentation example-field collapsible may be a serious advantage.

**Comment by anna-geller** [comment]
fully agree this will be useful. we'll include it in the new plugin documentation design - you can follow along in this issue https://github.com/kestra-io/kestra/issues/4154
