### ISSUE TITLE
Allow default setup of commons field across plugins tasks

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#4229]
### Feature description

Problem Description:

In our company, we frequently interact with multiple servers, performing several actions on the same server within a workflow. This necessitates specifying redundant information fields (such as host, port, password, user, etc.) for each task in the flow, leading to significant redundancy.

Concrete Example:

    We search for information via a query on two different servers (requiring two sets of host, pass, user, etc.).
    We compare this information, transform some data, etc.
    We insert the transformed information back into those servers (requiring the same two sets of host, pass, user, etc.).
    We delete specific information from those servers (requiring the same two sets of host, pass, user, etc.).
    We query some information regarding the state of those servers (requiring the same two sets of host, pass, user, etc.).

Each of these steps uses a different task, resulting in a lot of redundancy in the YAML file. This causes the usual problems associated with duplicate code, such as maintenance difficulties and reduced flexibility.

While PluginDefaults can address some of these issues, it may actually increase the number of lines rather than reducing them.
Proposed Solution:

Given that not all plugins have consistent naming conventions for similar properties, it would be beneficial to introduce a tool similar to PluginDefaults. This tool would allow specifying "lists of property names" and mapping each list to a single value, which would act as the default for each encountered value in the list. While this solution may not be perfect, it could significantly reduce redundancy and improve maintainability.

**Comment by anna-geller** [comment]
the KV Store will allow you to store any value and retrieve it by key `{{ kv('your_key') }}` - you can follow along on this PR https://github.com/kestra-io/kestra/pull/4217 

to introduce more modularity and avoid repeating some values, I'd recommend checking out subflows - they allow you to set default values for some inputs and call them like functions https://kestra.io/docs/workflow-components/subflows 

if you need more guidance to add more governance to your configuration, let us know - we have multiple dedicated features (like [namespace variables](https://kestra.io/docs/enterprise/namespace-management)) for that in the EE version https://kestra.io/demo

**Comment by ReLoutre** [comment]
Just to be sure that the problem is clear (since i am, personally, not sure of what should do the KV Store), here's an example of what i may found useful in my yaml flow :

``` yaml
defaultFields:
  - {"host", "server", "address"} : "0.0.0.0"
  - {"port", "ports", "endpoint"} : "8080"
  - {"pass", "pwd", "password", "secret", "key"} : "{{secrets.someSecret}}"
```

 Here, all fields named like a member of the list will have it's default value replaced by the value after the semi-colons.

**Comment by anna-geller** [comment]
what you're describing is already possible in EE with namespace variables 

KV Store will be OSS - you can store an entire JSON and then retrieve only specific attributes of a JSON field when needed using: `"{{ kv('myjson').property }}"`

Example:
`"{{ kv('myjson').name }}"` will give John Doe here:

![image](https://github.com/kestra-io/kestra/assets/86264395/2aa12fda-ed1e-4af5-ac96-7516c013aca0)
