### ISSUE TITLE
Potential enhancements to KV Store

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4232]
### Feature description

- [x] perhaps change checkbox to toggle?
![image](https://github.com/kestra-io/kestra/assets/86264395/55313d16-4fa6-4dae-891f-4b02102aa66d)
![image](https://github.com/kestra-io/kestra/assets/86264395/a4f16478-076c-46c5-9e5b-98eeffc491dc)
- [x] rename permission from KVS to KVSTORE
- [x] document that people need to explicitly add KVSTORE permission to their roles to be able to see KVSTORE  (just so we don't forget to document it) — alternatively we need to find a way to add that new permission to all roles that have NAMESPACE permission as part of database migration
- [x] add an icon for the KV plugin tasks -- @Nico-Kestra do you have an idea for a nice icon for a Key-Value Store plugin?
![image](https://github.com/kestra-io/kestra/assets/86264395/003ee670-bfda-4eaf-b693-67cd9f4355cc)

**Comment by Nico-Kestra** [comment]
<img width="619" alt="Capture d’écran 2024-07-05 à 11 55 01" src="https://github.com/kestra-io/kestra/assets/125994028/59c261c7-49cb-4d55-a9e9-97b2551d7b9a">
If it's okay with you, I'll clean up this icons.

**Comment by Nico-Kestra** [comment]
available [here](https://www.figma.com/design/uUvt0RQ9DWiBTweX6oT4Qp/Library-Icons-Plugins?node-id=104-524&t=BIeLoXnH9GlAb4vo-1)
