### ISSUE TITLE
Add a new API endpoint that will create an execution and WAIT for its completion

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4253]
## Current state: non-blocking call
Currently, user can create a flow:

```yaml
id: myflow
namespace: company.myteam
tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 30
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
```

And create an Execution of this flow from anywhere via an API call:

```bash
curl -X POST http://localhost:8080/api/v1/executions/company.myteam/myflow
```

The challenge is that this API call will respond immediately with:

```
{"id":"74DEZseJ1Oa4ADD508WYJb","namespace":"company.myteam","flowId":"myflow","flowRevision":1,"state":{"current":"CREATED","histories":[{"state":"CREATED","date":"2024-07-05T14:40:06.228074635Z"}],"startDate":"2024-07-05T14:40:06.228074635Z","duration":"PT0.114167S"},"originalId":"74DEZseJ1Oa4ADD508WYJb","deleted":false,"metadata":{"attemptNumber":1,"originalCreatedDate":"2024-07-05T14:40:06.228286677Z"}}
```

and the only way to verify the state of this execution is to go to the UI.

## Proposal: Blocking API endpoint to start an execution

To improve the process of executing Kestra workflows from anywhere, we should provide a new endpoint that will allow blocking calls.

HTTP POST API Endpoint: `/api/v1/executions/start`

This endpoint would create an execution of a specified `flow`, optionally with specific `inputs`. It returns a `URL` to follow the execution status in the UI initially and optionally allows the caller to wait for the execution to complete + will stream the execution state changes.

#### waitForCompletion: false

Request:
```bash
curl -X POST http://localhost:8080/api/v1/executions/start \
  -H "Content-Type: application/json" \
  -d '{
        "namespace": "company.myteam",
        "flowId": "myflow",
        "inputs": {
          ...optional inputs specific to the flow
        },
        "waitForCompletion": false
      }'
```

Response:
  ```json
  {
    "id": "74DEZseJ1Oa4ADD508WYJb",
    "namespace": "company.myteam",
    "flowId": "myflow",
    "flowRevision": 1,
    "state": {
      "current": "CREATED",
      "histories": [
        {
          "state": "CREATED",
          "date": "2024-07-05T14:40:06.228074635Z"
        }
      ],
      "startDate": "2024-07-05T14:40:06.228074635Z",
      "duration": "PT0.114167S"
    },
    "originalId": "74DEZseJ1Oa4ADD508WYJb",
    "deleted": false,
    "metadata": {
      "attemptNumber": 1,
      "originalCreatedDate": "2024-07-05T14:40:06.228286677Z"
    },
    "uiUrl": "http://localhost:8080/ui/executions/company.myteam/myflow/74DEZseJ1Oa4ADD508WYJb"
  }
  ```

#### waitForCompletion: true

Request:
```bash
curl -X POST http://localhost:8080/api/v1/executions/start \
  -H "Content-Type: application/json" \
  -d '{
        "namespace": "company.myteam",
        "flowId": "myflow",
        "waitForCompletion": true
      }'
```

Example Streaming Response:
- Initial response:
  ```json
  {
    "id": "74DEZseJ1Oa4ADD508WYJb",
    "namespace": "company.myteam",
    "flowId": "myflow",
    "flowRevision": 1,
    "state": {
      "current": "CREATED",
      "histories": [
        {
          "state": "CREATED",
          "date": "2024-07-05T14:40:06.228074635Z"
        }
      ],
      "startDate": "2024-07-05T14:40:06.228074635Z",
      "duration": "PT0.114167S"
    },
    "originalId": "74DEZseJ1Oa4ADD508WYJb",
    "deleted": false,
    "metadata": {
      "attemptNumber": 1,
      "originalCreatedDate": "2024-07-05T14:40:06.228286677Z"
    },
    "uiUrl": "http://localhost:8080/ui/executions/company.myteam/myflow/74DEZseJ1Oa4ADD508WYJb"
  }
  ```

- Streamed updates: one JSON returned per state change
  ```json
  {
    "state": {
      "current": "RUNNING",
        ...
    }
  }
  ```

  ```json
  {
    "state": {
      "current": "COMPLETED",
     ...
    }
  }
  ```

---

## Implementation 

- [ ] add a new endpoint `/api/v1/executions/start` 
- [ ] ensure that we parse the request body to extract `namespace`, `flowId`, `inputs`, and `waitForCompletion`
- [ ] implement the initial response with the execution details and UI URL
- [ ] implement streaming (if `waitForCompletion` is `true`)
   - Keep the connection open
   - Periodically check the execution state
   - Stream state updates to the client until the execution completes or fails
   - Close the connection once the execution finishes

## Benefits
This new endpoint will allow users to create an execution from anywhere and take action on the result of it + make it easier to monitor the execution state by returning the UI URL.

**Comment by brian-mulier-p** [comment]
I don't think it's a good idea to be in streaming mode (=SSE) because we already provide such feature with follow endpoint and it's complex to use (it's not a simple http call but an event / message-based API).

This new endpoint should only wait till the flow is completed (success or fail) and reply with the outputs extracted from the flow `outputs` section.

**Comment by anna-geller** [comment]
WIP draft @brian-mulier-p - apparently we already have that endpoint - will update the issue body soon

**Comment by anna-geller** [comment]
misunderstanding on my end, replaced by https://github.com/kestra-io/kestra/issues/4256
