### ISSUE TITLE
Make the Docker image with all plugins the default image

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4275]
## The plan
1. Rename `latest-full` to `latest` so that all plugins are included in the default image displayed at the top in DockerHub
![image](https://github.com/kestra-io/kestra/assets/86264395/c294ea26-2013-4bba-87fc-ef3ba9e40f1b)

2. Rename the current `latest` to `latest-no-plugins` with no plugins included.
3. Adjust the CI/CD and release processes to use `kestra/kestra:develop` instead of `kestra/kestra:develop-full`. Add `kestra/kestra:develop-no-plugins`.
4. Adjust the CI/CD and release processes to use `kestra/kestra:v0.18.0` instead of `kestra/kestra:v0.18.0-full`. Add `kestra/kestra:v0.18.0-no-plugins`

## Impact
- [x] Users who leverage the `latest` image will need to change the image in their deployment before upgrading to `latest-no-plugins` if they prefer to have only their custom plugins. We should make that **Breaking Change** very clear in the Release Notes
- [x] Adjust all Getting Started and Installation docs afterward to use the `kestra/kestra:latest` instead of `kestra/kestra:latest-full`
- [x] Adjust the main GitHub README
- [x] Adjust Helm Charts README and deployment guides
- [x] #4580

**Comment by loicmathieu** [comment]
The same should be done for all tags: develop/develp-full and v0.18.0/v0.18.0-full (and all future version tags).

**Comment by anna-geller** [comment]
extra TODO: let's check if we can then merge or close this PR https://github.com/kestra-io/validate-action/pull/1

**Comment by anna-geller** [comment]
- Docs: https://github.com/kestra-io/docs/commit/a2ca74ce30e42f04b60e49df063d738b77aa82cd
- main README is good as it uses docker compose

**Comment by loicmathieu** [comment]
@Skraye after the release the following PRs needs to be merged:
- https://github.com/kestra-io/helm-charts/pull/47, also publish the new chart
- https://github.com/kestra-io/deploy-action/pull/15
- https://github.com/kestra-io/validate-action/pull/3
- https://github.com/kestra-io/dbt-example/pull/1

I'll add more to the list if I saw other repo that needs to be impacted.
