### ISSUE TITLE
Disabled all triggers

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4277]
### Feature description

User requested in Slack, specifically useful when migrating Kestra and wanting to stop all triggers to prevent any new executions happening.

**Comment by anna-geller** [comment]
We have a Kill Switch along with Quotas and Rate Limits as a planned project for the EE: https://github.com/kestra-io/kestra-ee/issues/1310

You can share with that user that he can reach out to David if he needs this feature https://kestra.io/demo
