### ISSUE TITLE
Redesign how we process files between kestra and task runner environment (with respect to the working directory)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4279]
### Feature description

@brian-mulier-p just for tracking 

Copy of notes from @loicmathieu:
* process input files, namespace files, etc, locally using the working directory
 * Upload everything that is in the working directory into the target container (using archive then decompress for example)
 * Execute the task on the remote container
 * Download everything that is in the remote container working directory

**Comment by brian-mulier-p** [comment]
Done in https://github.com/kestra-io/kestra/commit/f35c9790b63a94272a5bb3b65c7bb64ebed04628 + https://github.com/kestra-io/plugin-aws/commit/5fc3c2eb2d0fd6c98861e129760a5ba2cf07033a + https://github.com/kestra-io/plugin-azure/commit/6dca044f244f6848e5a88cc3ec3fc93ad4255cfb + https://github.com/kestra-io/plugin-gcp/commit/ed1c3fa0167621f84357c5eb97540e49b466a92a
