### ISSUE TITLE
Add an option to select\delete all executions

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4297]
### Feature description

If you have a lot of executions (several hundreds) it is quite tiresome to select them via checkboxes and delete page-by-page.
Consider an option to select all items (i.e. on all pages) at once

**Comment by yuri1969** [comment]
IIRC the flow is:
1. Filter the Executions you want to delete
2. Check the select box selecting a whole page
3. Enable the _Select All_ button
4. Hit the _Delete_ button

![image](https://github.com/kestra-io/kestra/assets/13468636/4281ec30-fb6f-40c1-8011-105fd3edbc8d)

**Comment by aku** [comment]
@yuri1969 nice! I had automatic page refresh turned on so the button has disappeared before I ever noticed it. 
<img width="113" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/98434a2c-f34f-4816-9c69-def0cca7d51b">

Maybe you can fix this annoyance in UI cause in order to use this button you need te be pretty quick or disable periodic refresh

**Comment by aku** [comment]
Desired functionality is already implemented as pointed by Yuri
