### ISSUE TITLE
Extend TemplatedTask to Trigger

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#4302]
### Feature description

The TemplatedTask doesn't work for triggers

<img width="1189" alt="Screenshot 2024-07-10 at 16 11 52" src="https://github.com/kestra-io/kestra/assets/46634684/6f50da5e-cb93-40ef-acbf-66cc17338084">

https://kestra.io/plugins/core/tasks/templating/io.kestra.plugin.core.templating.templatedtask

**Comment by loicmathieu** [comment]
What you want is a TemplatedTrigger, or maybe even a TemplatedPollingTrigger and TemplatedRealtimeTrigger.
As the TemplatedTask would never allow to create a trigger, it is executed by the Worker as a runnable task.
I'm closing this one as it's impossible, please open a feature request for trigger with an example of what you want to achieve.
