### ISSUE TITLE
Broken link in md file

### ISSUE THREAD

**Issue by surajvm1** [kestra-io/kestra#4330]
### Issue description

Issue: The text `Kestra Code of Conduct` in the file: [CONTRIBUTING.md](https://github.com/kestra-io/kestra/blob/develop/.github/CONTRIBUTING.md) has broken hyperlink. 
Can I raise a PR and correct this?

**Comment by loicmathieu** [comment]
Thanks for the information, and of course, you can provide a PR, PRs are always welcomed ;)

**Comment by surajvm1** [comment]
Thank you @loicmathieu. Raised PR: https://github.com/kestra-io/kestra/pull/4332
