### ISSUE TITLE
Edit and Delete options not visible for KV Store

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4361]
### Describe the issue

When I go to the KV Store, I am unable to edit or delete `test`.

![Screenshot 2024-07-18 at 17 41 34](https://github.com/user-attachments/assets/651a28af-3cf1-48ee-abdd-f1d53cc4e4c6)

Expecting an option like the guide has: https://raw.githubusercontent.com/kestra-io/docs/ad65a2b93c5c83c1ed0143de55bd75b63a7f12d5/public/docs/concepts/kv-store/edit_delete_kv_pair.png

### Environment

- Kestra Version: 0.18 Snapshot OSS (pulled at the time of this issue)
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Closed by https://github.com/kestra-io/kestra/pull/4368
