### ISSUE TITLE
Selected namespace page shows information for all namespaces

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4364]
### Describe the issue

When going to **Namespaces** and then selecting a namespace of your choice, it shows you information for all of the namespaces, rather than the one selected.

While it has an option to change namespaces, it should be removed as this is just replicating the functionality of the **Dashboard** tab. This should only show information for the namespace selected originally so all the tabs (like Editor and Flows etc) are consistent.

![Screenshot 2024-07-19 at 12 20 06](https://github.com/user-attachments/assets/bbd28979-1789-4cae-bc67-4400e30b4fe1)

### Environment

- Kestra Version: 0.18 Snapshot
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Closed by https://github.com/kestra-io/kestra/pull/4368
