### ISSUE TITLE
KV Store pairs displaying for all namespaces

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4365]
### Describe the issue

I created a new KV pair under the namespace `key_value_store` and it shows up under all other namespaces too.

`key_value_store`:
![Screenshot 2024-07-19 at 12 22 48](https://github.com/user-attachments/assets/9924b650-1973-4918-ba5e-5a083ce2f123)

`company.team`:
![Screenshot 2024-07-19 at 12 23 04](https://github.com/user-attachments/assets/07533b85-6c6d-4ff6-8678-3145fa65a9c5)

`demo`:
![Screenshot 2024-07-19 at 12 23 17](https://github.com/user-attachments/assets/a6a242b6-3bde-4229-8a28-3e61c5ebcc29)

### Environment

- Kestra Version: 0.18 Snapshot
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Closed by https://github.com/kestra-io/kestra/pull/4368
