### ISSUE TITLE
Replace task index with the task ID in the deprecation warnings and error messages

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4394]
### Describe the issue

![image](https://github.com/user-attachments/assets/fe2e5eba-f675-4aed-93e3-e99de33db705)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by SakethkumarBadike** [comment]
Hello ! May i work on this?

**Comment by MilosPaunovic** [comment]
@SakethkumarBadike Go for it! 🚀

**Comment by SakethkumarBadike** [comment]
Could anyone please clear my doubt. Iam a complete beginner to contribution.

Do i need to set up locally to identify the issue or any alternatives?

I got stuck while seeting the project locally . I need help.

**Comment by MilosPaunovic** [comment]
You can use this guide as the initial point:
https://kestra.io/docs/getting-started/contributing#setup-to-work-without-building-the-backend-from-the-source-code

**Comment by SakethkumarBadike** [comment]
![image](https://github.com/user-attachments/assets/8e5e51cc-5b09-4a5c-8786-83a21487675f)
how to recreate the problem?

**Comment by MilosPaunovic** [comment]
Use this flow as an example and you'll get the warning box at the top, like in the image description of this issue.

```
id: testing
namespace: github

tasks:
  - id: template
    type: io.kestra.plugin.core.flow.Template
```

**Comment by SakethkumarBadike** [comment]
![image](https://github.com/user-attachments/assets/6f8561e5-9890-4bda-8f05-71d6a7ee21a6)
is it ok now?
shall i create a pull request?

**Comment by MilosPaunovic** [comment]
It is not good.

Image at the description of this issue states what needs to be done as part of it.
![image](https://github.com/user-attachments/assets/68cb5a6f-f782-4611-92ad-d073d4a3c7b1)

**Comment by SakethkumarBadike** [comment]
Iam making changes in FlowValidateCommand.java . Can you confirm if this is the correct file? After doing changes they are not reflecting on ui . Should do any thing after doing changes? ( Sorry for lot of questions )

**Comment by MilosPaunovic** [comment]
Maybe @Skraye can confirm you that?

**Comment by Skraye** [comment]
We needed to modify the constraint to have a custom message that use our taskid

**Comment by MilosPaunovic** [comment]
Hey @SakethkumarBadike, as this turned out to be rather tricky issue and after some discussions we figured out it needed handling mostly on the `Java` side of project, @Skraye will take over.

I appreciate your efforts on this and would like to encourage you to take another look at the[ list of our opened issues ](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=label%3A%22good+first+issue%22)filtered for new contributors and try and take your pick at something that might seem interesting. 🚀
