### ISSUE TITLE
Replace Deprecated annotation with a friendlier message 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4395]
### Issue description

![image](https://github.com/user-attachments/assets/45b58ae6-2985-460c-8d33-58a851f288ad)

Extend the annotation with sth like: "This feature is deprecated and will be removed in the future. We encourage you to migrate to the new plugin, but you can still use the deprecated version."

**Comment by loicmathieu** [comment]
This is what it looks like now for a deprecated task (where we don't know in the code the replacement as it's in the description)
![image](https://github.com/user-attachments/assets/6bbea80c-9156-4501-a9d8-a20108c690a2)

This is what it looks like for alias where we know a replacement:
![image](https://github.com/user-attachments/assets/3e5ed689-ba43-41cd-94a9-54a96be78ef2)
