### ISSUE TITLE
Rename "Render Expression" button in Outputs Tab

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#4396]
### Feature description

The Render Expression button in the Outputs tab is very useful to debug Pebble syntax. However it's not very explicit in naming.
Some ideas:
- Debug Pebble
- Render Pebble
- Pebble Debugger
- Outputs Syntax Debugs

**Comment by anna-geller** [comment]
we can't use the word Pebble as it's not as well known as when you say "Jinja" :) 

at first we'll try to make it more explicit that it's for Outputs in the new nested output UI where the expression is prefilled and you can edit and re-render some expressions with the large Render button. ofc if afterward it's still not clear that it's for rendering outputs, let's revisit then after https://github.com/kestra-io/kestra/issues/1528

![image](https://github.com/user-attachments/assets/f8c82391-6a83-4d44-a894-745622123da7)

**Comment by wrussell1999** [comment]
Thoughts on simply naming the button "Debug Outputs" with a hover pop up that says you can put any expression in here to debug. I know you can do any expression with it, but that wasn't obvious to me as a user. Instead a debug expression button could also be added to the overview page maybe?

**Comment by anna-geller** [comment]
Debug Outputs sounds great! I'll make the change in the UI. The challenge to you @wrussell1999 will be to update it in the docs — can you manage before vacation? if not, let's open an issue to adjust docs (we'll likely need to adjust many Output-related docs pages for the new outputs anyways)

**Comment by wrussell1999** [comment]
yup I can sort this out before the end of the week 🚀

**Comment by anna-geller** [comment]
I wonder even about Debug Execution or Debug Context as in the end you can even retrieve {{ execution }}

for now I changed to:

```json
      "title": "Debug Outputs",
      "tooltip": "Render any Pebble expression and inspect the Execution context."
```

**Comment by wrussell1999** [comment]
Yeah that's the challenge, it does a lot of things! I think having a separate debug button on the overview page could solve this too. Both do the same thing but clearer where to find them!

**Comment by anna-geller** [comment]
I see Will updated docs, so we're good now https://github.com/kestra-io/docs/commit/56c57436fd11b3c6364e4439ca88eda430abb798
