### ISSUE TITLE
New flow won't render topology until saved

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4404]
### Describe the issue

When creating a new flow, it shows the topology view with the error: `An issue occurred while generating the graph which prevents the topology to be displayed.` It goes away once you press save.

![Screenshot 2024-07-23 at 16 11 20](https://github.com/user-attachments/assets/6e15498d-99a6-4f9c-8c26-4330722b64bd)

Also for blueprints: After clicking **Use** on a blueprint, the editor page opens before the flow has been saved with the same error.
![Screenshot 2024-07-23 at 16 09 30](https://github.com/user-attachments/assets/fbda6eb1-456f-41b3-90f1-fe1d643df561)

### Environment

- Kestra Version: 0.18 Snapshot
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
can you still reproduce @wrussell1999? I can't reproduce anymore on preview

![image](https://github.com/user-attachments/assets/0f8aaaea-b151-4e21-a2d8-587969bb9068)

if not, you can close
