### ISSUE TITLE
Docker Compose stuck and Pulling Container

### ISSUE THREAD

**Issue by g33kroid** [kestra-io/kestra#4449]
### Describe the issue

I am new to Kestra I followed the guide downloaded the docker-compose file, and did
```
docker compose up -d
```
And it has been stuck in this step for hours till I killed the process. 
![image](https://github.com/user-attachments/assets/d591f274-39eb-4334-906c-eeb6e3d5417d)

I tried to pull the image alone and the same thing happens 

![image](https://github.com/user-attachments/assets/d50d5bb5-8944-4646-a270-5d6d3c989eb0)

### Environment

- Kestra Version: Latest
- Operating System (OS/Docker/Kubernetes): Ubuntu 22.04 Desktop
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
hmm I couldn't reproduce, can you restart your Docker service and try again? 

it could also be an issue with your network

alternatively, you can try our development image: `kestra/kestra:develop`
