### ISSUE TITLE
Rename the new JSON and ION expressions to less technical names (decode and encode can be confusing)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4451]
### Feature description

I think we've made a mistake here https://github.com/kestra-io/kestra/pull/4289 with the naming `jsonEncode` + `jsonDecode` + `ionEncode` and `ionDecode` - they seem too technical. (@loicmathieu you didn't do anything wrong by following the issue, mistake on my end with the too-technical naming)

Let's rename them to friendlier names before the release.

I think it's worth renaming as follows: 
1. jsonEncode  --> `toJson` =  Serializes a data structure into a JSON string
2. jsonDecode --> `fromJson` = Deserializes a JSON string into a data structure
3. ionEncode --> `toIon` = Serializes a data structure into an ION string
4. ionDecode --> `fromIon` = Deserializes an ION string into a data structure

pseudo-code:
```Python
json_string = toJson(data)
data = fromJson(json_string) 
```

pebble:
```yaml
{{ [1, 2, 3] | toJson  }} # "[1,2,3]"
{{ fromJson( '{"name": "kestra", "year": 2024}' ).name }} # kestra
```

After we rename, I'll update the Breaking Changes notes

**Comment by loicmathieu** [comment]
We don't have ionEncode filter, it was not listed in the original issue: https://github.com/kestra-io/kestra/issues/3715
@anna-geller Should I add it ?

**Comment by anna-geller** [comment]
yes, let's add it for consistency 👍
