### ISSUE TITLE
Add "display name" field for inputs

### ISSUE THREAD

**Issue by KrisF-Midnight** [kestra-io/kestra#4470]
### Feature description

Currently for input fields only the ID is shown as title when you execute the flow from the UI.
It'd be nice to have a separate field dedicated just for the title itself. 
If no title is set in the flow, then kestra could default to showing the id.

**Comment by anna-geller** [comment]
That's a very reasonable idea! We'll take it as a feature request and until it'S released, you can use the `description` field that will likely help a bit

**Comment by anna-geller** [comment]
@fhussonnois given you're currently working on inputs, could you tackle this one too? would be great to get it in 0.19 as planned
