### ISSUE TITLE
[Regression] Too many spaces added before list elements in inputs, tasks, triggers when using Autocompletion in the Editor

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4472]
### Describe the issue

Too many spaces added https://share.descript.com/view/P2OtmaGKnxJ

opening just to be sure -- might be a transient issue so if you can't reproduce @MilosPaunovic, close directly

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Tested on both previews, OSS and EE, and it behaves properly on the latest, `18.x` version, so closing this for now. We'll re-open if necessary.
