### ISSUE TITLE
Cannot change editor views for new flows

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4486]
### Describe the issue

1) Go to the Flows tab.
2) Click "Create" to create a new flow.
3) Cannot switch UI tabs in the editor, it shows the error message : "Only available on Flow tab"
<img width="941" alt="image" src="https://github.com/user-attachments/assets/76c595f3-53f0-4d22-8886-2420d6a0d2fb">

Cannot access blueprints tab either. 

### Environment

- Kestra Version: 0.17.16
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by anna-geller** [comment]
Hi John, can you check again on the latest version? I can no longer reproduce on `latest` (Kestra 0.18.2)

**Comment by johnkm516** [comment]
Hi @anna-geller,
This issue was fixed in 0.18. 

Closing.
