### ISSUE TITLE
Cannot "Use" custom blueprints

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4487]
### Describe the issue

1) Create any custom blueprint flow.
2) Save the blueprint.
3) Go to the "Custom Blueprints" tab in blueprints, and then click "Use" on the custom blueprint.
4) You get an internal server error 
<img width="773" alt="image" src="https://github.com/user-attachments/assets/016520ae-6b71-49bc-8fa6-8e220eee7cb3">

### Environment

- Kestra Version: 0.17.16
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by anna-geller** [comment]
We were able to reproduce this issue and we're working on a solution
