### ISSUE TITLE
Namespaces Jpeg file are corrupt upon export

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4489]
### Describe the issue

Step 1: Import a Jpg file in namespace Editor
Step 2: Export namespace files 
Step 3: Extract zip file and open image

Expecte: to open file
Actual: jpeg file corupted

### Environment

- Kestra Version: 1.8
- Operating System (Docker):
- Java Version ( Docker):

**Comment by loicmathieu** [comment]
Fixed by https://github.com/kestra-io/kestra/pull/5114
