### ISSUE TITLE
Namespace Editor returns internal server error when importing a file with a space in its name

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4491]
### Describe the issue

Prepare any file with space in naming example: "example test" 
Step 1: Import a file in Namespaces editor

Expected: Successfully imported
Actual result: Internal server error
Internal server error: Failed to convert argument [path] for value [/kestra trigers 2] due to: Illegal character in path at index 7: /kestra trigers 2

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Skraye** [comment]
Issue was duplicated, fixed in the 0.19
