### ISSUE TITLE
Debug Outputs return 401 Unauthorized

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4508]
### Describe the issue

1) Login as Superadmin.
2) Run any flow.
3) Go to the outputs tab.
4) Modify the pebble template to anything else.
5) Click "Debug Outputs:"
6) Kestra returns `401 Unauthorized` despite user being Superadmin

Response body : 

```
{
    "message": "Unauthorized",
    "logref": null,
    "path": null,
    "_links": {
        "self": {
            "href": "/api/v1/executions/6xvWcNZVXfl5j5F9vFVlTd/eval/5yReUyiK36OVi9jiXZhO9z",
            "templated": false,
            "profile": null,
            "deprecation": null,
            "title": null,
            "hreflang": null,
            "type": null,
            "name": null
        }
    },
    "_embedded": {}
}
```

### Environment

- Kestra Version: 0.18-SNAPSHOT
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by smunteankestra** [comment]
Hello, not reproducing, other issue opened https://github.com/kestra-io/kestra/issues/4550

**Comment by Ben8t** [comment]
cc https://github.com/kestra-io/kestra-ee/issues/1471
