### ISSUE TITLE
[Plugins] List of plugin not passing CI

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#4558]
### Describe the issue

- [x] MongoDB: [Link to CI](https://github.com/kestra-io/plugin-mongodb/actions/runs/10247839259/job/28347843150)
- [x]  ElasticSearch: [Link to CI](https://github.com/kestra-io/plugin-elasticsearch/actions/runs/10247824424/job/28347796996)
- [x] Azure: [Link to CI](https://github.com/kestra-io/plugin-azure/actions/runs/10247816711)
- [x] Singer: [Link to CI](https://github.com/kestra-io/plugin-singer/actions/runs/10247847906/job/28348699415).
- [x] Docker: [Link to CI](https://github.com/kestra-io/plugin-docker/actions/runs/10247823935/job/28347795636)
- [x] Solace: [Link to CI](https://github.com/kestra-io/plugin-solace/actions/runs/10247848979)
- [x] DBT: [Link to CI](https://github.com/kestra-io/plugin-dbt/actions/runs/10247823258)
- [x] Scripts: [Link to CI](https://github.com/kestra-io/plugin-scripts/actions/runs/10248215082/job/28349008028)
- [x] JDBC: [Link to CI](https://github.com/kestra-io/plugin-jdbc/actions/runs/10248033872/job/28348929987)

### Environment

- Kestra Version: 0.18.0-SNAPSHOT

**Comment by loicmathieu** [comment]
Notion is not a real plugin so we don't care, @Skraye you can remove it from your list
