### ISSUE TITLE
Raise a warning in the UI if the flow ID is too long (more than 250 characters)

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4560]
### Describe the issue

Create a new flow with a lot of characters (more than 250)
![image](https://github.com/user-attachments/assets/93ea04a5-3adb-412c-83f7-059409a0ef77)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
a fun one! thx for adding this

**Comment by loicmathieu** [comment]
We restict flowId, triggerId, namespace, ... and a bunch of other fields to 250 chars in the JDBC runner (not in the Kafka one) but didn't add any size limit.
We definilty should add those limits in the backend, it's a simple validation annotation to add.
