### ISSUE TITLE
Build all plugins periodically

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#4562]
### Issue description

We had issue with libraries dependency from the platform that breaks some plugins.
And issues with plugin no more compiling due to changes on Kestra core.
Those issues was discovered late as plugins was not build periodically.

We should add daily or weekly CI schedule workflow on all plugin repositories to catch those issues earlier.

**Comment by loicmathieu** [comment]
Use `--refresh-dependencies` Gradle option to be sure that dependencies are refreshed (snapshot, version range, ...)

**Comment by Skraye** [comment]
Done with https://github.com/kestra-io/plugin-amqp/commit/327f1adfc96314e2448a4beffdee67f3e6c1e9dd
Added to every plugin CI, with also a slack channel dedicated to it so we're aware of a failing CI on master/main branches
