### ISSUE TITLE
Critical 'unkillable' bugs message - jackson.databind.JsonMappingException due to large input sent as trigger variables 

### ISSUE THREAD

**Issue by nikita-stovpak** [kestra-io/kestra#4566]
### Describe the issue

If a large body error is triggered, it blocks the execution tab and doesn't close. In the video, please check that I am trying to delete the execution, and it doesn't get deleted.
https://monosnap.com/file/lX71sIgan18nFX9p1OhXJP4mGaSon8

Code: unnecessary

### Environment

- [Kestra Version:](image: kestra/kestra:latest-full)
- [Operating System]: (docker-compose)

![image](https://github.com/user-attachments/assets/d18602ae-6404-4eec-864f-b629ee9f6101)

**Comment by anna-geller** [comment]
Big thanks for reporting the issue. You spotted an important bug we haven't handled yet. We opened an issue that you can follow along here #4638. 

In the meantime, I recommend to:
1. Use FILE type input with JSON file for large inputs https://kestra.io/docs/workflow-components/execution#execute-a-flow-with-file-type-inputs
2. Delete the executions that generate the error (they shouldn't have been created in the first place, this is a bug)

Again, thanks for reporting this and let @paulgrainger85 know via Slack if you need more info on this
