### ISSUE TITLE
Changes are not reflected in the UI when saving them in the 'topology' tab.

### ISSUE THREAD

**Issue by nikita-stovpak** [kestra-io/kestra#4568]
### Describe the issue

When I make changes in the source and topology, everything works fine:
https://monosnap.com/file/AdmfHEKlYiJ3uOBTNsMcOYvwFeEZeI

When I make changes in the topology, the changes are not reflected:
https://monosnap.com/file/4rBpqfFLKJAZ0cxgweVRaBTfWteGzs

### Environment

- [Kestra Version:](image: kestra/kestra:latest-full)

**Comment by MilosPaunovic** [comment]
This is now fixed and just merged to develop. Could you test it to confirm, and, if alright, close the issue @smunteankestra?

**Comment by MilosPaunovic** [comment]
Relates to this issue https://github.com/kestra-io/kestra/commit/c184aa104d7e969876923ff32d4559dba5464f72.

**Comment by anna-geller** [comment]
confirmed, this is now fixed https://share.descript.com/view/hrNq9T3XiPS 

also purely from topology https://share.descript.com/view/gjK1U589Nli
