### ISSUE TITLE
Top navigation on the editor don't follow the themes

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4569]
See on the christian video: 
![image](https://github.com/user-attachments/assets/851203d2-8f86-4307-b2f7-4bcb6e7b705f)
the top navigation is dark grey and not bluish like the background off the editor

**Comment by MilosPaunovic** [comment]
If you mean the top 5 lines of code, starting from `tasks` and ending with `inputs`, that is what's called `Sticky Scroll` functionality of the `Monaco Editor` we're using, see https://learn.microsoft.com/en-us/visualstudio/ide/editor-sticky-scroll?view=vs-2022 for more details.

The same behaviour is default in `VSCode`, it's something users are used to, so, in my opinion, we should either keep it like this, with the default colour highlighting provided by editor or disable that functionality as a whole - meaning, it will be very confusing if we leave the functionality in but don't highlight that segment of code with different colour/shadow.

WDYT @tchiotludo?

**Comment by tchiotludo** [comment]
Yes I know for the sticky feature.
Just in vscode, the background color from the sticky section is the same one than the editor. 
This dark background for the sticky part is not really visually clean


![image](https://github.com/user-attachments/assets/92d8453b-f774-492e-9d6b-919c6859f8c8)
