### ISSUE TITLE
[Bugfix] Remove the confusing notification to switch to 0.19.0 Snapshot

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4583]
### Describe the issue

![image](https://github.com/user-attachments/assets/7776b958-e73a-446a-a195-80fb67942ee0)

**Comment by smunteankestra** [comment]
hey @anna-geller , could you please specify the version of kestra, don't see the issue on latest/develop

**Comment by anna-geller** [comment]
it's still there on kestra/kestra:latest

![image](https://github.com/user-attachments/assets/b5945217-d6ab-43ff-a36b-94c1cdad13a9)

**Comment by loicmathieu** [comment]
It's now OK since 0.18.1
