### ISSUE TITLE
No Dependencies, display a proper page

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4586]
When the flow don't have any dependencies, we are displaying this: 
![image](https://github.com/user-attachments/assets/161e275c-df7c-41cb-a14f-7f0fefd54dbc)

Replace this by removing the graph and display a proper page, something similar to: 
![image](https://github.com/user-attachments/assets/550d95a7-0821-4e16-9537-2490e29b671b)
- no button 
- a message: "Your flow don't have any dependencies"
- an image not afraying

**Comment by mounikaperi** [comment]
@MilosPaunovic @tchiotludo 
I would like to contribute to this issue.
If no-one has started on this yet, Please do assign it to me

**Comment by MilosPaunovic** [comment]
Could you create the page where the image is shown on the center and some text right below it, and @Nico-Kestra will provide here the artwork and the text itself, but Nico, please export and attach image files, as @mounikaperi is our external contributor and don't have access to Figma.

**Comment by mounikaperi** [comment]
sure @MilosPaunovic will do
@Nico-Kestra - Please share me the artwork and the text that has to be displayed

**Comment by MilosPaunovic** [comment]
You can use any sample image and text for the first draft and then changed when proper ones provided.

**Comment by Nico-Kestra** [comment]
<img width="1920" alt="Flow-Dependencies" src="https://github.com/user-attachments/assets/30442e71-5444-445c-982a-65b501b67f7d">

<img width="1920" alt="Flow-Dependencies2" src="https://github.com/user-attachments/assets/d08f73e6-c641-429b-b53a-0a04f5a249d3">


[Figma](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3247-28310&t=s2Puii3GFelr5mtm-1)

**Comment by Nico-Kestra** [comment]
You can use this svg:
![Empty_Dependencies](https://github.com/user-attachments/assets/9e3b7f42-acf9-42d9-afbe-14189ca91233)

**Comment by Nico-Kestra** [comment]
Light mode:
![Dependencies_Light_mode](https://github.com/user-attachments/assets/f10029f0-5cfd-4f9e-b1b1-06696a6c9497)

Dark mode:
![Dependencies_Dark_mode](https://github.com/user-attachments/assets/3680d952-ad49-4fda-8a0c-3213532cdc09)

**Comment by mounikaperi** [comment]
@MilosPaunovic @Nico-Kestra 
can you please provide me the link to the dependencies documentation
I see the above image has hyperlink to documentation of kestra dependencies
which when clicked by the user lands to the documentation page

**Comment by MilosPaunovic** [comment]
Maybe @Ben8t is the one to best provide the link reference/or to amend the text.

**Comment by mounikaperi** [comment]
@Ben8t can you please provide me the link to the documentation of flow dependencies?
@MilosPaunovic @Nico-Kestra - The above images that are shared do not download either as jpg or png formats. I am assuming I will have to place both the images in ui/images folder and refer to them in my vue component. Can you please share the jpg/png format image files

**Comment by MilosPaunovic** [comment]
Those are SVGs. You can save them from here (right click on image, save as) and import them like SVGs to the component.

**Comment by Ben8t** [comment]
@mounikaperi here it is https://kestra.io/docs/ui/flows#dependencies

**Comment by mounikaperi** [comment]
@MilosPaunovic 
Please review https://github.com/kestra-io/kestra/pull/5340
Attached smoke test results as well

**Comment by MilosPaunovic** [comment]
Great job @mounikaperi, keep up the good work! 🚀

**Comment by mounikaperi** [comment]
Thank you @MilosPaunovic
