### ISSUE TITLE
blueprintId=245 has Pull policy wrongly added

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4606]
### Describe the issue

[Run a Python script inside of a Kubernetes pod](http://localhost:8080/ui/blueprints/community/245)
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/ec727d47-3904-4573-87af-4721b6dc4b23">

Expected:   pullPolicy: ALWAYS
Actual:   pullPolicy: Always

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
well spotted, thanks! 

it's fixed https://kestra.io/blueprints/python/245-run-a-python-script-in-a-kubernetes-pod
