### ISSUE TITLE
Improve visibility of NamespaceFiles button

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#4607]
### Feature description

One user reported that the NamespaceFiles button in the UI is not visible enough; too small
Would it possible to make it a bit more explicit ?

![image](https://github.com/user-attachments/assets/e8a309c6-8656-456b-aab7-155bb053bf10)

**Comment by anna-geller** [comment]
done recently

**Comment by MilosPaunovic** [comment]
Adding link to the issue that fixed this one for tracking purposes https://github.com/kestra-io/kestra/issues/5355.
