### ISSUE TITLE
Flows > Executions > Select All > Restart with a filter on date don't filter

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4617]
In Execution of a flows, if you are 
- filtering on status + start / end Date 
- Select all 
- click on Restart 

It will restart all executions without the filter by date. 
To control on all the endpoint for select all, not the first time I report this issue

**Comment by MilosPaunovic** [comment]
Is this still valid @tchiotludo, as I can not reproduce it (or I am trying something that was not the initial idea here)?

**Comment by Ben8t** [comment]
I'm not able to reproduce either  🤔 @tchiotludo can you details a bit more your procedure ?
On my side I tried with:
- Flow > "select one flow" > Executions > filter absolute date > select all > "restart (or same with replay)"
but everything seems to work herer

**Comment by tchiotludo** [comment]
You could try in a multiple page way, using the select all. 
I'm my memories, the bug was on multiple page, I select all for a current Date and the filter by date was not sent. 
If you are not able to reproduce, let's close it
