### ISSUE TITLE
PluginClassLoader does't provide 'true' ClassLoadingIsolation (child-first strategy is not respected)

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#4621]
### Describe the issue

Currently, if a user create a custom a plugin and use a library already included/used by Kestra core, the library will always be loaded from the App ClassLoader and not the PluginClassLoader. Unfortunately, the version expected by the plugin and the one supplied with Kestra may not be compatible.

For example, with a plugin including the `Gson` library: 

![current-classloader](https://github.com/user-attachments/assets/7c64448d-5b21-4604-8243-34c4417be990)

For security reasons, we frequently update all our dependencies, which may not be the case for our user. Updating one of our libraries may break a user's custom plugin.

However, Child-First Strategy can cause error when classes from common libraries are expected to interact with classes loaded by the parent class loader (i.e., slf4j, Jackson, etc). Hence common libraries should always be loaded from the App classloader to avoid `java.lang.LinkageError: loader constraint violation.` exception.

### Environment

- Kestra Version: 0.18.0
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
is there any urgency here? without any details, moved for now to 0.25 aka cooldown
