### ISSUE TITLE
Better handling of large execution contexts

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4631]
### Feature description

My company is currently working with a development partner for an internal ERP project. I have showcased and done training sessions with 90+ developers to onboard them on using Kestra for batch jobs / integration purposes. While I am fully familiar with the product, the people who I onboarded are not, and despite explaining to them the importance of minimizing data in the execution context, I believe Kestra should handle large execution contexts without crashing, rather than leaving it up to the developer to not accidentally store large execution contexts. 

I am creating this issue more as a general Epic, as this encompasses a lot of different features both on backend and frontend, and there is a lot that could be discussed on how to handle large execution contexts. 

The general issue with how Kestra currently handles large execution contexts is that 
both the webserver and executor will generally crash, and the DB state will block the executor from executing new tasks because of the large execution context stuck in the task queue. 

**Some things that I see could be improved in the webserver :** 

- The triggers column in the Executions tab will cause the Executions tab to completely freeze up and crash the webserver, if you use something like an SQL trigger and the trigger has a lot of rows / columns. Even if you only get top 100 rows, if all the executions are SQL triggers it'll try to load all the executions * trigger data, which will cause the Executions tab to load for a long time and / or crash the webserver. This can be worked around by triggering the flow by taking only the top 1 row with the relevant WHERE clause and then querying the data in the flow straight after, but the trigger popup in the Executions tab should still limit how much data is queried and shown (only show the top 15 fields as a preview). The below image is just showing which part of the UI I'm talking about, if I had an SQL with 10000 fields the Executions tab would attempt to load all of it for each execution. 
<img width="757" alt="image" src="https://github.com/user-attachments/assets/d63f7b86-f502-4068-a713-6b9f72d53377">

- Inputs in the Overview tab of the Flow execution should be paged, if there's a lot of input data the Overview tab will take a long time to load and / or crash the webserver. 

**Things that could be improved on the backend :** 

- Even while keeping in mind that I should minimize execution contexts, during development while testing I could make a mistake. For example, I could have an SQL Query task and query 200,000 rows and load that into the execution context by accident (without using the store attribute), which will most likely crash the executor and even create a crash loop as the executor will repeatedly try to load 200,000 rows into the execution context and keep crashing. 
       
Some possible solutions might be to add a configuration field either during deployment or on the admin page to add a max size limit (in bytes) of the execution context, so that the admin can configure the limit as allowed by the amount of java heap space that was provided during deployment. The executor could first verify the size of the execution context before attempting to load the data (I don't even know if this is possible, please just take this as a possible suggestion). If the size of the execution context exceeds that set by the administrator, the executor could signal the task to fail with an error message (I don't know if this is possible either). 

Regardless of how a solution could be implemented, the executor should handle cases with large execution contexts without crashing. My biggest worry is that a developer could not follow the best practices in creating a flow, accidentally or otherwise, and crash the deployment, which could be a huge deal in production.

**Comment by anna-geller** [comment]
Hi John, perhaps worth having a call with @paulgrainger85 to go over these (feel free to add me to the invite)? I think a lot of those issues are a matter of flow design. Examples:
1. For JDBC Triggers, you have to use `store: true` if you pass large data. If you want some users to not have to worry about that, you can configure that in pluginDefaults for a given namespace with `forced: true` to ensure that data from the JDBC trigger is always passed to the Execution as an internal storage file. Regarding UI display, we didn't manage to implement it in 0.18 yet, but Trigger outputs data will have the same columnar display in the future as the current Outputs tab https://github.com/kestra-io/kestra/issues/4643
2. For inputs, we generally display a preview on hover + full inputs in the Overview page, nothing should crash there, if you see an issue can you open it case-by-case for each issue? (it's OK to create many issues 👍  easier for us to tackle small but specific issues than generic requests where we may not know exactly what's the problem or how to reproduce)
3.  @loicmathieu can you estimate whether this request is feasible? _"add a configuration field allowing to set a max size limit (in bytes) of the execution context, if exceeded, fail the execution"_  -- Loic, feel free to add any suggestions for what other guardrails we can consider to reduce the risk of Executor crashing due to too large execution context

**Comment by loicmathieu** [comment]
For 3, we have a mechanism to persist large execution contexts automatically inside the internal storage in the Enterprise Edition when using Kafka/Elasticsearch.

We can however add a limit and fail if it goes above it, but by default, we would not enforce such limit as there is no good limit, it is highly use case dependent.

> the executor should handle cases with large execution contexts without crashing

The executor should never crash. Otherwise, it's a bug.
If you have a case where the executor crashes, please open an issue with a reproducer.

> large execution context stuck in the task queue

For this, you can skip the execution, see https://kestra.io/docs/administrator-guide/troubleshooting#unprocessable-execution

**Comment by johnkm516** [comment]
Hi @anna-geller 

I created a separate issue for the Executions page #4644, I see that you created a separate issue for the overview page so I won't create another one.

I know that having a large execution context to begin with is a flow design issue. The issue is that while I know it, not all the developers who are new to the solution understand it, and I believe that there should be some sort of safeguard that throws an error in the flow if an execution context becomes too large. Now I know that "too large" could be not very simple to calculate considering how much metadata there is for each field. A single field with a very large JSON string probably will not be as bad as 5000 fields mapped in the execution context. 

> For 3, we have a mechanism to persist large execution contexts automatically inside the internal storage in the Enterprise Edition when using Kafka/Elasticsearch.

@loicmathieu  
This is exactly the kind of safeguard that I am talking about, but for the JDBC architecture. 

The issues are very easy to reproduce. On a JDBC architecture deployment purposely set a low amount of memory like ```-Xms512m -Xmx512m``` to make it easier to make the executor run out of memory, then query a relatively large amount of data and then attempt to do a EachParallel on each row with a Subflow task like this : 

```
id: test_SQL
namespace: erp.sample
tasks:
  - id: query
    type: io.kestra.plugin.jdbc.sqlserver.Query
    fetch: true
    fetchSize: 100
    logLevel: WARN
    password: "{{ secret('db.erp.password') }}"
    sql: |-
      WITH CompCodes AS (
          SELECT DTL_CD AS COMP_CD
          FROM CM_CD_D
          WHERE CM_CD = 'COMP_CD'
            AND RMRK7 = 'Y'
      )

      -- Main query to select shop info
      SELECT 
          SH.COMP_CD, 
          SH.SHOP_CD, 
          CONVERT(NVARCHAR(8), GETDATE(), 112) AS TGT_DT
      FROM 
          SA_SHOP_INFO_M SH
      JOIN 
          CompCodes CC ON SH.COMP_CD = CC.COMP_CD
      WHERE 
          SH.DLY_DDLN_YN = 'Y'
          AND SH.SHOP_CD NOT IN (
              SELECT SPB.SETL_DTL_TP_CD
              FROM SA_SLP_PRCS_BASE_M SPB
              WHERE SPB.COMP_CD = SH.COMP_CD 
                AND SPB.SETL_TP_CD = 'SD62'
          )
    url: "{{ secret('db.erp.jdbc_uri') }}"
    username: "{{ secret('db.erp.username') }}"
  - id: parallel
    type: io.kestra.plugin.core.flow.EachParallel

    workerGroup:
      key: WORKER_GROUP
    tasks:
      - id: InvokeWorker
        type: io.kestra.plugin.core.flow.Subflow
        retry:
          maxAttempt: 5
          behavior: RETRY_FAILED_TASK
          type: constant
          interval: 180.0
        workerGroup:
          key: WORKER_GROUP
        namespace: plm
        flowId: test_SQL_Worker
        inputs:
          masterDataRow: "{{ taskrun.value }}"
    errors: []
    value: "{{outputs.query.rows}}"


concurrency:
  limit: 1
  behavior: CANCEL
```

Doing ForEach parallel with a Subflow task will balloon the execution context. It will cause all sorts of issues on the webserver component, most of the tabs like outputs, logs, overview, topology, and gantt will fail to load, and ultimately cause the webserver to crash. On the backend, the executor will try to run the flow for hours, but ultimately will never actually finish the flow - the Java heap space will run out and either cause an exception or the flow will be stuck in the running state indefinitely. Triggering any other flow execution won't do anything, all tasks will be stuck in the CREATED state because the executor task queue is blocked. 

I currently have developers working on Kestra so I cannot purposely crash the executor (I don't have another environment to test on). But here's the executor crash log that I saved from a while back on 7/22 : 

https://pastebin.com/31rPXN1Y

I know calculating the execution context can be very situational. But I was hoping that there could be a solution to prevent users from creating bad flow designs that cause the executor and / or webserver to crash. I'm not sure if a similar limit that is implemented for the Elasticsearch architecture could be implemented for JDBC. The limit is also very dependent on the deployment and therefore should be configurable, as after experiencing series of crashes with the executor running out of heap space I gave it ridiculous amounts of memory giving it the option ```-Xms24g -Xmx24g``` just in case.
