### ISSUE TITLE
Fix python log levels

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4641]
### Describe the issue

repro:

```yaml
id: py
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.scripts.python.Script
    script: |
      import logging

      logger = logging.getLogger('my_logger')
      logger.setLevel(logging.INFO)

      console_handler = logging.StreamHandler()
      console_handler.setLevel(logging.INFO)

      formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
      console_handler.setFormatter(formatter)

      logger.addHandler(console_handler)

      logger.info("This is a log message from my_logger.")
      logger.debug("Debug message")
      logger.warning("Warn message")
      logger.error("Error message")
```

![image](https://github.com/user-attachments/assets/bcf33f37-c91a-461e-96d2-d4d505a99c5c)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by sebastianknopf** [comment]
Is there a deeper documentation about how to structure python logs correctly? I am using the latest docker image but still facing the same issue when running python scripts with log entries in similar formats. All log entries are treated as warning.

**Comment by tchiotludo** [comment]
@sebastianknopf it's not released so far, only on the `develop` image for now

**Comment by sebastianknopf** [comment]
Thank you for the quick reply! Is there a plan in which release this feature will be included?

**Comment by tchiotludo** [comment]
in the `0.19.0` coming soon

**Comment by sebastianknopf** [comment]
Sadly I am still facing the same issue, using 0.19.1. Could you mention the correct pattern here, which is needed to recognize the logging levels correctly?

**Comment by anna-geller** [comment]
here is an example: https://kestra.io/docs/workflow-components/tasks/scripts/logging#python

```Python
from kestra import Kestra

logger = Kestra.logger()
logger.debug("Hello World from logs!")
logger.info("Hello World!")
```

**Comment by sebastianknopf** [comment]
Thank you so much!
