### ISSUE TITLE
Fix typos in the API schema

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4653]
### Describe the issue

Needed for https://github.com/kestra-io/kestra/issues/4652

SchemaStore runs [codespell](https://github.com/codespell-project/codespell) check which looks for potential typos in the schema file - running this highlighted a few typos in the file which we should correct in our API schema:

run: `codespell <schema>.json --ignore-words-list CopyIn,notIn`

This will produce a list of potential typos in the file - running this initially produced the following
src/schemas/json/kestra-0.18.json:146926: crypted ==> encrypted
src/schemas/json/kestra-0.18.json:147022: crypted ==> encrypted
src/schemas/json/kestra-0.18.json:148341: fro ==> for, from
src/schemas/json/kestra-0.18.json:158524: leas ==> least, lease
src/schemas/json/kestra-0.18.json:169789: carefull ==> careful, carefully
src/schemas/json/kestra-0.18.json:170398: carefull ==> careful, carefully
src/schemas/json/kestra-0.18.json:170581: carefull ==> careful, carefully
src/schemas/json/kestra-0.18.json:170692: carefull ==> careful, carefully
src/schemas/json/kestra-0.18.json:170991: carefull ==> careful, carefully
src/schemas/json/kestra-0.18.json:190266: exemple ==> example
src/schemas/json/kestra-0.18.json:194667: Succeded ==> Succeeded
src/schemas/json/kestra-0.18.json:205664: convertion ==> conversion
src/schemas/json/kestra-0.18.json:207519: labled ==> labeled, labelled
src/schemas/json/kestra-0.18.json:209811: overriden ==> overridden
src/schemas/json/kestra-0.18.json:209811: ot ==> to, of, or, not, it

To reproduce and fix those typos:
- Start 0.18
- Get the schema
- Look at those lines and search for the task

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by benpops89** [comment]
@anna-geller - I have created PRs in each of the affected plugins to correct the typos

**Comment by anna-geller** [comment]
This is great, thanks so much Ben!
