### ISSUE TITLE
400 response code on Delete flow logs 

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4663]
### Describe the issue

400 response on deleting flows logs 

Request URL:
http://localhost:8080/api/v1/logs/debug/podCreateCheckFileDate
Request Method:
DELETE

Response: 
```json
{
    "message": "Bad Request: Required QueryValue [triggerId] not specified",
    "logref": null,
    "path": null,
    "_links": {
        "self": {
            "href": "/api/v1/logs/debug/podCreateCheckFileDate",
            "templated": false,
            "profile": null,
            "deprecation": null,
            "title": null,
            "hreflang": null,
            "type": null,
            "name": null
        }
    },
    "_embedded": {}
}
```
https://github.com/user-attachments/assets/a3cb5b75-87bb-44b7-9aa8-6f1eee0f10e3

Related issue https://github.com/kestra-io/kestra/issues/5024

### Environment

- Kestra Version: develop 0.19
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
Just tested it and it now works with a 200 status code.
Can you test again with develop?

**Comment by smunteankestra** [comment]
reproducing on my side, ran with today's develop build, last pulled in morning, we can check together, maybe something else 
https://github.com/user-attachments/assets/ccc21aca-3ae5-4b5b-a0bd-2860517009a1

**Comment by MilosPaunovic** [comment]
Is this still reproducible @smunteankestra, as I can not do it on current `Preview` deployment?

**Comment by smunteankestra** [comment]
@MilosPaunovic yes, still reproducing
<img width="1650" alt="image" src="https://github.com/user-attachments/assets/3bcc4ff8-10d3-4261-bbb0-77cc52c0e667">

**Comment by mounikaperi** [comment]
@anna-geller @smunteankestra @MilosPaunovic 
Is the issue still present? In that case I would like to look into it

**Comment by anna-geller** [comment]
Sure, go ahead @mounikaperi - thank you!

**Comment by Ben8t** [comment]
Not reproducible on 0.19. Closing for now, do not hesitate to repopen
