### ISSUE TITLE
Introduce new filter/search bar for Flows and Executions

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4664]
### Feature description

With the growing number of filters, this filter/search bar is cluttered:

![image](https://github.com/user-attachments/assets/eaf6dcde-de8e-4c66-ad7d-9ef3ea9d1c2c)

It would be great to implement a similar approach to GitLab's filter -- Walkthrough: https://share.descript.com/view/N8dV18u74Um

## Related issues

Issues that will be enabled/improved by this:
- [x] https://github.com/kestra-io/kestra/issues/3029 
- [x] Flows page
- [x] Logs
- [x] Logs in the Executions page https://github.com/kestra-io/kestra/issues/5730
- [x] main Dashboard
- [x] Blueprints https://github.com/kestra-io/kestra/issues/5729
- [x] Concurrency tab https://github.com/kestra-io/kestra/issues/5825

**Comment by VamshiReddy02** [comment]
Hey @MilosPaunovic, can I work on this issue? because there is currently no associated pull request for this issue.

**Comment by MilosPaunovic** [comment]
@VamshiReddy02 Absolutely, go for it! :rocket:

**Comment by MilosPaunovic** [comment]
@VamshiReddy02 Any progress on this?

**Comment by anna-geller** [comment]
@VamshiReddy02 here is a design how this can look like -- if you can't manage, don't worry we understand, it's a complex feature

![image](https://github.com/user-attachments/assets/1c4602d8-6c8c-4781-a141-2c81c1b75c7c)

![image](https://github.com/user-attachments/assets/a538b2c0-bbce-4ab8-9f47-6108b51d5177)

[Internal figma link](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3437-30603&t=YvgrD3fKKpUVig7X-4)

**Comment by anna-geller** [comment]
History of past searches + Saved searches

![image](https://github.com/user-attachments/assets/436223a2-5d06-4622-87d4-ffb29888e194)

@Skraye can you assess whether enabling a history of past searches needs storing this somewhere, or would we only cache it on the front-end side?

**Comment by Skraye** [comment]
As current state, we could only store it on the frontend side

**Comment by anna-geller** [comment]
- `Relative` date is a dedicated filter separate from `Absolute` one
- `Absolute` date is a separate filter with a date range picker
- `Trigger execution ID` field is not needed anymore for now due to correlationId
- only when you type `Enter`, we filter the data
- **View elements** separate from filters: 
    - which `columns` should show in the table
    - whether to `show chart`
    - refresh toggle
    - the column selector will be on the right
- `Save` button for Saved searches
- Sorting is already handled by the columns in each table
- For now, we only focus on filters for which we have backend implementation e.g. no multi-select of namespaces until it's done on the backend side
- For **search**, user can just type:
![image](https://github.com/user-attachments/assets/417fdf8f-b168-4507-8bdd-fc8fd86f8ea6)


---

long term we could add recent/all for dropdown values e.g. for `namespace` field

![image](https://github.com/user-attachments/assets/25778a79-2c6a-41d6-9478-870890bb5260)

**Comment by sachinks07** [comment]
Can I give a try on this.

**Comment by MilosPaunovic** [comment]
Hey @sachinks07,

We've decided to handle this internaly, but I can loop you in for feedback once there's something to be checked.

Maybe you can look at the issues with `good first issue` labels and pick something from there?

**Comment by sachinks07** [comment]
Sure. Thank you

**Comment by MilosPaunovic** [comment]
First related PR is merged https://github.com/kestra-io/kestra/pull/5844.
