### ISSUE TITLE
Blueprints page is broken on develop

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4665]
### Describe the issue

See https://share.descript.com/view/xiOOvteAt5t

![image](https://github.com/user-attachments/assets/8d353660-ea2d-432e-b823-62b59e0eb89c)

the same on Chrome

![image](https://github.com/user-attachments/assets/463be59c-eb6a-40a5-9b32-599092d5e881)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/kestra/commit/82f183788f64dd8a2d106c1b9e3ebe0550d3162b.
