### ISSUE TITLE
Error Stack-trace on Debug Outputs is hidden (too narrow column to show full error message, no scroll)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4674]
### Describe the issue

![image](https://github.com/user-attachments/assets/df79124b-60d5-4cf6-b3fb-da484786b745)

### Environment

develop

**Comment by MilosPaunovic** [comment]
Added scroll for errors and two handy little buttons, as well.

![image](https://github.com/user-attachments/assets/ee712f87-d660-4f50-8016-dbf90b6df8ee)
