### ISSUE TITLE
Fix plugin display names for CLI tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4676]
### Describe the issue

As shown here, it affects both UI and website. We should rename them as shown below as "Cli" doesn't mean anything:

![image](https://github.com/user-attachments/assets/ad760cfa-e4bb-408b-98c8-046589ea4d2f)

**Comment by MilosPaunovic** [comment]
I've changed the labels, as the labels here are shown as they are retrieved from the endpoint.

**Comment by anna-geller** [comment]
when you say you changed the labels, you mean you have a PR or where they not deployed yet? I see just Cli everywhere atm

**Comment by MilosPaunovic** [comment]
No, no, just the GH Issue labels, remove `area/frontend` and added `area/backend`. Sorry for creating the confusion.

**Comment by anna-geller** [comment]
will be done in https://github.com/kestra-io/docs/issues/1456
