### ISSUE TITLE
Parent namespace doesn't display child namespace files in Namespaces Page

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4684]
### Describe the issue

Inside of the namespaces view, you can view all of the flows under **Flows** inside of the parent and all child namespaces too. However you can't see any child namespace files in the **Editor** view.

Example namespaces:
![Screenshot 2024-08-16 at 16 48 30](https://github.com/user-attachments/assets/d0f752a4-9ddf-4e3b-b86e-a98b6ff284b2)

`company` sees no files but sees all the child flows:
![Screenshot 2024-08-16 at 16 48 47](https://github.com/user-attachments/assets/52fc4dc3-b066-46a8-92bb-ec6a16ebb31d)
![Screenshot 2024-08-16 at 16 49 07](https://github.com/user-attachments/assets/15643d7d-500a-4da4-9c11-dd8d4ae3ff08)

As you can see, they are all inside of child namespaces from the Flows page:
![Screenshot 2024-08-16 at 16 49 21](https://github.com/user-attachments/assets/7039c656-e324-4497-87b8-37fbfb6f23fd)

`company.team` does have a namespace file that is visible as expected in its actual namespace but not in the parent view:
![Screenshot 2024-08-16 at 16 50 09](https://github.com/user-attachments/assets/c604127a-aa9e-4d72-a2e7-b855209ef3e7)

`company.myteam` also contains 2 namespace files but neither are visible in the parent.
![Screenshot 2024-08-16 at 16 50 43](https://github.com/user-attachments/assets/bf447712-0318-4b6e-9454-af037fd448ec)

While this might have been intended by design, it's not coherent with the Flows page.

### Environment

- Kestra Version: 0.19.0 Snapshot
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
Namespace files are tied to a specific namespace without being inherited by children. This is intended behavior. If the fact that the Flows tab shows child namespaces is confusing (as compared to the Editor), we can filter Flows only for that single namespace (it seems useful to keep and add a namespace column to be explicit https://github.com/kestra-io/kestra/issues/4686)
