### ISSUE TITLE
Add a new core property allowing to log only to a file (i.e. logs won't be captured by the DB backend)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4688]
## Problem

Often, users run Python/Terraform/Shell scripts that generate a looooot of logs to the point that it unnecessarily clutters their database. They wish they could avoid capturing logs by the database backend and instead only log to an internal storage file that can be downloaded when needed for troubleshooting.

## Solution

Add a boolean property `logToFile` by default set to `false` — if set to `true`: 
1. Store the logs generated by the task only locally in a temp file on the worker 
2. Since logs are not captured by the backend, they won't  be displayed in the UI — we should generate a friendly message `"Logging to a file. Check the Outputs tab after the task run finishes to inspect the logs."`
3. Upload the file to the internal storage e.g. as `taskrun.log` and output that file as a downloadable kestra output

**Comment by tchiotludo** [comment]
There is multiple concern we need to address before starting this one, why I would prefer this is [one](https://github.com/kestra-io/kestra/issues/988) first and this [long term one](https://github.com/kestra-io/kestra-ee/issues/1406): 
- how to manage stdout and stderr? 
- do we capture outputs why special [syntax](https://kestra.io/docs/developer-guide/scripts/outputs-metrics#how-to-emit-outputs-and-metrics-from-script-tasks)? 

IMO, the pain is about performance, our implementation should be safe and invisible to end users, this properties should be avoid. 
Also, we already have a `logLevel` to control log output

**Comment by anna-geller** [comment]
EDIT: we will evaluate implementing this for all plugins instead of only for script tasks

**Comment by johnkm516** [comment]
Hi @anna-geller , @tchiotludo 

Is there a timeline on this?
I think #988 would also solve this issue. I have a lot of batch tasks with a lot of logs that I want to see / access on the Kestra UI directly (it already stores logs locally on the batch server). I also do not want to use LogLevel, I want to be able to store and see the logs in Kestra. My current workaround mentioned [https://github.com/kestra-io/plugin-fs/issues/141](here) works but breaks the formatting making the log very difficult to read.

**Comment by anna-geller** [comment]
It's planned for 0.19, which will be shipped on Oct 3rd. You can track it for any issues on this field here:

![image](https://github.com/user-attachments/assets/b8783aef-4a21-4703-9fbf-356f08df71d7)
