### ISSUE TITLE
Ability to process incoming webhooks with large header

### ISSUE THREAD

**Issue by n0obHere** [kestra-io/kestra#4719]
### Feature description

In current release v0.18.2, if an incoming webhook has a large JSON payload, Kestra replies with a '413 Request Too Large'. This behavior was introduced after [#4566](https://github.com/kestra-io/kestra/issues/4566) & [#4638](https://github.com/kestra-io/kestra/issues/4638). Recommended way of sending webhooks with large payloads is to use [file-type inputs](https://kestra.io/docs/workflow-components/execution#execute-a-flow-with-file-type-inputs), but not all systems out there (mostly closed-source/proprietary) support or offer file-type input functionality when configuring webhooks.

**Comment by anna-geller** [comment]
There is quite little we can do with that currently. It's common that you typically send only small bits of metadata in a webhook payload. If file type is not feasible, you can try:
1. Storing your data in some local file or S3 object and only pass the path as a string 
2. Configure the sender application to paginate data into multiple smaller payloads sent sequentially 
3. (Not the best option) Consider some compression before sending the payload

**Comment by loicmathieu** [comment]
We must have payload size protection, it's mandatory to have some limit or t would be very easy to make Kestra webserver crash as a payload is loaded into memory which is not the case for attachment parts (file upload).

However, you can increase this limit to fit your need.
But I'm surprised you hit this limit as I think by default we set it to 10GB.

```yaml
micronaut:
  server:
    max-request-size: 10GB
```

If you can have a reproducer (flow but a cURL to the webhook) to reproduce it we can better understand what you want to achieve.

**Comment by anna-geller** [comment]
good catch Loic! @n0obHere could you share a reproducer? in fact, the issue you are referring to 413 has not been added yet, so you should not see any limits there as of today. An example we could reproduce would be helpful

**Comment by loicmathieu** [comment]
@n0obHere without any reproducer we cannot work on this issue, can you provide a flow and a webhook request? If you're using Postman you can export a request as a cURL.

**Comment by n0obHere** [comment]
@loicmathieu @anna-geller  Sorry guys, I was away for a few weeks. I'll get you a reproducer by tomorrow. I originally experienced this issue with our VoIP PBX, but I think I also experienced the same with another system, a billing engine, when I had it send webhooks to Kestra upon any billing activity with JSON payload. I'll share the flow and webhook payload for you guys to analyze.

**Comment by loicmathieu** [comment]
@n0obHere great, we'll have a look later when you provide the reproducer.

**Comment by n0obHere** [comment]
@loicmathieu @anna-geller here's that simple Kestra webhook flow I was using along with the ngrep capture of the webhook from the source system attached. I think its the JWT auth signature that's making the payload so large.

[ngrep_output.txt](https://github.com/user-attachments/files/16911584/ngrep_output.txt)

`id: testFlowID
namespace: testNamespace.accounting

tasks:
  - id: webhookData_cxName
    type: io.kestra.plugin.core.debug.Return
    format: "{{ trigger.body | jq('.invoice.customer.name') | first }}"

  - id: webhookData_invoiceNumber
    type: io.kestra.plugin.core.debug.Return
    format: "{{ trigger.body | jq('.invoice.number') | first }}"

  - id: logValues
    type: io.kestra.plugin.core.log.Log
    level: INFO
    message: "Invoice created for customer {{ outputs.webhookData_cxName.value }}, Invoice number {{ outputs.webhookData_invoiceNumber.value }}."

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: 4wjtkzwVGBM9yKnjm3yv8r
disabled: false`

**Comment by loicmathieu** [comment]
I can reproduce the issue, this is caused by the `X-Lago-Signature` header being too long.

The default max size is 8k, you can increse it inside the Kestra configuration file:

```yaml
micronaut:
  server:
    netty:
      max-header-size: 16384
```

**Comment by loicmathieu** [comment]
We will upgrade it to 32k on the next bugfix release.
