### ISSUE TITLE
KV json validation 

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4720]
### Describe the issue

In KV if a user inputs a string instead JSON - it will change the type to String after save

Check Video

https://github.com/user-attachments/assets/0c9e34e0-b77e-41b9-9063-d14a90295690

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Pinako-Ana** [comment]
I would like to contribute to this issue

**Comment by MilosPaunovic** [comment]
@Pinako-Ana Go for it!

**Comment by Pinako-Ana** [comment]
@MilosPaunovic 
I submitted PR

**Comment by Pinako-Ana** [comment]
hmm.. i just noticed the label is backend.. 🥲

**Comment by Ben8t** [comment]
@MilosPaunovic I see the PR from @Pinako-Ana is merged: can we close the issue ?
