### ISSUE TITLE
Vanilla instance serves Dashboard page instead of Welcome Page

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/kestra#4724]
### Describe the issue

When I launch Kestra latest and hit _localhost:8080_ , I'm redirected to `/ui/dashboard` instead of  `/ui/welcome`

![welcome](https://github.com/user-attachments/assets/8fbf1105-2c72-4acc-9ce9-a9c13118e951)

### Environment

- Kestra Version: v0.18.2
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by anna-geller** [comment]
the "Ready to see your flow in action" should be removed to be sure it will never be shown again

Regardless of whether the user hits /ui/dashboard or /ui/welcome, the page on the right should show up 👍 

@MilosPaunovic can you have a look when you are back?

**Comment by anna-geller** [comment]
related issue incl. Figma design for it https://github.com/kestra-io/kestra/issues/3692

**Comment by anna-geller** [comment]
I think we can close this one as atm the welcome page is always showing up -- see the demo of a new fresh instance https://share.descript.com/view/otP7GF6QNjl

if anything, the welcome page is now showing too much 😄 but this will be handled in https://github.com/kestra-io/kestra/issues/4999
