### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#4726]
### Issue description

All those tests were flaky during v0.18.3 release:

- [ ] [MysqlRunnerTest.forEachItem(): jdbc-mysql/src/test/java/io/kestra/runner/mysql/MysqlRunnerTest.java#L1](https://github.com/kestra-io/kestra/commit/4ede173331eeff629ac75f2d2527850fa64f64b8#annotation_25388689848) -> java.lang.AssertionError: Expected: is <true> but: was <false>
- [ ] [MysqlServiceLivenessCoordinatorTest.shouldReEmitTasksWhenWorkerIsDetectedAsNonResponding(): jdbc-mysql/src/test/java/io/kestra/runner/mysql/MysqlServiceLivenessCoordinatorTest.java#L1](https://github.com/kestra-io/kestra/commit/4ede173331eeff629ac75f2d2527850fa64f64b8#annotation_25389576131) -> java.lang.AssertionError: Expected: is <true> but: was <false>
- [ ] [H2RunnerTest.forEachItemFailed(): jdbc-h2/src/test/java/io/kestra/runner/h2/H2RunnerTest.java#L1](https://github.com/kestra-io/kestra/commit/4ede173331eeff629ac75f2d2527850fa64f64b8#annotation_25391389501) -> java.lang.AssertionError: Expected: is <true> but: was <false>

**Comment by loicmathieu** [comment]
Tests that were flaky for this CI build that needs 5 attemps to pass: https://github.com/kestra-io/kestra/actions/runs/10904444741

- [ ] [H2RunnerTest.forEachItemNoWait(): jdbc-h2/src/test/java/io/kestra/runner/h2/H2RunnerTest.java#L1](https://github.com/kestra-io/kestra/pull/4924/files#annotation_26370012000)
java.lang.AssertionError: Remaining count was 24 Expected: is <true> but: was <false>
- [ ] SchedulerStreamingTest.simple()
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "java.util.Map.get(Object)" is null
- [ ] H2RunnerTest.forEachItemSubflowOutputs()
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
- [ ] PostgresRunnerTest.forEachItemNoWait()
java.lang.AssertionError: Remaining count was 24
Expected: is <true>
     but: was <false>

**Comment by loicmathieu** [comment]
Other flaky tests: https://github.com/kestra-io/kestra/issues/1257

**Comment by brian-mulier-p** [comment]
Closing as I grouped everything [here](https://github.com/kestra-io/kestra/issues/2722)
