### ISSUE TITLE
Custom Blueprints page generates internal server error

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4729]
### Describe the issue

Since 0.18.2 Custom Blueprints page does not load properly. 
The page returns an internal server error. 

### Environment

- Kestra Version: 0.18.3
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by anna-geller** [comment]
I was able to reproduce it:
![image](https://github.com/user-attachments/assets/b1f06103-19cc-445d-9c48-acdf9ff81493)

We will fix it as a high priority, and by the latest on Thursday, the 29th, we should release a fix.

Thanks for the issue, John!

**Comment by Skraye** [comment]
@anna-geller this seems fixed, can you confirm and then close the issue ?

**Comment by anna-geller** [comment]
yup, confirmed, it's fixed now. 

@johnkm516 the fix should be released tomorrow (Thursday 29th)
