### ISSUE TITLE
[docs] `delay` should indicate time value in Documentation for Pause

### ISSUE THREAD

**Issue by johnsturgeon** [kestra-io/kestra#4741]
### Issue description

https://kestra.io/plugins/core/tasks/flow/io.kestra.plugin.core.flow.pause#delay

Currently it says:
> Duration of the pause — useful if you want to pause the execution for a fixed amount of time.

But it does not specify units (seconds, milliseconds, days.. )

It would be helpful to note that in the documentation

**Comment by anna-geller** [comment]
hmm when you see a duration property, this means the ISO duration which can be in any unit you like e.g. PT30S will be 30 seconds and PT1H will be one hour: https://en.wikipedia.org/wiki/ISO_8601#Durations 

I'll clarify this in the task doc

**Comment by johnsturgeon** [comment]
I did not know that. lol.  

I feel kind of embarrassed that I didn't think of that.

**Comment by anna-geller** [comment]
all good! we should do a better job with our docs to clarify that 👍
