### ISSUE TITLE
Add a confirmation dialog with a warning when user tries to delete a RUNNING or CREATED execution

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4746]
### Feature description

Based on internal discussion, we will not prevent users from deleting running Executions. However, we should warn them about the consequences of such action: 

> Are you sure you want to delete this unfinished Execution? We highly recommend to first Kill any Execution in progress before attempting to delete it. This will avoid inconsistencies and zombie processes on your instance.

**Comment by loicmathieu** [comment]
It's already the case and they still delete running execution so I think this can be close.

**Comment by anna-geller** [comment]
You are right!

![image](https://github.com/user-attachments/assets/17bf841b-f385-4c48-90d1-d89b1b476e8a)


I'll look into the wording, perhaps we can make the warning even more explicit, then I'll close the issue
