### ISSUE TITLE
[UI] Flows Page: ID column is tiny and hard to read on a notebook screen (e.g. 13.3")

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/kestra#4748]
### Describe the issue

First-time Kestra users on a small screen (this is MBAir 13.3") see the following in the _Flows_ page (pre-filled, with a tiny _Id_ column:
<img width="1486" alt="flows" src="https://github.com/user-attachments/assets/4cb62ae4-8e3c-4bd2-a688-11397b27d98f">

More generally speaking I was surprised to see that the _Id_ is the first column to get shrunk when resizing window:
![resize](https://github.com/user-attachments/assets/c8490b2e-f82d-4544-922c-485787597f83)

Seems to me that the other (larger) columns, could equally deserve a resize at first (as _Id_ remain a key bit of information).

### Environment

- Kestra Version: 0.18.3
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by MilosPaunovic** [comment]
This is now fixed, thanks for the report @nicoallgood. 🚀
