### ISSUE TITLE
Worker group attribute should be a listbox populated with existing worker group keys

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4755]
### Feature description

The low code editor as well as the editor auto-complete should reference worker groups shown in the Cluster Monitor and populate the worker group keys as a listbox in the low code editor, as well as autocomplete when editing manually in the raw yaml. 

![image](https://github.com/user-attachments/assets/179338ae-1964-498f-bd5b-f1e2c07f4d01)

This is relevant to kestra-io/kestra-ee#1726, where if the user inputs a worker group key that does not exist, tasks are stuck in the CREATED state.

**Comment by anna-geller** [comment]
Yes, we are planning to require creating a worker group via UI/API first, then it will be possible to have validation/autocompletion of the keys. We are tracking it internally in the EE repo https://github.com/kestra-io/kestra-ee/issues/1525

**Comment by johnkm516** [comment]
Closing this as an internal issue already exists.
