### ISSUE TITLE
PostgreSQL query plugin crashes when no result with `fetchOne : true`

### ISSUE THREAD

**Issue by acompagnon** [kestra-io/kestra#4763]
### Describe the issue

After our discussion on Slack, I open an issue : 
 
When using the `io.kestra.plugin.jdbc.postgresql.Query` task type with `fetchOne: true`, an exception raises if no rows are matching which makes the task (and the flow) fail :  
```
ResultSet not positioned properly, perhaps you need to call next. 
```

It prevents the developper to deal with an empty result since the flow crashes.  

Thanks a lot for all your work !

### Environment

- Kestra Version: 0.13.0
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker): X

**Comment by loicmathieu** [comment]
Hi, you're running a very old version of Kestra, can you try to upgrade to a more recent one and see if it fixes the issue?

**Comment by acompagnon** [comment]
Hi, no sorry I can't upgrade on my work environment because it creates issues I had to rollback, I think your colleagues managed to reproduce on the latest Kestra versions https://kestra-io.slack.com/archives/C03FQKXRK3K/p1724863127811069

**Comment by loicmathieu** [comment]
OK, anyway we will not backport it to 0.13 so you would need to upgrade to 0.18 to have the fix.

**Comment by acompagnon** [comment]
Yes I know, but since I've been told that it would be great for others I made a workaround for me and opened this issue
