### ISSUE TITLE
GCP Batch Logging Msgs not showing Logs for Batch Task Runner

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#4772]
### Describe the issue

- utilizing Go library - https://pkg.go.dev/cloud.google.com/go/logging
- Logs show in GCP Log Explorer - Image 1 (in comment)
- Logs not showing in kestra UI 1/2 - Image 2
- Logs not showing in kestra UI 2/2 - Image 3

![Screenshot 2024-08-29 at 2 12 22 PM](https://github.com/user-attachments/assets/d5302501-4192-4d22-a778-a8f9ece01847)

![Screenshot 2024-08-29 at 2 13 50 PM](https://github.com/user-attachments/assets/f948b359-3e56-450d-8f56-61601916952f)

### Environment

- Kestra Version: 0.18.3
- Operating System (OS/Docker/Kubernetes): Kestra Cloud
- Java Version (if you don't run kestra in Docker): n/a

**Comment by japerry911** [comment]
<img width="840" alt="Screenshot 2024-08-29 at 2 15 31 PM" src="https://github.com/user-attachments/assets/b1ab9774-cca4-40b7-beac-a3250aa8aeda">
 Image 1 ^

**Comment by japerry911** [comment]
![image](https://github.com/user-attachments/assets/cc69a8d5-8897-4813-a867-71e5a11b4dbf)

noticed these are failing too, tried to execute with admin privileges temporarily still didn't show

**Comment by japerry911** [comment]
![image](https://github.com/user-attachments/assets/1b99f54f-9511-4946-85d2-cbdcdccd0d48)

was able to get logs to start showing in Kestra UI, but warnings are showing as INFO when I test

**Comment by loicmathieu** [comment]
@japerry911 if I understand correctly this issue is fixed, you can see the logs, however as you use structured login you would expect them to be parsed by Kestra so at least the level is correctly set which is described here: https://github.com/kestra-io/kestra/issues/4778

Can we close this one and keep the other one?

**Comment by japerry911** [comment]
That is all correct, good to close/move to 4778

**Comment by loicmathieu** [comment]
Thanks for the confirmation.

Closed in favor of https://github.com/kestra-io/kestra/issues/4778
