### ISSUE TITLE
The logs view could benefit from more spacing between logs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4776]
### Feature description

![image](https://github.com/user-attachments/assets/85106a00-aa63-4337-a0f5-d9bd8b47ed88)

**Comment by Nico-Kestra** [comment]
<img width="1654" alt="Capture d’écran 2024-09-04 à 09 22 23" src="https://github.com/user-attachments/assets/6bdaf6e5-238a-4f98-894d-d29d29aea7cc">
And can we make something for this? it's unsightly

**Comment by MilosPaunovic** [comment]
@Nico-Kestra For the image you've added, UI is rendering what is retrieved as a log from BE, and, for that particular example what is recieved is:

```js
...
# We open the 'exported' files created by kestra and that will be downloaded at the end of the process
# in order to be used by next tasks
...
```

Which is rendered as `H1` title in `HTML`. @anna-geller Could you please open a separate BE issue for it when you get a chance?
