### ISSUE TITLE
Add ability for Kestra UI to interpret Structured Logging from GCP Cloud Logging in Kestra UI

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#4778]
### Feature description

- Add ability for Kestra UI to interpret Structured Logging from GCP Cloud Logging in Kestra UI
- GCP docs reference on structured logging [here](https://cloud.google.com/logging/docs/structured-logging)
- Would solve this issue - #4772

**Comment by japerry911** [comment]
Hello team, I no long need this issue resolved, integrated this with our processes - https://pkg.go.dev/github.com/japerry911/kestra-go and it does what i desired 🚀 logs show in UI with correct level too

**Comment by MilosPaunovic** [comment]
Awesome @japerry911, I'll close this one for now, we'll re-open in the future if necessary.
