### ISSUE TITLE
Folder doesn't appear until refresh when creating a new namespace file with folder path included

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4779]
### Describe the issue

When I press **Create file** and type `scripts/code.py` or something where there's a folder structure defined but the folder doesn't exist, it will create the file correctly but it isn't displayed in the UI until it has been refreshed.

https://github.com/user-attachments/assets/02a4b477-5d11-4b39-882a-77c0efe343a2

### Environment

- Kestra Version: 0.19 Snapshot
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Sheikh-Abubaker** [comment]
Hey @wrussell1999 could you please help me with the section of the code where I should look ? to know more about this one ? Looking forward to contributing in java codebase.

**Comment by wrussell1999** [comment]
@Sheikh-Abubaker believe it will be somewhere in here: https://github.com/kestra-io/kestra/tree/develop/ui/src/components/inputs

**Comment by anna-geller** [comment]
I can reproduce still
