### ISSUE TITLE
Refresh the overview page 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4788]
So far, the page is not friendly, and look unprofessional: 
![image](https://github.com/user-attachments/assets/93b293a2-ffb7-4caf-b3d0-b1a839918953)

- We should align all table head 
- probably we should also add the output browser for inputs and trigger (since the webhook will generate large dataset) 

@Nico-Kestra to help

**Comment by MilosPaunovic** [comment]
Would say this can be closed now, as we've overhauled overview page some time ago @tchiotludo?
