### ISSUE TITLE
Flows > Editor : Namespace Files should be opened by default and saved in local storage. 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4789]
So far, the namespace files are are collapsed by default, I think the feature is hidden for new comer. 

I think we should : 
- let this namespace file list opened by default 
- keep the open / close state in local storage 
- add a some doc link to explain what is this: 

![image](https://github.com/user-attachments/assets/86adfaca-06f3-42d5-bfdd-50b4e64d9cfa)

**Comment by anna-geller** [comment]
What if we think about an alternative, more prominent display of that toggle? The reason we kept it collapsed by default:
1. VS Code behavior 
2. 70-80% of users rely on plugins (no custom scripts)
3. The future improved low code workflow builder will make scripts browser open by default confusing to non-coders users 

Keeping it open by default might be a little annoying for the majority. I understand the rationale though. Maybe there's a middle ground?

**Comment by tchiotludo** [comment]
I agree on main argument, just I didn't say keeping open, I say open the first time by default, it mean the first closing will hide the panel, like we have now, just it will be shown for new users and will not change for every users that close it

**Comment by anna-geller** [comment]
new prominent icon was recently added
