### ISSUE TITLE
Relative filter is not centered 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4790]
![image](https://github.com/user-attachments/assets/7bd9bf66-4541-473e-aaec-8bfa155d5355)

**Comment by anna-geller** [comment]
part of this should be done here https://github.com/kestra-io/kestra/issues/3822

still good call, as other pages need adjustment too.

Short term adjustments needed:
- [x] Main dashboard
- [ ] Executions
- [ ] Logs
- [ ] Task Runs (EE)
- [x] Namespace Overview

long term https://github.com/kestra-io/kestra/issues/4664

**Comment by riyamustare** [comment]
hey, can you assign me this task if its still needed.

**Comment by riyamustare** [comment]
are the short term adjustments done cause i can see everything aligned

**Comment by MilosPaunovic** [comment]
It seems like it needs adjusting on Executions and Logs.

**Comment by riyamustare** [comment]
issue #2798 right?

**Comment by MilosPaunovic** [comment]
No, this issue. The alignment of date filter options from the image above is not alright, not centered inside the field.

**Comment by riyamustare** [comment]
okay okay, thankyou.

**Comment by MilosPaunovic** [comment]
Great catch @riyamustare, looking forward to some more of your contributions! 🚀

**Comment by riyamustare** [comment]
thankyou @MilosPaunovic and sure would love to contribute more!
