### ISSUE TITLE
Namespaces menu: some options are 'lost' in between EE greyed-out options

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/kestra#4805]
### Describe the issue

It's nice that we hint at additional EE functionality, however it should not come to the expense of having to search/find  available (non-EE) features. Under _Namespaces_, the layout is confusing in that respect:

<img width="995" alt="Screenshot 2024-09-03 at 11 57 17" src="https://github.com/user-attachments/assets/5f1f113f-ac08-451d-a0d7-56f152f8ce01">

_Dependencies_ and _KV Store_ mixed in between EE greyed-out menus.

This can turn up even more confusing on smaller screen sizes, where one needs to scroll to discover that more available menus exist after the greyed-out. ones

![menus](https://github.com/user-attachments/assets/955993e4-7c85-4254-90f9-7c80ee6e80bc)

Proposal: EE greyed-out options should be stacked to the right, so that all (non-EE) available functionality is available straight away on the left hand side

### Environment

- Kestra Version: 0.18.4
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by wrussell1999** [comment]
+1 - the KV Store does kinda get lost to the side when zoomed in.

**Comment by anna-geller** [comment]
Those folks with tiny screens 😄 I can see everything on 15'6 laptop

Sure, we can reorder the tabs to show Dependencies and KV Store first after Flows tab - @MilosPaunovic can you reorder? (can be the same for OSS and EE)
