### ISSUE TITLE
Allow replay/restart from within the list of executions

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/kestra#4806]
### Feature description

_Replay_ and _Restart_ are awesome: they're practical, they help achieve rapid 'try and adjust' sequence when developing a flow, and overall they're energy/time-savers.

In my Kestra discovery journey, I found myself hoping that I could replay/restart an execution right from where it's listed (e.g. in the main execution page, but also in the _Executions_ menu of a flow):

![replay](https://github.com/user-attachments/assets/78da90f4-43e0-44c1-91f0-646c0d5f5be1)

-----
**Proposal**: interestingly enough we do offer this kind of 'quick access' under the _Logs_ page of a specific execution. Here we can individually and rapidly _replay_ (and/or more) a specific task:

![yes](https://github.com/user-attachments/assets/73568b05-53ef-44bd-94c5-ca4d36165728)

Having a similar kind of menu when viewing lists of executions would be great I believe 🚀

**Comment by loicmathieu** [comment]
You can do it easily if you select the execution, there will be "bulk action buttons" appearing.

**Comment by nicoallgood** [comment]
Ah! Thanks for the tip 🙏 

This gets me wondering if it could be made more explicit though (UX-wise), as it didn't feel natural as a first-time user. I'll let the POs judge on that.

**Comment by Ben8t** [comment]
@nicoallgood _"I found myself hoping that I could replay/restart an execution right from where it's listed"_

I usually need to check what happened, potentially update my flow, then hit restart.

Don't you check what happened to your failed execution before replay? What are the cases where you know by default this need a restart 🤔 ?

Flow are often designed to be idempotent - meaning have the same behavior/outputs if nothing has changed in the context/inputs (yes, it depends on the user, but it's a common design pattern)

**Comment by nicoallgood** [comment]
Yup I think you got this flow right @Ben8t :
> I usually need to check what happened, potentially update my flow, then hit restart.

I think my 'UX flow' has been:
- Investigate Logs of execution (to understand the problem)
- hit 'Edit flow' top button (to go fix the problem)
- at this stage I cannot hit Execute top-right because my flow depends on output of a parent flow
- and so I go back to _Executions_ tab
- and this is where I was hoping to _Replay_ directly (instead of having to re-open last execution)

For sure no biggie (though let me know if my steps are surprising) + Loïc's tip helped me actually figure it out.

It's fine for me if we close this as is for now!

**Comment by Ben8t** [comment]
Ok thanks for the details !!
Let's close for now - probably a small improvement to keep in mind around shortening the feedback-loop - mostly tackled here https://github.com/kestra-io/kestra-ee/issues/1547
