### ISSUE TITLE
Consider leveraging optimistic concurrency control (OCC) for executions in progress

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4808]
## Use cases

OCC might be useful for the following use cases:
- change task run state
- change execution state
- delete an execution
- change execution labels

We want the executor to manage 100% of the execution state. 

## Context

We increment a number the first time Execution is created.

When the executor starts the first task run, we increment this number again, and we continue incrementing this number anytime there is a change in the execution state.

When a user attempts to Delete an execution, we send the Execution ID and the sequence number. For stuck executions, we allow their deletion, because the executor will no longer attempt to process it since it's acknowledged as a deleted execution. 

The [OCC-like sequence number](https://en.wikipedia.org/wiki/Optimistic_concurrency_control ) implementation already exists in the Kafka implementation but not on JDBC yet

**Comment by loicmathieu** [comment]
We will investiguate more about this issue on the next cooldown period before thinking about an implementation, see https://github.com/kestra-io/kestra/issues/4826
