### ISSUE TITLE
Flows => Source Search has multiple pages but no data returned

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4841]
### Describe the issue

Flows => Source Search has multiple pages but no data returned 

![image](https://github.com/user-attachments/assets/6c89d3bf-8e3c-466a-9234-f9bf2451bc9c)
![image](https://github.com/user-attachments/assets/b9bea68f-052a-4daa-876e-c6d2399a53a6)

### Environment

- Kestra Version: Develop
- Operating System (Docker):

**Comment by Ben8t** [comment]
When search is empty it indeed return no results. However when filling the search everything looks good.

Not sure we want to load all logs by default. Prefer to wait for user inputs.

-> Change the message "No logs emitted so far" by "Search results are empty."

**Comment by sachinks07** [comment]
I would love to work on this issue. thanks!

**Comment by MilosPaunovic** [comment]
@sachinks07 Any progress on this?

**Comment by sachinks07** [comment]
Will fix this issue today and raise the pr.

**Comment by MilosPaunovic** [comment]
Fantastic, thanks for all the efforts! 🚀

**Comment by Skraye** [comment]
THe original issue here was that even with no result, we had pagination 
![image](https://github.com/user-attachments/assets/85aeb7cc-8b42-4f02-b8e0-57ff758e6d9c)
But I could not reproduce anymore, so I merge @sachinks07 [PR](https://github.com/kestra-io/kestra/pull/5497) that correct the message, feel free to re-open if the issue happen again @smunteankestra

**Comment by sachinks07** [comment]
Sorry, I misunderstood the issue I just thought we need to update the incorrect message. I am able to reproduce the issue. Will fix it and raise the pr. 

<img width="1786" alt="Screenshot 2024-10-16 at 7 52 18 PM" src="https://github.com/user-attachments/assets/3a8c6000-8d62-4108-bbdd-d046814be4b0">
