### ISSUE TITLE
Docker image missing for latest release in Docker Hub

### ISSUE THREAD

**Issue by zd-dalibor** [kestra-io/kestra#4844]
### Issue description

Docker image missing  in Docker Hub for latest release v0.18.5.

<img src="https://github.com/user-attachments/assets/b40c4d46-1140-47aa-95cb-632d3bc9279d" width="400px"/>
<img src="https://github.com/user-attachments/assets/91cf73fa-e8fe-4b18-8a0c-0e58e8d5a6b1" width="400px"/>

Are you using different registry starting from version 0.18.5?

**Comment by loicmathieu** [comment]
Thanks, we forgot to push the images, it's done now.
