### ISSUE TITLE
Create Flow - Pre-fill namespace from current filter

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/kestra#4863]
### Feature description

**Use-case**
When orchestrating worflow(s), one may have to write multiple Kestra flows within a common namespace. While progressing, the main _Flows_ page, filtering on the _namespace_ is a nice way to keep tabs on where things stand. In that 'contextual' view, it would be convenient to have the context/filter info automatically applied to a flow created from there.

**Proposal**
If a user hits _Create_ on the Flows page with an active filter on namespace, pre-fill the vanilla flow with that same namespace

**Illustration**

![prefill](https://github.com/user-attachments/assets/060f35e8-52af-4a0e-990a-4b7d8647e138)

💅🏻

**Comment by Ben8t** [comment]
Definitely something I was considering too. Thanks for the issue !

**Comment by riyamustare** [comment]
Hey can you assign me this task?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it! 🚀

**Comment by riyamustare** [comment]
thankyou!
