### ISSUE TITLE
Have a pop up over the Trigger tab to tell the user that they need to add a trigger first

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4865]
### Feature description

The Trigger tab is greyed out until there is a trigger present in the flow. This can be confusing as you might assume you would configure a trigger from scratch in this menu.

Can also be confused as a paid feature too (like the greyed out namespace tabs).

To resolve any confusion, add a little hover pop up to say "Add a Trigger in the Editor first"
![tgiggers](https://github.com/user-attachments/assets/dcc154e0-5b42-409d-879e-4277d3d464ba)

**Comment by kumaradityaraj** [comment]
@MilosPaunovic  I want to work on this issue. Please assign me. Thank you.

**Comment by mounikaperi** [comment]
@wrussell1999 @MilosPaunovic I would like to contribute to this issue. If no-one else has picked this up yet please do assign it to me

**Comment by MilosPaunovic** [comment]
@mounikaperi Go for it!

**Comment by mounikaperi** [comment]
@MilosPaunovic i am done with the code changes but unable to test in local
with dockerfile in develop branch i am receiving below error
/usr/local/bin/docker-entrypoint.sh: 5: exec: /app/kestra: not found

**Comment by MilosPaunovic** [comment]
@mounikaperi Check this guide out, it should solve all the issues you're having with the BE setup. https://kestra.io/docs/getting-started/contributing#setup-to-work-without-building-the-backend-from-the-source-code

**Comment by mounikaperi** [comment]
@MilosPaunovic once i follow all the steps from above guide, how do i ensure the changes that i have done in my new branch feature-issue-4865 are pulled as the docker compose file has image of develop

**Comment by MilosPaunovic** [comment]
You can run BE from docker, and run FE locally, using `npm run dev`, so you owuld get HMR properly running.

**Comment by mounikaperi** [comment]
@MilosPaunovic @wrussell1999 
Please review https://github.com/kestra-io/kestra/pull/5358
Test results attached
