### ISSUE TITLE
Inputs & Variables in "Edit Metadata" low code form shouldn't be deletable

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4868]
### Describe the issue

Step 1: Create and save a Flow
Step 2: Navigate to Actions => Edit Metadata
Step 3: Remove Variables and inputs

https://github.com/user-attachments/assets/a7f00969-bf89-49b6-97c5-e1b4805d4a0d

### Environment

- Kestra Version: develop
- Operating System (Docker):

**Comment by Ben8t** [comment]
Good catch, even if reopening this "Edit Metadata" form put back the inputs and variables forms... issue is still valid, probably easy to fix

**Comment by shabith16** [comment]
Hi, is there anyone working on this issue.

**Comment by MilosPaunovic** [comment]
@shabith16 You're absolutely welcome to take it on!

**Comment by shabith16** [comment]
yes I will work on this

**Comment by MilosPaunovic** [comment]
Great work here @sachinks07! :rocket:
