### ISSUE TITLE
Add success message and Flow Metadata are saved through the low code form

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4870]
### Feature description

Step 1: Create and save a Flow
Step 2: Navigate to Actions => Edit Metadata
Step 3: Edit some data
Step 4: Click Save button
Please add a Success Message
![image](https://github.com/user-attachments/assets/69b7585a-f856-4268-841e-3b238a5fef2f)

**Comment by pranavmugatkar** [comment]
Hello @MilosPaunovic   , I am interested in contributing to this issue. as am beginner in open source contribution Any guidance or specific requirements would be greatly appreciated. Thank you!

**Comment by MilosPaunovic** [comment]
Hi @pranavmugatkar, thanks for the will to contribute, it's greatly appreciated! 🚀 

First steps would be to try and follow this contributor guide https://kestra.io/docs/getting-started/contributing.

**Comment by pranavmugatkar** [comment]
Thank you @MilosPaunovic, I understand all the rules and steps to be followed, now can I take the issue for contribution?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it!

**Comment by MilosPaunovic** [comment]
Actually, after a bit of investigation here, it is confirmed that on metadata editor, when we make a change and hit save button, the flow itself is not being saved on server, but only the changes locally.

To save the entire flow, you need to click the `Save` button in the top right corner, just above the editor itself.
