### ISSUE TITLE
The user/system filter should be multiselect

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4873]
![image](https://github.com/user-attachments/assets/5db18073-cafe-4bdb-9636-d9640418c34e)

as discussed https://github.com/kestra-io/kestra/issues/4557, the filter needs to allow selecting both at the same time. We can either:
1. Make this multiselect field
2. Add option for both "User and System Flows"

option 1 is better

**Comment by MilosPaunovic** [comment]
The BE is created in a way that if no parameter is sent it acts as both were selected. Do we need it to be explicit?

**Comment by anna-geller** [comment]
I believe so, yes -- It took me a while to understand that removing filter is the option to have both but even then, the Only User Flows should be the default option, not both

**Comment by brian-mulier-p** [comment]
part of it:
https://github.com/kestra-io/kestra/commit/af4fc147d5e434589ef5f0d19555b1c553a2250b
https://github.com/kestra-io/kestra-ee/commit/85075a4844512db27f9f45ef73981aded82e5477

**Comment by MilosPaunovic** [comment]
This has now been pushed to develop, so if you could check it once you have some time, @anna-geller, that would be great!

**Comment by anna-geller** [comment]
LGTM -- the "Only" doesn't make that much sense given you can select both so I'll cut it and we're good 👍 
![image](https://github.com/user-attachments/assets/39dda4bf-0b8d-435e-b8ab-12d9d01a7ec0)
