### ISSUE TITLE
Test the behavior and document that our scheduler can be horizontally scaled, even on JDBC architecture

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4891]
### Feature description

@Skraye as discussed:

- [x] Test that this works
- [x] Update our Architecture documentation with info that it now can be scaled and is no SPOF anymore https://kestra.io/docs/architecture

**Comment by anna-geller** [comment]
the issue shouldn't have been closed without docs updated

I did it now https://github.com/kestra-io/docs/commit/b8e5e8838621280da69dbd8825e98e3d7c7bd62a - @Skraye please validate if we need to add anything in the docs

**Comment by Skraye** [comment]
Docs were updated, however, issue wouldn't have been closed https://github.com/kestra-io/docs/commit/8d25f61c86311482b42b02f352f1a2896facfd3d

**Comment by anna-geller** [comment]
Very strange, you can see that 2 days ago we still have in the docs "the only exception is the Scheduler, you can have only one Scheduler component in a JDBC-based architecture (_in the near future, Scheduler will also be able to scale_)." - must have been some docs build issue. thx for clarifying!
