### ISSUE TITLE
Quick enhancements to the new log levels

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4896]
### Feature description

![image](https://github.com/user-attachments/assets/b01ece83-8ed3-499a-895d-3069e493f0cc)

- [ ] change log level to uppercase 
- [ ] cut the arrow (or change the visual so that users don't get the idea they need to click on it

**Comment by Nico-Kestra** [comment]
We can delete arrow. And also, I wonder if we should only highlight the one that is selected and not the others.
