### ISSUE TITLE
Disable flow toggle does not work

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4906]
### Describe the issue

Editing a flow - and toggle disable

https://github.com/user-attachments/assets/b347d317-e769-400a-ba05-ce2974c0b5b2

### Environment

- Kestra Version: develop
- Operating System (Docker):

**Comment by mounikaperi** [comment]
@smunteankestra @MilosPaunovic 

I would like to contribute to this issue. Can you please assign it to me if no one else is already working on this issue?

**Comment by mounikaperi** [comment]
@smunteankestra @MilosPaunovic 
with latest ui, i dont see actions -> edit metadata in flows -> editor  section
can you please check and let me know on how can I proceed further?
![image](https://github.com/user-attachments/assets/4c9ca35b-aa81-42e4-8ceb-c78a284924dd)

**Comment by smunteankestra** [comment]
@mounikaperi hi, can't reproduce on my side, try pulling again latest or develop, might help

**Comment by mounikaperi** [comment]
@smunteankestra @MilosPaunovic 
can you please review the MR (https://github.com/kestra-io/kestra/pull/5265) and let me know if the code changes look good. Please feel free to drop any review comments

**Comment by mounikaperi** [comment]
@smunteankestra @MilosPaunovic 
Do the changes look good? Can we proceed and merge it?

**Comment by smunteankestra** [comment]
@mounikaperi  we need to fix this https://github.com/kestra-io/kestra/issues/5273 if you wish I can assign it to you

**Comment by mounikaperi** [comment]
@smunteankestra is the PR of this issue related to https://github.com/kestra-io/kestra/issues/5273?

**Comment by Ben8t** [comment]
@smunteankestra not sure #5273 is related to this issue 🤔 

@MilosPaunovic can you check if the PR provided by @mounikaperi (#5265 ) fix this one 🙏 ?

**Comment by mounikaperi** [comment]
@smunteankestra @Ben8t 
I see @MilosPaunovic  merged the MR.
You can close the issue
Will start with the other one
Thank you!!!

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/kestra/pull/5265.
