### ISSUE TITLE
Improve logToFile display of the preview and download buttons

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4909]
### Feature description

https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=1446-11615&t=54jFXASaFGiOifWd-4 

![image](https://github.com/user-attachments/assets/bd899b28-553a-4111-995e-3b56288fe050)

Current state:

![image](https://github.com/user-attachments/assets/42136eb5-536c-4371-87ac-c0374eb689ae)

The adjustment will be needed for both `Logs` tab and `Gantt` view too:

![image](https://github.com/user-attachments/assets/2b5f230f-f273-4089-be17-e5f8cfa2db26)

**Comment by sachinks07** [comment]
@anna-geller I would like work on this issue. Can I get the access to Figma have requested for it. Thanks

**Comment by MilosPaunovic** [comment]
@sachinks07 We can not provide access to Figma to outside contributors, but it's basically the first image from description of this issue - to move the purple buttons on the right side of the line.

**Comment by sachinks07** [comment]
Understood. Thanks.

**Comment by MilosPaunovic** [comment]
Hey @sachinks07, any progress on this?

**Comment by sachinks07** [comment]
No, actually I wasn't able to reproduce this scenario. Will try once again and let you know the progress tomorrow.

**Comment by MilosPaunovic** [comment]
Is there any progress with this @sachinks07?

**Comment by MilosPaunovic** [comment]
Hi @anna-geller, could you provide minimal flow reproduction for this?

**Comment by anna-geller** [comment]
You can use the default hello world flow, only add this line to the task: `logToFile: true`
