### ISSUE TITLE
Add Executions tab filtered by a namespace to the Namespace page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4954]
### Feature description

![image](https://github.com/user-attachments/assets/5c881444-eb2c-47bf-a9fd-0b4a360c934d)

**Comment by sachinks07** [comment]
@MilosPaunovic Can I work on this. thanks!

**Comment by MilosPaunovic** [comment]
Yes, definitely, go for it! 🚀

**Comment by sachinks07** [comment]
Thanks, I have already made the changes have raised the pr #5322. Let me know if any changes required.
