### ISSUE TITLE
Multiple Runtime triggers crash Kestra

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4976]
### Describe the issue

Steps to reproduce - Run test "flowsAddActionTrigger"  located in e2e-tests-ee/src/test/java/io/kestra/qa/tests/FlowsTest.java

add the repeated test tag 
![image](https://github.com/user-attachments/assets/f2b271f8-106b-46c0-aa2d-06e362f459e6)
And add more threads for triggering faster 

![image](https://github.com/user-attachments/assets/adb612db-4aca-44eb-8d2a-9e1643e55e6b)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Ben8t** [comment]
@smunteankestra for my interesting: what do you mean by "Multiple Runtime triggers" ?

**Comment by smunteankestra** [comment]
@Ben8t   (in a few words: add a large amount of triggers at the same time)
tiger an automated test that will create: A new Flow and then add  a Realtrime trigger to it => repeat this flow 100 times - with 8 threads in parallel - this will overload kestra with Triggers

**Comment by loicmathieu** [comment]
This is a known issue, we need to review the threading model as it cannot scale with the number of realtime trigger.

**Comment by loicmathieu** [comment]
The root case is in fact https://github.com/kestra-io/kestra-ee/issues/1773.
Closing this one in favor of https://github.com/kestra-io/kestra-ee/issues/1773
