### ISSUE TITLE
Add Labels filtering option to Dashboard screen

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#4981]
### Feature description

I think it'd be cool to have labels filter option in Dashboard screen. And then have graph/stats update when you add label(s) to show stats, would be useful in reporting execution data to company.

Image shows current dashboard, would just want labels added somewhere, and then graphics/stats to update when it is filtered on.

<img width="1101" alt="Screenshot 2024-09-19 at 10 30 42 AM" src="https://github.com/user-attachments/assets/20671b98-f909-4b8a-ba3a-99d71b7ed52e">

Lemme know if this is possible, or if anyone has thoughts on it.

**Comment by Ben8t** [comment]
We have the project to add "custom dashboard" with possibilities to filter by label, add aggs, etc. 

So definitely in the pipe 😉  Closing this one for now. We will keep you posted !
(internal reference in EE repo https://github.com/kestra-io/kestra-ee/issues/1711)
