### ISSUE TITLE
Cannot load UI 

### ISSUE THREAD

**Issue by gjdoyle** [kestra-io/kestra#499]
### Expected Behavior

after running docker-compose up -d the UI should open on port 8080

### Actual Behaviour

Received error in CMD : Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/wait-for-it": stat /usr/bin/wait-for-it: no such file or directory: unknown

I have an Ubuntu image and have placed the docker-compose.yml file in a folder on my desktop.  

### Steps To Reproduce

With the docker-compose.yml file in a folder on my desktop I ran docker-compose up -d in my command prompt. 

I should note that I do not currently have kafka installed. 

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes): Windows 10, Docker
- Java Version (If not docker):

**Comment by tchiotludo** [comment]
I was in a middle on trying to stabilize the docker compose. 
I've just updated the compose right now.
Can you retry please ?

**Comment by eregnier** [comment]
@tchiotludo same here , I still have the error.

**Comment by tchiotludo** [comment]
@eregnier: can you try please ? :  
```yaml 
# redownload last docker-compose.yml
docker-compose down 
docker-compose rm 
docker volume prune
docker-compose pull 
docker-compose up -d 
```
If you have an old installation with old volume, the application will crash since I changed the kafka image and volume are not compatible
