### ISSUE TITLE
Kestra UI Flow overview : Add description in a never executed flow

### ISSUE THREAD

**Issue by cedrelek** [kestra-io/kestra#4992]
### Feature description

Hi,
In a flow overview page, when a flow has never been executed, there is only the panel "Ready to see your flow in action ?" and I was looking for the description of the flow.
Would it be possible to add this "Description markdown panel" ? This is a very minor feature request.

**Comment by Ben8t** [comment]
Yes 100%, I'm closing as already opened here https://github.com/kestra-io/kestra/issues/1161 ;)
