### ISSUE TITLE
Add QA automated test for the `Use` Button in Blueprints to copy over Blueprint to workflow

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#4997]
### Describe the issue

- `Use` Button in Blueprints doesn't copy over Blueprint to workflow, instead creates Log example workflow
- happening to blueprint `Load a CSV file to a Postgres table` after I click `Use` on top right

![Screenshot 2024-09-20 at 2 17 32 PM](https://github.com/user-attachments/assets/10018022-05b1-49a2-9ac1-56f020970e63)

### Environment

- Kestra Version: 0.18.7
- Operating System (OS/Docker/Kubernetes): Kestra Cloud
- Java Version (if you don't run kestra in Docker): n/a

**Comment by anna-geller** [comment]
@smunteankestra this keeps reappearing, it's now fixed on develop but it keeps coming back so we should add some automated QA to catch that

**Comment by smunteankestra** [comment]
covered with automation
