### ISSUE TITLE
Relative/Absolute filter on the Executions page is split into 2 lines

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4998]
### Describe the issue

on both OSS and EE:

![image](https://github.com/user-attachments/assets/6e18e8c4-bbca-4f44-8671-51831568a4d4)

![image](https://github.com/user-attachments/assets/a552d4ac-33dd-4a81-8923-0b0802a87673)

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
Same behavior on logs, see https://github.com/kestra-io/kestra/issues/5044#issuecomment-2374098469.
