### ISSUE TITLE
Welcome page is showing up instead of the main Dashboard even after multiple successful executions

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4999]
### Describe the issue

We overcorrected the Welcome page to the point that sometimes the Welcome page is showing up instead of the (beautiful!) new main Dashboard; see the screenshare: https://share.descript.com/view/FdZBHxGhV6m 

The opposite issue is also still open, worth tackling together https://github.com/kestra-io/kestra/issues/4724 

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
if there is at least one execution, this means user already went through the getting started and the welcome page doesn't need to be shown, we can show the new Dashboard

**Comment by MilosPaunovic** [comment]
Welcome page is now only shown only there is `0` executions and if the number of flows is `0` (not counting `tutorial` namespace ones).

**Comment by anna-geller** [comment]
overcorrected -- the Welcome page is now not showing up at all even though I have no Executions -- see explanation https://share.descript.com/view/vGBSWExGHkb
