### ISSUE TITLE
Low-code topology editor follow-up

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5000]
### Feature description

Follow up to https://github.com/kestra-io/kestra/issues/4581:
- [x] https://github.com/kestra-io/kestra/issues/3334 
- [x] https://github.com/kestra-io/kestra/issues/2058
- [x] https://github.com/kestra-io/kestra/issues/4870
- [x] https://github.com/kestra-io/kestra/issues/4868
- [x] https://github.com/kestra-io/kestra/issues/5051
- [x] https://github.com/kestra-io/kestra/issues/5071

**Comment by MilosPaunovic** [comment]
Closing this as two remaining issues are already opened as separate ones.
