### ISSUE TITLE
Improve empty states on main dashboard

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5017]
Improve empty states of charts and tables (there already is a design for it, [here](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=2194-28454&node-type=frame&t=XILzkbsqrZe4YFh7-0))

Follow up on https://github.com/kestra-io/kestra/issues/3822#issuecomment-2363978033.

**Comment by Sanjai451** [comment]
I'm Interested in this project. Can I get assigned?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @Sanjai451! 🚀 

I'm pasting the imagined empty states from Figma below:
![image](https://github.com/user-attachments/assets/b774993c-c891-4aad-b5d2-ede6a55747e1)

**Comment by Ben8t** [comment]
@Sanjai451 did you succeed to make any progress on this :) ?

**Comment by Sanjai451** [comment]
I'm currently working on it, @Ben8t. As this is my first open-source project, I appreciate your understanding and patience with delays.

**Comment by anna-geller** [comment]
all "No data" visuals have been added so closing

if you meant sth else, please reopen + clarify @MilosPaunovic
