### ISSUE TITLE
Move the Delete logs button next to all actions in the top right corner

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5024]
### Describe the issue

![image](https://github.com/user-attachments/assets/bedbb24f-e500-49a7-814f-84dd85def1a6)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by AbdurRahman2004** [comment]
I see that the issue titled “400 response code on Delete flow logs” (#4663) is marked as a good first issue. I would like to request if I can be assigned to work on this issue, as I'm eager to contribute and learn.

As a beginner in open source contributions, I would greatly appreciate any guidance on how to approach this issue. If someone could help me understand the steps I should take or point me to the relevant files, I would be very grateful!

**Comment by anna-geller** [comment]
You've got it, we'd like your contribution here!

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/kestra/pull/5266.
