### ISSUE TITLE
Color of the date in the newsfeed is barely legible -- can we make it white?

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5034]
### Describe the issue

![image](https://github.com/user-attachments/assets/dd7d8368-ccd1-4f32-ae06-b36278c5d837)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Sanket-0510** [comment]
hey @anna-geller can I work on this?

**Comment by MilosPaunovic** [comment]
@Sanket-0510 Go for it, ping me for a PR review when it's done.

**Comment by Ben8t** [comment]
@Sanket-0510 did you get the chance to move forward ?

Otherwise, @MilosPaunovic can you take it back under your radar please :) ?
