### ISSUE TITLE
Executions Page options overflow over list of executions

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#5044]
### Describe the issue

When I select an execution, the options overflow the screen. I am using 125% zoom on Chrome with window half width on a 1440px wide monitor.

![Screenshot 2024-09-24 at 11 05 46](https://github.com/user-attachments/assets/775f3a30-6105-48a1-a133-f30eca28968e)

### Environment

- Kestra Version: 0.19 EE Snapshot Commit #1e06a58
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by wrussell1999** [comment]
Happens if you make the flows page super narrow too.

![Screenshot 2024-09-24 at 11 07 55](https://github.com/user-attachments/assets/50014cf6-03ca-450b-8dd2-7b12c8f80b5b)

**Comment by smunteankestra** [comment]
also similar behaviour in logs page 
![image](https://github.com/user-attachments/assets/0227f55b-0a41-491d-90d9-c1f8bfd79991)

**Comment by MilosPaunovic** [comment]
> also similar behaviour in logs page ![image](https://private-user-images.githubusercontent.com/171780240/370734504-0227f55b-0a41-491d-90d9-c1f8bfd79991.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzE0ODIsIm5iZiI6MTcyNzI3MTE4MiwicGF0aCI6Ii8xNzE3ODAyNDAvMzcwNzM0NTA0LTAyMjdmNTViLTBhNDEtNDkxZC05MGQ5LWMxZjhiZmQ3OTk5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMzMzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWI3MGI3MmFiODFhNjQxODdkNDdhMDNiZDU0M2E1MTNiMGRlOTMzMDFlMzZjNzI4MTIwNjljYjU0YjIwNzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DI-wOnUJERUyEdeU8W9GhySSRn2Ypl7q-oQmPSNW5jY)

@smunteankestra Your comment was related to this issue: https://github.com/kestra-io/kestra/issues/4998, which is now amended and merged.

**Comment by Ben8t** [comment]
@MilosPaunovic does it means this issue can be closed too ?

**Comment by MilosPaunovic** [comment]
Nope, this one opened by Will is still to be amended.

**Comment by shawnfrost69** [comment]
Hi @anna-geller @MilosPaunovic I believe I can contribute to resolving this issue. Would it be okay for me to take it on?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it! 🚀

**Comment by shawnfrost69** [comment]
I hope these changes will fix this issue, even though i tested it locally.  
https://github.com/kestra-io/kestra/pull/5742

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/kestra/pull/5742.

Thanks for the contribution @shawnfrost69! 🚀
