### ISSUE TITLE
Improve Inputs naming

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5045]
### Feature description

In the screenshot the inputs "Name" actually returns the Inputs "ID" so would be great to change the naming to "ID" rather what we have now "Name" 

![image](https://github.com/user-attachments/assets/05ebebde-e536-4c72-8a5a-e4901bc8454a)

**Comment by anna-geller** [comment]
duplicate of https://github.com/kestra-io/kestra/issues/5047
