### ISSUE TITLE
Schedule Later Time Picker disappears when scrolling down the picker

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#5046]
### Describe the issue

Picker for time disappears when trying to scroll down for a later time.
https://github.com/user-attachments/assets/5f9226e1-315e-4445-9a60-3d42543bd01f

### Environment

- Kestra Version: 0.19 EE Snapshot #1e06a58 
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by mounikaperi** [comment]
@wrussell1999 @MilosPaunovic 
I would like to contribute to this issue. 
Please do assign it to me, If no one else is working on it

**Comment by MilosPaunovic** [comment]
@mounikaperi any progress on this?

**Comment by mounikaperi** [comment]
@MilosPaunovic Yes, I will give you the PR to review in a while

**Comment by MilosPaunovic** [comment]
Awesome, thanks for the update! 🚀

**Comment by mounikaperi** [comment]
@MilosPaunovic can you please confirm if this issue is still reproducible. 
I tried reproducing it in local and could select the date.
Providing screenshot reference for the same
![image](https://github.com/user-attachments/assets/736da162-416c-4cc9-94a9-667b021b1893)

**Comment by Skraye** [comment]
@mounikaperi Have you tried opening the time selector and scrolling to the bottom?

**Comment by mounikaperi** [comment]
Yes @Skraye 
I am seeing it scrollable and it doesn't disappear
![image](https://github.com/user-attachments/assets/92b454e9-fe48-4da3-8bb3-3ee6f953f181)

**Comment by Skraye** [comment]
Effective I can not reproduce too!

@wrussell1999 If you face the issue again, please add more detail like os, browser, etc

closing for now

**Comment by wrussell1999** [comment]
It seems to work for me on 0.19.3 now. 

OS: macOS Sonoma 14.5
Browser: Chrome Version 129.0.6668.100 (Official Build) (arm64)
