### ISSUE TITLE
Cannot disable flow from low-code editor

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/kestra#5051]
### Describe the issue

If I hit _Actions_ -> _Edit Metadata_ and I try to disable the flow, the change doesn't get persisted :(

![disabled](https://github.com/user-attachments/assets/225c2f16-b9e5-40b9-a9bd-9790501fa9f5)

### Environment

- Kestra Version: 0.19.0-SNAPSHOT (d329c68)
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by sachinks07** [comment]
I would like to work on this issue. thanks

**Comment by MilosPaunovic** [comment]
Go for it @sachinks07! :rocket:
