### ISSUE TITLE
Cross dependent input - returns 500 in validate endpoint 

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5052]
### Describe the issue

Add 2 inputs that depend on each other (negative scenario) - validation will return 500

![image](https://github.com/user-attachments/assets/41471e70-d114-4753-a0d0-14b851256a0e)

`id: example_conditional_inputs
namespace: io.kestra
inputs:
  - id: "cloud_providers"
    required: false
    dependsOn: 
      inputs: [ aws_credential ]
    type: SELECT
    expression: "{{ secret('cloud_providers') }}"
    displayName:   " "
    

  - id: "aws_credential"
    type: SELECT
    values:
      - ENV
      - SECRETS
    dependsOn: 
      inputs: [ cloud_providers ]
      condition: "{{ inputs.cloud_providers equals 'AWS' }}"

  - id: "aws_access_key"
    type: STRING
    dependsOn: 
      inputs: [ aws_credential ]
      condition: "{{ inputs.aws_credential equals 'AWS' }}"

  - id: "aws_secret_key"
    type: STRING
    dependsOn: 
      inputs: [ aws_credential ]
      condition: "{{ inputs.aws_credential equals 'AWS' }}"

  - id: "azure_connection"
    type: STRING
    dependsOn: 
      inputs: [ cloud_providers ]
      condition: "{{ inputs.cloud_providers equals 'AWS' }}"

tasks:
  - id: data
    type: io.kestra.plugin.core.debug.Return
    format: SUCCESS
    allowFailure: true

  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    onResume:
      - id: "s3-bucket"
        type: STRING
        required: true
        dependsOn:
         inputs:
            - "cloud_provider"
         condition: "{{ outputs.data.value equals 'SUCCESS' }}"`

### Environment

- Kestra Version: develop
- Operating System (Docker):

**Comment by fhussonnois** [comment]
Fixed by https://github.com/kestra-io/kestra/pull/5074
