### ISSUE TITLE
Add a new dedicated design for the Flows overview page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5060]
### Feature description

For now, we show the same overview as the Namespace-level dashboard. The planned design for the Flows overview was: https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=2237-25171&t=FsvoquWA1o6L07q9-4 

![image](https://github.com/user-attachments/assets/70522311-e5d4-4488-8b8d-da42227b186b)

**Comment by Ben8t** [comment]
related to #1161 - probably can tackle both

**Comment by MilosPaunovic** [comment]
@Ben8t This should be done.

**Comment by anna-geller** [comment]
looks great!
