### ISSUE TITLE
Blueprints don't load from System Namespace

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#5069]
### Describe the issue

Works fine from the Blueprints page and then filtered by the System tag. Looks like it might be using the wrong URL? It's trying to use `/ui/blueprints/blueprints/` rather than `/ui/blueprints/community`.

It does work if you press Use. It does not work when you just click it to view.

https://github.com/user-attachments/assets/124f05f4-962e-4717-a35f-508ae0ef0848

### Environment

- Kestra Version: 0.19 EE Snapshot
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
seems no longer an issue, couldn't reproduce this specific issue on the preview https://share.descript.com/view/drMtxUxXq4x -- please reopen if I'm wrong or if I misunderstood the issue
