### ISSUE TITLE
Flow metadata is not persisted upon `Save` from low-code editor

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/kestra#5071]
### Describe the issue

If I edit flow metadata from the UI low-code editor, even changes if changes are reflected in-source, they are not 'captured' as an actual source change, and the flow's _Save_ button is therefore inoperative. Upon page reload, or any navigation to another page, I then lose these changes.

![no_save](https://github.com/user-attachments/assets/605a92fa-cbeb-472f-abe9-079a8885eaf6)

### Environment

- Kestra Version: Kestra Version: 0.19.0-SNAPSHOT (d329c68)
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by sachinks07** [comment]
I would like to work on this issue. thanks!

**Comment by MilosPaunovic** [comment]
Sure, go ahead! :rocket:
