### ISSUE TITLE
First exec upon newly added input does not ask for input

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/kestra#5072]
### Describe the issue

- defined an _input_ for my flow
- Saved the flow
- hit _Execute_
- 🔴  I am not prompted to fill the input
- 💥  Execution fails (`null` received)

Visually:

![bad_exec](https://github.com/user-attachments/assets/8a6995aa-053e-4dd1-92e7-d29556a84ffa)

**Notes**:
- at first I thought of a possible race condition, but even if I wait 5 seconds before _Execute_ the behaviour is the same
- on subsequent _Execute_ the input is correctly asked!

### Environment

- Kestra Version: Kestra Version: 0.19.0-SNAPSHOT (d329c68)
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by anna-geller** [comment]
seems fixed, can't reproduce on OSS preview 

https://preview-oss.kestra.io/ui/executions/company.team/reproducer/16rpEMospRk9jxerbRkeDM/gantt

demo https://share.descript.com/view/k1aaJhROE5C
