### ISSUE TITLE
Too much space on the Flows page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5099]
![image](https://github.com/user-attachments/assets/0cced115-f58a-4576-819f-9fae7ef459b6)

**Comment by MilosPaunovic** [comment]
Current `OSS` preview:
![image](https://github.com/user-attachments/assets/92a116af-5837-449f-bac2-c3cceb6d4b13)

Current `kafka` preview:
![image](https://github.com/user-attachments/assets/3358ca71-acba-489d-8bd4-11d1ec2a90b5)

Need more details here.

**Comment by anna-geller** [comment]
https://preview-oss.kestra.io/ui/flows/edit/demo_converteo/airbyte?startDate=2024-08-26T16:47:13.086%2B02:00&endDate=2024-09-25T16:47:13.086%2B02:00&scope=USER&flowId=airbyte

![image](https://github.com/user-attachments/assets/3c899f16-41d4-44fd-bee7-0786f78c7fb3)

**Comment by anna-geller** [comment]
if you still can't reproduce, can you ping me to huddle via Slack? maybe it's a Brave browser issue again on my end?

**Comment by anna-geller** [comment]
on EE right now https://preview-ee-kafka.kestra.io/ui/flows/edit/com.kestra.demonstration/Custom-Demonstration?startDate=2024-08-26T16:52:27.051%2B02:00&endDate=2024-09-25T16:52:27.051%2B02:00&scope=USER&flowId=Custom-Demonstration 
![image](https://github.com/user-attachments/assets/7545d20e-8753-4302-88a9-9d30308c0d8a)

**Comment by MilosPaunovic** [comment]
Yes, definitely not reproducible on my side, neither locally nor on any of the available previews. Ping me on Slack when you're available @anna-geller.

**Comment by anna-geller** [comment]
we need to center one element, visible when we zoom out

**Comment by MilosPaunovic** [comment]
Closed by two merged `PRs` from above.
