### ISSUE TITLE
Replace the Flows Execution barchart with the barchart used on the main dashboard to include axis label, legend, description of color to state mapping

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5100]
Replace this chart:

![image](https://github.com/user-attachments/assets/974c5a2c-fc2d-4927-a52e-0e993b8104c0)

with this one:

![image](https://github.com/user-attachments/assets/801e9dad-82fc-436a-b947-2903a95ddea2)

**Comment by MilosPaunovic** [comment]
@ahsan-naveed You're more than welcome to submit PR for this.

**Comment by sachinks07** [comment]
Hi @MilosPaunovic, I would love to work on this issue. Thanks.

**Comment by MilosPaunovic** [comment]
Great work @sachinks07, thanks for the contribution! 🚀 

If you're up for it, check out this [link](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=release%3A%22v0.20.0%22++label%3A%22good+first+issue%22) with filtered `good first issue` labels, where you might find something else you think you can solve.
