### ISSUE TITLE
Executions Indent

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5101]
### Describe the issue

Execution and Triggers indent not aligned

![image](https://github.com/user-attachments/assets/d3ad628f-4494-402a-b17b-c38374420c13)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by tarunchaudhary1** [comment]
Can i work on this??

**Comment by smunteankestra** [comment]
Hi @tarunchaudhary1 , sure

**Comment by Dhanush111** [comment]
hi @MilosPaunovic @tarunchaudhary1 can i solve this issue? could you please assign it to me?

**Comment by MilosPaunovic** [comment]
Go for it @Dhanush111! 🚀

**Comment by Ben8t** [comment]
@Dhanush111 did you succeed to make any progress on this :) ?

**Comment by MilosPaunovic** [comment]
Would say we can close this one @smunteankestra, as we've done the overhaul of this page some time ago?
