### ISSUE TITLE
Reevaluate link color in the tables on the main Dashboards

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5115]
![image](https://github.com/user-attachments/assets/1590c1ed-f66a-4b06-bea5-62b3ed8c6ec2)

Given that we show many links, the table has a lot of purple:

![image](https://github.com/user-attachments/assets/c38dfb91-8368-4dbf-9402-4d448e1322fc)

We can have a look during the cooldown to see whether adding some lighter color might improve the contrast

**Comment by AbdurRahman2004** [comment]
Is anyone working on this issue ?

**Comment by anna-geller** [comment]
hey, this issue needs design, perhaps you can take one of these labeled with `kind/good-first-issue`? you can check them here https://github.com/search?q=org%3Akestra-io+label%3Akind%2Fgood-first-issue+is%3Aopen&type=issues

**Comment by anna-geller** [comment]
we can use those colors 

![image](https://github.com/user-attachments/assets/d1d79109-c6e1-47e0-b74b-89992eee76d5)

@AbdurRahman2004 would you like to pick this up?

**Comment by Dev-Aditya-More** [comment]
I would like to take this issue. @anna-geller

**Comment by MilosPaunovic** [comment]
Go for it @Dev-Aditya-More! :rocket:

**Comment by AbdurRahman2004** [comment]
> I would like to take this issue. @anna-geller

Hi [Dev-Aditya-More](https://github.com/Dev-Aditya-More) I saw that you expressed interest in this issue recently. Are you currently working on it? If not, I would be happy to pick it up and help out. Let me know! 😊

**Comment by Dev-Aditya-More** [comment]
@AbdurRahman2004 Thanks for reaching out! I’ve already submitted a pull request for this issue. here's [PR](https://github.com/kestra-io/docs/pull/1883)

**Comment by MilosPaunovic** [comment]
Your PR is not opened in the right repository @Dev-Aditya-More, we don't want to change anything on the documentation page.

**Comment by Dev-Aditya-More** [comment]
yeah i noticed that! i will make another one pr hopefully correct this time give me some time.

**Comment by AbdurRahman2004** [comment]
Hi @MilosPaunovic,

I hope you’re doing well! I wanted to let you know that I have submitted a pull request addressing issue #5115, which involves updating the link colors in the tables on the main dashboards.

When you have a moment, could you please take a look at it? I would greatly appreciate your feedback!

Thank you!

Best regards,
Abdur Rahman

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @AbdurRahman2004! 🚀
