### ISSUE TITLE
The trigger toggle on the main dashboard has no effect

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5116]
### Describe the issue

![image](https://github.com/user-attachments/assets/4507812e-a59e-4710-8d4d-72b0a61f3a40)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by smunteankestra** [comment]
dublicate of https://github.com/kestra-io/kestra/issues/5107
