### ISSUE TITLE
After changing state of a execution needs refresh

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5136]
### Feature description

After change state refresh will show up the new state, would be nice to update instantly 
https://github.com/user-attachments/assets/7d224fb9-820b-4cf2-8b27-7f2fe0d3e520

**Comment by MilosPaunovic** [comment]
Can not reproduce this anymore neither on `OSS` nor `EE`. There was some work on executions recently, so it might fixed this one, as well. Could you double check @smunteankestra and close if alright?

**Comment by Ben8t** [comment]
Indeed it works on 0.20 SNAPSHOT (tested on oss-preview)
