### ISSUE TITLE
Topology view modification overwrites the flow without Saving it

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5137]
### Describe the issue

Flow should be saved to apply changes 
https://github.com/user-attachments/assets/b8fe575e-5395-4fa4-aac6-b063591e5aa3

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):

**Comment by Harsh4902** [comment]
@MilosPaunovic Can I work on this issue?

**Comment by MilosPaunovic** [comment]
Absolutely @Harsh4902, go for it!

**Comment by MilosPaunovic** [comment]
Hi @Harsh4902, any progress here?

**Comment by Harsh4902** [comment]
@MilosPaunovic I am on it.

**Comment by Harsh4902** [comment]
@MilosPaunovic I have noticed that code overwrite without saving is happening with TopologyView as well as SourcecodeView.

**Comment by MilosPaunovic** [comment]
Okay, than that needs fixing also.

**Comment by Harsh4902** [comment]
@MilosPaunovic I want little help. I found that while we are changing the without saving flow, it's actually going in the `Dirty` state. It's not getting saved, so I am not able to understand how to get it back from the `Dirty` state.

**Comment by MilosPaunovic** [comment]
@Harsh4902 You can set the `dirty` flag to false by commiting `editor/changeOpenedTabs` mutation. See https://github.com/kestra-io/kestra/blob/39c2698756e500228d692f2e1caf2f92842060fb/ui/src/components/inputs/EditorView.vue#L730 and https://github.com/kestra-io/kestra/blob/39c2698756e500228d692f2e1caf2f92842060fb/ui/src/components/inputs/EditorView.vue#L745 for more details.

**Comment by Harsh4902** [comment]
> @Harsh4902 You can set the `dirty` flag to false by commiting `editor/changeOpenedTabs` mutation. See https://github.com/kestra-io/kestra/blob/39c2698756e500228d692f2e1caf2f92842060fb/ui/src/components/inputs/EditorView.vue#L730 and https://github.com/kestra-io/kestra/blob/39c2698756e500228d692f2e1caf2f92842060fb/ui/src/components/inputs/EditorView.vue#L745 for more details.

Aha, got it.

**Comment by MilosPaunovic** [comment]
The PR from @Harsh4902 is now merged to `develop` branch, he did a great job on it, but I'll move this issue to `In Review` state until @smunteankestra gets a change to re-test it and confirm that it is now solved.

**Comment by smunteankestra** [comment]
fixed
