### ISSUE TITLE
Kestra dashboard not displaying results and charts

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5142]
### Describe the issue

Fresh kestra postgres instance, run the first flow - "logs" for instance
Expected result: Dash should show the chart

![image](https://github.com/user-attachments/assets/e2b167e1-84f7-43af-8ad2-60318e0ff38a)

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):

**Comment by anna-geller** [comment]
this is now fixed on develop, LGTM now

![image](https://github.com/user-attachments/assets/43361c64-5cf2-4526-a796-139ca3aa499a)

**Comment by smunteankestra** [comment]
on EE works 
![image](https://github.com/user-attachments/assets/f8c27eb7-6521-49d7-a24e-bb74ff7371c9)
but on OSS does not 
![image](https://github.com/user-attachments/assets/85e80382-bce5-4ffe-a928-919dc88fd97a)

**Comment by smunteankestra** [comment]
wrong item sorry
