### ISSUE TITLE
2 min issue -- remove extra } in the tooltip

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5157]
### Describe the issue

super quick win one -- remove extra }

![image](https://github.com/user-attachments/assets/3aabd034-236c-4e46-bd9a-eece6a6e17a1)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/kestra/commit/f2d562bbbfb3b64b8d284b2bb2cde312410ebbfb.
