### ISSUE TITLE
the Flow Dashboard has too much space at the top on screens with a larger resolution like 3456 × 2234

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5158]
### Describe the issue

Due to one element that is put in center, the Flow Dashboard has too much space at the top on screens with a larger resolution like 3456 × 2234

@MilosPaunovic as discussed in a huddle on Thursday

Example what I see: 

![image](https://github.com/user-attachments/assets/1237be77-3bba-4c4a-b488-f1ed64966bb4)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Related to https://github.com/kestra-io/kestra/issues/5099.
