### ISSUE TITLE
The "Logs" chart on the main Dashboard is currently not populated with any data even though bunch of logs exist

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5159]
### Describe the issue

![image](https://github.com/user-attachments/assets/c7b2381e-4bf1-4ece-9851-25304cc1bf9e)

video demo: https://share.descript.com/view/B9La34SqEav 

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
I can't reproduce this. Could you try to clear local storage and try again (or use different browser), and if stril borken, check network tab, look for `/api/v1/stats/logs/daily` to see if the results have arrived from server. @anna-geller

**Comment by anna-geller** [comment]
@smunteankestra can you try to reproduce?

**Comment by smunteankestra** [comment]
On OSS can reproduce
![image](https://github.com/user-attachments/assets/854871c5-b2b5-4c52-b4c9-4cd90760c959)

on EE works fine

**Comment by anna-geller** [comment]
that's what I expected -- @MilosPaunovic do you remember what we agreed in the meeting with Ludo? 😄 we anticipated this chart may not work on JDBC and the plan was to only include it in EE with Kafka backend unless we somehow optimize some index and find a way to make it work on JDBC -- it looks like we need to cut this chart on JDBC

**Comment by MilosPaunovic** [comment]
@anna-geller On FE I do not have information on which backend we're using, but on the preview OSS I see logs properly.
![image](https://github.com/user-attachments/assets/a390d036-0d62-4ee3-b7fe-de5c4f0c8c4c)

**Comment by smunteankestra** [comment]
I was using postgres - try toi run this command docker run --pull=always --rm -it -p 8080:8080 --user=root \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp:/tmp kestra/kestra:develop server local

**Comment by anna-geller** [comment]
on OSS preview it's quite laggy - https://share.descript.com/view/ykvPqDarMyt 

first feeling is that we'll need to cut it on the OSS edition to avoid issues that it either doesn't show up or has a big lag 

for now, I re-pulled the image and it's now showing up again 🤷 will close for now and let's watch this after the release - we'll take action if it keeps reappearing 

![image](https://github.com/user-attachments/assets/9443f933-6db5-430e-8998-b848f013c56f)
