### ISSUE TITLE
Add a UI linter for usage of `this` in vue template

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5181]
### Issue description

Using `this` in vue template works when running the apps via `npm run dev` but not when build.

We have a lot of these issues, like https://github.com/kestra-io/kestra/pull/5180 so we need to add a linter for that so CI fail.

Byt the way, InteliJ warn about it!

**Comment by yuri1969** [comment]
The ESLint Vue plugin apparently doesn't treat the `this` keyword in Vue templates as something leading to unintended behavior but as a mere stylistic problem. This is why it wasn't caught by the current linter setup.
