### ISSUE TITLE
[UI] Two minors navigation bugs on the in-app docs

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5182]
### Describe the issue

1. Click on docs -> Developer Guide: the section on the navigation is opened then closed
2. Clic on docs -> Concepts -> Flowable tasks then scroll down. CLick on Runnable tasks, the scroll didn't goes up

### Environment

- Kestra Version: 0.19.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by brian-mulier-p** [comment]
The 1. was fixed ([this one](https://github.com/kestra-io/kestra/commit/9dc32febf6183efac0f4324b88b5a7eb47187cc8)) and I can't reproduce 2. so I believe it's also fixed, feel free to reopen if I missed something
