### ISSUE TITLE
[UI] In-app docs are missing a title

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5183]
### Describe the issue

None of the documentation pages have a title.
See the following, it misses the **Docker** title.

![image](https://github.com/user-attachments/assets/a1110af1-6cbd-4390-b0fa-1cdf7223f090)

### Environment

- Kestra Version: 0.19.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by vedang685** [comment]
@loicmathieu I can see the title in the navbar. Is the issue about rendering the title above the content inside the document page?

<img width="1224" alt="Screenshot 2024-09-29 at 4 58 37 PM" src="https://github.com/user-attachments/assets/9e36ede1-2044-4784-8e7d-53a8e1a322aa">

**Comment by loicmathieu** [comment]
Yes but it may already be fixed as this functionality is a work in progress.
Let's wait to avoid double work
