### ISSUE TITLE
In app docs menu scroll bar too narrow to click

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#5186]
### Describe the issue

When scrolling, it only scrolls the page
https://github.com/user-attachments/assets/9fad08e6-5349-4a69-a965-ecac04f76288

### Environment

- Kestra Version: 0.19 Snapshot EE
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by wrussell1999** [comment]
Seems to work now but the scroll bar is so narrow, it's hard to click to scroll manually.
![Screenshot 2024-09-30 at 16 49 52](https://github.com/user-attachments/assets/c2df3c91-af1b-4846-94b5-03586a2a7162)

**Comment by VarshaUN** [comment]
hi @wrussell1999 if this issue is open can u assign it to me??

**Comment by wrussell1999** [comment]
Looks like this is assigned to @brian-mulier-p who might be happy for you to have a go first!

**Comment by MilosPaunovic** [comment]
Thanks for you contribution @VarshaUN, keep up the good work! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/5473.
