### ISSUE TITLE
Filters and the chart on the Executions page are gone 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5192]
### Describe the issue

See demo: https://share.descript.com/view/OtxRb6clRzz 

![image](https://github.com/user-attachments/assets/21effcf1-4fca-4926-855c-64a17cbffc82)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by karthik7129** [comment]
Hello @anna-geller  I am a newbie here can I try to work on this issue...

**Comment by anna-geller** [comment]
sure, you can give it a try 👍 for transparency, this issue is a regression - some bug introduced in a commit done within the last 2 days as this issue didn't exist before 

feel free to check [this contributor guide docs page](https://kestra.io/docs/getting-started/contributing) if you have any issues along the way + or ask us in the #contributors channel in our Slack: https://kestra.io/slack

**Comment by karthik7129** [comment]
Thanks for supporting ☺️

**Comment by anna-geller** [comment]
reopening as the fix from https://github.com/kestra-io/kestra/pull/5195 hasn't solved the issue 

![image](https://github.com/user-attachments/assets/71d2a4bb-ff11-4a2d-a290-2e2d3a569394)
