### ISSUE TITLE
Move "Language" selection to "Localization" section next to Timezone and Date format settings

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5193]
It makes sense that Language and Region are configured together so we can move both into a dedicated **Localization** section (or maybe call it "Language and Region?"):

![image](https://github.com/user-attachments/assets/b6596c5c-f52a-4784-ae29-68903f336950)

**Comment by vedang685** [comment]
@anna-geller Is anyone working on this issue?

**Comment by anna-geller** [comment]
Not yet, feel free to take it if you'd like to contribute 🙏

**Comment by Sanjay8602** [comment]
Hello I would like to work on it. First I will go through the code if possible

**Comment by kaushal-03** [comment]
hi can i take this issue

**Comment by vedang685** [comment]
@Sanjay8602 @kaushal-03 Yes please go ahead!

**Comment by mohdshubair313** [comment]
please assign to me

**Comment by anna-geller** [comment]
wow, love the enthusiasm, big thanks to all of you! How about this plan: let's contribute a PR - we'll take the first PR and everyone else will be able to add your review? 🙏

**Comment by ssparser** [comment]
hello @anna-geller i have made the changes and raised a pull request. 
[pull request](https://github.com/kestra-io/kestra/pull/5196)

this could be my first contribution. Thank you.

**Comment by Ben8t** [comment]
thx @ssparser for the contribution ❤️
