### ISSUE TITLE
Missing option to deselect the log level and return to a regular logs view

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5198]
### Describe the issue

The new log level navigation is super useful but it's currently lacking the option to "unselect" the log level and go back to the regular log view: https://share.descript.com/view/OZhpej37qI0

![image](https://github.com/user-attachments/assets/8b7539c1-94c3-4718-bfd8-269005e5b47a)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by aninditamitro** [comment]
@anna-geller I would like to contribute to this issue. Please assign it to me if no one else is looking into it.

**Comment by anna-geller** [comment]
thanks so much @aninditamitro

**Comment by Ben8t** [comment]
@aninditamitro did you get the chance to move forward on this issue ?

**Comment by aninditamitro** [comment]
> @aninditamitro did you get the chance to move forward on this issue ?

Thank you for checking in. I’ve reviewed the documentation and have gained a good understanding of the issue. However, I’m currently unsure of the best approach to solve it. Could you provide some guidance on how I should proceed or suggest any resources that might be helpful in tackling this?

I appreciate your support and look forward to your suggestions.

**Comment by anna-geller** [comment]
@aninditamitro don't worry, this one is actually already solved on develop 🚀 see a demo here https://share.descript.com/view/iQ4enBt8zZI

will close the issue, feel free to pick up another one marked as a [good first issue](https://github.com/search?q=org%3Akestra-io+label%3A%22good+first+issue%22+is%3Aopen+label%3Aarea%2Ffrontend++no%3Aassignee&type=issues&utm_source=GitHub&utm_medium=github&utm_campaign=hacktoberfest2024&utm_content=Good+First+Issues) 👍
