### ISSUE TITLE
Add "See all" options to Executions in progress + Next scheduled executions

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5200]
### Feature description

It would be helpful to have a link in the top right corner allowing to navigate to all Executions in progress/scheduled: https://share.descript.com/view/RH0QguM7YJS 

![image](https://github.com/user-attachments/assets/918e2479-b48b-4d3a-83a4-7ef5cfd0ab72)

**Comment by Chaitanya-087** [comment]
hello @anna-geller i want to contribute to this issue. But i am having issue setting up this code in local

**Comment by MilosPaunovic** [comment]
Hi @Chaitanya-087, have you followed the steps from https://github.com/kestra-io/kestra/blob/develop/.github/CONTRIBUTING.md?

**Comment by anna-geller** [comment]
@Chaitanya-087 the up to date version of contributor guide https://kestra.io/docs/getting-started/contributing

**Comment by Chaitanya-087** [comment]
thank you @anna-geller

**Comment by Chaitanya-087** [comment]
![image](https://github.com/user-attachments/assets/e2939c79-8358-42ca-ae37-49d87033baf2)

getting errors not able to build, run

**Comment by loicmathieu** [comment]
@Chaitanya-087 it seems you don't have the correct Java version, we're using Java 21. Please ask help on our Slack contributors channel for help on contributing.

**Comment by Unga-batman** [comment]
hi @MilosPaunovic  @loicmathieu @anna-geller I am trying to set up the project locally. the build was successful, but the backend server is not running. Also,  gradle task `./gradlew runstandalone` mentioned in https://kestra.io/docs/getting-started/contributing is not available.

**Comment by Chaitanya-087** [comment]
@anna-geller, please assign this to me

**Comment by Chaitanya-087** [comment]
![image](https://github.com/user-attachments/assets/ead53d38-9582-45f9-96b1-5ce0cd24ae69)
should is also write see_all in en.json

**Comment by MilosPaunovic** [comment]
Yes, you should, but only in English. We have a workflow which will generate values for other languages.

**Comment by Chaitanya-087** [comment]
Hi, did the changes and raised a pull request, made changes to en.json, inProgress.vue, nextScheduled.vue files

- nextScheduled

![image](https://github.com/user-attachments/assets/246b08fb-00fa-4a9f-a18b-0a1b6b5ce23e)

- inProgress

![image](https://github.com/user-attachments/assets/081b91da-f273-44b8-86fc-378fac649692)

- style same for both

![image](https://github.com/user-attachments/assets/816087be-a3bc-4fa6-afca-ca7780bc0c79)

- added see_all to translations/en.json

![image](https://github.com/user-attachments/assets/c36f13d4-ad29-41c2-8c2f-7416e4a8f555)

please checkout the pr below
[pull request #5260 ](https://github.com/kestra-io/kestra/pull/5260)
