### ISSUE TITLE
Code syntax highlighting is no longer visible in the plugin documentation

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5208]
![image](https://github.com/user-attachments/assets/04efd2db-1bc0-4b5e-b319-1f2496df045e)
- No More code highlight 
- line height is too large

**Comment by MilosPaunovic** [comment]
Where is this happening @tchiotludo?

**Comment by tchiotludo** [comment]
on the embed documentation of the editor

**Comment by tchiotludo** [comment]
also visible on the plugins page 
![image](https://github.com/user-attachments/assets/68e89293-1fc0-4e00-a6e3-93c929f1b7e0)
(EE on my test)
