### ISSUE TITLE
Topology execution status are not visible

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5216]
Actual : 
![image](https://github.com/user-attachments/assets/583505c6-a162-4d9f-aa83-10ebf23a5170)

Should be: 
![image](https://github.com/user-attachments/assets/f22637d0-46c3-4326-9129-c84e7c57c2a1)

**Comment by MiirzaBaig** [comment]
would love to give it a try... if there isn't any assignees assigned to it

**Comment by anna-geller** [comment]
@MiirzaBaig do you know how to proceed? you can reproduce by running any tutorial flow and going to the Execution topology view

**Comment by MiirzaBaig** [comment]
@anna-geller Got it....

**Comment by Ben8t** [comment]
@MiirzaBaig did you get the chance to move forward on this issue ?

**Comment by msravikrishna** [comment]
Tried reproducing it, by running a tutorial flow and going to the Execution topology view
But seems issue doesn't appear. 
(Able to see execution status.)
 
Did I miss something?

<img width="261" alt="Screenshot 2024-10-27 at 12 47 44" src="https://github.com/user-attachments/assets/36fbe2ba-6edc-492d-a90e-28a7934eb20a">

**Comment by MilosPaunovic** [comment]
@msravikrishna Could you try and check is it alright on dark mode, also?

**Comment by msravikrishna** [comment]
@MilosPaunovic same case with dark mode as well.

<img width="406" alt="Screenshot 2024-10-28 at 18 56 18" src="https://github.com/user-attachments/assets/f9aaf678-54b6-4333-b3a5-a7915a2ddf5e">

**Comment by MilosPaunovic** [comment]
@tchiotludo Would you say we can close this or is there something we're missing here?

**Comment by tchiotludo** [comment]
we can close, seems to be already fixed
