### ISSUE TITLE
Outputs > Debug outputs missed a border bottom

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5217]
![image](https://github.com/user-attachments/assets/01a16c19-6ab7-478b-9a72-8e4deb666c08)

**Comment by kunalranjan19** [comment]
Hey @tchiotludo can you assign this issue to me I would like to work on it.

**Comment by kunalranjan19** [comment]
hey @tchiotludo I'm sorry, I haven't been able to locate this section yet, could you help me a bit.

**Comment by tchiotludo** [comment]
I think it's here : https://github.com/kestra-io/kestra/blob/develop/ui/src/components/executions/outputs/Wrapper.vue#L72

**Comment by kunalranjan19** [comment]
Thank you i'm looking into.

**Comment by sachinks07** [comment]
@tchiotludo I would love to work on this issue. Thanks!

**Comment by Ben8t** [comment]
@sachinks07 we're willing to review you PR :)

**Comment by MilosPaunovic** [comment]
Thanks @sachinks07! 🚀
