### ISSUE TITLE
[UI][DOCS] Sidebar is not displayed correctly when closed

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#5221]
### Describe the issue

The sidebar is not displayed correctly when closed

![kestra-docs-sidebars](https://github.com/user-attachments/assets/104d1d37-8a77-4027-aba4-903b91ef1b8a)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by AnkitAnandMastery17** [comment]
@fhussonnois Can I work on this issue?

**Comment by Ben8t** [comment]
@fhussonnois I'm not sure to understand the issue here 🤔 ?

Everything's looks good on my side (kestra:develop pulled 01/10 morning)

**Comment by MilosPaunovic** [comment]
@fhussonnois Could you confirm if this is still present as there was some work around docs this morning. If it is, I'll handle the change, with the help of @AnkitAnandMastery17.

**Comment by Ben8t** [comment]
I'm closing for now. I tested on several env. and no issue regarding left bar with doc
