### ISSUE TITLE
[UI][KVStore] string literal, boolean and numeric values should be allowed for JSON type.

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#5222]
### Issue description

Currently, the JSON type for K/V store restricts values to object and array types. But, string literal, boolean and numerics are valid type for JSON. So we should be able to pass values such as `"42"`, `42`, `true`.

![kestra-kv-json-string-literal](https://github.com/user-attachments/assets/ff1ce6fd-c38b-4423-85b7-dc176e9d7765)

**Comment by ssparser** [comment]
hello @fhussonnois  does changing the 
condition : `if (typeof parsed !== "object" || parsed === null) `
to  : `if (typeof parsed === "undefined" || parsed === null) `work ?

**Comment by anna-geller** [comment]
hey @fhussonnois this is expected, this was done by the community https://github.com/kestra-io/kestra/pull/5190 and seeing the upvotes looks like many users agree that JSON should validate that it's an object or array, treating string alone as invalid value for JSON type. I tend to agree, if someone wants to store STRING values, we have a STRING type in KV types, same for integers
