### ISSUE TITLE
[UI][KVStore] Error messages must be cleared when the value type is changed

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#5223]
### Issue description

Error message for invalid input is not removed when the value type is changed, e.g., switching from JSON to STRING.

![kestra-kv-error](https://github.com/user-attachments/assets/aeed9a1c-cb3b-45d8-9bf8-45af696820cd)

**Comment by mounikaperi** [comment]
@fhussonnois I would like to contribute to this issue. Please assign it to me if no one else is looking into it

**Comment by sujal011** [comment]
@fhussonnois  I would like to contribute to this issue. Please assign it to me if possible

**Comment by mounikaperi** [comment]
@fhussonnois @MilosPaunovic 
Please review https://github.com/kestra-io/kestra/pull/5321
Testing screenshots added in PR

**Comment by mounikaperi** [comment]
Thank you for merging the PR @MilosPaunovic 
We can close this issue if all good.
Will try working on others

**Comment by MilosPaunovic** [comment]
@mounikaperi This is now merged.

I have to say your PRs are a pleasure to review - you write up a complete description along with necessary screenshots so the whole process is streamlined as possible. May I only suggest that you try to use [Semantic Commit Messages
](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) and also [GitHub keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests), so we can automate event more.

Anyway, great job on finding and fixing this! 🚀 And, as always, if you're up to more contributions, check out this [link](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=release%3A%22v0.20.0%22++label%3A%22good+first+issue%22) with filtered good first issue  labels, where you might find something you think you can solve.

Closed via https://github.com/kestra-io/kestra/pull/5321.

**Comment by mounikaperi** [comment]
Thank you @MilosPaunovic 
I will take the feedback and try to implement it. 
Please feel free to keep correcting my mistakes whenever you find any.
