### ISSUE TITLE
In App doc not displaying

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#5224]
### Describe the issue

in-app doc not displaying content (both tested with preview-oss and localy `kestra-ee:develop`)

`TypeError: JPr.replaceAll is not a function`
<img width="1440" alt="Screenshot 2024-09-30 at 11 02 57" src="https://github.com/user-attachments/assets/46b09c3c-78d1-4e63-98ec-d38302af8e83">

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
This is a known issue and Brian is currently working on it, it didn't work on "build" UI but only on "npm run dev"

**Comment by tchiotludo** [comment]
![Image](https://github.com/user-attachments/assets/1164fe46-03bb-4d05-8049-8ee51ea545c6)
![Image](https://github.com/user-attachments/assets/b7ab34d1-e642-429a-8e44-e112439c3b46)
Probably related using EE with tenants
