### ISSUE TITLE
[UI][KVStore] increase the input for K/V type JSON

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#5225]
### Issue description

We should use a Textarea for JSON values. It is not uncommon to copy and paste multiline JSON objects/arrays.

![kestra-kv-json-input](https://github.com/user-attachments/assets/af77b45e-0d65-450f-9e4e-d64eb332629e)

**Comment by kunalranjan19** [comment]
Hey @fhussonnois can you assign this issue to me, I would like to work on it.

**Comment by anna-geller** [comment]
this is already working -- try to paste a large JSON and you'll see the field gets bigger to accommodate

![image](https://github.com/user-attachments/assets/ee09d213-e4ef-46b5-b1fd-64c352777ad3)
