### ISSUE TITLE
The `system` namespace is visible even when listing "User" flows

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5226]
### Describe the issue

The `system` namespace is visible even when listing "User" flows.
![Capture d’écran du 2024-09-30 11-12-01](https://github.com/user-attachments/assets/16b359a2-1a6a-43a1-9e67-39d8e31e20b8)

This leads to an empty list of flows when selecting it.
![Capture d’écran du 2024-09-30 11-08-05](https://github.com/user-attachments/assets/06c62d5b-fadd-456d-aeab-f7857aba546d)

So we had to un-check USER type of flow to list the system flows
![Capture d’écran du 2024-09-30 11-08-14](https://github.com/user-attachments/assets/0030f658-9d0b-45f8-9397-307fcce301db)

### Environment

- Kestra Version: 0.19.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Mahitej28** [comment]
@loicmathieu, can I work on this issue under hacktoberfest'24... also let me know what's need to be done for the same.

**Comment by loicmathieu** [comment]
@Mahitej28 you can work on the issue but I'm not sure what needs to be done, if you didn't find it by yourself maybe find an easier issue to work on.

**Comment by Mahitej28** [comment]
Okay will have a look

**Comment by MilosPaunovic** [comment]
@Mahitej28 But if you're up for a try, please go ahead! 🚀

**Comment by MilosPaunovic** [comment]
It's true that a current solution feels a bit weird, but it's intended behavior.

We could amend it in two ways:
1. Don't show `system` in the namespace filter options.
2. If selecting `system` namespace as a filter option, we remove the `User Flows` and add `System Flows` filter, which can lead to more confusion as that way we'd be changing filters for user in way it's not expected.

I would prefer either first option or leaving it as is now. WDYT @Ben8t?

**Comment by Ben8t** [comment]
> 1. Don't show system in the namespace filter options.

Seems the good solution for now. `system` is a "protected" namespace name (hence the filter User vs System).

Please take account that it can be configurable:
```yaml
kestra:
  system-flows:
    namespace: system
```

So we should filter on this namespace value

**Comment by MilosPaunovic** [comment]
I have filtered out `system` namespace on NS selection filter component we're using throughout the project in [this PR](https://github.com/kestra-io/kestra/pull/5403), but we definitely need to tackle [this issue ](https://github.com/kestra-io/kestra/issues/5396) to have everything handled in a proper way.
