### ISSUE TITLE
In-app docs missing part of sentence with links

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5237]
### Describe the issue

This is a strange behavior.

In the in-app doc, for example in this page: http://localhost:8080/ui/docs/workflow-components/tasks/scripts/languages#go-1

Part of the sentence (the links) are missing:
![image](https://github.com/user-attachments/assets/00ad6fdd-d21f-4256-84cc-5983b16f1c66)

The same page on the website is correctly displayed: https://kestra.io/docs/workflow-components/tasks/scripts/languages#go

![image](https://github.com/user-attachments/assets/5971ae3f-ef61-4b0e-bd74-f720e58a5ce0)

### Environment

- Kestra Version: 0.19.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by tchiotludo** [comment]
![image](https://github.com/user-attachments/assets/4d0f9c61-86bb-4a18-adee-47e41cbae50a)
seems ok now
