### ISSUE TITLE
Color is not the same between Gantt and Topology execution views

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#5238]
### Describe the issue

The green for success task execution is not the same between these two views

![image](https://github.com/user-attachments/assets/5e5dd467-6e07-4e73-a7be-21e27a7556b2)
![image](https://github.com/user-attachments/assets/834de2bb-8774-41ec-bf31-f5ba65f5a2d6)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Vivvek09** [comment]
heyy @Ben8t, has anyone taken this up?

**Comment by Ben8t** [comment]
hey @Vivvek09, not yet afaik - are you willing to provide a PR ?

**Comment by Vivvek09** [comment]
yes sure

**Comment by ssparser** [comment]
hey @Ben8t do you think this will work I am overriding the .bg-success  for Topology class.
 ```
 .status-div {
        &.bg-success {
            --bs-bg-opacity: 1;
            background-color: rgba(var(--bs-success-rgb), var(--bs-bg-opacity)) !important;
        }
      }
```

**Comment by Vivvek09** [comment]
heyy @Ben8t 
I ran kestra on docker at localhost:8080 and realized that the colors for succes on gant and topology are now the same

<img width="758" alt="gant" src="https://github.com/user-attachments/assets/76781906-5941-49d6-abeb-625a4c004a68">
<img width="714" alt="image" src="https://github.com/user-attachments/assets/24f5b73a-5f66-44c1-9859-72452df02d6d">

So this issue can be closed or am I missing something?

**Comment by Ben8t** [comment]
On latest version (kestra:develop) it's still not the same 🤔 
What version did you test ?

![image](https://github.com/user-attachments/assets/84e7878b-cb33-4633-bb19-81472c09b205)
![image](https://github.com/user-attachments/assets/f66eab92-9dea-4393-aab9-81bdf7cb6498)

**Comment by Vivvek09** [comment]
@Ben8t Looks like I was running the release version🫢
I ran the develop version now and made changes in the root.scss to change the success color of the topology view to #03daba same as that of the Gant View for the Light Mode
<img width="956" alt="image" src="https://github.com/user-attachments/assets/e389146f-1325-462b-be7d-c17d46c39a3f">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/f47a8d6d-e8ac-403e-a8fe-a999452d0499">

Should I make the colors same for the dark mode as well?

**Comment by MilosPaunovic** [comment]
Yes, please amend the dark mode, as well @Vivvek09.

**Comment by Vivvek09** [comment]
heyy @MilosPaunovic, I have made changes for the dark mode as well

<img width="959" alt="image" src="https://github.com/user-attachments/assets/a8d879db-7b74-43c5-98ca-c92ab0f44e5b">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/3e45420d-4b58-4420-83f7-a471b9780a90">

The commits are in the same pull request

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @Vivvek09! 🚀
