### ISSUE TITLE
[Idea] Add a new design for the Flow properties

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5241]
### Feature description

![image](https://github.com/user-attachments/assets/b0c3a63c-c4be-4baf-9a4b-aebc2ae3d3a2)

maybe some Expand-Collapse model + some art work

**Comment by MiirzaBaig** [comment]
Shall i work on this issue...?

**Comment by anna-geller** [comment]
Sure, you're assigned! thank!

**Comment by anna-geller** [comment]
sorry @MiirzaBaig, for this one we'd need figma design from our product designer

**Comment by Nico-Kestra** [comment]
For me, it just needs to follow the same style as the docs.
Whether I read the documentation in the editor or in the docs section, it should be the same component, same design. 
And if we need to change something, it will propagate everywhere without having to do it in two different pages.

<img width="1743" alt="Capture d’écran 2024-10-01 à 12 04 13" src="https://github.com/user-attachments/assets/32d91594-c6d6-4c8c-92fd-cf9c68af1436">

**Comment by Nico-Kestra** [comment]
But if I understand correctly, you'd like to revisit this page a bit. We can set up a meeting during the week if you'd like @anna-geller

**Comment by anna-geller** [comment]
that works, we can use the same design as for Docs!

The main issue Ludo raised was that links + that table don't look very visually appealing but if we take the same as we have for docs, it will look good 👍

**Comment by anna-geller** [comment]
@MiirzaBaig feel free to pick this up if you'd like to 👍 the goal is that this markdown view should look the same way as we have on the Plugin Docs + on the website

**Comment by MiirzaBaig** [comment]
@anna-geller done, will start working onit.....

**Comment by Ben8t** [comment]
@MiirzaBaig did you get the chance to move forward on this issue ?
