### ISSUE TITLE
Add an artwork instead of disabling the tab when no Trigger is defined for a flow

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5246]
### Feature description

Similarly to how we show artwork + helpful text with a documentation link on the Concurrency tab, we should do the same for the Trigger tab:

![image](https://github.com/user-attachments/assets/e68d1f2b-b239-4920-96df-77dae283d1e7)

In the future this may even link to embedded in-app docs so having this tab active will be a great start

**Comment by Nico-Kestra** [comment]
https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3331-25851&t=fIloBQsTIU3EhdKV-1

**Comment by anna-geller** [comment]
![image](https://github.com/user-attachments/assets/87379f03-0bfd-4daa-b103-3fe07509b884)

**Comment by shawnfrost69** [comment]
@anna-geller
If possible, I believe I can contribute to resolving this issue. Would it be okay for me to take it on?

**Comment by Ahmadmidlaj** [comment]
can i work on this issue?

**Comment by shawnfrost69** [comment]
@Ahmadmidlaj I started working on this.

**Comment by anna-geller** [comment]
@Ahmadmidlaj check [one of these issues](https://github.com/search?q=org%3Akestra-io+label%3A%22good+first+issue%22+is%3Aopen+label%3Aarea%2Ffrontend++no%3Aassignee&type=issues&utm_source=GitHub&utm_medium=github&utm_campaign=hacktoberfest2024&utm_content=Good+First+Issues)

**Comment by Ahmadmidlaj** [comment]
> @Ahmadmidlaj I started working on this.

okay cool

**Comment by Ahmadmidlaj** [comment]
> @Ahmadmidlaj check [one of these issues](https://github.com/search?q=org%3Akestra-io+label%3A%22good+first+issue%22+is%3Aopen+label%3Aarea%2Ffrontend++no%3Aassignee&type=issues&utm_source=GitHub&utm_medium=github&utm_campaign=hacktoberfest2024&utm_content=Good+First+Issues)

okay sure

**Comment by anna-geller** [comment]
@shawnfrost69 how is it going? I unassigned given no updates since a month, keep us posted if you can share a PR, thx a lot!

**Comment by MilosPaunovic** [comment]
Great work @Piyush-r-bhaskar, very clean and easy to review, thanks for that! Add a comment here for me to be able to assign it to you.

**Comment by Piyush-r-bhaskar** [comment]
Sure Milos. Please you may assign it to me.
