### ISSUE TITLE
Can not delete namespace file on Windows

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#5247]
### Describe the issue

Can not delete namespace file on Windows

### Environment

- Kestra Version: 0.19.0-snapshot

**Comment by pranavmugatkar** [comment]
Hello @Skraye , I am interested in contributing to this issue. as am beginner in open source contribution Any guidance or specific requirements would be greatly appreciated. Thank you!

**Comment by Skraye** [comment]
Hello @pranavmugatkar, really appreciate your interest ! 
Unfortunately, as you can see above a PR is already provided for this issue
But you can get the list here: https://github.com/search?q=org%3Akestra-io+label%3Akind%2Fgood-first-issue+is%3Aopen&type=issues
Also if you want the guildelines for contributions you can find them here: https://kestra.io/docs/getting-started/contributing
