### ISSUE TITLE
bug: github discussion link on issue template is broken

### ISSUE THREAD

**Issue by jaiakash** [kestra-io/kestra#5249]
### Issue description

Hi, I was checking the issue template and noticed that the Github discussion link is broken.
![Screenshot 2024-10-01 at 2 48 26 AM](https://github.com/user-attachments/assets/3036a87f-8ae1-4a95-8472-9da527c92dc3)

## How to reproduce bug
1. Click new issue : https://github.com/kestra-io/kestra/issues/new/choose
2. Click on "GitHub Discussions"

## How to solve this
I don't think the discussion section is open to public for this repo. We can open it for public.

**Comment by tchiotludo** [comment]
thanks @jaiakash for the report, I just removed `GitHub Discussions` link, we prefer to avoid spreading peoples on multiple channel, and so far Slack is the way to go
