### ISSUE TITLE
Use standard graph everywhere 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5250]
We have multiple type of charts 

New one: 
![image](https://github.com/user-attachments/assets/10c80bc7-09b7-4932-a404-12ba4e8e40cf)
![image](https://github.com/user-attachments/assets/fef58d09-56a7-48ed-8bad-d2bd9dac3c43)

Old one: 
![image](https://github.com/user-attachments/assets/be3891c7-6a73-43c0-87cf-e856686efa95)
![image](https://github.com/user-attachments/assets/ebe18988-70ad-4778-b716-ccfc0a775231)
![image](https://github.com/user-attachments/assets/a29cc49b-ed8f-4f11-a8fa-3b4aee7655c4)
![image](https://github.com/user-attachments/assets/23a36e6a-a84c-4eed-9a2c-670c822b1dd1)

We should use the new everywhere, and make it available as components (abstracted component to be easily reuse) to avoid duplication.

**Comment by MiirzaBaig** [comment]
Would love to solve this issue...

**Comment by sachinks07** [comment]
Can I work on this issue. Thanks!

**Comment by MilosPaunovic** [comment]
@sachinks07 Yes, but be careful, this is quite a large one.

**Comment by sachinks07** [comment]
Understood. Will First list all the places where changes are required and will use a shared component and test each of charts  whether they are working as expected.

**Comment by MilosPaunovic** [comment]
That sounds like a great plan! 🚀 

May I suggest that after you list all the place, add a comment here for us to validate first, before you start working on it?

**Comment by sachinks07** [comment]
Sure, will comment with the list of a places where changes required.

**Comment by sachinks07** [comment]
1.Flows --> Executions Page
<img width="1790" alt="Screenshot 2024-10-09 at 12 51 42 PM" src="https://github.com/user-attachments/assets/ae31e343-9a26-4c51-af87-1b4b485a7be9">

2.Flows --> Logs Page
<img width="1791" alt="Screenshot 2024-10-09 at 12 51 57 PM" src="https://github.com/user-attachments/assets/c3f26aab-b37c-4ae6-88b0-1ae245e22bb6">

3. Flows --> Metric Page
<img width="1788" alt="Screenshot 2024-10-09 at 1 21 54 PM" src="https://github.com/user-attachments/assets/0a2c2b29-1362-4fcd-9011-d26fd07eac6b">

4. Executions Page
<img width="1792" alt="Screenshot 2024-10-09 at 12 52 04 PM" src="https://github.com/user-attachments/assets/f993f20b-af99-45f4-9ea8-d3df0df11f42">

5. Logs Page
<img width="1792" alt="Screenshot 2024-10-09 at 12 52 42 PM" src="https://github.com/user-attachments/assets/6889bfaf-1ec2-42c4-814e-44a4828a1a4a">

@MilosPaunovic Please, let me know If these are places which requires the changes

**Comment by MilosPaunovic** [comment]
This seems like it's alright to me, but let's ask @Ben8t if he can add something to the list. Also, @wrussell1999 might have some insights on this one also.

**Comment by wrussell1999** [comment]
Just checked to see if the Namespaces page has any of these graphs. It doesn’t, but might be worth having them for the flows and executions tab. What do you think @Ben8t ?

**Comment by Ben8t** [comment]
Yes Namespaces > Overview should be tackled too
@MilosPaunovic on EE we have TaskRun tab also concerned (we can do a follow up issue for this specifically)

**Comment by MilosPaunovic** [comment]
Okay, so @sachinks07 you have the complete list, you can tackle the issue.
@Ben8t I'll open an issue on EE in a few minutes to have it tracked.

**Comment by sachinks07** [comment]
Sure, have started working on this.

**Comment by sachinks07** [comment]
@MilosPaunovic In **Namespace Flows** and **Namespace Executions**, as we will be showing the charts, can we also show the filters and disable the namespace selection similar to the Namespace overview
<img width="1791" alt="Screenshot 2024-10-11 at 12 42 10 PM" src="https://github.com/user-attachments/assets/e8ab6208-6495-4d5f-952c-cc5b4a8de5a7">
<img width="1791" alt="Screenshot 2024-10-11 at 12 42 18 PM" src="https://github.com/user-attachments/assets/b6196175-fcad-499b-969b-ac853f893361">

**Comment by MilosPaunovic** [comment]
Yup, makes perfect sense, let's go with it.

**Comment by MilosPaunovic** [comment]
Awesome work @sachinks07, this really makes a difference and improves the product! 🚀 Keep up the great work!
