### ISSUE TITLE
The "Next" link in the tutorial is not clickable, errors out

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5252]
### Describe the issue

https://share.descript.com/view/JipC7MZrt7J

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by brian-mulier-p** [comment]
closed by https://github.com/kestra-io/kestra/commit/1fbb0bf420f07d6f3cdfc02c9625a5aaeb4f15ec
