### ISSUE TITLE
[Regression] The default namespace set in Settings seems to have no effect on Filters

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5253]
### Describe the issue

https://share.descript.com/view/BGZE4UgsG7p

### Environment

- Kestra Version: develop

**Comment by MiirzaBaig** [comment]
Would like to work on this issue....

**Comment by anna-geller** [comment]
Sure, you're assigned! thank!

**Comment by Chaitanya-087** [comment]
[https://share.descript.com/view/Y4p4yA92DxV](https://share.descript.com/view/Y4p4yA92DxV)
hi, @anna-geller, made necessary changes to fix this issue
please checkout the below pr #5406 
https://github.com/kestra-io/kestra/pull/5406

**Comment by MilosPaunovic** [comment]
This is now solved via https://github.com/kestra-io/kestra/pull/5406.

Thanks for the contribution @Chaitanya-087, keep up the good work! 🚀
