### ISSUE TITLE
Markdown tables in the docs have white text that is not legible in light mode e.g. Task Runner docs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5254]
### Describe the issue

![image](https://github.com/user-attachments/assets/18a9e407-cee5-4bc6-aa2b-192ea7c21675)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by brian-mulier-p** [comment]
closed by https://github.com/kestra-io/kestra/commit/1fbb0bf420f07d6f3cdfc02c9625a5aaeb4f15ec
