### ISSUE TITLE
Missing text on Executions > overview > Change status

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5268]
![image](https://github.com/user-attachments/assets/b50559ce-f788-4d50-b269-d4d9de58e92b)
![image](https://github.com/user-attachments/assets/d71807c4-6440-47c3-baf8-67dcb58feada)

There is no text and missing translations, we could reuse partially the one from task change status

**Comment by sachinks07** [comment]
Hi @MilosPaunovic I would like to work on this issue. Thanks!

**Comment by MilosPaunovic** [comment]
Yup, go for it! 🚀

**Comment by sachinks07** [comment]
Thanks, can you tell me what needs to be done here. I didn't understood this part "There is no text"

**Comment by MilosPaunovic** [comment]
It's regarding missing translation keys, check browser console on that page for more details.

**Comment by sachinks07** [comment]
There were also missing translation text for the same change status in main Execution page and Execution logs. Have fixed it in the above pr #5346

**Comment by MilosPaunovic** [comment]
I'll take a look at this PR shortly. 

Before that, just one note - if you ever find yourself to need to add translation keys to the project, just edit the `en.json` file and create PR like that, as we have automation which will generate missing translation key/value pairs (by following some of our rules) once the PR is merged to `develop`.

**Comment by MilosPaunovic** [comment]
As always, great job @sachinks07! 🚀
