### ISSUE TITLE
Execution > Restart > unreadable text 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5269]
![image](https://github.com/user-attachments/assets/2ef543df-aae4-476d-a1af-d8376b177f7e)
The text "You can change..." is not readable on the dark theme, validate the change on the light one also

**Comment by Ahmadmidlaj** [comment]
Can i work on this issue?

**Comment by MilosPaunovic** [comment]
Absolutely @Ahmadmidlaj, go for it! 🚀

**Comment by Ahmadmidlaj** [comment]
> Absolutely @Ahmadmidlaj, go for it! 🚀

okay

**Comment by Suleman9580** [comment]
Is this issue solved ?
If not, can i contribute.

**Comment by Ahmadmidlaj** [comment]
> Is this issue solved ? If not, can i contribute.

iam working on it

**Comment by Ahmadmidlaj** [comment]
@MilosPaunovic @tchiotludo 
When I tried to replicate the issue #5269 locally, I noticed the following:
![image](https://github.com/user-attachments/assets/d1101c2d-58f8-469a-8a5e-343a701c3e72)

It seems like the issue has already been resolved, but I just wanted to confirm—am I looking at the correct issue, or did I miss something?

**Comment by MilosPaunovic** [comment]
Nope, you're on the wrong track there @Ahmadmidlaj.

You need to open list of executions (left menu item), open single execution, then click on `Replay` button near the top right corner. There, you'll see the dialog with text and description which is unreadable color on dark mode.

![image](https://github.com/user-attachments/assets/468970a1-f117-492e-96f0-b724f1df8189)

**Comment by Ahmadmidlaj** [comment]
Thank you for the clarification! I appreciate the guidance and will follow those steps. I'll take another look at it and see if I can replicate the issue correctly this time. Thanks for your help!

**Comment by MilosPaunovic** [comment]
Great work @Ahmadmidlaj, looking forward to more of you contributions! 🚀

**Comment by Ahmadmidlaj** [comment]
> Great work @Ahmadmidlaj, looking forward to more of you contributions! 🚀

Thank you so much for the encouragement! I'm really excited to be contributing to this project and I'm looking forward to making more meaningful contributions in the future. Your feedback and support are greatly appreciated!

**Comment by MilosPaunovic** [comment]
That's always great to hear!
Check out [this filtered list](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=label%3A%22good+first+issue%22) to potentially find issues which you might find interesting to tackle! 🚀

**Comment by Ahmadmidlaj** [comment]
> That's always great to hear! Check out [this filtered list](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=label%3A%22good+first+issue%22) to potentially find issues which you might find interesting to tackle! 🚀

Absolutely! I'll check it out. Thanks for the opportunity! 👍
