### ISSUE TITLE
Doc > Section with index and childs are blinking on click 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5270]
[Screencast_20241002_082044.webm](https://github.com/user-attachments/assets/43eabc31-9905-44af-9314-ef1ee7667fc4)
When the section have an index, on first click, it will open the menu child, and being automatically collapse, leading to a bad impression of blinking

**Comment by mansidhamne** [comment]
Hi! Can you assign this issue to me? I would like to work on it

**Comment by brian-mulier-p** [comment]
Hello ! Sorry I didn't see your comment and I already tackled it :'( There is plenty of other that you can take so feel free
