### ISSUE TITLE
KV Json value- dark theme omitted 

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5273]
### Describe the issue

Small issue but still need a fix :) 

![image](https://github.com/user-attachments/assets/bfc1af30-c514-4498-9365-da07f053195d)

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):

**Comment by mounikaperi** [comment]
@smunteankestra - can you please briefly describe the issue? and what needs to be done?

**Comment by smunteankestra** [comment]
dark theme not supported on the KV Json field - you can se the Value Field in the screenshot

**Comment by mounikaperi** [comment]
Got it. I will take a look @smunteankestra. You can assign this to me

**Comment by mounikaperi** [comment]
@smunteankestra @MilosPaunovic 
I tried reproducing the issue in local by running the docker with latest build image
the value is in dark theme too. I dont see it in light theme. Can you please check once from your end, if this is an issue still?
Putting screenshot for your reference
![image](https://github.com/user-attachments/assets/4c41030c-1420-4c80-8cac-21841f64c282)

**Comment by MilosPaunovic** [comment]
Confirming, no issue here. @smunteankestra Might be some auto-fill from a browser extension on your side.
