### ISSUE TITLE
Plugin > Align menu with docs

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#5274]
### Describe the issue

On the plugin page, the menu is not aligned with the edge of the page; there are empty spaces on the left and at the bottom. The menu needs to be aligned to the left, and the background should stretch to the bottom of the page (and top). Use the exact same template as the UI for the documentation.

<img width="2012" alt="Capture d’écran 2024-10-02 à 10 45 15" src="https://github.com/user-attachments/assets/212bb973-9336-4ee8-a229-a45ac6bbf69c">
<img width="762" alt="Capture d’écran 2024-10-02 à 10 47 57" src="https://github.com/user-attachments/assets/746a816b-f43b-4c1e-826b-e3af344cea83">

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by mansidhamne** [comment]
Hi! Can you assign this issue to me? I would like to work on it.

**Comment by MilosPaunovic** [comment]
@mansidhamne Go for it! 🚀

**Comment by mansidhamne** [comment]
<img width="1440" alt="Screenshot 2024-10-03 at 12 16 50 PM" src="https://github.com/user-attachments/assets/931720d5-f88d-4327-94c1-69191023f7ec">

This screenshot is on ```http:localhost:5173``` (local machine) and it's perfectly aligned ie solves the issue. I am running on kestra:develop.


<img width="1440" alt="Screenshot 2024-10-03 at 12 17 47 PM" src="https://github.com/user-attachments/assets/d2bebdb8-716f-4853-a06f-7c34ed860bd9">

This screenshot is on ```http:localhost:8080``` and here the issue exists.

**Comment by MilosPaunovic** [comment]
Confirming that this is amended on latest `develop` branch, so I'll close it.

Thanks @mansidhamne for figuring this one out, and feel free to explore other issues which could be good if you want to contribute at https://go.kestra.io/contribute. 🚀
