### ISSUE TITLE
Unable to unselect the currently chosen log level 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5283]
### Describe the issue

![image](https://github.com/user-attachments/assets/36ddb25c-9f1a-4db1-ba0f-1ce6da7ffa99)

I expect that when you click on the currently selected log level, it will clear the selection - if not this way, we need some way to clear the selection and show all log levels equally

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Vivvek09** [comment]
Heyy @anna-geller, I would love to work on this issue
I am thinking that whenever a log level is selected, a small cross button will appear beside it to unselect it and when that button is pressed, it will clear the selection and show all log levels equally

**Comment by iamviqar** [comment]
@anna-geller Do we have any documentation describing the existing behavior of this log screen? I am just trying to understand how this scroller is displayed based on level selection

![image](https://github.com/user-attachments/assets/2239717c-21d6-4965-89c1-a642ce61ccf9)

**Comment by Vivvek09** [comment]
Heyy @anna-geller 
I have tried to resolve the issue
Was this the expected solution?

https://github.com/user-attachments/assets/d12982cc-fd5c-4bbf-942b-b72e8d82476f

**Comment by anna-geller** [comment]
yes, that's perfect, thanks so much for contributing @Vivvek09 ❤️
