### ISSUE TITLE
Success and Failure Ratios include Running flows in the total count

### ISSUE THREAD

**Issue by ssewell** [kestra-io/kestra#5289]
### Describe the issue

When calculating the "Success Ratio" and "Failure Ratio" shown at the top of the new Dashboard introduced in Kestra 0.19.0, the denominator in the calculation uses the total number of flows. This results in the values showing an invalid value while flows are being executed. With any sort of flow execution density, these values will perpetually be underrepresented.

Example:
 - 1 flow has executed, and 1 flow has succeeded: Success shows 100%, as expected
 - A second flow has begun but not yet completed: Success shows 50% even though the process has not completed yet, due to the calculation of [Successful Flows] / [Total Flows] = 1/2 = 0.5
 - Once the second flow completes: Success shows 100%

I propose the "Total flows" denominator used in the "Success Ratio" and "Failure Ratio" exclude any flows classified as "Running". This will result in the logical deferral of a flow classification as part of success or failure ratio until after the process flow has stopped execution.

### Environment

- Kestra Version: 0.19.0
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):

**Comment by Ben8t** [comment]
Thanks @ssewell for raising this !

As discussed internally, here the rules we will implement:

* Use only terminated states as a total number
* Success Ratio is the sum of `SUCCESS`, `CANCELLED`, `WARNING` executions divided by the total number of execution in a terminated state.
* Failed ratio is the sum  of `FAILED`, `KILLED`, `RETRIED` executions divided by the total number of execution in a terminated state.

Also @MilosPaunovic could you add a tooltip on the two headings to display these calculation 🙏 ?

**Comment by MilosPaunovic** [comment]
This was a great catch, indeed @ssewell! Thanks for opening this issue! 🚀 
I've pushed a commit to `develop` which now handles it properly, based on the comment from above.
