### ISSUE TITLE
Don't allow to disable already disabled flow

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5290]
### Feature description

When a flow is disabled, the user can still click the 'Disable' button, and a success message appears stating '0 Flows Disabled.' To improve this, we could consider disabling the 'Disable' button once the flow is already disabled to avoid confusion.

![image](https://github.com/user-attachments/assets/82ea6edb-e85f-4a74-8ce4-5c8d72612eb0)

**Comment by riyamustare** [comment]
hey is this issue solved if not would like to contribute

**Comment by MilosPaunovic** [comment]
Sure, go for it @riyamustare!

**Comment by riyamustare** [comment]
thankyou will start working on it!

**Comment by MiyuruAmarasiri** [comment]
please assign me

**Comment by Suleman9580** [comment]
Hey, is this issue solved ?
If not then assign me i'll help.

**Comment by riyamustare** [comment]
> Hey, is this issue solved ? If not then assign me i'll help.

hii ive submitted a pull request so waiting for approval.

**Comment by riyamustare** [comment]
> Hey, is this issue solved ? If not then assign me i'll help.

hii ive created a pull request for this issue just waiting for approval, i probably messed up while creating the pr so you can't see it here - new here so sill figuring out the space :)

edit: figured out.

**Comment by MilosPaunovic** [comment]
As @gantoin submitted the first PR for this, that is now merged via https://github.com/kestra-io/kestra/pull/5319.

Thanks to everybody that tried to help out on this one, and, as always, if you're up to more contributions, check out this [link](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=release%3A%22v0.20.0%22++label%3A%22good+first+issue%22) with filtered good first issue  labels, where you might find something you think you can solve.
