### ISSUE TITLE
NaN on new v19 dashboard

### ISSUE THREAD

**Issue by alexdremov** [kestra-io/kestra#5299]
### Describe the issue

<img width="1088" alt="Screenshot 2024-10-03 at 21 15 47" src="https://github.com/user-attachments/assets/23f76df3-5c1a-4f93-9894-7d78218e5dd7">

Executions per day show NaN

### Environment

- Kestra Version: v19.0.1
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker): —

**Comment by MilosPaunovic** [comment]
@alexdremov Is there any other detail about this you can share, as right now I cannot reproduce it.

@smunteankestra Could you try to create reproduction for this?

**Comment by smunteankestra** [comment]
can't reproduce either - please feel free to reopen if will encounter again 
![image](https://github.com/user-attachments/assets/dfeef21f-9e5e-4c00-80a3-b69a9a542b6e)

**Comment by alexdremov** [comment]
It is reproducible in my setup and I have nothing unusual in it, so reopening 

What can I provide for debugging this?

**Comment by alexdremov** [comment]
@smunteankestra @MilosPaunovic could you reopen please? :)
This is anything but `Done`

**Comment by smunteankestra** [comment]
@alexdremov  Can you share more details about your setup? Like os, browser and so on

**Comment by alexdremov** [comment]
That's what `/api/v1/stats/executions/daily` returns https://gist.github.com/alexdremov/0c317e23598f2cb8ab91677f66059646

Sure, browser: Safari Version 17.5 (19618.2.12.11.6)
OS: Mac OS Sonoma 14.5 (23F79)

**Comment by alexdremov** [comment]
<img width="977" alt="Screenshot 2024-10-04 at 10 28 53" src="https://github.com/user-attachments/assets/64556516-4ca7-4b03-ae70-4388ae3a18f0">

Nans are also in the view aggregated by namespace

**Comment by alexdremov** [comment]
So, I've changed filterings, if I select each specific namespace, it's fine 
<img width="984" alt="Screenshot 2024-10-04 at 10 41 47" src="https://github.com/user-attachments/assets/a696b4bd-4696-4603-a0bd-d138921f1e18">


But there's one namespace that when filtered returns NaN and 0% success / failure
<img width="981" alt="Screenshot 2024-10-04 at 10 41 55" src="https://github.com/user-attachments/assets/9e0482b1-5bec-44d4-a245-8c916acf5f77">

**Comment by MilosPaunovic** [comment]
Thanks for the extra details @alexdremov, we're working on a solution.

**Comment by alexdremov** [comment]
Thanks!

Also, here's the daily stats for the buggy namespace. I feel that it can be useful 

https://gist.github.com/alexdremov/acd37a103e21bce6952bbb7773192953

**Comment by MilosPaunovic** [comment]
Okay, I've found and amended the issue; the values returned from endpoints you've shared here were definitely useful @alexdremov! 

We're having the next planned `patch` release next Tuesday, so that's when it's going to be available as `0.19.2`, but when the CI passes (it takes about an hour and a half) it will be available as part of the `develop` Docker image (`kestra/kestra:develop`), so you can check it there.

Will leave this issue open until we get confirmation from you that it now behaves as expected.
And yes, thank you very much for reporting this one! 🚀

**Comment by alexdremov** [comment]
Cool! That was fast

I'll write a note here after updating to `v0.19.2`

**Comment by alexdremov** [comment]
confirming that it works

thanks again, closing the issue
