### ISSUE TITLE
How to launch Developer backend?

### ISSUE THREAD

**Issue by fdelbrayelle** [kestra-io/kestra#530]
### Issue description

I have double checked the documentation and `CONTRIBUTING.md` and `README.md` but I was not able to launch properly the backend. So I think some details should be added in the "Develop backend" part because it's not very clear how to launch things, I mean do we have to launch `./gradlew build` and then `./gradlew run` or `./gradlew execute` with `io.kestra.cli.App` as a main class or ` ./build/scripts/kestra server standalone -PmainClass=io.kestra.cli.App`?

```
Erreur : impossible de trouver ou de charger la classe principale io.kestra.cli.App
Causé par : java.lang.ClassNotFoundException: io.kestra.cli.App
```

**Comment by tchiotludo** [comment]
thanks @fdelbrayelle for the report, clearly there is a lot of missing informations. 
Tell me if it's better now or we need more ;)
