### ISSUE TITLE
Flow Execution Labels can't be deleted

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5310]
### Describe the issue

Flow had no labels

After Flow is executed - if user will add a Label - they can't be deleted - fist label grayed out

https://github.com/user-attachments/assets/648fc588-eb8a-4b7d-a981-99ffa5aa3954

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):

**Comment by paragaher15** [comment]
@MilosPaunovic are you working on this project if need help feel free to ask ..

**Comment by MilosPaunovic** [comment]
@paragaher15 If you're willing to contribute, please do! :rocket:

**Comment by MilosPaunovic** [comment]
We need to add the BE endpoint for deletion here.

**Comment by Skraye** [comment]
No need to create a new endpoint, updating this method will be enough I think : https://github.com/kestra-io/kestra/blob/develop/webserver/src/main/java/io/kestra/webserver/controllers/api/ExecutionController.java#L1582
