### ISSUE TITLE
Rewrite in Go / Rust

### ISSUE THREAD

**Issue by yonas** [kestra-io/kestra#5317]
### Feature description

I mean, how did you not choose Go or Rust? Possibly NodeJS, but that's a sinking ship.

Feature request to completely rewrite this awesome project in Go or Rust, preferably Rust.

**Comment by anna-geller** [comment]
Thank you for your suggestion and for your enthusiasm for Rust and Go. We appreciate your interest in improving the project. 

While we recognize the benefits Rust or Go could offer in certain scenarios, rewriting our entire Java application into a new language would be a substantial undertaking. The existing Java codebase has been extensively optimized over time and is deeply integrated with our infrastructure. Rewriting it would introduce significant risks, including potential downtime, instability, and delays in delivering new features. Moreover, Java’s rich ecosystem, mature libraries, and strong performance make it well-suited to our current requirements.

We will continue to explore ways to incorporate newer technologies where it makes sense, but for now, we’ll be focusing on maintaining and enhancing the current Java-based architecture. Again, we appreciate your suggestion and look forward to more feedback.
