### ISSUE TITLE
UI - Can't toggle Auto Refresh Toggle Button in Dashboard

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#5318]
### Describe the issue

Can't toggle "auto refresh toggle button" in Dashboard
- able to do it though in EE Monitoring page though
- image shows it as unclickable/blurred out

![Screenshot 2024-10-05 at 9 54 24 AM](https://github.com/user-attachments/assets/ee5f17f5-0f46-4498-ba03-59e0a2d6f8e1)

### Environment

- Kestra Version: 0.19.1
- Operating System (OS/Docker/Kubernetes): Kestra Cloud
- Java Version (if you don't run kestra in Docker): n/a

**Comment by Ben8t** [comment]
Same behavior on OSS 0.19.1

**Comment by MilosPaunovic** [comment]
Hi @japerry911,

Auto-refresh option is only available on `Relative` dates, so can you make sure to check if that works properly if you have you date filter set to relative. if so, we can close the issue.

**Comment by japerry911** [comment]
@MilosPaunovic , you are correct, I was on absolute date range. Thank you/closing 🙏
