### ISSUE TITLE
[Regression] "Show chart" toggle and many other filter elements are gone -- we should bring them back

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5329]
### Describe the issue

Current latest 0.19.1 has the toggle as expected:

![image](https://github.com/user-attachments/assets/3e9f35ca-6090-4793-9a80-2608f6f37bae)

now on develop it's missing:

![image](https://github.com/user-attachments/assets/29bd1a88-ad40-473b-a1da-7a042b3b44aa)

![image](https://github.com/user-attachments/assets/3c232039-c54d-4e99-82fa-027f9fc220fd)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
might be related to https://github.com/kestra-io/kestra/pull/5309 - @MilosPaunovic could you check?

**Comment by MilosPaunovic** [comment]
@sachinks07 Interested in checking out this follow-up to the issue you've already solved?

**Comment by sachinks07** [comment]
Sure @MilosPaunovic will check.

**Comment by sachinks07** [comment]
@anna-geller I have checked the code the above filters which are mentioned were not there in Flows sections before.

**Comment by MilosPaunovic** [comment]
It might have been on executions. But, could you add a toggle on every page which shows charts (except main dashboard) as part of the filters, which will toggle the visibility of the charts on the page (via `v-if`).

**Comment by sachinks07** [comment]
<img width="1790" alt="Screenshot 2024-10-07 at 9 22 22 PM" src="https://github.com/user-attachments/assets/730bee37-11e1-4476-b31a-c436a25edc77">
Do we need to add toggle in Flows overview also. If so on toggle we need to hide the Executions(per day) and Total Executions charts. Is this correct

**Comment by anna-geller** [comment]
on the Flow overview page this is totally fine to keep as is as this is a dashboard :) the chart is not expected for some users on the Flows and Executions pages where we list multiple flows/executions in a table - some users expect to see only a table and prefer to hide the chart. in kestra 0.19.1 this is the case, that's why it's marked as a regression

**Comment by sachinks07** [comment]
Understood. Thanks!

**Comment by sachinks07** [comment]
- Added the chart visibility toggle in **Flows** and **Logs** Page

<img width="1792" alt="Screenshot 2024-10-08 at 12 10 38 PM" src="https://github.com/user-attachments/assets/53bc8efe-7a94-421a-bc0a-6f737d707435">
<img width="1792" alt="Screenshot 2024-10-08 at 12 10 46 PM" src="https://github.com/user-attachments/assets/c6d639a7-b172-489c-90bc-b7c53f5bafab">
