### ISSUE TITLE
Request to make `timeout` Flow.Pause Property Dynamic

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#5338]
### Feature description

Is it possible if Flow.Pause timeout property could be Dynamic? https://kestra.io/plugins/core/tasks/flows/io.kestra.plugin.core.flow.pause#timeout

My reasoning is I have Pause in a Subflow, and some flows will have shorter timeouts than others. Some flows will need to always be reviewed, while some will be fine without review and can have auto-approve/timeout hit.

Also worth noting is that we use Pause in a subflow, because we built slack/resuming integration that is reusable among many workflows.

This would be super helpful, but if not possible, we can make adjustments so Pause is in every flow instead of called by subflow. Thought it was worth requesting if possible to do.

Thank you 🙏

**Comment by mgabelle** [comment]
@loicmathieu Can you confirm that Duration still has parsing issue when it comes to v2 property ?

**Comment by loicmathieu** [comment]
@mgabelle I'm not sure but this task has special treatment inside the executor so it's not as simple as it seems.
