### ISSUE TITLE
The "Delete logs" button is not correctly aligned in the Flow -> Logs tab

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5352]
### Describe the issue

Click on Flows, then click on a flow, then on the Logs tab.
On the upper right corner there is a delete logs button that is not correctly aligned.

![image](https://github.com/user-attachments/assets/4a8e45e1-080c-4ae1-af4d-3c9c579ac45e)
 

### Environment

- Kestra Version: 0.20.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Sahil-195** [comment]
Hello @loicmathieu,I would like to work on this issue, can you assign this issue to me ??

**Comment by MilosPaunovic** [comment]
@loicmathieu Could you pull latest develop or check on OSS preview, that should've been already amended?

**Comment by loicmathieu** [comment]
@MilosPaunovic OK on preview-oss, my frontend is probably not up-to-date locally, sorry for the noise.

![image](https://github.com/user-attachments/assets/65e3cd80-c9de-43c9-a517-7ae663b39269)
