### ISSUE TITLE
Add an option to bulk-delete multiple KV pairs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5359]
### Feature description

![image](https://github.com/user-attachments/assets/2a8c8291-e82d-4d35-8920-c062acc6d24c)

This can be done in the same way as on the Executions page:

![image](https://github.com/user-attachments/assets/968acf1c-0628-4768-b502-f3216fe0820a)

![image](https://github.com/user-attachments/assets/b1a2f0f3-8ad3-4880-b7b7-08b9f780e3e5)

**Comment by iamviqar** [comment]
@anna-geller  I would like to work on this

**Comment by iamviqar** [comment]
- I see, currently delete API for KV takes single value as param [../api/v1/namespaces/company/kv/{key}].
- Before starting to work on UI, It would be better to have a new API to delete multiple KVs like we have it for deleting multiple executions.

**Comment by anna-geller** [comment]
@fhussonnois perhaps you could help with the backend endpoint to delete multiple KV pairs? 🙏

**Comment by fhussonnois** [comment]
The new Bulk API is merged on develop: 

```
DELETE/ /api/v1/namespaces/{namespace}/kv

Request body:
{ 
   "keys": []   # List of keys to be deleted
}
`

**Comment by iamviqar** [comment]
Thanks @fhussonnois  for API .

@anna-geller Please check, if this updated GUI is as per expectation

![image](https://github.com/user-attachments/assets/d8f64995-841c-4e1c-ab0a-e01291fac080)

Do need delete option on individual line item?

tagging @MilosPaunovic

**Comment by MilosPaunovic** [comment]
Yes, let's leave it as it is already there.

**Comment by anna-geller** [comment]
looks great @iamviqar, you can send a PR 🚀

**Comment by iamviqar** [comment]
Created the PR: https://github.com/kestra-io/kestra/pull/5413

Refer this screen recording demonstrating the feature: 
[kestra_5359.webm](https://github.com/user-attachments/assets/2f05c7e8-09e4-40f4-b8db-84473ab3d51a)

note: a confirmation message [Are you sure to delete <code>{name}</code> KV(s)?] has been added on en.json, if the proper text is provided for other languages, I can update them accordingly.

Please let me know if I am missing something else.

tagging @anna-geller  @MilosPaunovic

**Comment by MilosPaunovic** [comment]
This is now closed via https://github.com/kestra-io/kestra/pull/5413.

Wonderful job @iamviqar, code was clean and with the video demonstration and extensive description it was a pleasure to review and merge this. 🚀 

On the question of translation files - we have automation which creates missing key/value pairs for all the other languages, and it uses English as a base, so, if you encounter changing something in `en.json` file, that is enough, other languages are going to be there on merge.

I would encourage you to take a look at the l[ist of curated good first issues,](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=label%3A%22good+first+issue%22) and check if there is anything else you might find interesting enough to give it a go.
