### ISSUE TITLE
UI Responsiveness Issue: Overlapping Components on the Flows Page

### ISSUE THREAD

**Issue by mithindev** [kestra-io/kestra#5380]
### Issue description

I have noticed a responsiveness issue on the UI/flows page where certain components overlap when resizing the browser window or viewing on smaller screen sizes.

Attached is a screen recording that demonstrates the issue in action. 

https://github.com/user-attachments/assets/df254a49-91be-4e02-9dec-2fd1b86cc4c1

**Comment by mithindev** [comment]
@MilosPaunovic , Can I solve this issue? 🙂

**Comment by MilosPaunovic** [comment]
Absolutely, go for it! @mithindev

**Comment by MilosPaunovic** [comment]
Nice job, keep up the great work @mithindev! 🚀
