### ISSUE TITLE
Add `Used by` section to our OSS repository

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5381]
Some `Java` projects have a `Used by` section on their repository pages:

https://github.com/google/gson
https://github.com/google/guava

We should try to add it to our own, as well, if possible.

**Comment by sanketmagar2001** [comment]
hi @MilosPaunovic  , as per online resource [Github official link](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository)

The "Used by" section on a GitHub repository page is automatically generated by GitHub and shows which other repositories depend on the repository in question. This section cannot be manually added, but it will appear if other public repositories declare your repository as a dependency using specific dependency management tools.

**Comment by anna-geller** [comment]
thanks a lot, good call @sanketmagar2001! makes sense given that kestra is a platform, not a framework
