### ISSUE TITLE
endsWith string filter

### ISSUE THREAD

**Issue by acompagnon** [kestra-io/kestra#5390]
### Feature description

As [startsWith](https://kestra.io/docs/expressions/filter/string#startswith), It would be quite useful to have endsWith

My use case is available here https://kestra-io.slack.com/archives/C03FQKXRK3K/p1728487183257299

**Comment by Harsh4902** [comment]
@acompagnon @MilosPaunovic  `endsWith` filter is already there. At least I can see code of it [here](https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/runners/pebble/filters/EndsWithFilter.java). But, there is no mention of it in documentation.

**Comment by MilosPaunovic** [comment]
@brian-mulier-p Might be the right person to answer that one.

**Comment by loicmathieu** [comment]
Yes it's here ;) it's only missing in the doc.

@acompagnon it is available since 0.16.

**Comment by acompagnon** [comment]
Hidden features I love it ! Thank you 😁

**Comment by loicmathieu** [comment]
Closing this one, I opened https://github.com/kestra-io/docs/issues/1843 on the doc repo so our tech writer can handle this.
