### ISSUE TITLE
Error in outputValues when using array as values

### ISSUE THREAD

**Issue by razuro** [kestra-io/kestra#5411]
### Describe the issue

<img width="411" alt="Screenshot 2024-10-10 at 23 47 25" src="https://github.com/user-attachments/assets/47ba5b57-f7b2-4492-891d-a0aa5e197284">

## The above yaml will produce error:
```At flow: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`) at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.kestra.core.models.flows.Flow["tasks"]->java.util.ArrayList[0]->io.kestra.plugin.core.output.OutputValues["values"]->java.util.HashMap["test"])```

### Environment

- Kestra Version: 0.19, 0.18.8, 0.18.5, 0.17.0
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):

**Comment by Malaydewangan09** [comment]
Hey @razuro 
Can I pick up this issue if it hasn't been solved yet?
Thanks!

**Comment by Skraye** [comment]
Hello @Malaydewangan09 ! We want this to be fixed before the next bugfix release which is tuesday, is it okay for you ? 
I can give you until Monday, however I'll take back the issue! 

Let me know if you're willing to do it, I'll assign it to you !

**Comment by Malaydewangan09** [comment]
Hey @Skraye 
I can fix it by Monday. Please assign it to me.

**Comment by Malaydewangan09** [comment]
Hey @Skraye 
We need to handle this check for OutputValues tasks on the frontend and also modify the error message?
Because the sub type can only be a string for output values right?

**Comment by Skraye** [comment]
Hello @Malaydewangan09 
Effectively, for some reason, we decided to go with a Map<String, String>, but now I think it should have been a Map<String, Object> to allow nested maps & arrays.
