### ISSUE TITLE
Add a "Forms" tab to the Flows page allowing to create custom forms to create a parametrized execution

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5424]
### Feature description

OSS companion to https://github.com/kestra-io/kestra-ee/issues/1429 

No spoilers will be disclosed here for now :) other than:
1. Users will be able to create custom forms with their selected inputs
2. When the end user clicks on `Submit` in the form, this will create an Execution 
3. If the form has the option to wait for execution outputs, the flow outputs will be displayed on this page.

**Comment by BadriVishalPadhy** [comment]
@anna-geller can u assign me

**Comment by anna-geller** [comment]
this one is a bit too complex and needs design. Can you check one from the [good first issue list](https://github.com/search?q=org%3Akestra-io+label%3A%22good+first+issue%22+is%3Aopen&type=issues&utm_source=GitHub&utm_medium=github&utm_campaign=hacktoberfest2024&utm_content=Good+First+Issues)? thx in advance!
