### ISSUE TITLE
The blueprint 264 (logging info about GitHub stars) is mistakenly preloaded along with tutorial flows

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5441]
### Describe the issue

This looks like a bug — there should be only `tutorial` flows that are preloaded (optionally also purge system flow https://github.com/kestra-io/kestra/issues/5219)

![image](https://github.com/user-attachments/assets/51792bee-8cb7-4893-8b57-1e6b1895e1a2)

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
now we have it even twice 

![image](https://github.com/user-attachments/assets/1a2a8e4e-cc4f-40ce-a461-b3ff75dc8600)

@MilosPaunovic could you have a look why this flow keeps getting loaded by default?

**Comment by MilosPaunovic** [comment]
After a bit of digging this seems like it's related to BE side, maybe @brian-mulier-p could try and take a look at it as he's been doing things around blueprints recently?

Also, clearing Postgress and running it fresh seems to be loading 3 `tutorial` workflows, one `blueprints` and one `company.team` now, guessing it's all related.

![image](https://github.com/user-attachments/assets/6610035e-6694-4497-824d-9190ef98b315)

**Comment by anna-geller** [comment]
done by Brian
