### ISSUE TITLE
Variable State : CRUD 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#545]
These [tasks](https://kestra.io/plugins/core/tasks/states/io.kestra.core.tasks.states.Get.html) use a state store, but during lifecycle, users may want to clean / delete / update the store.
Provide this directly on the UI (maybe also on terraform?)

**Comment by anna-geller** [comment]
the plan to introduce KV Store https://github.com/kestra-io/kestra-ee/issues/911
