### ISSUE TITLE
purge flow not cleaning kestra tables in postgres

### ISSUE THREAD

**Issue by jspablo** [kestra-io/kestra#5450]
### Describe the issue

I am using [Purge flow](https://kestra.io/docs/administrator-guide/purge) to clean every two days all logs but tables keep increasing in Postgres, mainly the queues one. I am using kestra [standalone setup with docker compose](https://github.com/kestra-io/kestra/blob/develop/docker-compose.yml) to orchestrate services in real time with JSON inputs (>1MB).

I am using the following query to check for tables size:

```sql
select schemaname as table_schema,
    relname as table_name,
    pg_size_pretty(pg_total_relation_size(relid)) as total_size,
    pg_size_pretty(pg_relation_size(relid)) as data_size,
    pg_size_pretty(pg_total_relation_size(relid) - pg_relation_size(relid))
      as external_size
from pg_catalog.pg_statio_user_tables
order by pg_total_relation_size(relid) desc,
         pg_relation_size(relid) desc
limit 10;
```
The output:
```
 table_schema |      table_name       | total_size | data_size  | external_size 
--------------+-----------------------+------------+------------+---------------
 public       | queues                | 664 GB     | 3639 MB    | 660 GB
 public       | executions            | 5269 MB    | 2272 kB    | 5267 MB
 public       | logs                  | 3968 MB    | 1714 MB    | 2254 MB
 public       | metrics               | 60 MB      | 49 MB      | 12 MB
 public       | executorstate         | 28 MB      | 25 MB      | 3632 kB
 public       | worker_job_running    | 3120 kB    | 8192 bytes | 3112 kB
 public       | flows                 | 320 kB     | 16 kB      | 304 kB
 public       | triggers              | 248 kB     | 160 kB     | 88 kB
 public       | service_instance      | 168 kB     | 112 kB     | 56 kB
 public       | flyway_schema_history | 80 kB      | 8192 bytes | 72 kB
```

What is the correct way to purge all data related to old executions? I saw this issue too https://github.com/kestra-io/kestra/issues/5055 but I haven't seen any tables reduce its size after a week

### Environment

- Kestra Version: 0.19.1
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
The `queues` table is purged using a different mechanism, the JdbcCleaner that purge to 7 days by default: https://kestra.io/docs/configuration-guide/database#kestrajdbccleaner

You can lower the value if needed.

**Comment by Ben8t** [comment]
Thanks Loic, @jspablo I'm closing the issue for now. Do not hesitate to re-open if needed
