### ISSUE TITLE
Dynamic properties and null values 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5453]
Now a null properties in a flow definition will lead to a null values, 
Example with a defintion : 
```yaml 
id: myId
type: io.kesta....Example
```
and this plugins: 
```java
public class Example extends Task implements RunnableTask<Output> {
    private Property<String> projectDir;
    @Override
    public ScriptOutput run(RunContext runContext) throws Exception {
        runContext.logger("value {]", projectDir)
        return null;
   }
}
```

`projectDir` will be null and this will bug prone based on our previous implementation. 

we should change the deserializer to inject the `Property` even if null and add a method `isPresent`

**Comment by loicmathieu** [comment]
This is a little more complicated as we didn't serialize null, the deserializer may not be called for null properties.
@brian-mulier-p has some ideas he want to prototype.

**Comment by loicmathieu** [comment]
Null safety has been provided by methods on the run context to render the new Property carrier type, see https://github.com/kestra-io/kestra/pull/5725
