### ISSUE TITLE
Execution logs filter size changes 

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5457]
### Describe the issue

Small issue but would look better if filter would have the same size when selected

https://github.com/user-attachments/assets/9852137d-12e8-4885-9359-6762b7967fff

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by shawnfrost69** [comment]
Hi @smunteankestra 
I believe I can contribute to resolving this issue. Would it be okay for me to take it on?

**Comment by smunteankestra** [comment]
@shawnfrost69 sure!, thanks

**Comment by anna-geller** [comment]
this has already been fixed https://share.descript.com/view/8XS4HeKxPzF
