### ISSUE TITLE
[Frontend] Logs disappear when navigating back to Logs page.

### ISSUE THREAD

**Issue by mithindev** [kestra-io/kestra#5469]
### Preconditions
Logs are present on the Dashboard.

### Steps to Reproduce
1. View logs on the Dashboard.
2. Navigate to another page, e.g., "Flows" or "Dashboard".
3. Return to the Dashboard.

### Expected Behavior
Logs should remain visible on the Dashboard when returning from other pages.

### Actual Behavior
Logs disappear when returning to the Logs Page. A refresh temporarily restores them, but the issue reoccurs after further navigation.

### Demo

https://github.com/user-attachments/assets/6041f5c6-e5c3-4756-9eb5-c96537fc0eae

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by mithindev** [comment]
Can I solve this issue as well @MilosPaunovic?

**Comment by MilosPaunovic** [comment]
Absolutely @mithindev, and for future reference, you're always going to be welcome to solve any issue which you create yourself, and also, any other that no one is currently working on.

We at Kestra really appreciate your dedication and efforts, keep up the awesome work you're doing! 🚀

**Comment by brij0** [comment]
I will attempt to solve this as a part of my university project.

**Comment by MilosPaunovic** [comment]
@brij0 I would say that @mithindev is already working on a solution for this issue, but feel free to check out the [list of filtered good first issues](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and take your pick at something else that seems interesting.
