### ISSUE TITLE
push docker `latest-full` as clone of `latest`

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5475]
In the past, `latest-full` was our `latest` of today, but we stopped to push on the `0.19.0` meaning that all people (a lot since it's was our default) are stuck on the `0.18.X`, we need to push the `latest-full` as clone of our `latest` for retro compatibility

**Comment by loicmathieu** [comment]
I did it for EE but forgot to add it to OSS :(

**Comment by loicmathieu** [comment]
@tchiotludo maybe you can run `regctl image copy kestra/kestra:latest kestra/kestra:latest-full` so latest-full would point to 0.19.3.

**Comment by tchiotludo** [comment]
done for manual thing `regctl image copy` 
but the goal of the ticket is to include this on our release process

**Comment by loicmathieu** [comment]
Yes, it's done now
