### ISSUE TITLE
Avoid using applicationContext.init() to init a RunContext

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5492]
### Issue description

Today we init some services needed by the RunContext using `applicationContext.init(this)`.
This is costly and as we init a lot of run context this should be improved, for ex by setting the needed dependencies.

See https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/runners/DefaultRunContext.java#L120

**Comment by PurandharAdigarla** [comment]
Hi @loicmathieu, can I get assigned to this issue, I want to give it a try

**Comment by loicmathieu** [comment]
@PurandharAdigarla be my guest, but as it's schedule for 0.21 and very technical we may not merge it soon.

**Comment by PurandharAdigarla** [comment]
Thanks for letting me know, I will understand the issue deeper and try to solve it effectively.
