### ISSUE TITLE
Add error message and stacktrace to the execution overview tab

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5495]
### Feature description

In case an execution fail, we now have inside the execution object an `error.message` and `error.stackTrace`.
See https://github.com/kestra-io/kestra/pull/5491

This information is valuable so we should display them in the execution overview tab, I would say either at the top or under the execution properties.

![image](https://github.com/user-attachments/assets/1c0f30a8-d401-4a96-92d2-e6a442af420c)

**Comment by loicmathieu** [comment]
@Nico-Kestra can you come up with some design for it, like a red box with the error message (usually one line) and either the stacktrace (10 lines) or a carret/more info to display it.

**Comment by Nico-Kestra** [comment]
![image](https://github.com/user-attachments/assets/7382ce67-06d1-42e7-901b-d5c57b79b719)

<img width="1241" alt="Capture d’écran 2024-10-16 à 16 00 23" src="https://github.com/user-attachments/assets/9f408873-3f07-4cde-a488-9a12aed59324">

[Figma](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=1446-8508&t=rDlrvJtzxeQib4gQ-1)

**Comment by abhishek-singh0710** [comment]
Hi, Can this issue be assigned to me?

**Comment by anna-geller** [comment]
@abhishek-singh0710 are you working on this or can we assign it to someone else?

**Comment by abhishek-singh0710** [comment]
I'm really sorry I was facing some health issues so could not work on it earlier.
But I've started working on it since yesterday and will try to do it at the earliest.

**Comment by abhishek-singh0710** [comment]
I'm sorry but maybe you should assign this issue to someone else as my health has taken a turn for the worse.
I am really sorry for the inconvenience I caused.

**Comment by anna-geller** [comment]
No problem! Get well soon

**Comment by Vivvek09** [comment]
Heyy @anna-geller 
I would love to work on this!

**Comment by MilosPaunovic** [comment]
Go for it @Vivvek09! :rocket:

**Comment by Vivvek09** [comment]
Heyy @MilosPaunovic 
I tried to solve the issue by displaying error.message and error.stacktrace using the given design. 

Here are the results: 
<img width="524" alt="image" src="https://github.com/user-attachments/assets/fba75125-fcfd-4399-8269-6159270e0273">
<img width="530" alt="image" src="https://github.com/user-attachments/assets/d6dd40d6-be7d-4d86-bd50-206950edcffb">

However, I had a small doubt. The design given has llinks eg. task failed at line 115. Should that be incorporated as well?
Please let me know if any changes are needed

**Comment by MilosPaunovic** [comment]
Hi @Vivvek09, 

I would say links in stack trace would be nice to have, but not really that useful in the web environment. If it's easy to implement, maybe you can link to files in `Kestra` repo, if it's difficult, I'd say we can go by without them. Does that sound alright @anna-geller?

**Comment by anna-geller** [comment]
Can you share your PR? Congrats @Vivvek09, this looks ready to be merged 🎉

**Comment by Vivvek09** [comment]
Heyy
I tried to link the errors to files in the Kestra repo. However, the files were not in one common folder.
E.g., Fail.java is in kestra\core\src\main\java\io\kestra\plugin\core\execution\Fail.java, whereas WorkerTaskCallable.java is in kestra\core\src\main\java\io\kestra\core\runners\WorkerTaskCallable.java. Hence, I could not find a way to link them.

I have created a PR for the previous change

**Comment by MilosPaunovic** [comment]
Nice job, thanks for this @Vivvek09! 🚀
