### ISSUE TITLE
logs screen : "hamburger menu" is displayed even if it contains nothing

### ISSUE THREAD

**Issue by brahimalm** [kestra-io/kestra#55]
When a taskRun has no output nor is restartable, the "hamburger menu" is still displayed and contains nothing.

depends on: #54

**Comment by eregnier** [comment]
Yes, we must do the #54 first, because with actual implementation we waste frontend computation. Doing this without #54 would be worst.

**Comment by tchiotludo** [comment]
fix in 84a764bc8f4d3b11537fd9321fdedbd4d33aa388
