### ISSUE TITLE
Code blocks lack indentation within in-app docs 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5504]
### Describe the issue

To reproduce, go to the `Docs` page within the app. Then, browse through a couple of pages and check the code blocks. Currently the indentation is not the same as on the kestra.io/docs 

![image](https://github.com/user-attachments/assets/468268e6-0a22-41be-9e46-5e9f2b61fe3e)

### Environment

- Kestra Version: develop

**Comment by rishavd3v** [comment]
I would like to work on this issue.

**Comment by anna-geller** [comment]
great, thanks a lot @rishavd3v! @brian-mulier-p mentioned it might be an issue of some CSS that changed as it's used to work before
