### ISSUE TITLE
Right click actions for editor tabs

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5508]
When we have multiple tabs opened in the editor, we want to implement right click menu for tabs which will provide multiple closing actions:

- [x] Close all tabs
- [x] Close other tabs
- [x] Close tabs to the right

Bare in mind that the first tab which is always the flow can not be closed, ever.

**Comment by 2231sshubham** [comment]
Hey @MilosPaunovic , I'm new to open source and I would like to pick this up.

**Comment by MilosPaunovic** [comment]
Go for it @2231sshubham! :rocket:

**Comment by tunchungcheng** [comment]
Hi @MilosPaunovic @anna-geller Can assign to me? 
<img width="1582" alt="截圖 2024-11-10 晚上10 50 55" src="https://github.com/user-attachments/assets/e84611ef-7254-4f8a-ad4d-4247f279be7a">

**Comment by MilosPaunovic** [comment]
This was really great work @chengtc-dev, and I do mean it! 🚀

You've managed to do everything independently in new, large scale code base and to do it right the first time. I've added just a few stylistic changes and merged this.

Maybe it'd be interesting to you to check out more [editor related issues](https://github.com/kestra-io/kestra/issues/3690) and maybe tackle some of them too.

Thanks a lot for the contribution, looking forward to reviewing more of your PRs!
