### ISSUE TITLE
Add horizontal scroll bar to file tree view

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5509]
Add horizontal scroll bar when the file is too long https://share.descript.com/view/lMp67IZsjUk

**Comment by code-grey** [comment]
I would like to work on this, any suggestions for a beginner contributor? :)

**Comment by MilosPaunovic** [comment]
Hi @code-grey,

First take a look at [this](https://kestra.io/docs/getting-started/contributing#setup-to-work-without-building-the-backend-from-the-source-code) guide to set everything up and running.

After, you'll want to find the `EditorSidebar.vue` component and start looking for solution there.

**Comment by code-grey** [comment]
Thanks! I'll get started

**Comment by Ben8t** [comment]
@code-grey did you succeed to make any progress on this :) ?

**Comment by code-grey** [comment]
I was successful on setting up the dev environment and started working on it but then got occupied with my studies.. please assign it to someone else for the time being :)
(Sorry for being unable to make any contributions)

**Comment by MilosPaunovic** [comment]
That's perfectly fine @code-grey, don't worry about it and good luck with the exams! 🚀

**Comment by Niravdas** [comment]
@MilosPaunovic 
I would like to pickup this.

**Comment by MilosPaunovic** [comment]
Go for it @Niravdas! 🚀

**Comment by Niravdas** [comment]
I need to set `max-width` to `el-tree` element to make scroll visible.

by setting fixed width it will not be responsive anymore, what would be best solution for this?

![image](https://github.com/user-attachments/assets/11afa17e-8716-4482-98e8-a0591553f15a)

**Comment by MilosPaunovic** [comment]
Hi @Niravdas,

We need to keep it responsive, so you might need to look into some of the nested elements; can't guide you any further without properly getting into the topic, so why don't you try and poke around a bit more by yourself.

**Comment by Niravdas** [comment]
Yup, I am already on it, will update once done.

**Comment by Niravdas** [comment]
can anyone please review PR raised?

https://github.com/kestra-io/kestra/pull/5651

**Comment by MilosPaunovic** [comment]
This is still open for grabs for any external contributor, if anyone wants to tackle it.

You can easily reproduce this by going to `Create file` and typing this as the filename:
```
abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde/abcde.js
```

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic ,

Please you may assign it to me and review my PR if it is as per the expectation.
