### ISSUE TITLE
Right-click action on file tree sidebar in the Namespace Files Code Editor

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5510]
Add the right click menu on the file tree sidebar to create a new file with extension (e.g. myscript.py) or folder

**Comment by code-grey** [comment]
Hey there, @MilosPaunovic ! 
I want to work on this. Any suggestions? (I am a beginner)

**Comment by MilosPaunovic** [comment]
@code-grey Let's first solve the other issue you pinged me for, and after, you can tackle this one if no one else does it in the meantime.

**Comment by code-grey** [comment]
Okay!

**Comment by ayesha-firdaus** [comment]
Hi! I'm interested in working on this issue. Could I be assigned to it?

**Comment by MilosPaunovic** [comment]
@ayesha-firdaus It's all yours! :rocket:

**Comment by Ben8t** [comment]
@ayesha-firdaus did you succeed to make any progress on this :) ?

**Comment by ayesha-firdaus** [comment]
Yes sir I am working on it

**Comment by tunchungcheng** [comment]
Hi @MilosPaunovic Can assign to me?

<img width="1468" alt="截圖 2024-11-15 凌晨1 00 33" src="https://github.com/user-attachments/assets/f3f68c50-3dac-4bda-8942-315553a02c03">

**Comment by MilosPaunovic** [comment]
Yup @chengtc-dev, go for it! 🚀

**Comment by MilosPaunovic** [comment]
Really great work @chengtc-dev, thanks for this! 🚀
