### ISSUE TITLE
Unify all empty pages so that they use the same component

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5525]
### Feature description

We have 3 empty pages (and more will be added in the future), we need to standardize them to use the same component so that they use the same size of the Title, Description and image. 

<img width="1921" alt="Flow-Dependencies" src="https://github.com/user-attachments/assets/705a9cce-54bf-4801-abdd-c4824337b535">

![Flow-Triggers](https://github.com/user-attachments/assets/d47b914e-e848-4d5f-98c6-5d343a203e1f)

<img width="1921" alt="Flow-Dependencies-1" src="https://github.com/user-attachments/assets/3385d8eb-15ee-4a86-b0b0-a4a682c16aca">

**Comment by aravindinduri** [comment]
can i work on this @anna-geller @MilosPaunovic

**Comment by anna-geller** [comment]
@aravindinduri thanks so much! LMK if you need further explanation

![image](https://github.com/user-attachments/assets/35b8b3cf-0de9-4897-a8fe-af853d13608f)

**Comment by Vivek-1102** [comment]
Hey @anna-geller is this issue still open ? if yes then I am happy to work on this issue

**Comment by aravindinduri** [comment]
I wanted to inform you that, unfortunately, I won't be able to contribute to the assigned issue at this time. I apologize for the inconvenience.
Thanks for the cooperation.

**Comment by MilosPaunovic** [comment]
Not a problem @aravindinduri, thanks fo the effort! :rocket:

@Vivek-1102 let's go one by one, you're assigned to one issue already, after merging that, we can assign you here.

**Comment by D-I-R-M** [comment]
can i work on this @anna-geller @MilosPaunovic

**Comment by JoeCelaster** [comment]
Can i work on this project ?
> @anna-geller 
> @MilosPaunovic

**Comment by anna-geller** [comment]
@JoeCelaster let's give @D-I-R-M a chance as he asked first. Joe, we assigned you to this one you also requested https://github.com/kestra-io/kestra/issues/5209, is it OK for you? 👍

**Comment by JoeCelaster** [comment]
> @JoeCelaster let's give @D-I-R-M a chance as he asked first. Joe, we assigned you to this one you also requested #5209, is it OK for you? 👍

It's completely fine @anna-geller. I'll take that one.

**Comment by D-I-R-M** [comment]
@anna-geller 
I removed my assignment cuz i was unable to figure it out 
Is there a time limit ? I might take some days as I have my examinations going too . Is it ok?
It's my first time with a large codebase.

**Comment by Ben8t** [comment]
@D-I-R-M thanks for the notice. We plan to make this done by next release (beg. of December)

I assigned to @SanjyotX in the meantime: do not hesitate to discuss together to solve this one. I will check progress or any questions you might have in a few days 👍

**Comment by SanjyotX** [comment]
As a begineer at this i will researchh about this and try to get done asap and will discuss if have any doubt.......thank you so muchhh

**Comment by Vivvek09** [comment]
heyy @anna-geller @MilosPaunovic !
I am willing to work on this issue. I studied the code and wanted to clarify that a single component should be used only when there are no dependencies, concurrencies, triggers; otherwise they should display the dependencies, concurrency, triggers through their own component ryt?
Please correct me if I am getting it wrong. Thanks!

**Comment by MilosPaunovic** [comment]
Yes, you should create single Vue component for empty page and show it in the three instances from above.

**Comment by Vivvek09** [comment]
Heyy I tried to solve the issue through the following approach:
1) Create a new EmptyState.vue component as a common, reusable component
2) The component is used as follows. For example, in the Flow Concurrency view:
```
<empty-state
        v-else
        :title="$t('concurrency-view.title_no_limit')"
        :description="$t('concurrency-view.desc_no_limit')"
        :image="noConcurrencyImage"
    />
```
The title and description are fetched from en.json, and the image is sourced from the assets folder.

Here are the results:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/2b9fbf66-3a4e-467c-8692-51f6960dff7a">
<img width="958" alt="image" src="https://github.com/user-attachments/assets/6a24eae0-a049-4a88-899f-c0b270ae3cf8">

However, I couldn't find an empty state for Triggers.

Does my approach meet the requirement?

**Comment by anna-geller** [comment]
Nice work! I wonder why does it look a bit different in the image you shown as compared to the initial one shown in the issue@Vivek-1102? 

![image](https://github.com/user-attachments/assets/aaa8b27a-564f-4320-b71f-4c3610b4eb35)

the intent was that everything looks the same way as it currently does (as shown in the issue description) with the difference that it would be managed via the same component to make this code more [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself)

**Comment by Vivvek09** [comment]
ohh okay got it @anna-geller 

I updated the component layout andhere are the results:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/e8017326-c974-4ccb-a768-04842fff4b0a">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/22217be2-8a7c-4d89-9eb2-13e7dfaedce2">

They are standardized to use the same component
Should I open a PR if it seems alright?

**Comment by anna-geller** [comment]
yes absolutely, thanks so much!

**Comment by MilosPaunovic** [comment]
Good job here, @Vivvek09! 🚀

**Comment by Vivvek09** [comment]
Thankyou @MilosPaunovic !
I saw your commits and I will work on improving the formatting and removing unnecessary code henceforth!
Onto the next contribution 🚀
