### ISSUE TITLE
Add a background color to each namespace within Namespaces overview page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5526]
### Feature description

Should be:

![image](https://github.com/user-attachments/assets/93684c73-d289-419f-a488-c213bf78b7fa)

![image](https://github.com/user-attachments/assets/b7442f9a-6cf1-4ca2-884f-4739e3c8381a)

Currently is:

![image](https://github.com/user-attachments/assets/6291a5c0-7c5a-4766-8053-cd041ce34176)

[internal figma link](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=681-5355&t=x7cKh6nwfA4p61Q3-4)

**Comment by A-Vamshi** [comment]
Can I work on this?

**Comment by abhishekkhairnar** [comment]
please assign me this issue 
@MilosPaunovic checkout this pr
[#5526](https://github.com/kestra-io/kestra/pull/5603)

**Comment by MilosPaunovic** [comment]
Great work @abhishekkhairnar, thanks for the contribution! 🚀
