### ISSUE TITLE
Improve EncryptedString documentation

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5527]
### Feature description

EncryptedString is a special type of output that will be automatically encrypted and decrypted so it is stored safely, and can't be decoded in the UI from the debug output functionality.

It's cool.

But it's visible in the documentation, see https://kestra.io/plugins/plugin-gcp/tasks/auth/io.kestra.plugin.gcp.auth.oauthaccesstoken#io.kestra.plugin.gcp.auth.oauthaccesstoken-accesstokenoutput

For an output named `token` of type EncryptedString, two properties will be emitted (type and value) and replaced at runtime by a single property.
So even if in the documentation you think that `token.value` exist, it cannot be used in a Pebble expression which should use, simply, `token`.

Documentation is misleading, we should at least remove the EncryptedBody definition.

We could also, but not mandatory, either replace EncryptedString by String when generating the schema/doc, or add a note to explain what it is and how it works.

**Comment by RashmitTopG** [comment]
Can i try ??

**Comment by loicmathieu** [comment]
Hi @RashmitTopG  thanks for your interest in improving Kestra, but we're not sure yet of what exactly needs to be done here, better to work on an issue labeled [good first issue](https://github.com/kestra-io/kestra/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).
