### ISSUE TITLE
The "See all" button in the Executions in progress panel points to unfiltered Executions page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5529]
### Describe the issue

Currently, the "See all" button points to `/ui/executions`:
![image](https://github.com/user-attachments/assets/f63bacef-e990-49d1-804a-d148ddd1a3d1)

It should instead point to a filtered table with in-progress states: `state=RUNNING&state=RESTARTED&state=CREATED&state=PAUSED&state=RETRYING&state=QUEUED&state=KILLING`

### Environment

- Kestra Version: develop

**Comment by RashmitTopG** [comment]
Can i try this ??

**Comment by MilosPaunovic** [comment]
@RashmitTopG Ping me for a review once completed.

**Comment by sachinks07** [comment]
One doubt here the api which is used for fetching the **execution in progress data** doesn't include the created state as query param . So while redirecting to executions page on clicking see all is it required to pass **created** also as query param.

<img width="1605" alt="Screenshot 2024-10-21 at 12 39 07 PM" src="https://github.com/user-attachments/assets/99cced2b-ffb3-44e2-a05c-4f3315d05a7e">

**Comment by anna-geller** [comment]
that's probably OK, the CREATED state is a special state, so it's OK if it's not included here 👍

**Comment by anna-geller** [comment]
@RashmitTopG or @sachinks07 any progress on this? keep us posted if you need more input

**Comment by MilosPaunovic** [comment]
Hi @RashmitTopG, is there any progress on this?

**Comment by SayedQassim** [comment]
Hi @MilosPaunovic, Can I be assigned to this? I have already took a look and fixed the issue, I will raise a PR in a moment. Thank you.

**Comment by MilosPaunovic** [comment]
Thanks for this @SayedQassim! 🚀
