### ISSUE TITLE
Some plugin icon colors are incorrectly inverted in the UI

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5530]
### Describe the issue

Compare [the following blueprint](https://kestra.io/blueprints/system/272-create-github-issue-when-a-workflow-fails):

![image](https://github.com/user-attachments/assets/2f433499-5e08-4677-ad09-bebd59006404)

with the same in the UI http://localhost:8080/ui/blueprints/272:

![image](https://github.com/user-attachments/assets/13ac7798-bd71-45ff-84cf-3d7cd2f0e84a)

On the website, all icons are displayed correctly but in the UI, some icon colors are incorrectly inverted:

![image](https://github.com/user-attachments/assets/e2467b28-f476-4d24-8eb0-ff1558810933)

![image](https://github.com/user-attachments/assets/8d20f9bc-642a-4fd0-a9cb-91a5108e3666)

![image](https://github.com/user-attachments/assets/827b63f9-3078-4108-89ec-5a4acf757d21)

![image](https://github.com/user-attachments/assets/ecdb0ca8-5911-41ce-988d-e586e9faa0e8)

### Environment

- Kestra Version: develop

**Comment by shivanshsharma13** [comment]
Hi @anna-geller greetings!, can I take this issue?

**Comment by Abi20601** [comment]
Hey, can i take this issue ? If its still available

**Comment by anna-geller** [comment]
I'll assign you both so you can both try, it might be a complex one so you can work together, validate what is the root issue 👍 thanks so much!

**Comment by shivanshsharma13** [comment]
Hi @anna-geller @MilosPaunovic. Greeting for the day!

I tried to debug the issue and found that `icon = icon.replaceAll("currentColor", color);` logic is not attached on FILL property on GitHub SVG. That is the cause of unchanged color of logo. 

Also I tried to find icon file and not able to find GitHub SVG file location in folder- kestra\core\src\main\resources\icons.

![image](https://github.com/user-attachments/assets/2d77cb41-bbe1-4bb4-9923-71f60fe25065)

So Am I missing on something, or GitHub SVG is coming from somewhere else?

**Comment by anna-geller** [comment]
it might be an issue in the plugin - the logos were added by a contributor so might be that Shruti didn't add the icons the right way [here](https://github.com/kestra-io/plugin-github/commit/aeb082ce7a6923632e87dfce21414ef55e67a5f8) - feel free to amend this by adding a PR on this plugin repo 👍 thx for working on this @shivanshsharma13!

**Comment by shivanshsharma13** [comment]
#### Hi @anna-geller, Greetings!

I’ve added a PR addressing the changes for the GitHub SVG images. For the `modalCLI`, I’d like to clarify the expectations. Should the images in the editor also have a grey background?

If so, I can explore ways to implement this, although it would apply universally. Let me know your thoughts!

#### Something like this
![image](https://github.com/user-attachments/assets/71fd9054-4c50-47d1-9539-44379c36a6f2)

Thanks!

**Comment by anna-geller** [comment]
Thanks so much for contributing and fixing this issue on the GitHub plugin! Feel free to submit equivalent PR on the modal plugin if you'd like 👍
