### ISSUE TITLE
Multi Select Inputs Clear Button

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#5533]
### Feature description

Really like the Multi Select Inputs, is there a way to add a clear icon-like button next to selection window to clear it to empty?

**Comment by JP-sDEV** [comment]
could I get an example of how you want it look and function @japerry911? I would like to try implement this feature

**Comment by japerry911** [comment]
![Screenshot 2024-10-17 at 12 19 53 PM](https://github.com/user-attachments/assets/81410c8c-57a6-4015-915b-51e6a8f1ffb3)

Im not sure the best placement but something where red is is what I was thinking, and then I could click it and the input would empty

**Comment by JP-sDEV** [comment]
Thank you for the screenshot! Before I attempt working on the feature, I'll get familiar with the frontend.

**Comment by codewithjk** [comment]
can you assign to me

**Comment by JP-sDEV** [comment]
@codewithjk could take it

**Comment by MilosPaunovic** [comment]
@JP-sDEV As you were the first here, yes, you can take it. Can you try to tinker with it for a bit and propose a solution or a few, and then we'll decide on the direction we want to go?

**Comment by Skraye** [comment]
Tips for the people that will fix it, but the component used already has a property `clearable` that you can enable to have a cross to remove everything

**Comment by MilosPaunovic** [comment]
Is there any progress with this @JP-sDEV? Are you still willing to tackle it @codewithjk?

**Comment by JP-sDEV** [comment]
Sorry for the absence. I am no longer interested in the issue.

**Comment by MilosPaunovic** [comment]
Okay, so, @codewithjk, Iif you want to tackle this one, it's yours.

**Comment by Piyush-r-bhaskar** [comment]
Hi @japerry911 @MilosPaunovic 

What's the situation here actually?

@japerry911 are you asking for a clear button thing outside of the selection box anywhere red represents? (_Or is it only that you want to use the `clearable` for el-select_)

Could you provide a reproducible path where you want to see this change ?
