### ISSUE TITLE
Increase the width of the scrollbar — it's too small to be used without a mouse wheel or keyboard arrow keys

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5537]
### Describe the issue

We should make the purple scrollbar as wide as the grey one:

![image](https://github.com/user-attachments/assets/763335b0-60f7-4056-b0b1-a4f80f0aee58)

Short demo: https://share.descript.com/view/mNysMkAwtnQ

If it's intended behavior, we can close the issue right away.

**Comment by Rafael-Floriano** [comment]
Hi Anna! May I get this task?

**Comment by Rafael-Floriano** [comment]
Hey Anna, what do you think? I made two versions of the change, both with the same bar size you indicated. However, one has a border-radius and the other does not. Which version should I move forward with?

Without border-radius:
![Screenshot from 2024-10-18 15-11-17](https://github.com/user-attachments/assets/74e67c6d-9003-4590-b785-be7fa351b10b)

With border-radius:
![Screenshot from 2024-10-18 15-19-56](https://github.com/user-attachments/assets/750d3622-f6f8-4164-948b-1aa4dc070f7e)

Note: I created the version with border-radius as I found it visually interesting, and I’m curious to know your opinions about it 🙂

**Comment by anna-geller** [comment]
you're totally right, that looks great! looking forward to your PR 💯

**Comment by Rafael-Floriano** [comment]
I created the [PR](https://github.com/kestra-io/kestra/pull/5552) for this issue 🙂

**Comment by MilosPaunovic** [comment]
It's merged now, thanks for the contribution @Rafael-Floriano! 🚀
