### ISSUE TITLE
Remove the long Inputs definitions from the Pause task documentation

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5538]
### Describe the issue

As a result of the `onResume` property, the plugin documentation of the Pause task lists all Inputs definitions. This look like unintended behavior? if it's intended, let's close the issue. Demo: https://share.descript.com/view/1qZ0WukqIX4 

Link to the docs showing the same https://kestra.io/plugins/core/tasks/io.kestra.plugin.core.flow.pause#definitions 

### Environment

- Kestra Version: develop

**Comment by RahulPrasadYadav** [comment]
can i work this issue @anna-geller

**Comment by MilosPaunovic** [comment]
Go for it @RahulPrasadYadav! 🚀

**Comment by Ben8t** [comment]
@RahulPrasadYadav did you succeed to make any progress on this :) ?

**Comment by bppdanto-t** [comment]
Hi @anna-geller @Ben8t, can you assign this issue to me? I can raise a PR for the fix.

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @bppdanto-t! 🚀

**Comment by Skraye** [comment]
I believe this is not an issue but the correct behaviour.

The Definitions is filled when a property have a subtype, here we have the onResume that is an array of Inputs, so we provide the definitions of inputs

@anna-geller If its clear for you, you can close the issue

**Comment by anna-geller** [comment]
as I mentioned in the video, it doesn't make sense to have documentation of all possible inputs in the Pause task; if anything, this would need to be added in the main docs i.e. in `basic.md`

I'd recommend to ignore this issue for now as there is a design from Nico we wanted to add for a while that will have expand collapse for all properties/outputs — once that design is implemented, this long list of inputs might resolve itself with collapse -- see here https://github.com/kestra-io/kestra/issues/4154

**Comment by bppdanto-t** [comment]
I found that some properties in Pause task wasn't being rendered properly in the documentation and the form. Should I make this PR to only fix that?

**Comment by anna-geller** [comment]
I like that filtering approach, big thanks for the PR @bppdanto-t! We can't merge it today as we are in the release process so I'll add a reminder for tomorrow.

**Comment by Skraye** [comment]
Removing documentation from our JSON Schema will remove it from Autocompletion
What's displayed in the documentation, is a markdown rendering of our JSON Schema, so we should close this issue without any changes in favor of #4154 to make a better UX instead of cutting in the documentation and features.

**Comment by bppdanto-t** [comment]
Just want to add, that I included `baseCls == null` as additional condition to specifically filter the definitions when it's trying to generate the schema for the documentation. Since the other usages are using the same endpoint but with `?all=true` flag, it won't be affected by the filtering, CMIIW.

If it's decided that this issue will be closed, then I'll raise different PR regarding the fix on the Pause (and probably other similar) schema annotation.

**Comment by anna-geller** [comment]
We won't be able to do that without removing the autocompletion of `onResume` input types:

![image](https://github.com/user-attachments/assets/ac3e2a37-5345-43b0-bc47-d99d862b58a9)

We'll tackle it as discussed in the https://github.com/kestra-io/kestra/issues/4154 with expand/collapse functionality

**Comment by bppdanto-t** [comment]
Just FYI, tested on my end to confirm that the Autocompletion still works using the my PR.
![image](https://github.com/user-attachments/assets/1a8e69e5-328a-427d-8b66-0a475c9f4665)

The form is working as well when trying to generate the dropdown.
![image](https://github.com/user-attachments/assets/abc97166-755f-40d6-aa2b-ec3b6f408fff)

But I get the point that it has been decided to resolve this 'issue' with different approach, just want to clarify. I'll try to find other issue that I may be able to help. Thanks

**Comment by MilosPaunovic** [comment]
@bppdanto-t, may I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by anna-geller** [comment]
thx @bppdanto-t, I asked Yann, we'll investigate and get back to you

**Comment by anna-geller** [comment]
@bppdanto-t it seems that you are right — it interferes with documentation generation but not the schema. Yann validated it and reopened your PR; we'll merge it once CI is green. Big thanks for your PR and for taking time to explain everything
