### ISSUE TITLE
Standardize the font size in the filter forms

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#5541]
### Describe the issue

Standardize the font size in the filter fields to 16px (1rem).

<img width="1724" alt="Capture d’écran 2024-10-18 à 10 01 21" src="https://github.com/user-attachments/assets/676256a7-ed5d-4752-b19f-84c06499a2c7">

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Ahmadmidlaj** [comment]
can i work on this

**Comment by MilosPaunovic** [comment]
Thanks for this @Ahmadmidlaj, great job! 🚀

**Comment by Ahmadmidlaj** [comment]
> Thanks for this @Ahmadmidlaj, great job! 🚀

Thank you for the kind words! I'm glad to contribute to the project. 🚀
