### ISSUE TITLE
Rework the Trigger page to show only columns that have data

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5546]
### Feature description

To reproduce, go to the Administration - Triggers page. You will see that there are too many columns. We should find a creating solution to only display columns that have some data. 

![image](https://github.com/user-attachments/assets/090ba127-d244-466a-8afc-f899970ca408)

**Comment by MRADUL9936** [comment]
@anna-geller i would like to work on this issue .

**Comment by MilosPaunovic** [comment]
Thanks @MRADUL9936, looking forward to more of your PRs! 🚀
