### ISSUE TITLE
When search returns no data, we should improve the display, especially in the tables

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5547]
### Feature description

Instead of:

![image](https://github.com/user-attachments/assets/896861b7-c9c9-4619-b6d5-4e6db3512338)

We can display: https://element-plus.org/en-US/component/empty.html 

The same for empty charts e.g. when no Executions exist or no Executions match the filter criteria:

![image](https://github.com/user-attachments/assets/2d283142-44bf-45ba-8776-6f1444eaa10b)

**Comment by sikehish** [comment]
I'd like to take this up. Could you assign this to me?

**Comment by MilosPaunovic** [comment]
Go for it @sikehish! 🚀

**Comment by sikehish** [comment]
> Go for it @sikehish! 🚀

Thanks for the oppurtunity! I wanted to know where the "No Data" message part is coming from. I couldn't find it in the codebase. I'm looking into Flows.vue and SelectTable.vue to make the changes.

**Comment by MilosPaunovic** [comment]
It should be a prop of the `element-plus` table, or the table component that is using it. Check their docs for the exact prop name.

**Comment by sikehish** [comment]
> It should be a prop of the `element-plus` table, or the table component that is using it. Check their docs for the exact prop name.

 Is this what you are looking for?
![image](https://github.com/user-attachments/assets/6c3091c5-e60a-485b-a732-201b9d029f36)

**Comment by anna-geller** [comment]
Yup, very nice!

**Comment by MilosPaunovic** [comment]
You've done an awesome job with this, it's going to improve the product immensely! Thanks for this contribution @sikehish  and we're looking forward to more of them in the future! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/5557.

**Comment by sikehish** [comment]
> You've done an awesome job with this, it's going to improve the product immensely! Thanks for this contribution @sikehish and we're looking forward to more of them in the future! 🚀
> 
> Closed via #5557.

Thank you:)) Looking forward to contributing!
