### ISSUE TITLE
The video container in the built-in Docs is too large

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5549]
### Describe the issue

Too much empty space in the video container within in-app Docs. Compare the UI state (too much space, too large):

![image](https://github.com/user-attachments/assets/890cddea-c07e-43f6-8c0f-ac1115df63e0)

with what's on the website (much better):

![image](https://github.com/user-attachments/assets/af48718c-d854-472d-98b8-557cdbc972b3)

Essentially, only the width should adapt to the screen, not the height of the video container. 

### Environment

- Kestra Version: develop

**Comment by kb-s** [comment]
can I work on this issue @anna-geller ?

**Comment by anna-geller** [comment]
yes absolutely, @kb-s, thanks a lot!

**Comment by kb-s** [comment]
thank you @anna-geller :)

**Comment by anna-geller** [comment]
@RyanVem you seem to have a working fix, would you like to contribute a PR?

**Comment by 5AIPAVAN** [comment]
can i take this @anna-geller :-)

**Comment by MilosPaunovic** [comment]
Let's see first if @RyanVem would like to submit a PR, if not, you can take over @5AIPAVAN.

**Comment by RyanVem** [comment]
Hello, I am currently not available to submit a PR, @5AIPAVAN can definitely work on the issue, thanks

**Comment by 5AIPAVAN** [comment]
@MilosPaunovic is this issue still in open (because the video container seems ok for me ) :-)
if still need some changes, i will make them and open a PR ( untill now i faced some issue to run kestra locally,now its fine, so i am ready to contribute)

**Comment by MilosPaunovic** [comment]
Maybe @Ben8t could tell us do we still need amending here or not.

**Comment by 5AIPAVAN** [comment]
## I just tried to decrease padding-top further to 50.25% (currently 56.25%)
## Depending upon your wish i will open a PR :-)
## Updated space (padding top-50.25%) looks like this
![image](https://github.com/user-attachments/assets/a9252db6-e905-42da-b3de-6c09091d5206)

**Comment by Ben8t** [comment]
@MilosPaunovic @5AIPAVAN the padding on current version seems good to me too. 

![image](https://github.com/user-attachments/assets/990b4982-ce0d-4b64-9055-992d5397fe66)


Closing issue for now
