### ISSUE TITLE
Change the markdown table design of the Flow Properties to match the markdown style shown in Docs and Plugin documentation 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5550]
### Feature description

The flow properties markdown table uses a different markdown design that the rest of the application:
![image](https://github.com/user-attachments/assets/5d89da02-993e-4c3c-8991-e848e4138370)

We want it to use the same markdown as e.g. here:

![image](https://github.com/user-attachments/assets/7fdada31-4ebf-42eb-994d-983929c59d7f)

**Comment by sanjaykumar584** [comment]
Hello @anna-geller,

I’d like to work on this issue. I have experience with VueJs, which I believe will help in resolving it.

Could you please assign this issue to me? Thank you!

**Comment by MilosPaunovic** [comment]
Go for it @sanjaykumar584! :rocket:

**Comment by abhishekkhairnar** [comment]
hello @anna-geller and @MilosPaunovic

i already have started working on this issue, can you please assign it to me 
here are my changes please check out 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/f2bcf51f-a51e-4732-93c1-aeff73aab823">

**Comment by anna-geller** [comment]
great work! could you also change the color of inline code blocks to match how they show in the Docs? 

Compare:
![image](https://github.com/user-attachments/assets/20741009-62b1-4613-8bdc-8da50717ce33)

Here - too much pink/red:

![image](https://github.com/user-attachments/assets/3e61cd89-d50a-423d-a12b-fe26d80b2b5e)

Thanks so much!

**Comment by sanjaykumar584** [comment]
Hi @anna-geller and @MilosPaunovic,

I noticed that @abhishekkhairnar  mentioned they’re working on the issue I was assigned to, and I saw your feedback to them. I just wanted to clarify that I was assigned to this issue first and have been making progress on it.

Would it be possible to revisit the assignment? I’d really appreciate the opportunity to complete the work.

Thank you for your understanding!

**Comment by abhishekkhairnar** [comment]
hii @anna-geller pls checkout this is this ok?
should i make pr?
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/bce49930-94eb-45e2-b1af-b4d2464b80f7">

**Comment by vvivekranjan** [comment]
Hey @anna-geller, I'm a beginner to open source and I would like to start my open source, journey by working on your project.
Would you please assign me this project?

**Comment by anna-geller** [comment]
Hi @abhishekkhairnar, a PR would be welcome, thanks a lot!

---

@sanjaykumar584 perhaps you can do the same for plugin documentation? I can open a separate issue and assign you 👍 this will be the same issue to ensure the markdown is consistent, e.g. check the plugin documentation for the Shell task - it also uses the pink inline code blocks instead of using the same grey ones that show in the Docs:

![image](https://github.com/user-attachments/assets/71587d69-9111-4d3a-810c-75a202fe5621)

**Comment by anna-geller** [comment]
@sanjaykumar584 please respond on the issue if you'd like to be assigned to that one (the same topic but this time for plugin docs) 👍 https://github.com/kestra-io/kestra/issues/5562

**Comment by abhishekkhairnar** [comment]
[#5564](https://github.com/kestra-io/kestra/pull/5564)
@anna-geller here it is

**Comment by sanjaykumar584** [comment]
@anna-geller yeah sure please assign me for the plugin documentation

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @abhishekkhairnar! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/5564.
