### ISSUE TITLE
Override hard-written parameters

### ISSUE THREAD

**Issue by thomas-depierre** [kestra-io/kestra#5551]
### Feature description

Would it be possible to add an override parameter to the task parameters?
Explanation :
Some parameters like 'allowFailure', 'concurrent', 'concurrency.limit' or others have fixed types which do not allow them to be replaced by variables.
In certain cases, we want to be able to control the level of parallelism according to external context elements or to authorize the failure of a task in the same way and so on.
The idea would be not to burden it with additional parameters but to have an environment parameter which authorizes the use of variables in these places.

**Comment by anna-geller** [comment]
can you give an example flow showing the requested change? 

in 0.20, all task properties will be dynamic, so you will be able to pass any properties like allowFailure boolean or the number of concurrent tasks for the ForEach task from inputs or variables 🎉 

if you mean concurrency.limit flow variable, this one cannot be dynamic as it's a flow level property, but everything else you mentioned will work in 0.20, you can already try it on the `develop` image 👍

**Comment by thomas-depierre** [comment]
Very good, that's perfect, I'll wait until December then. For flow properties like concurrency.limit, wouldn't it be possible that they depend on inputs transmitted by the parent flow?
e.g. :
- concurrency:
    limit: 2
-> concurrency:
       limit: "{{ inputs.concurrency.limit }}"

**Comment by anna-geller** [comment]
Afaik flow level concurrency limits cannot be changed through inputs because the executor needs to know how many parallel executions are allowed for that flow before attempting to run an execution. Maybe it is possible to make that being passed through inputs, let me ask @loicmathieu on Monday. 

Keep in mind that you can change the limit at any time in a new revision and the executor will always evaluate concurrency based on that last revision. If this is enough for the use case, feel free to close the issue. Perhaps you can say more about the use case that needs flow concurrency to be dynamic?

Btw are you perhaps trying to trigger multiple subflow executions based on some dynamic values? I believe you could explore the ForEachItem task

**Comment by thomas-depierre** [comment]
Okay, I understand.
Indeed, these executions are the result of calls to a ForEachItems.
The idea being that alongside this, we measure the performance of the db which executes SQL to know whether or not the performance allows us to launch new parallel tasks at any time.

**Comment by thomas-depierre** [comment]
Managing competition in this way will not achieve this dynamic outcome

**Comment by loicmathieu** [comment]
Some task properties are handled by the executor and used in places where we cannot access the execution context (or it is not already created like for concurrency limit), so even if technically we can now make virtually any properties of any tasks dynamic, some properties will never be dynamic and I think that both concurrence limit and allowFailure fall in this area.

**Comment by anna-geller** [comment]
@loicmathieu just to confirm, do you mean that the flow-level `concurrency.limit` cannot be dynamic (e.g. passed from inputs)? the question here is about this flow-level property, not task properties

**Comment by loicmathieu** [comment]
The issue talks about multiple properties, some on tasks, and some on flow.

For Flow level properties, even if we "could" make them dynamic (which I didn't say we could for concurrency limit) we mayb be careful do to so as in this case they will become "execution" level property and not "flow" level property.

For concurrency, this didn't make sense if some execution allows 4 concurrent execution and other 5 ... this means each execution can decide if they can pass the concurrence check ? :thinking: I don't think it would be a good idea and all monitoring around concurrency limit would be wrong (and I'm not sure the way we pop queued executions out of the queue would not risk to be wrong).

So, this is not trivial, and all properties at the flow, global tasks level, and on flowable tasks needs to be evaluated as they may impact the executor.

**Comment by anna-geller** [comment]
Yes, that's what I also thought. Two benefits I can think of for why making `concurrency.limit` dynamic (if feasible) could be useful:
1. Dynamic stress-test of the system - some folks are testing the limits of some operations in kestra so perhaps they would create 100 executions with a concurrency limit set to 100, then dynamically overwrite it to 200 when triggering 200 executions via API call. An edge case but I can imagine it could be useful 
2. Fetching this value from the KV Store - I can imagine how some operational DevOps team could want to manage this property centrally per flow depending on available infrastructure. 

If technically feasible with the new dynamic properties feature, I'd say let's allow this pattern of setting this dynamically just to enable the edge cases. We could e.g. add to documentation that there are some risks of race conditions in the executor if this is dynamic; there is some value here (if feasible) 👍

**Comment by Skraye** [comment]
@anna-geller the new dynamic properties does not help to make anything easier to become dynamic, this is only a dev thing made at first to avoid forgetting rendering pebble

**Comment by loicmathieu** [comment]
As I said, it's not sure we can do it, and what about the UI part (observability), the UI is out of an execution context so if it's dynamic, we would not be able to display it.

**Comment by loicmathieu** [comment]
So do we remove it?
