### ISSUE TITLE
Use a compressed version of blueprint header

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5556]
This image is really to huge: https://github.com/kestra-io/kestra/blob/develop/ui/src/assets/plugins/headband.svg (5mb :scream:), use a compressed version like webp

**Comment by MRADUL9936** [comment]
@tchiotludo  can i do it ?

**Comment by MilosPaunovic** [comment]
Go for it @MRADUL9936! :rocket:

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/kestra/pull/5559.

Thanks for the contribution @SharadK10, and also thanks @MRADUL9936 for all the efforts on this and all the other issues! 🚀
