### ISSUE TITLE
Outdatet slack link everywhere

### ISSUE THREAD

**Issue by BLACK4585** [kestra-io/kestra#5560]
### Issue description

Hey,
I sadly cannot reach other community members due to the broken slack invite link. Every link you provide leads to your broken slack invite.

**Comment by MilosPaunovic** [comment]
Hi @BLACK4585, which provided links you think of? Can you give the example?

**Comment by BLACK4585** [comment]
When I click on the kestra link on your website e.g., I get this screen, which says this link is not active anymore.
![grafik](https://github.com/user-attachments/assets/cb59f238-dec6-43a9-a561-f4b220e7f53b)
https://kestra.io/slack

**Comment by MilosPaunovic** [comment]
Thanks for the additional information @BLACK4585. Could you investigate this a bit further @wrussell1999?

**Comment by wrussell1999** [comment]
Hmm weird. It works for me on my phone but I will test this again. @BLACK4585 can you let me know what browser / OS you're using?

**Comment by BLACK4585** [comment]
Oh yes, I see. In Chrome it is working. 
I am using Zen Browser with Win11.
One theory could be that the hardened Browser could interfere there, although other slack invite links do work.

**Comment by MilosPaunovic** [comment]
Can confirm that it works on Chrome on Linux, as well.

**Comment by BLACK4585** [comment]
Okay, then it's going to be a Layer 8 problem, I guess.
Thank you anyway for looking into this!
