### ISSUE TITLE
Show more information about triggers in Triggers page

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#5568]
### Feature description

The Triggers page under Administration -> Triggers are a great way to manage all the triggers under a tenant. However there's some improvements that could be made in the UI. 

1) Show additional information about the trigger. The exact icon shown in the below image could be shown in the trigger page, to be able to quickly see the type of trigger, and additional information for each trigger when hovered over : 

![image](https://github.com/user-attachments/assets/43a83ef9-e7d4-4374-8f46-17a388986c88)

2) Show the interval for the trigger. The current triggers tab shows the next scheduled timestamp and the last executed timestamp, but it does not show the interval for the trigger. It would be nice if there was a column that shows the interval for each trigger.

**Comment by rajneesh-18** [comment]
I want to work on this issue.

**Comment by Skraye** [comment]
Go for it then! :rocket:

**Comment by opbot-xd** [comment]
can i work on it?
@Skraye

**Comment by Skraye** [comment]
@rajneesh-18 Have you made some progress?

@opbot-xd Let's wait for Rajneesh feedback first

**Comment by rajneesh-18** [comment]
> Reference in new is

Buddy actually my system have some glitches with the docker so i was unable to do anything with that issue.

**Comment by Skraye** [comment]
@opbot-xd Then you can pick it if you want!

**Comment by Skraye** [comment]
@opbot-xd How is it going?

**Comment by johnkm516** [comment]
The assignee doesn't seem to be active. Could this be followed up by the Kestra team?

**Comment by MilosPaunovic** [comment]
Yup, absolutely, I'll take care of it today @johnkm516!
