### ISSUE TITLE
KV Store - Column sort buttons not working

### ISSUE THREAD

**Issue by KoenWindey** [kestra-io/kestra#5576]
### Describe the issue

On any KV Store tab in Namespaces, clicking the up or down arrow next to a column header does not result in sorting the column.

![image](https://github.com/user-attachments/assets/d597ff0a-9be4-4daf-a5d7-4c29f19a4a2a)

### Environment

- Kestra Version: 0.19.2
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker): n/a

**Comment by pphy03** [comment]
Hi, I would like to contribute to this issue. please assign this to me.

**Comment by MilosPaunovic** [comment]
Go for it @pphy03! 🚀

**Comment by Ben8t** [comment]
@pphy03 I'm removing you from assignee as we didn't get any news on your progress here. Feel free to let me know if I miss something :)

**Comment by tlrznf46** [comment]
Can i try this issue ?

**Comment by MilosPaunovic** [comment]
Go ahead @tlrznf46! 🚀

**Comment by tlrznf46** [comment]
I'm working on solving a particular issue but am uncertain if my approach is correct.

1. Is it appropriate to modify the NamespaceKV.vue page to address this issue? I suspect that the current problem lies in the fact that certain functions are not implemented or connected within NamespaceKV.vue.

2. Should the sorting function be implemented directly within NamespaceKV.vue, or would it be better to create it in a separate location? If creating it elsewhere is advisable, which folder would be the most suitable?

Would it be alright to proceed with the approach I'm considering? If you have any recommendations for the development direction, I would greatly appreciate your advice.

**Comment by MilosPaunovic** [comment]
Hi @tlrznf46, You need to check how all the other tables are being sorted and use the same logic (you'll might need to explore `kestra/ui/src/mixins/dataTableActions.js` mixin.

**Comment by tlrznf46** [comment]
You're absolutely right. I also noticed that the sorting functionality is implemented there. 

However, I found that the sort doesn’t work properly in NamespaceFlow.vue, where this function is used. This made me wonder whether I should rely on this function or create a new one.

I’ll try to modify or use the code to make the most of dataTableAction with NameSpaceKV. 

Thank you for your response!

**Comment by MilosPaunovic** [comment]
@tlrznf46 

As the [endpoint which fetches the KV data](https://kestra.io/docs/api-reference/open-source#get-/api/v1/namespaces/-namespace-/kv
) is not like the other ones (there are no parameters for sorting to be accepted), we need to sort locally, meaning to add `@sort-change="onSort"` to the `select-table` component and to implement that method locally.

**Comment by tlrznf46** [comment]
Oh, I was just wondering how to use @sort-change! I’ll proceed based on your advice. Thank you!

**Comment by MilosPaunovic** [comment]
Great work, thanks for the contribution @tlrznf46! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/5952.
