### ISSUE TITLE
Align the pie chart labels when there are many states to display

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5578]
### Describe the issue

When there are too many state labels to display, the donut chart labels take too much space
![image](https://github.com/user-attachments/assets/0022f57c-db08-48bc-84e2-27eb59f4e400)

We should adjust the font to fit all states within the regular size of the chart

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by DVUN716** [comment]
@anna-geller I'd like to try this! Do you want to skip a few ui or do you want it to stretch when clicked?

**Comment by anna-geller** [comment]
@DVUN716 Thanks a lot, you are assigned! I was thinking about perhaps adjusting the font size of the States legend to make it fit? or stretching and stacking beneath each other... Feel free to give it a try and see what looks nice 👍 

do you need a couple of flows to generate those states to reproduce the issue? if so, LMK and I can share them

**Comment by DVUN716** [comment]
@anna-geller Sorry for the late answer. What file should I modify to modify the pie chart labels? I looked it up, but I don't know, so I'm asking you a question.

**Comment by DVUN716** [comment]
@anna-geller How do I make the created and killing states in Dashboard?

**Comment by MilosPaunovic** [comment]
Doughnut chart file is the `kestra/ui/src/components/dashboard/components/charts/executions/Doughnut.vue`, but for the legend labels, you'd need to tweak the `kestra/ui/src/components/dashboard/components/charts/legend.js` file, more precisely, `totalsLegend` plugin.

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @DVUN716! 🚀
