### ISSUE TITLE
Adjust the Blueprints page design

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5583]
### Feature description

New design:

![image](https://github.com/user-attachments/assets/304e4b39-42f6-4da6-92e5-76abf2d172e3)

https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3454-46907&t=qQw8i9EDFO02mKpb-4

**Comment by elevatebart** [comment]
As per our conversation with @Nico-Kestra 
I will wait until the white version is ready, then create a new layout where the background can bleed into the page instead of being contained inside the header

**Comment by Nico-Kestra** [comment]
![Blueprint_V2_Light](https://github.com/user-attachments/assets/0fdab4b4-b547-49a5-93b5-2fb0c5fac22a)


https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3513-34309&t=5li5UwoltWzKcfsW-1

**Comment by elevatebart** [comment]
TYTY!

**Comment by abhishekkhairnar** [comment]
@anna-geller please checkout this

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/2bf9f6a0-fd63-496c-940f-1c72c8f821e5">

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/18bfc30d-6a04-4c97-87c2-f1a9b050ec9f">

**Comment by MilosPaunovic** [comment]
Hi @abhishekkhairnar,

This looks like you're on a good track to close this one, among others.

But, you've already submitted PRs for two issues that had someone else assigned/working on it. As much as we appreciate your efforts in helping us solve that many bugs, we'd appreciate even more if you'd approach contributing by looking at the i[ssues that aren't already assigned to someone else](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22), and asking us beforehand if it's alright to start working on them. That way your help would be used in a best possible manner. 🚀

**Comment by abhishekkhairnar** [comment]
@MilosPaunovic Ohh sorry for that 
Now? Should I make pr for this or look for another issue

**Comment by anna-geller** [comment]
@abhishekkhairnar I appreciate your effort, but this issue was already assigned to a new colleague who just joined our team. Let's give him the opportunity to work on this :) 

meanwhile, you can explore [one of these issues](https://github.com/search?q=org%3Akestra-io+label%3A%22good+first+issue%22+is%3Aopen+label%3Aarea%2Ffrontend++no%3Aassignee&type=issues&utm_source=GitHub&utm_medium=github&utm_campaign=hacktoberfest2024&utm_content=Good+First+Issues). How about this one https://github.com/kestra-io/kestra/issues/2926 @abhishekkhairnar?
