### ISSUE TITLE
Add a new design of tables within Executions and Flows pages

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5586]
### Feature description

This is how those tables currently look like:

![image](https://github.com/user-attachments/assets/f3b74649-ddaf-4ae3-8b71-a5c2ac2a7603)

![image](https://github.com/user-attachments/assets/e7a5116e-699e-4bab-806f-a7600f6dd243)

The new design changes the following:
1. No more alternating rows, instead a single color with a darker on-hover effect
2. Unified display of States
3. Sorting icons changes
4. Trigger icons without borders
5. More space for the header row with column names
6. All text is displayed in a single color, no more pink text within the tables - links like the one for Execution ID or Flow ID are also displayed in white and only change to light purple on hover

![image](https://github.com/user-attachments/assets/c31e8380-3d8c-4592-9a4d-4d6c0a7ee7d2)

![image](https://github.com/user-attachments/assets/0ff8bd90-065c-4304-90aa-61df9e17ca75)

[Internal figma link](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3412-31752&t=PAglRoBvszd58WzR-4)

**Comment by Sarvesh0820** [comment]
hey, I'm interested in working on this issue. I am a newbie and I am eager to contribute to this project. Can you please assign me this work.

**Comment by MilosPaunovic** [comment]
As @Pk9697 was first, the assignment goes to him. @Sarvesh0820 feel free to take a look at our [list of curated good first issues](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and take your pick from there.

**Comment by anna-geller** [comment]
light mode SVG:
![Flow-Executions](https://github.com/user-attachments/assets/3ecd7a9e-f169-40c8-9a3c-0cf73c76981d)
![Flow-Executions (1)](https://github.com/user-attachments/assets/21aa4013-3358-4807-b34f-82c24e05145a)

**Comment by Pk9697** [comment]
> ### Feature description
> This is how those tables currently look like:
> 
> ![image](https://private-user-images.githubusercontent.com/86264395/378584475-f3b74649-ddaf-4ae3-8b71-a5c2ac2a7603.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTU4MTgsIm5iZiI6MTcyOTU5NTUxOCwicGF0aCI6Ii84NjI2NDM5NS8zNzg1ODQ0NzUtZjNiNzQ2NDktZGRhZi00YWUzLThiNzEtYTVjMmFjMmE3NjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDExMTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYzVjYmQxZGRiYmEyYTJjMjQxMDViMzVmNjc3OGU5ZGUwZDA1OTFiZWZkYzhkNDJlMmU3Mjg3NGRjMzU2Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NwLQ8aJJv3lnx3Spi3ksYAesFri2NZl6GVwffTdbMMw)
> 
> ![image](https://private-user-images.githubusercontent.com/86264395/378584558-e7a5116e-699e-4bab-806f-a7600f6dd243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTU4MTgsIm5iZiI6MTcyOTU5NTUxOCwicGF0aCI6Ii84NjI2NDM5NS8zNzg1ODQ1NTgtZTdhNTExNmUtNjk5ZS00YmFiLTgwNmYtYTc2MDBmNmRkMjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDExMTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3Zjc2YzNlMjJiM2Q2MjEzYzZjOWUwNTliNjAyZmNjNTQzMDRhZmE5YzFmYWFlY2ZiODc4MmVjN2IzMmUyMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j7DJZf672Ri_Oj119bYAEuClUfOOwCo16FgVEQl-kvY)
> 
> The new design changes the following:
> 
> 1. No more alternating rows, instead a single color with a darker on-hover effect
> 2. Unified display of States
> 3. Sorting icons changes
> 4. Trigger icons without borders
> 5. More space for the header row with column names
> 6. All text is displayed in a single color, no more pink text within the tables - links like the one for Execution ID or Flow ID are also displayed in white and only change to light purple on hover
> 
> ![image](https://private-user-images.githubusercontent.com/86264395/378586267-c31e8380-3d8c-4592-9a4d-4d6c0a7ee7d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTU4MTgsIm5iZiI6MTcyOTU5NTUxOCwicGF0aCI6Ii84NjI2NDM5NS8zNzg1ODYyNjctYzMxZTgzODAtM2Q4Yy00NTkyLTlhNGQtNGQ2YzBhN2VlN2QyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDExMTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYWE2NDFlMjEyNjExNzg4Njk5YjhmYzY1ZmYwZGVjZDkwZjZkZTVhNWYyZjkyMWE5MGFjNTdlYTYyZjhiNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fKu2af8m_U4u2jJBHuD7ORtVjZueiaLBll5ouAXLfb8)
> 
> ![image](https://private-user-images.githubusercontent.com/86264395/378586489-0ff8bd90-065c-4304-90aa-61df9e17ca75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTU4MTgsIm5iZiI6MTcyOTU5NTUxOCwicGF0aCI6Ii84NjI2NDM5NS8zNzg1ODY0ODktMGZmOGJkOTAtMDY1Yy00MzA0LTkwYWEtNjFkZjllMTdjYTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDExMTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYjZmNWEzOThlN2Q5MjQ2YjcwYmM2MDk4ZjQ0ZTI4MWNhM2VmNzQ3NDUzOTMxNWVmM2IyMWIyZTYzMTBiZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9t-MCFJXo2qTrS2RvOcRP26VyPhrTG5ZRtRQR0fnpfU)
> 
> [Internal figma link](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3412-31752&t=PAglRoBvszd58WzR-4)

Kindly provide the figma link access, requested with prashant.aman9@gmail.com

**Comment by MilosPaunovic** [comment]
We can not provide Figma access to external contributors, but what would you see there are the images Anna attached to this issue, so you can go by them.

**Comment by anna-geller** [comment]
if it helps @Pk9697 , here are all figma designs exported as SVG files: 
[tables.zip](https://github.com/user-attachments/files/17477718/tables.zip)

**Comment by Ben8t** [comment]
@Pk9697 did you succeed to make any progress on this :) ?

**Comment by Piyush-r-bhaskar** [comment]
Hi @anna-geller  @MilosPaunovic @Ben8t 

I would like to go ahead & try this. Would it be fine to assign plz ?

Also, are those buttons already styled & exists in repo or need to be styled ?

**Comment by MilosPaunovic** [comment]
You can take this on @Piyush-r-bhaskar.

Ignore the entire filters line.

Which buttons are you referring to?

**Comment by Piyush-r-bhaskar** [comment]
> You can take this on @Piyush-r-bhaskar.
> 
> Ignore the entire filters line.
> 
> Which buttons are you referring to?

Ahha my bad not the buttons but the style of States

**Comment by MilosPaunovic** [comment]
You can ignore the states styling for now, as there is this in place - https://github.com/kestra-io/kestra/issues/5127.

**Comment by anna-geller** [comment]
already done by Yann
