### ISSUE TITLE
[question] Can the orchestration results of Kestra run in any application?

### ISSUE THREAD

**Issue by liaodalin19903** [kestra-io/kestra#5588]
### Issue description

Can the orchestration results of Kestra run in any application? For example (mobile app, web end, desktop end)?

such as, I am developing a react web app, can I use kestra to arrange the logics? and the react runs the results(logic flow)?

**Comment by Ben8t** [comment]
Hello,
Kestra is API first meaning you can access any outputs or trigger flow from a simple API call.
Please find the corresponding [API reference here](https://kestra.io/docs/api-reference)

Please join our [slack](https://kestra.io/slack) if you want to discuss it more
