### ISSUE TITLE
Show tasks logs on topology execution can open 2 side popup

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#559]
![image](https://user-images.githubusercontent.com/2064609/163340115-0a385156-f833-4fe3-b67a-7394a470ce89.png)
It's must be because we don't destruction properly `TopologyTree.vue`

**Comment by noobyogi0010** [comment]
Hey @tchiotludo !
I would love to contribute by resolving this issue.
Can you please provide some brief about it?

Thank you!

**Comment by tchiotludo** [comment]
Hey @noobyogi0010, for sure.
- For the [TopologyTree](https://github.com/kestra-io/kestra/blob/develop/ui/src/components/graph/TopologyTree.vue), we mount [manually component to be able to display it on cytoscape](https://github.com/kestra-io/kestra/blob/develop/ui/src/mixins/VueManual.js#L17) (since cytoscape is not a vue component). 
- I've seen in the past that we need to [destroy](https://github.com/kestra-io/kestra/blob/develop/ui/src/mixins/VueManual.js#L29) it manually (if we don't, vue will keep all previous vue component leading to open multiple popup for example).
- You can reproduce it easily on the demo: 
  - Go [here](https://demo.kestra.io/ui/executions/io.kestra.demo.google/postgres-to-bigquery/uBU5zuBDsWNCHGyu0KM3r/topology)
  - Login with default credential 
  - Press the show task logs button, and you will see a popup with log on the right 
  - Go to another tabs and go back to topology 
  - Press the same button and 2 popup will be open. 

Is that clear for you ?

**Comment by noobyogi0010** [comment]
Yes it is @tchiotludo 
I will start working on it.
Thank you!
