### ISSUE TITLE
Add Ellipsis mode to long Task name in Logs screen

### ISSUE THREAD

**Issue by brahimalm** [kestra-io/kestra#56]
![Kestra-Bug-EachTask-Ellipsis](https://user-images.githubusercontent.com/47592117/73924987-9b58b900-48cd-11ea-9675-e7052b4ce5ba.png)

**Comment by eregnier** [comment]
https://github.com/kestra-io/kestra/commit/b539dbc6e4ecf981d765658f653670e3f8913531#diff-86cc4060556bfba085c02c306ad69809R37
