### ISSUE TITLE
Blueprints search field works odd

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5607]
### Describe the issue

Caught by automated issue  https://github.com/kestra-io/kestra/issues/4997
Blueprint search shows more results than expected 

Also the blueprint: "[Load a CSV file to a Postgres table]" opens a link differently then before 

java.lang.AssertionError: The current URL does not contain the expected path

Expected :a string containing "ui/flows/new?blueprintId=58"
Actual   :"http://localhost:8080/ui/flows/new?blueprintId=company.team.copyin_postgres&blueprintSource=community"

![image](https://github.com/user-attachments/assets/6ffbbb76-1ab2-4ec2-99c5-cf9ec06aa6fe)

Another small issue is error handling 
Ass this link to the search field : "http://localhost:8080/ui/blueprints/community?size=10&page=1&q=Load+a+CSV+file+to+a+Postgres+table"

it will return 500

https://github.com/user-attachments/assets/ccc5db54-1567-4ffb-8017-21b8cbc9f042

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
This might be due to the changes on handling blueprints (Strapi -> GH). I'm assigning @brian-mulier-p to investigate about that.

**Comment by brian-mulier-p** [comment]
The 1. is correct, the links are changed because the blueprints ids are no longer strapi ones so you can update your test.
I just fixed the 2.
