### ISSUE TITLE
No message when flow list is empty

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#5632]
### Describe the issue

When there is no flow, the page is just empty without any message :
![image](https://github.com/user-attachments/assets/eafec645-12ae-4727-9ac0-18eaf4efffbb)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by shantanuk7** [comment]
For locally running environment (using docker), I see a "No data" message already.
![kestra-flows-empty-screenshot](https://github.com/user-attachments/assets/ad69d716-aa51-4f5a-bec1-e31317cd8c8a)

But if it is a system specific issue, this may help as a reference.

**Comment by MilosPaunovic** [comment]
Can you look in the code @shantanuk7 and check situations when something like this could happen, to try and pinpoint the problem?

**Comment by prajyot004** [comment]
I am running it locally it's not showing anything

**Comment by MilosPaunovic** [comment]
Nice job, thanks for the contribution @prajyot004! 🚀
