### ISSUE TITLE
Sync with System theme option is missing in the Editor Theme

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5637]
### Describe the issue

When you select the option "Sync with System", we should apply the same to code blocks:

![image](https://github.com/user-attachments/assets/2f03e5f8-e8fb-4f26-87f5-5d5c3d840c74)

Let's add the same "Sync with System" option to the Editor Theme:

![image](https://github.com/user-attachments/assets/7cdfb7eb-7107-4a47-865a-78ed6ae2f81e)

### Environment

- Kestra Version: develop

**Comment by RudhraBharathy** [comment]
@anna-geller I'm interested in solving this issue, please assign this issue to me
TIA

**Comment by MilosPaunovic** [comment]
@RudhraBharathy Use this [PR](https://github.com/kestra-io/kestra/pull/5554) as a guide.

**Comment by RudhraBharathy** [comment]
Hey, @anna-geller / @MilosPaunovic

Should the **default** editor theme be 'dark' or 'light'?

**Comment by anna-geller** [comment]
I'm not sure if we set any default here. The "Sync with System" seems like a smart default. Btw keep in mind @RudhraBharathy this issue is to add the equivalent "Sync with System" option to the code editor 👍

**Comment by RudhraBharathy** [comment]
Hi @anna-geller / @MilosPaunovic,

I have submitted a PR. Please take a look and share your feedback. If any changes are needed, I’d appreciate your guidance. Thank you!

**Comment by MilosPaunovic** [comment]
Nice work @RudhraBharathy, thanks for the contribution! 🚀
