### ISSUE TITLE
Stacktrace are not multiline 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5649]
![image](https://github.com/user-attachments/assets/205a5f25-91ca-4dad-9c3c-5ac796181c9b)
Stacktrace are not readable (removing multiline `\n`) that is sent by the backend. 
We should 
- keep multiple line 
- label (TRACE) should be aligned on the top and not on the center

**Comment by Danesh-md** [comment]
can i also work on this?

**Comment by Ben8t** [comment]
@ThalaPravin did you succeed to make any progress on this :) ?

**Comment by aabhas-sao** [comment]
Hi @Ben8t, I would like to work on this issue.
Is there any config to enable trace. How can I reproduce the issue.
