### ISSUE TITLE
KV store: delete not possible if an entry is selected

### ISSUE THREAD

**Issue by schmanat** [kestra-io/kestra#5650]
### Describe the issue

It's not possible to delete an entry in the KV store via checkbox. If I select an entry (i.e. os) and than try to delete it, i get the following error message: 

```
method not allowed:
Method Not Allowed: Method [DELETE] not allowed for URI [/api/v1/namespaces/adsd.linux.system/kv]. Allowed methods: [HEAD, GET]
```
![delete_not_posible](https://github.com/user-attachments/assets/d527fbda-ebd5-4060-b402-f6854a2da134)

But, if I use the trash icon everything works.

### Environment

- Kestra Version: 0.19.5
- Operating System (OS/Docker/Kubernetes): docker (docker-compose)

**Comment by MilosPaunovic** [comment]
Can't reproduce it locally or on OSS preview. @Ben8t, could you try it?

**Comment by Ben8t** [comment]
Not able to reproduce either on my side (OSS preview or locally on develop) @schmanat can you try on kestra:develop ?

**Comment by schmanat** [comment]
Hi 

in the develop version it works (kestra:develop).

**Comment by MilosPaunovic** [comment]
@fhussonnois Could this be happening because we've missed to backport the bulk delete endpoint to the `0.19.x` version?

**Comment by Ben8t** [comment]
@MilosPaunovic @fhussonnois can we close this one ? 

> "we've missed to backport the bulk delete endpoint to the 0.19.x version?"

is it still relevant ?

**Comment by MilosPaunovic** [comment]
Nope, confirming that we've backported what was necessary and now it works properly.
