### ISSUE TITLE
Allow customization of columns displayed in the Executions data table

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#566]
For now, the list of columns displayed on every data table are fixed.
We need to allow customization of columns visible and maybe add some that can be useful (for example inputs for execution).

**Comment by yuri1969** [comment]
One of the useful columns for the Execution data table would be the `taskId` of execution's "current Task".

Use case: multiple _failed_ executions with their `taskId` visible would hint the task which caused the error immediately.

**Comment by anna-geller** [comment]
Let's start with a small inventory. Here are the columns that are currently available:
1. ID
2. Start date
3. End date
4. Duration
5. Namespace
6. Flow
7. Labels
8. State
9. Trigger

It's clear that we'd need a UI feature allowing selecting columns to be displayed/or hidden.

Below are the candidates of columns that could be additionally added:
1. `taskId` - Yuri suggests the `taskId` -- this could be the currently occurring task or the `taskId` of the last task run within the Execution. Is this feasible to display? 
2. `inputs` - the issue suggests inputs. This would be valuable for troubleshooting.
3. `variables` 
4. flow `revision` of a given execution
5. for scheduled flows, the table might display the fields of "`previous`" and "`next`" Execution date -- this would be valuable for troubleshooting, especially for troubleshooting of failed backfills

### Displaying large payloads in the Executions table

There might be some issues displaying large JSON payloads such as `inputs` and `variables` -- we may want to consider adding those as a string column with a "copy" button:

![image](https://github.com/kestra-io/kestra/assets/86264395/b3537705-6e21-4c8f-be0f-64104c37075f)
