### ISSUE TITLE
UI Overflow Issue near Execute Button and Tabs on Small Screens

### ISSUE THREAD

**Issue by mithindev** [kestra-io/kestra#5665]
### Issue description

UI Overflow Issue near Execute Button and Tabs on Small Screens

https://github.com/user-attachments/assets/e1e6d469-5014-4ab0-bd05-41d5a9266a66

**Comment by MRADUL9936** [comment]
@anna-geller  as i am working on kind of similar issue , i would be happy to work on this too .
