### ISSUE TITLE
Pre-transform Error: Failed to Resolve Import from @nuxtjs/mdc

### ISSUE THREAD

**Issue by mithindev** [kestra-io/kestra#5670]
### Describe the issue

I'm encountering a **pre-transform error** while setting up the Kestra frontend locally. This error started appearing recently, as I wasn't facing it a week ago.

`Pre-transform error: Failed to resolve import "#build/mdc-image-component.mjs" from "node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue". Does the file exist?`

## Steps to Reproduce

1. **Clone the Kestra repository.**
2. **Follow the instructions** in the setup guide to configure the frontend.
3. **Run the development server.**

The setup crashes with the above pre-transform error.

## Additional Notes

- This error may be related to recent updates or dependency changes. (I wasn't getting it mabe a week ago)
- The file path mentioned suggests an issue with the `@nuxtjs/mdc` dependency, specifically in resolving `mdc-image-component.mjs`.

Any guidance on resolving this would be appreciated!

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
@mithindev Could you try if [this Slack thread ](https://kestra-io.slack.com/archives/C03FQKXRK3K/p1729443061302449?thread_ts=1729442057.301619&cid=C03FQKXRK3K)will solve it for you (pasting here for simplicity)?

```
Delete the package-lock.json file and node_modules folder.
Pull the latest changes
Do Npm i
Open the package-lock.json file,change the @nuxtjs/mdc version to 0.8.3
Again do Npm install, it will resolve your problem.
```

**Comment by mithindev** [comment]
Resolved! Thank you s much.
