### ISSUE TITLE
Load of Blueprint inside flows page briefly shows error message before displaying the actual data

### ISSUE THREAD

**Issue by shivanshsharma13** [kestra-io/kestra#5672]
### Describe the issue

Similar to #4799 

When viewing a Flows, the load of the Blueprint view briefly displays the following error before displaying correctly.

 `No blueprints to show.` 

The issue can easily be seen on Cloud: [link](https://us.kestra.cloud/ui/demo/executions/shiny_rocks/slack_failure_alert/bTg6GZRtIis1oSJbZ0RcZ) .

https://github.com/user-attachments/assets/f4b650b5-3d3e-4abc-b4db-754a1be69129

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Great catch @shivanshsharma13, thanks for this! 🚀
