### ISSUE TITLE
Main Dashboard - rename the Create to "Create Flow" to avoid confusion with "Create Dashboard" option

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5686]
### Feature description

![image](https://github.com/user-attachments/assets/6ad251ee-85cb-45e9-9eb1-c6ce0b98f7ca)

**Comment by shivanshsharma13** [comment]
Hi, @anna-geller Greetings! I can do that and quickly win 😅

**Comment by MilosPaunovic** [comment]
Thanks for this @shivanshsharma13! 🚀
