### ISSUE TITLE
Documentation for API

### ISSUE THREAD

**Issue by vissul** [kestra-io/kestra#569]
### Feature description

any plan about OpenAPI ?

**Comment by tchiotludo** [comment]
hey @vissul :wave: 

What kind of open api integration you need? 
Not really sure to understand here your need? 
May you can expand your idea a little bit?

**Comment by vissul** [comment]
like airflow [Stable REST API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html)

**Comment by tchiotludo** [comment]
Haaa ! 
It's not documented for now but Kestra have a complete API, you can do everything using Open API, see the specs on our demo [here](https://demo.kestra.io/swagger/kestra-ee.yml).
Keep it open in order to add a proper documentation

**Comment by vissul** [comment]
thanks a lot

**Comment by tchiotludo** [comment]
it's available [here](https://kestra.io/docs/api-guide/)
