### ISSUE TITLE
Remove automatic Flow source generation

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5694]
### Issue description

Today, we automatically create the Flow source when it didn't exist.
We also "normalize" the flow source when we get it.

This was because:
- Before 0.9, flow source was not existing
- We still have deprecated endpoints to create a flow without a source.

We should:
- remove flow source automatic generation and flow source "normalization"
- Generate the source when needed in the flow JSON endpoints

**Comment by Skraye** [comment]
JSON endpoints are deprecated, maybe we should just delete them
That would also unlock an issue on the TF provider (that must handle both type)

**Comment by loicmathieu** [comment]
@Skraye this needs to be discussed internally first, you can open a discussion about it.
