### ISSUE TITLE
Move the new "Save Changes" button in the Settings page to the top navigation bar

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5695]
So far, any changes made to settings have been always auto-updated. I was changing some settings and was confused why they weren't applied -- it turned out that this step now requires a manual save. Given that this manual "Save Changes" step is required to make any changes, we should place it more prominently -- e.g. in the main navigation bar where all actions usually are added (like for "Save flow", "Create flow", "Execute" etc).

![image](https://github.com/user-attachments/assets/e26d4d0d-dac9-435f-a252-09bac505f34b)

Example of a more prominent Save button:

![image](https://github.com/user-attachments/assets/2b5c2d13-6ffe-45de-86d5-b0be99ec3d86)

**Comment by shivanshsharma13** [comment]
Hi @anna-geller, I would like to take this one!

**Comment by MilosPaunovic** [comment]
Thanks for this @shivanshsharma13! 🚀
