### ISSUE TITLE
Display value for dynamic tasks on logs page 

### ISSUE THREAD

**Issue by brahimalm** [kestra-io/kestra#57]
![Kestra-Bug-EachTask-EachSequentialNested-Restart](https://user-images.githubusercontent.com/47592117/73925197-f9859c00-48cd-11ea-88a0-a250f4d7d875.png)

**Comment by eregnier** [comment]
Any suggestions of what should be done, or at least what seems strange ?
I only iterate over an attempt list and I think this is the right way. So, what is the logic to apply to diplay the appropriate information accordingly ?
We may start by checking data integrity / content : does the API returns something logic ?

**Comment by tchiotludo** [comment]
We don't display the `value` of the taskRun in this specific case !

**Comment by tchiotludo** [comment]
done in 84a764bc8f4d3b11537fd9321fdedbd4d33aa388
