### ISSUE TITLE
Missing padding on hover for namespace 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5723]
On namespaces page: 
![image](https://github.com/user-attachments/assets/72986571-d058-4a25-8594-46db1dbc305c)
We are missing some padding and probably some rounded corner on the hover

**Comment by pranay9831** [comment]
Hi Tchiotludo,

I came across this issue on the namespaces page and noticed the need for additional padding and rounded corners on hover. I'd love to work on this and help improve the UI. Could you please assign this issue to me?

Thank you, and looking forward to contributing!

Best,
Pranay

**Comment by MilosPaunovic** [comment]
Go for it @pranay9831! :rocket:

**Comment by MilosPaunovic** [comment]
Thanks for this @pranay9831! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/5852.
