### ISSUE TITLE
Validate insecure registries

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5724]
### Issue description

@smunteankestra can you validate if those instructions are correct? https://kestra.io/docs/task-runners/types/docker-task-runner#insecure-registry along with [this explanation](https://github.com/kestra-io/plugin-docker/commit/4e4c4d8e1d969d67bb0952b67291fa602048113f#diff-62069fdf05ba71a5ce7862fd962a03471ea427b683668b15a4a50b5551f8a6a0R114) -- protocol is no longer a property and the insecure registry should be handled at the docker daemon level (aka not in Kestra itself)

This was intended to address https://github.com/kestra-io/plugin-docker/issues/32 but we didn't have the chance to QA this

**Comment by brian-mulier-p** [comment]
The note provided in commit works for sure so no need to test it but the kestra.io doc must be tested, especially the `config` property usage to specify an HTTP registry

**Comment by anna-geller** [comment]
@smunteankestra did you get the chance to have a look? ask Ben if you don't know what to do next 👍

**Comment by smunteankestra** [comment]
small issue, on the web page @MarcoSaba spotted a redundant  dot symbol 
![image](https://github.com/user-attachments/assets/c59bdaaa-0692-459d-a657-2a1093051965)

**Comment by anna-geller** [comment]
do you want me to remove that dot?

**Comment by smunteankestra** [comment]
the ip should be x.x.x.x:port ? not x.x.x.x.:port

**Comment by anna-geller** [comment]
good catch, fixed https://github.com/kestra-io/docs/commit/0c47b5bbfb55f89165bfd4c84a130ca828a336c2

**Comment by MarcoSaba** [comment]
According to @smunteankestra, this can be closed.
