### ISSUE TITLE
UI Overflow Issue in the List of Flows: Button and Tabs Overlapping on Small Screens

### ISSUE THREAD

**Issue by mithindev** [kestra-io/kestra#5727]
### Describe the issue

UI Overflow Issue in the List of Flows: Button and Tabs Overlapping on Small Screens

<img width="730" alt="SCR-20241030-sfut" src="https://github.com/user-attachments/assets/d16f5592-5b26-4cbc-b897-88464de2491c">

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by sanjaykumar584** [comment]
Can I work on this issue? have been trying to contribute to kestra for a long time @anna-geller

**Comment by MilosPaunovic** [comment]
Hi @sanjaykumar584, as @SarthakBorude asked first, he can have a first go at it, and you can take a look at [this curated list of good first issues](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and take your pick from there.

**Comment by Aniruddha775** [comment]
Hello, is the issue fixed?

**Comment by SarthakBorude** [comment]
Actually I'm on it.

**Comment by SarthakBorude** [comment]
> Hello, is the issue fixed?

Actually I'm on it. It will be fixed soon.

**Comment by Aniruddha775** [comment]
> > Hello, is the issue fixed?
> 
> Actually I'm on it. It will be fixed soon.

Ok.

**Comment by MilosPaunovic** [comment]
@Aniruddha775 If you're willing to contribute, you can check [this curated list of good first issues](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and take your pick from there.

**Comment by Aniruddha775** [comment]
> @Aniruddha775 If you're willing to contribute, you can check [this curated list of good first issues](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and take your pick from there.

Yeah sure.

**Comment by SarthakBorude** [comment]
I've checked relevant components and added responsive CSS, but I’m not seeing changes. Could anyone guide me on which files/components typically handle responsive behavior for button groups, or if there’s a standard approach for handling similar UI adjustments in Kestra? @MilosPaunovic

**Comment by MilosPaunovic** [comment]
@SarthakBorude  Have you started your local development server, to be able to see changes, as described [here](https://kestra.io/docs/getting-started/contributing#setup-to-work-without-building-the-backend-from-the-source-code)?

**Comment by MilosPaunovic** [comment]
Closing this issue as it is amended now.
