### ISSUE TITLE
Adjust the search bar on the Blueprints page to use the new search/filter UX 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5729]
### Feature description

This will look better and will additionally allow users to see recent searches on the blueprints page:

([figma link](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3529-34854&t=lZkzOIuq0y1AgfVg-4))
![image](https://github.com/user-attachments/assets/806b1c94-5c42-43e5-9d51-6fd113bed957)

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/kestra/pull/6531 & https://github.com/kestra-io/kestra-ee/pull/2544.

**Comment by Ben8t** [comment]
This is buggy as for now on develop on the embedded blueprint search in the editor:

![Image](https://github.com/user-attachments/assets/8cc46aaf-fd4b-4fa4-81e0-cc0da06906c6)


I think it only needs the text search isn't? It doesn't make sense to have namespace, flow, etc. filters

**Comment by MilosPaunovic** [comment]
This was actually fixed a few hours before reopening this issue via https://github.com/kestra-io/kestra/pull/6563, but possibly haven't been deployed yet in the time of testing.

@Ben8t Can you check again to confirm?

**Comment by Ben8t** [comment]
Indeed, all good now 💪 Thanks a lot !
