### ISSUE TITLE
"No Data" visualization is not applied yet within Source Search and tables in the main Dashboard

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5733]
### Describe the issue

![image](https://github.com/user-attachments/assets/84736e21-a25c-4906-ac22-e39c08339859)

It should use the same visual as here:

![image](https://github.com/user-attachments/assets/428c4520-7e4a-4d06-b0ab-89c399d44773)

It's also missing in those two tables in the main Dashboard:

![image](https://github.com/user-attachments/assets/fc8c2743-9393-4a1e-aa89-3f1cb9df0ec2)

### Environment

- Kestra Version: develop

**Comment by MRADUL9936** [comment]
@anna-geller  can i work on this

**Comment by MilosPaunovic** [comment]
Go ahead @MRADUL9936! 🚀
