### ISSUE TITLE
UI issue on Light Theme

### ISSUE THREAD

**Issue by schmanat** [kestra-io/kestra#5735]
I'm using the kestra:devleop branch. In the current version its hard to read execution errors. In the overview, there is a new "box" with an warning. If I use the Light Theme and extend this box its hard to read, because the font is white and the background is also light. I think a screenshot should say everything :)
![kestra-ui](https://github.com/user-attachments/assets/bd9158bf-9aef-4ccb-bd07-01b57e92266b)

If I use the dark theme, everything looks great.

### Environment

- Kestra Version: destra:develop
- Operating System (OS/Docker/Kubernetes): docker (docker-compose)

**Comment by MilosPaunovic** [comment]
@schmanat Just to confirm, that is the error stack trace on Execution overview page, right?

**Comment by MilosPaunovic** [comment]
@Vivvek09 Mind checking this one out, as it's related to your https://github.com/kestra-io/kestra/pull/5703?

**Comment by Vivvek09** [comment]
yeah sure, i'll look into this

**Comment by schmanat** [comment]
> @schmanat Just to confirm, that is the error stack trace on Execution overview page, right?

yes, of course.

**Comment by Vivvek09** [comment]
Heyy, 
I made the changes for the light theme
<img width="959" alt="image" src="https://github.com/user-attachments/assets/f3eda37f-fe8e-43b4-8f61-29c27632f039">

I'll create a PR for the same

**Comment by MilosPaunovic** [comment]
@schmanat This is now merged to develop, thanks o great and quick work from @Vivvek09! 🚀
