### ISSUE TITLE
Fix padding and display of this warning

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5765]
### Feature description

![image](https://github.com/user-attachments/assets/583722ef-520d-4a8a-8641-7534889bf558)

**Comment by Piyush-r-bhaskar** [comment]
Hey @anna-geller 

I would like to work on this issue. Could you please assign it to me?

**Comment by MilosPaunovic** [comment]
Go for it @Piyush-r-bhaskar! 🚀

**Comment by MilosPaunovic** [comment]
Thanks for this @Piyush-r-bhaskar! 🚀
