### ISSUE TITLE
Add a Setting allowing to choose which Execution tab shows up as the one opened by default when opening the Execution page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5775]
### Feature description

When you execute the flow, we show Gantt by default:

![image](https://github.com/user-attachments/assets/ce6a0437-5624-4af3-b360-924216476039)
 
Some users prefer e.g. Logs or Overview pages.

We can add a setting with the default being set to Gantt:

![image](https://github.com/user-attachments/assets/f71c7771-ff9d-4580-8787-3f2876670c7e)

**Comment by rd-99** [comment]
Hi @anna-geller , i can take this up.Thanks

**Comment by MilosPaunovic** [comment]
Go for it @rd-99! 🚀

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @rd-99! 🚀
