### ISSUE TITLE
Under "Edit metadata", there's a missing space between the 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5780]
### Describe the issue

To reproduce, go to Edit Metadata:
![image](https://github.com/user-attachments/assets/2e4dac31-5c19-476a-b495-fb623c189f91)

You'll see there's a missing space here:
![image](https://github.com/user-attachments/assets/bb0a6995-fc6e-4625-9831-6d1e9b577c47)

cc @Nico-Kestra in case you have a better design idea for this

### Environment

- Kestra Version: develop

**Comment by 5AIPAVAN** [comment]
i would like to do this ( will open a pr within a day :-))
please assign this to me

**Comment by Nico-Kestra** [comment]
<img width="504" alt="Capture d’écran 2024-11-05 à 16 14 49" src="https://github.com/user-attachments/assets/ef2f567f-8d76-4b11-92e0-0192167b927f">

We can make it like on the new forms.
Let’s use the same tab menu as [here](https://github.com/kestra-io/kestra/issues/5619)

We could also take this opportunity to remove the pink everywhere and change the font. WDYT, @anna-geller ?

**Comment by Akshaykomar890** [comment]
@nsteinmetz Can i work on this issue ?

**Comment by Akshaykomar890** [comment]
@MilosPaunovic Can I work on this issue ?

**Comment by anna-geller** [comment]
totally makes sense, Nico!

@5AIPAVAN do you know how to implement what Nico is suggesting?

**Comment by 5AIPAVAN** [comment]
> totally makes sense, Nico!
> 
> @5AIPAVAN do you know how to implement what Nico is suggesting?

yes, started working

**Comment by 5AIPAVAN** [comment]
![image](https://github.com/user-attachments/assets/d4858026-5b84-455b-8915-2b1f01fb0dd3)
@anna-geller @Nico-Kestra can any one confirm wheather this is fine or do i need to make any modifications ? :-)
i have removed pink text color and added gap...

**Comment by anna-geller** [comment]
Fantastic progress! We wanted it to look like this:

![image](https://github.com/user-attachments/assets/f70b59f1-b477-4fd1-a1b8-022c8f8b0b02)

maybe you want to try a small tweak to include those pencil and eye icons and match colors as shown above? share your PR and we can help get it to the finish line 🚀

**Comment by 5AIPAVAN** [comment]
# is this fine?
@anna-geller 
 changed text color to white in dark mode
 added space,icons for buttons
 changes backfround color of hover effects
 added padding to these buttons
# Dark Mode
![image](https://github.com/user-attachments/assets/0ed7f3e9-a34d-4ecc-afde-78696b6edbaa)
# Light Mode
![image](https://github.com/user-attachments/assets/a2c7d37b-fa3c-4a13-ba8e-dbf9a28af62a)

**Comment by anna-geller** [comment]
yes, fantastic work! looking forward to your PR! 👍

**Comment by MilosPaunovic** [comment]
Thanks for this @5AIPAVAN! 🚀
