### ISSUE TITLE
Make arrow disappear when user is all the way at the end of the tabs

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5782]
### Feature description

Making the arrow disappear when user scrolled till the end would make it look better

![image](https://github.com/user-attachments/assets/9b570fa9-f02c-46c3-b609-8a4bbfa38d2f)

**Comment by Akshaykomar890** [comment]
@MilosPaunovic can you please assign this issue to me?

**Comment by shawnfrost69** [comment]
Hi, @MilosPaunovic I believe I can contribute to resolving this issue. Can I take it on?

**Comment by MilosPaunovic** [comment]
Sure, go ahead @shawnfrost69! :rocket:

**Comment by sarthakvijayvargiya** [comment]
Hi @shawnfrost69  Are you working on this?

**Comment by shawnfrost69** [comment]
@sarthakvijayvargiya  you can work on it.

**Comment by sarthakvijayvargiya** [comment]
@shawnfrost69 👍 , @MilosPaunovic Can i work on this?

**Comment by MilosPaunovic** [comment]
Yup, go for it @sarthakvijayvargiya! :rocket:

**Comment by MilosPaunovic** [comment]
Hi @sarthakvijayvargiya, is there any progress on this?

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic,

May I take this ?

Also, this should also be applicable for the arrow in left. It should not be visible unless we started scrolling. What do you think ? 🙂

**Comment by MilosPaunovic** [comment]
Yup, you can take it and yup, your proposition about the left one also makes sense.

**Comment by Piyush-r-bhaskar** [comment]
> Yup, you can take it and yup, your proposition about the left one also makes sense.

Thank you Miloš

**Comment by MilosPaunovic** [comment]
Fantastic solution @Piyush-r-bhaskar, I really thought this one could be very tricky to handle, but you've managed it in a very simple way, with just a few lines of code. Great work! 🚀
