### ISSUE TITLE
add state save and delete to python and node package  

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#579]
add a method `Kestra.stateSave(data)` & `Kestra.deleteData()` in order to interact directly with state store

**Comment by priamai** [comment]
Yes this will save a lot of boiler plate code to get and set the state from another task!

**Comment by anna-geller** [comment]
State Store will be deprecated and instead user can interact directly with state via KV Store API from anywhere, check https://kestra.io/docs/concepts/kv-store
