### ISSUE TITLE
Hello,I run kestra in local mode ,How to download all plugins locally at once

### ISSUE THREAD

**Issue by daodol** [kestra-io/kestra#5790]
Hello,I run kestra in local mode ,How to download all plugins locally at once

**Comment by Ben8t** [comment]
Hello @daodol,like described [in this part of the documentation](https://kestra.io/docs/installation/docker#add-plugins-to-a-docker-image), you can install plugins with the following command

```
/app/kestra plugins install \
  io.kestra.plugin:plugin-notifications:LATEST \
  io.kestra.storage:storage-gcs:LATEST \
  io.kestra.plugin:plugin-gcp:LATEST ...
```

You can find a command to list of all plugin [here](https://github.com/kestra-io/kestra/blob/4cda597bcd01bd1ff1572d9b42e1e72382fc1e9d/.github/actions/plugins-list/action.yml#L23). 

Please join our [Slack](https://kestra.io/slack) for such question, as it's not really an issue :)

**Comment by daodol** [comment]
thank u
