### ISSUE TITLE
Provide kestra package to avoid to comment during dev

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#580]
python & node.js package can be used during local developpement and for now, there is no way to work locally without commenting this package. 
Publish them to pip & npm ?

**Comment by tchiotludo** [comment]
https://pypi.org/project/kestra/

**Comment by Ben8t** [comment]
@tchiotludo I guess we still lack npm ?

**Comment by tchiotludo** [comment]
exactly and the pip package failed to update, don't know why

**Comment by tchiotludo** [comment]
npm is up now, see [here](https://www.npmjs.com/package/@kestra-io/libs)
```
npm i @kestra-io/libs
```
