### ISSUE TITLE
Displayed favorites even if not

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#5807]
### Describe the issue

When having Users as favorites, every other page on IAM will be marked as favorites :
![image](https://github.com/user-attachments/assets/5fcd0666-91cf-4e5f-9051-c86c0b69bdd7)

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
I couldn't reproduce on EE preview

![image](https://github.com/user-attachments/assets/ad00fedb-3f67-42da-9f87-5998748e0ab4)

if you still can reproduce, feel free to reopen
