### ISSUE TITLE
Add tags below the "About this blueprint" to the blueprints detail page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5810]
### Feature description

Similarly to how we show blueprints on the website:

![image](https://github.com/user-attachments/assets/6a01db38-927d-4605-afb1-17ced17f9e6d)

It would be great to include the blueprint tags here for consistency:
![image](https://github.com/user-attachments/assets/c258e767-3db6-4eb8-9e8c-288c82502dba)

**Comment by priyanshudotexe** [comment]
hi, can I be assigned this issue, I can try fixing it, Thanks in advance!!

**Comment by Piyush-r-bhaskar** [comment]
Hi @priyanshudotexe 🙂

I noticed that this issue hasn't seen an updates for a while. I would be happy to take it over if you are yet to work/make a progress on it.

Thank you!

**Comment by priyanshudotexe** [comment]
> Hi @priyanshudotexe 🙂
> 
> I noticed that this issue hasn't seen an updates for a while. I would be happy to take it over if you are yet to work/make a progress on it.
> 
> Thank you!

Sure ! feel free. I won't be able to work on it atm

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @Piyush-r-bhaskar! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/5914.
