### ISSUE TITLE
Render warning text as Markdown in popup windows

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5814]
### Feature description

Atm, we put plain text into warnings like this one because it's not rendered as markdown - can we change that?

![image](https://github.com/user-attachments/assets/e28d22df-da13-4f92-a44b-5a495a639835)

**Comment by anna-geller** [comment]
ideally, we should change the design of the popup as follows - [figma link](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=4046-35621&t=AO1Hq9itnulrzdfG-4):

![image](https://github.com/user-attachments/assets/f9eb4bf1-9240-4542-b6b8-ef5575e426ad)

**Comment by satvik2131** [comment]
I wanna take up this issue , can I ? @anna-geller

**Comment by MilosPaunovic** [comment]
Go for it @satvik2131! :rocket:

**Comment by satvik2131** [comment]
@anna-geller  , please provide figma access

**Comment by MilosPaunovic** [comment]
@satvik2131 We can not provide Figma access to external contributors, but it is basically only the image already pasted here comment https://github.com/kestra-io/kestra/issues/5814#issuecomment-2459927734.

**Comment by satvik2131** [comment]
![Screenshot From 2024-11-14 22-13-31](https://github.com/user-attachments/assets/9c9d09c2-74d9-4b22-9f86-191306ff16bc)
Hi , is this look okay , I have created a dialog and have given margin-top of 300px , please let me know if any changes should be made

**Comment by MilosPaunovic** [comment]
@satvik2131 You need to open up a PR for me to be able to take a closer look. Then, we can adjust if necessary.

**Comment by anna-geller** [comment]
@satvik2131 the image you shared doesn't look quite yet as the figma example -- the ⚠️ icon seems missing? 

Also, worth trying with some real markdown in the warning -- try replacing https://github.com/kestra-io/kestra/blob/cf615e829107709211554099dd2a6392099c4cde/ui/src/translations/en.json#L904

with markdown:

"Using **trigger variables** won't work with manual flow execution. Add the `??` coalesce operator to solve the issue. For example, instead of `trigger.date`, use `trigger.date ?? execution.startDate`.",

**Comment by satvik2131** [comment]
Here is the image , also I will add a commit for @MilosPaunovic for having a review on that .
![Screenshot From 2024-11-15 10-24-14](https://github.com/user-attachments/assets/dd66664f-35c5-4fbe-b5ad-07f28d08f928)

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @satvik2131! 🚀

Closed via https://github.com/kestra-io/kestra/pull/5933.

**Comment by satvik2131** [comment]
thanks @MilosPaunovic , will improve things on the future PRs  :)
