### ISSUE TITLE
Change the Namespace icon to avoid confusion with the "Copy" icon

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5824]
### Feature description

Current icon:

![image](https://github.com/user-attachments/assets/d78b5e45-730e-42b9-a40a-12c5b9e40e30)

We want to replace it with this one, similar to the K8s namespace icon - [Figma link](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=681-5355&t=AO1Hq9itnulrzdfG-4):

![image](https://github.com/user-attachments/assets/bb910759-c54c-402c-88e0-fd98019f4a74)

**Comment by MilosPaunovic** [comment]
Could you export icon as SVG and attach here for external contributors @Nico-Kestra?

**Comment by Piyush-r-bhaskar** [comment]
> Could you export icon as SVG and attach here for external contributors @Nico-Kestra?

That would be great. Thanks @MilosPaunovic 

I would like to work on this. Could you please assign this to me ?

**Comment by Piyush-r-bhaskar** [comment]
> Could you export icon as SVG and attach here for external contributors @Nico-Kestra?

Hope this would be helpful @Nico-Kestra - https://www.npmjs.com/package/vue-material-design-icons?activeTab=code

**Comment by Nico-Kestra** [comment]
https://pictogrammers.com/library/mdi/icon/dots-square/

**Comment by MilosPaunovic** [comment]
Thanks for this @Piyush-r-bhaskar! 🚀 

Related commit for EE https://github.com/kestra-io/kestra-ee/commit/25602a4a14d5129b392ad08094897d2ac315a96e.
