### ISSUE TITLE
Change the "No data" visual to a kestra specific one

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5830]
### Feature description

Current one (standard ):

![image](https://github.com/user-attachments/assets/073dc6c3-213b-4837-9e0c-ef5bd8b11bb9)

We want to replace it by this one:

![image](https://github.com/user-attachments/assets/5832e4b5-7185-41a1-833f-df24cbcb187c)

@Nico-Kestra will add light mode version + Figma link

**Comment by MilosPaunovic** [comment]
If @Nico-Kestra could add the exported images directly here, that would be awesome, as that's how external contributors could tackle this one.

**Comment by Piyush-r-bhaskar** [comment]
I would like to start working on this once exported images are attached. Meanwhile, could you please assign it to me ? Thanks @MilosPaunovic & @anna-geller

**Comment by anna-geller** [comment]
![Property 1=Variant2](https://github.com/user-attachments/assets/efaebc29-e198-4a0e-8c2a-ecc83482ac02)
![Property 1=Variant3](https://github.com/user-attachments/assets/e4a8ba0f-e149-4593-b769-3d439c736541)

Are those exports enough @MilosPaunovic @Piyush-r-bhaskar?

**Comment by MilosPaunovic** [comment]
Should be, yeah @anna-geller.

@Piyush-r-bhaskar As we're currently using `empty` component from Element Plus (https://element-plus.org/en-US/component/empty), the image shown is their default one.

What we would want is to create the separate `vue` component which will use that `empty` one, customized that it uses the images from above and to have default text, with the ability to override it, and we need to replace all occurrences of `el-empty` in the code with this new one, which can be registered globally.

**Comment by Piyush-r-bhaskar** [comment]
Perfect. Thank You for the defining the expectation @MilosPaunovic 

I will work to create new component & to import & keep you informed on progress. Maybe, I can use some help for using it with Dark / Light theme.

**Comment by MilosPaunovic** [comment]
There is `utils.js` helper and in it, you'll find the `getTheme` method which you can use.

**Comment by Piyush-r-bhaskar** [comment]
Thank You @MilosPaunovic 

Please review the changes & suggest.

**Comment by MilosPaunovic** [comment]
Thanks for this @Piyush-r-bhaskar! 🚀

**Comment by Nico-Kestra** [comment]
Many thanks! I have a few small feedback points:

1. Could you add a line break after the second sentence?
2. Reduce the font size to 14px.
3. Increase the size of the illustration a bit.
4. Center the content horizontally in the box.

<img width="1416" alt="Capture d’écran 2024-11-12 à 10 43 09" src="https://github.com/user-attachments/assets/ca0c7823-114f-40a1-8236-75df8e40f7e9">

**Comment by MilosPaunovic** [comment]
@Piyush-r-bhaskar Would you be willing to tackle those improvements from above?

**Comment by Piyush-r-bhaskar** [comment]
@MilosPaunovic Sure I can check this. 

Thanks You & Thanks @Nico-Kestra  for your feedback & suggestions.

**Comment by Piyush-r-bhaskar** [comment]
Hi @Nico-Kestra 

One confirmation needed: Do you want to Increase the size of the illustration for components using Bar only ?  means here it's Executions (3) or for Total executions - 4 (using Doughnut) too ?

**Comment by MilosPaunovic** [comment]
Nope, increase the size for a bit globally.

**Comment by MilosPaunovic** [comment]
Thanks for this @Piyush-r-bhaskar! 🚀
