### ISSUE TITLE
Align the left and right margins

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#5846]
### Describe the issue

Align the left and right margins to 32 px to prevent resizing on each new page.

![Enregistrement de l’écran 2024-11-07 à 16 49 57 (1)](https://github.com/user-attachments/assets/43a797b6-b3b3-484c-a7e7-9afa3e046405)

<img width="408" alt="Capture d’écran 2024-11-07 à 16 55 39" src="https://github.com/user-attachments/assets/602dec87-56e4-4bae-9dc3-66208e51550f">

To do on:
- Namespace page and all subcategories
- Executions page and all subcategories (except outputs)
- Flows homepage and all subcategories (except editor)
- Logs
- etc. if you see any others.

### Environment

- Kestra Version: develop

**Comment by pranay9831** [comment]
Hey @MilosPaunovic,  I would like to contribute. Could you assign this issue to me?

**Comment by Shivang14d04** [comment]
Hi @Nico-Kestra ! Can i work on this issue . Can you assign it to me?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @Shivang14d04! :rocket:

**Comment by Piyush-r-bhaskar** [comment]
Hi @Shivang14d04 

I noticed that this issue hasn't seen an updates for a while. I would be happy to take it over if you are yet to work on it or in case needed, collaborate with you.

Thank you!

**Comment by Shivang14d04** [comment]
Hi @Piyush-r-bhaskar 

This is actually my first contribution project, so I’ve been taking some time to learn about the project . I appreciate your offer to collaborate and would be happy to work together on this issue.

Thank you !

**Comment by MilosPaunovic** [comment]
Why don't oyu @Shivang14d04 submit a PR, and @Piyush-r-bhaskar could be the first to review it and help you get it closer to  the finish line.

**Comment by Shivang14d04** [comment]
Okay , @MilosPaunovic I 'd be happy to do it .
