### ISSUE TITLE
Improve bulk action design in the execution list page

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5861]
### Feature description

With the addition of unuque and force run of executions, 2 new buttons has been added to the execution list bulk actions.

There is now a lot of buttons, and in not wide screen (or just if you split your screen) there can now be an horizontal scrollbar.

I think we need to redesign these button, either use smaller one or hide some inside a "More action" menu.
@Nico-Kestra maybe you have some ideas.

Current design
![image](https://github.com/user-attachments/assets/8d61faf2-63e0-4591-866f-6cc5cdbc00e9)

**Comment by Nico-Kestra** [comment]
A button with dots for More action is a good option:

<img width="1920" alt="Flow-Executions" src="https://github.com/user-attachments/assets/fcd71dce-add5-49a8-b3d8-3c2ef5b1053b">

[Figma](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3433-34304&t=RW4my1D5bWCurjRw-1)

**Comment by MilosPaunovic** [comment]
I like the new design here, we just need to make a decision from the product perspective which buttons do we show fully, and which ones are part of the dropdown menu of the new button. @Ben8t @anna-geller

**Comment by Ben8t** [comment]
To show fully: `Select All`, `Change State`, `Restart`, `Replay`, `Kill`, `Delete`
In the dropdown: `Set Labels`, `Resume`, `Pause`, `Unqueue`, `ForceRun`

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic 

I have a PR ready for these changes for review. Can You please assign?
Meanwhile I will link it for your review.

Thanks

**Comment by MilosPaunovic** [comment]
Great job, as many times before @Piyush-r-bhaskar! 🚀
