### ISSUE TITLE
Bash Task dockerOptions: Volume

### ISSUE THREAD

**Issue by VinayGandra** [kestra-io/kestra#589]
### Feature description

Ability for runner: DOCKER of Bash Tasks to write/read persistent data on a mounted volume shared with dockerHost

`docker run --rm -it -v /abc/def/data:/app/data alpine head -1 /app/data/xyz.txt`

**Comment by tchiotludo** [comment]
Humm, this one have security concern. 
Allow mounting host volume could break the isolation from docker runner. 

What is your use case? 
You can't use previous task to fill the docker file system ? 
Or use the [Worker](https://kestra.io/plugins/core/tasks/flows/io.kestra.core.tasks.flows.Worker.html) that allow you to have multiple task sharing the same filesystem ?

**Comment by VinayGandra** [comment]
We have many scripts(java/python/bash/etc.) written by various people over time which sit on the host/git and each of these scripts have varying dependencies/packages that can provided by a different docker image.

By mounting, the scripts can be pulled to host from git and the containers can execute them without having to pull them.

[Worker](https://kestra.io/plugins/core/tasks/flows/io.kestra.core.tasks.flows.Worker.html) seems to work for all tasks within a workflow but not globally

Or in scenarios like [aws-cli](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html#cliv2-docker-share-files)
 where details around security are managed on host and shared with the container

**Comment by tchiotludo** [comment]
Will be available in `develop` image in 30 minutes. 
you need to add this on your configuration to enabled it since there is a true security concern: 

```yaml
kestra:
  tasks:
    scripts:
      docker:
        volume-enabled: true
```
