### ISSUE TITLE
Error when doing bulk delete in KV Store

### ISSUE THREAD

**Issue by razuro** [kestra-io/kestra#5897]
### Describe the issue

DELETE method not allowed

<img width="1420" alt="Screenshot 2024-11-13 at 16 02 35" src="https://github.com/user-attachments/assets/ac204165-8a9e-43f0-96ff-8595f2f16bb6">

### Environment

- Kestra Version: v0.19.9

**Comment by MilosPaunovic** [comment]
This should've already been fixed in latest version, can you confirm @Ben8t?

**Comment by razuro** [comment]
seems like a duplicate of https://github.com/kestra-io/kestra/issues/5650 but that is in version v0.19.5

**Comment by Ben8t** [comment]
Indeed, working well now :) closing, thx !
