### ISSUE TITLE
Add a pebble function `fileSize()` that returns the file size in bytes

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5902]
### Feature description

This is needed for use cases when you need to check the file size within a condition and perhaps skip some downstream tasks if the file is empty.

This can be a function that takes an internal storage file URI as a single input parameter: `fileSize(URI)`

**Comment by benjoEK1337** [comment]
Hey, could I take this one?

**Comment by MilosPaunovic** [comment]
Yup, absolutely, go for it @benjoEK1337! 🚀

**Comment by benjoEK1337** [comment]
Quick question. Regarding this task, are there any deadlines or something similar?

**Comment by MilosPaunovic** [comment]
We usually like to give a few days for our community assignees to tackle the issue, and if it's not done by that time, someone from the team/other community member will take over.

If there is work in progress, those deadlines are not that hardcoded.

**Comment by benjoEK1337** [comment]
Cool, thanks. It should be done in a few days. 🤞

**Comment by benjoEK1337** [comment]
Hey @MilosPaunovic and @anna-geller 

I finished the code and want to push to the repo, but I am getting the message:

`> _remote: Permission to kestra-io/kestra.git denied to benjoEK1337._`

I checked all my settings locally related to git and it seems fine, so before I continue to debug the issue, I wanted to check if you need to give the access to me?

**Comment by MilosPaunovic** [comment]
Hey @benjoEK1337,

To push directly to the `Kestra` repository, you’d need `write` permissions, which are granted only to members of our core team. If you’re interested in joining the team, keep an eye on our [careers page](https://kestra.io/careers)!

For this particular case, you’ll need to fork the repository and open a pull request (PR) from your fork, using our `develop` branch as the base.

**Comment by benjoEK1337** [comment]
ahh, seems like a habit from working in a team :D

forgot totally about fork... thanks :D

**Comment by benjoEK1337** [comment]
https://github.com/kestra-io/kestra/pull/5935

here we go 🚀

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @benjoEK1337 ! 🚀

And if you're up for it, there certainly are a few more interesting issues you could tackle, can check them out [here](https://github.com/kestra-io/kestra/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

**Comment by benjoEK1337** [comment]
No problemo @MilosPaunovic 🚀 (seems you guys like rockets 😄 )

Will take a look.

**Comment by MilosPaunovic** [comment]
What gave it away? 😄

That's awesome, looking forward to see some more of your PRs being opened (and then merged)! 🚀🚀🚀
