### ISSUE TITLE
Amend filter placeholder font color

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5911]
Make placeholder inside the new filters component be a bit dimmed in color in comparison to paragraph text.

![image](https://github.com/user-attachments/assets/9427dde6-0be5-4785-8008-281643d576c6)

New filters are (for now) only used on `Executions` page.

**Comment by aabhas-sao** [comment]
Hi @MilosPaunovic, 

I would like to work on this issue can you please assign me this issue.

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @aabhas-sao! 🚀

**Comment by aabhas-sao** [comment]
Hi @MilosPaunovic,

I have created one PR. please check it out if the shade of font color is ok and if the code looks good. I haven't worked with SCSS in long time :full_moon_with_face:.

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @aabhas-sao, `SCSS` changes worked like a charm! 🪄

Closed via https://github.com/kestra-io/kestra/pull/5950.
