### ISSUE TITLE
Make filters expand fully if we omit some of the non required buttons

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5912]
When we omit refresh buttons, the entire Filters section does not stretch horizontally to the right side of the page, and it should, see image below for more details.

![image](https://github.com/user-attachments/assets/ed7e4fe2-f16d-44eb-87a0-3663d3adf60a)

New filters are (for now) only used on `Executions` page.

**Comment by iAmAjayTeli** [comment]
hi @MilosPaunovic i can fix that  please assign this issue to me

**Comment by MilosPaunovic** [comment]
Yup, go for it @iAmAjayTeli! 🚀 

Small hint you'll need to check `kestra/ui/src/components/filter/Wrapper.vue` component to achieve that.

**Comment by iAmAjayTeli** [comment]
thanks @MilosPaunovic

**Comment by iAmAjayTeli** [comment]
@MilosPaunovic i can't able to find this shown screen in live website ?

**Comment by MilosPaunovic** [comment]
Small note here @iAmAjayTeli, I've just merged a refactoring commit to `develop` branch, so the component in question, mentioned above, has been renamed to `kestra/ui/src/components/filter/KestraFilter.vue`.

**Comment by anna-geller** [comment]
@iAmAjayTeli are you still on it?

**Comment by Piyush-r-bhaskar** [comment]
Hey @MilosPaunovic 

Please assign it to me. I will link link a PR for this sometime EoD 😊

**Comment by MilosPaunovic** [comment]
Excellent work, @Piyush-r-bhaskar! 🚀 
Closed via https://github.com/kestra-io/kestra/pull/6364.

**Comment by MilosPaunovic** [comment]
Have to re-open this one @Piyush-r-bhaskar, try to add many filters, it will end up going off screen.

![image](https://github.com/user-attachments/assets/9d5d923e-7cf2-4c17-bb6f-392202ef0c7a)

I've reverted the CSS changes from the PR in e9033462c631ca03903ed7f8c1934cf3f8a407ad.

**Comment by Piyush-r-bhaskar** [comment]
> Have to re-open this one @Piyush-r-bhaskar, try to add many filters, it will end up going off screen.
> 
> ![image](https://github.com/user-attachments/assets/9d5d923e-7cf2-4c17-bb6f-392202ef0c7a)
> 
> I've reverted the CSS changes from the PR in e9033462c631ca03903ed7f8c1934cf3f8a407ad.

😳 Didn't see that coming.

I will check this @MilosPaunovic .
Thank you for identifying this.

**Comment by Piyush-r-bhaskar** [comment]
> > Have to re-open this one @Piyush-r-bhaskar, try to add many filters, it will end up going off screen.
> > ![image](https://private-user-images.githubusercontent.com/62475782/394755337-9d5d923e-7cf2-4c17-bb6f-392202ef0c7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzAzNzcsIm5iZiI6MTczMzk3MDA3NywicGF0aCI6Ii82MjQ3NTc4Mi8zOTQ3NTUzMzctOWQ1ZDkyM2UtN2NmMi00YzE3LWJiNmYtMzkyMjAyZWYwYzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAyMjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMjYyODk1N2Q5ZTRlMzkzMmNiMDJjN2NiMzYwZGUwMGY3Y2ZhN2MxYjc4M2IyMTAyNGZjNGExY2EwZmRkMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HRoFplPAHpgut0TpiqlvYUS3g9AFLvijHLJWB9gMerk)
> > I've reverted the CSS changes from the PR in [e903346](https://github.com/kestra-io/kestra/commit/e9033462c631ca03903ed7f8c1934cf3f8a407ad).
> 
> 😳 Didn't see that coming.
> 
> I will check this @MilosPaunovic . Thank you for identifying this.

Hey @MilosPaunovic & @anna-geller  😊
Good Morning!

I got a chance to check this today but It seems this issue of overflow was from beginning & it seems not introduced from my commit when I checked on `http://localhost:8085/`

![image](https://github.com/user-attachments/assets/94c194fa-a445-46a0-a011-aa50035d6f77)

It's really a great thing that we have observed it as a potential issue. But I would like to know your feedback if we should handle this in this very same issue or shall we open a new issue particularly for this overflow ? - Whatever you say I am always ready to do it 😊
