### ISSUE TITLE
 Improve filter highlighting

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5924]
Improve highlighting of already selected items in second and third dropdowns, like it is in the first one.

First dropdown properly shows the selected values.
![image](https://github.com/user-attachments/assets/a254e3e0-1cb0-446f-b587-c5878f89f526)

Second & third one do not.
![image](https://github.com/user-attachments/assets/ba941d76-95be-4f0c-aac9-1017e5813d3d)

Component in question is `kestra/ui/src/components/filter/KestraFilter.vue`.
New filters are (for now) only used on `Executions` page.

**Comment by aabhas-sao** [comment]
Hi @MilosPaunovic, 
I would love to work on this issue. Just followed setting up dev env. can you please assign me this issue.

**Comment by inesqyx** [comment]
Hi there @MilosPaunovic ! 👋
I’m a new contributor to this repository but have prior experience working with open-source projects. This issue seems like a great way to get familiar with the codebase and start contributing. May I take this up? Thank you!

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @inesqyx! 🚀

**Comment by inesqyx** [comment]
tysm! 🎉 I’ll take some time to familiarize myself with the codebase and aim to have a PR ready by Wednesday 🚀

**Comment by MilosPaunovic** [comment]
This was some great work @inesqyx, thanks so much for the contribution! 🚀 

May I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

Looking forward to reviewing more of your PRs!
