### ISSUE TITLE
Limit the width of the filter dropdown menu

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5925]
Limit the width of the dropdown menu with options, from it now being full width, as the entire `Select` component to be a fixed width (for start, let's say `300px` and we'll adjust the value if necessary).

![image](https://github.com/user-attachments/assets/707f1991-f211-4726-b264-7c03b433b1d6)

New filters are (for now) only used on `Executions` page.

**Comment by rd-99** [comment]
can try this @MilosPaunovic

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @rd-99! 🚀
