### ISSUE TITLE
Change color of part of filter label

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5926]
Make the comparators ("is" and such), along with the colon characters around it be in primary color to improve readability (specially since text is incredibly small).

![image](https://github.com/user-attachments/assets/ba10e6e2-1c97-4fdb-b666-6529d106d9f1)

New filters are (for now) only used on `Executions` page.

**Comment by yuri1969** [comment]
@MilosPaunovic I can handle this one. Thanks

**Comment by MilosPaunovic** [comment]
Thanks for this @yuri1969! 🚀
