### ISSUE TITLE
Prevent duplicate values in filter recent items

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5927]
Make sure to not allow duplicate values in recent listing (to think about preventing duplicates in saved).

![image](https://github.com/user-attachments/assets/c9c0a45b-e3ae-4dd9-9230-1eb7045651df)

Component in question is `kestra/ui/src/components/filter/components/history/History.vue`.
New filters are (for now) only used on `Executions` page.

**Comment by MilosPaunovic** [comment]
Thanks for this @yuri1969! 🚀

I'd like to assign you to this issue, to have a trace that you've closed it, but would need you to add a comment here, because without it, GH won't allow me to add the assignment.

**Comment by yuri1969** [comment]
@MilosPaunovic ofc, here it is.
