### ISSUE TITLE
Open filter date picker automatically

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5928]
When selecting Absolute date as filter, and getting to third dropdown, open the date picker automatically, preventing the extra click for users to open it manually.

![image](https://github.com/user-attachments/assets/280cd38c-5ecb-4ae3-8ae6-6806fbcb1ac7)

Component in question is `kestra/ui/src/components/filter/KestraFilter.vue`.
New filters are (for now) only used on `Executions` page.

**Comment by grammicus** [comment]
Can I pick this up?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @grammicus! 🚀

**Comment by AHB102** [comment]
@MilosPaunovic I'm wondering if modifying the callback function to include certain checks would be an effective solution. If so, could I create an issue for this?

**Comment by MilosPaunovic** [comment]
Not sure what do your mean, but id you open up a PR with the solution which works, we can go from there and make small tweaks if necesarry.

**Comment by MilosPaunovic** [comment]
Is there any progress on this @AHB102?

**Comment by AHB102** [comment]
@MilosPaunovic Unfortunately, I was unable to resolve this issue. As I'm not proficient in Vue, I'll be disengaging from this task. If anyone else is interested in taking it on, feel free to do so.
