### ISSUE TITLE
Make filter absolute date label in humanly readable format

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5929]
Make labels for `Absolute date` filter in humanly readable format using [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) instead of standard date format.

![image](https://github.com/user-attachments/assets/222a0559-e518-4ccc-b1b0-069055ecdc39)

New filters are (for now) only used on `Executions` page.

**Comment by MilosPaunovic** [comment]
Great job @chengtc-dev, thanks for the contribution! 🚀

I'd like to assign you to this issue, to have a trace that you've closed it, but would need you to add a comment here, because without it, GH won't allow me to add the assignment.

**Comment by tunchungcheng** [comment]
Noted. Thanks for your review.
