### ISSUE TITLE
Change background of page settings button dropdown

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5931]
Page settings dropdown at the right end looks like a tooltip, make it a bit lighter in dark mode.

![image](https://github.com/user-attachments/assets/ce22470a-e1ed-4662-acb5-45b9a4e1a780)

Component in question is `kestra/ui/src/components/filter/components/Settings.vue`.
New filters are (for now) only used on `Executions` page.

**Comment by satvik2131** [comment]
would like to go for this one :rocket:

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @satvik2131! 🚀

**Comment by satvik2131** [comment]
I am working on it and wanted to clear the issue , we want to make background for "show main chart" widget  a bit lighter.
We are using  color variables for this so what `--bs-gray` should i use

**Comment by MilosPaunovic** [comment]
Make it `300` and we'll see how it looks.

**Comment by satvik2131** [comment]
![Screenshot From 2024-11-25 02-51-13](https://github.com/user-attachments/assets/7edb0161-b25b-4cf5-b90e-002dac88253a)
it is looking like this , when i have changed the --bs-gray-300 . Do we have any design or something , what exactly we are trying to approach

**Comment by MilosPaunovic** [comment]
No design for this, you can open a PR and we'll check.

**Comment by satvik2131** [comment]
done , @MilosPaunovic  please add labels on the issue for Ux , will work on other issue until the design got finalized .

**Comment by MilosPaunovic** [comment]
I meant open a Pull Request with the change to `gray-300`.

**Comment by satvik2131** [comment]
oh sorry , will create a PR now  , I haven't seen it properly , should I close the Design issue I created ?

**Comment by MilosPaunovic** [comment]
Yup, please.

**Comment by MilosPaunovic** [comment]
Hi @satvik2131, is there any progress on this?

**Comment by satvik2131** [comment]
> Hi @satvik2131, is there any progress on this?
Yes , I was trying some solutions , will create a PR for this on Monday.

**Comment by satvik2131** [comment]
@MilosPaunovic raised a PR for the bg color change, sorry for the delay , back on work now . Also, I don't see much noticeable changes when done bg-grey-300 .

**Comment by MilosPaunovic** [comment]
Closing this, as we'll keep background of all dropdowns in filter section the same as is now.
