### ISSUE TITLE
Nested folders creation with parent folder selected initially does not render properly in the UI

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5932]
When we try to create new folder from the editor sidebar, with parent folder selected, and try to add nested folder into the dialog, like `aaa/bbb/ccc` it will create the structure properly on the BE, but the initial render on the UI is not good, as the only one folder is being created with the name `aaa/bbb/ccc`.

After refreshing the page, it's all structured properly, so it's a matter of properly rendering in the UI.

Initial state:
![image](https://github.com/user-attachments/assets/e143c3a9-1663-4bc8-8a84-b2962a128417)

After page reload:
![image](https://github.com/user-attachments/assets/19aaeeba-0d38-494b-baa2-64f816b66f16)

**Comment by SaumyaG1318** [comment]
Hey @MilosPaunovic I should like to work on this issue can you assign this issue to me.

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @SaumyaG1318! 🚀

**Comment by anna-geller** [comment]
@SaumyaG1318 how is it going? are you still on it?

**Comment by SaumyaG1318** [comment]
@anna-geller I am really sorry for the delay, I did setup the project and have it running locally and reproduced the issue. I have been learning the related technology and trying to fix the problem, I just can't work on it right now I have my end semester exams going on right now so I won't be able to work on it till Dec 13th. Sorry for not communicating my halt on the issue you can assign it to someone else if you would like too, I don't think I can work on it before my exams ends.

**Comment by anna-geller** [comment]
np, good luck with your exams! :)

**Comment by jayg2309** [comment]
@anna-geller Can I work on it?

**Comment by anna-geller** [comment]
sure!

**Comment by MilosPaunovic** [comment]
Hi @jayg2309, is there any progress on this?

**Comment by jayg2309** [comment]
Hi @MilosPaunovic 
I tried it once but then got busy with my exams. Please assign it to someone else.
Sorry for the inconvenience.

**Comment by aabhas-sao** [comment]
Hi @MilosPaunovic,

can you please assign me this issue ☺️. I'm going through the code. Will need some time to understand the tree algorithm. how it is rendering. started checking this out.

**Comment by MilosPaunovic** [comment]
@aabhas-sao Your focus should be on `kestra/ui/src/components/inputs/EditorSidebar.vue` file.

**Comment by aabhas-sao** [comment]
Hi @MilosPaunovic,
I have created a PR to resolve this issue. Please check it out.
This was a really good issue. I got a chance to actually think about recursive and tree based algorithms ✨

**Comment by MilosPaunovic** [comment]
Great work here @aabhas-sao, thanks for this! 🚀
