### ISSUE TITLE
[Regression] Inputs validation check icon seems unnecessary

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5948]
### Describe the issue

There's some new extra validation check - seems unnecessary:
![image](https://github.com/user-attachments/assets/0069ef31-5a14-4b88-92b2-07fdb750eaaf)

here's the same on the latest stable version:
![image](https://github.com/user-attachments/assets/8cee0148-f710-4a85-8ab3-2c39efeb410e)

@MilosPaunovic do you know where this check came from and whether it's intended? 😄 

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
After a bit of digging, it seems like it came a few days ago, as part of [this commit](https://github.com/kestra-io/kestra/commit/fb34f7b6c9bf0948162994ff09a67e7a85eb4c77).

I've [merged a PR](https://github.com/kestra-io/kestra/pull/5953) to resolve this, but if @Skraye could just check it, to see if it does not interfere with some desired behavior he implemented.
