### ISSUE TITLE
Add clear all filters button

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5954]
Implement a functionality to clear all selected filters at once (now we need to remove them one by one).

It can be done using the `clearable` atribute of `el-select` component with the custom handler on `@clear` event, which will empty the `current` variable value and trigger search with new filter values. 

![image](https://github.com/user-attachments/assets/3263a525-79b2-4ba9-b4d1-f4c0c14dad93)

Component in question is `kestra/ui/src/components/filter/KestraFilter.vue`.
New filters are (for now) only used on `Executions` page.

**Comment by tabzzz1** [comment]
Hey @MilosPaunovic  I should like to work on this issue can you assign this issue to me.🥰🥰

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @tabzzz1! 🚀

**Comment by piyush7833** [comment]
Hey @MilosPaunovic, if no one is actively working on it, should I give it a try?

**Comment by MilosPaunovic** [comment]
Is there any progress on this @tabzzz1?

**Comment by tabzzz1** [comment]
I'm sorry, I don't think I can deal with this problem, because I have never learned Java, I'm really sorry. @MilosPaunovic

**Comment by MilosPaunovic** [comment]
This is a purely UI issue, @tabzzz1. Does that change anything?

**Comment by Givemeboga** [comment]
Hey @MilosPaunovic , I would like to work on this issue can you assign this issue to me.

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @Givemeboga! 🚀

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic 

I have linked a PR for this. I see issue is open for weeks.

**Comment by MilosPaunovic** [comment]
Hey @Piyush-r-bhaskar, thanks for the PR, but, in the future, let's try to pick the issues which don't have other assignee already, that would be of grater help.

**Comment by Piyush-r-bhaskar** [comment]
> Hey @Piyush-r-bhaskar, thanks for the PR, but, in the future, let's try to pick the issues which don't have other assignee already, that would be of grater help.

Well Noted @MilosPaunovic

**Comment by MilosPaunovic** [comment]
Thanks @Piyush-r-bhaskar! 🚀 
Closed via https://github.com/kestra-io/kestra/pull/6359.
