### ISSUE TITLE
Namespace Files editor truncates the filename if it contains dots which are not part of the file extension

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5956]
### Describe the issue

![image](https://github.com/user-attachments/assets/f9e98ced-3673-45b0-8882-55bd4f13b0af)

To reproduce, create a file `etl-0.1.0-py3-none-any.whl` in the Editor. It works fine:

![image](https://github.com/user-attachments/assets/d9e400f8-cd38-4689-907c-3d869dae3226)

But then, when you refresh the page, the file display is truncated + it loses its original icon. on the backend side, the file is stored correctly and technically works.

### Environment

- Kestra Version: develop

**Comment by shivam221098** [comment]
Hi, I would like to work on this issue. Please assign it to me. Let me know if there are any specific guidelines or requirements to follow. 

Thank you!

**Comment by MilosPaunovic** [comment]
Hi @shivam221098, go for it! 🚀 

As for specific stuff, there is none, and the only guideline is that you take a look at `kestra/ui/src/components/inputs/EditorSidebar.vue` file first, but will probably have to dig around a bit more.

**Comment by MilosPaunovic** [comment]
Hi @shivam221098, is there any progress on this?

**Comment by shivam221098** [comment]
Hi @MilosPaunovic,
I got a bit busy and didn't got time to fully look at it. How about if I do it this weekend? Does it makes sense?

**Comment by MilosPaunovic** [comment]
Yeah, absolutely, it would be greatly appreciated.

**Comment by shivam221098** [comment]
Hi @MilosPaunovic,

Now it works perfectly fine.

![image](https://github.com/user-attachments/assets/5cc34f51-1462-458b-802a-b582d29d2f7c)

There are few more potential issue, I can see.

When someone uploads a file with no extension, that automatically shows as directory and internally also that's treated as directory. As once I click on it, it gets an error.

https://github.com/user-attachments/assets/ae33602c-d3fc-461f-aa0c-9010b360f1ed

I will see, if there's already an issue for it, if not, I will create one.

**Comment by shivam221098** [comment]
For PR, I will create one in a while.

Thanks

**Comment by shivam221098** [comment]
Hi @MilosPaunovic,

I was trying to run QA on the app by verifying if the flow is actually executing. Do you have any idea about this error?
![image](https://github.com/user-attachments/assets/2d9d7004-34ab-4ea3-9906-1616b2664fe4)

**Comment by MilosPaunovic** [comment]
Great way of solving the problem @shivam221098, thanks for the contribution! Looking forward to reviewing more of your PRs! 🚀
