### ISSUE TITLE
Filters by labels don't work

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5974]
### Describe the issue

https://github.com/user-attachments/assets/3726536e-94b9-4301-96c9-ffb9cb83cb2f

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
It seems in the video that you have empty space character between `artist:` and `rick_astley` @smunteankestra.

**Comment by anna-geller** [comment]
confirmed:

![image](https://github.com/user-attachments/assets/927cc258-f62e-4b13-b929-94f65322b037)

works using key:value

**Comment by smunteankestra** [comment]
Ok, small changes, was working with the space before - was covered by automation
