### ISSUE TITLE
All popup windows now use markdown — some confirmation dialogs need adjustments

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5981]
### Describe the issue

Followup to https://github.com/kestra-io/kestra/issues/5814#issuecomment-2477174652
![image](https://github.com/user-attachments/assets/e3187d2e-01e1-4aa7-8748-a2567253dc89)

Demo https://share.descript.com/view/UanOyAPuOj1

### Environment

- Kestra Version: develop

**Comment by pphy03** [comment]
Hi I'd like to take on this issue. Can I take it?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @pphy03! 🚀

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @pphy03! 🚀

And thanks to @Piyush-r-bhaskar for the review!
