### ISSUE TITLE
[Regression] Make the filter/search react immediately instead of after clicking on the search icon

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5982]
Demo: https://share.descript.com/view/dbRDqGTVBeW

Trying to change filter e.g. for last 5 minutes or for the entire last year has no effect, the UI still displays the same time period - let's investigate @MilosPaunovic  🙏 

Seems related to https://github.com/kestra-io/kestra/issues/5875 when Stefan didn't notice that he needs to click on "Search" icon after removing some filters

**Comment by MilosPaunovic** [comment]
I'm not sure I understand the issue here - you need to click on the search icon now to confirm the filters and to trigger search @anna-geller.

**Comment by anna-geller** [comment]
this is unexpected, a bit unintuitive - WDYT?

Nico seemed to have given a similar recommendation https://github.com/kestra-io/kestra/issues/5990 - we'll discuss tomorrow at 12 👍

**Comment by MilosPaunovic** [comment]
https://github.com/kestra-io/kestra/issues/5845

First task, suggested by the rest of developer team on last weekly call, as they all had the same thoughts.

**Comment by anna-geller** [comment]
also already done
