### ISSUE TITLE
Introduce new filters throughout the product

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5984]
Replace usage of filters throughout the application & add missing filters.

List of places where we need the change:

- [x] Dashboard
- [x]  Flows listing
- [x]  Single flow, Overview
- [x]  Single flow, Executions
- [x]  Single flow, Logs
- [x]  Single flow, Metrics
- [x]  Single flow, Audit Logs (EE)
- [x]  Executions listing
- [x]  Single execution, Logs
- [x]  Single execution, Audit Logs (EE)
- [x] Logs listing
- [x] Administration, Audit Logs (EE)
- [x] Administration, Triggers 
- [x] Administration, Cluster, Services (EE)

@Ben8t Could you do another full sweep through the product to check if I missed any place where we should replace the old filtering system with the new one (make not that, for now, not using it if there is only the search field in place)?

**Comment by MilosPaunovic** [comment]
@Ben8t I've added new filtering system to all the checked pages from above. Could you test it to see if something is broken or if there are inconsistencies of any sort?

**Comment by Ben8t** [comment]
Very neat globally speaking 🎉
Few adjustements:
- On Namespace page, when I'm on a specific namespace I can still filter by another namespace 🤔 
![image](https://github.com/user-attachments/assets/58727963-5986-48bc-a254-99eda2ccbcc4)

- On flow page (overvie, execution, logs) the filter is on the namespace while it should be on flow_id (at least something tied to the flow). Removing the filter still keep the scope to the flow_id so it's ok; but changing to another namespace for example still give results -> should be tied to flow

![image](https://github.com/user-attachments/assets/b85278dd-d1f9-4a3d-ad3c-903af6907404)
![image](https://github.com/user-attachments/assets/f6eed222-0de5-4930-8dd4-67ea38171984)

**Comment by anna-geller** [comment]
> On flow page (overvie, execution, logs) the filter is on the namespace while it should be on flow_id (at least something tied to the flow). Removing the filter still keep the scope to the flow_id so it's ok; but changing to another namespace for example still give results -> should be tied to flow

given that removing this filter won't be saved, we are good here ✅
