### ISSUE TITLE
New filters: improvements

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#5990]
### **Results**

- [x] In general, as soon as a filter is selected, the page should automatically filter without needing to click the magnifying glass.
In the end, the magnifying glass is rarely used, but it serves to indicate that it’s a search bar. Maybe it shouldn’t look like a button and could be greyed out.

<img width="560" alt="Capture d’écran 2024-11-19 à 14 18 11" src="https://github.com/user-attachments/assets/925f99d3-c5a3-43d1-b036-fa6c909b13be">

----------------------

- [x] When I make a search, I should be able to search for the typed word without having to select the suggested filter.

<img width="1491" alt="Capture d’écran 2024-11-19 à 13 56 20" src="https://github.com/user-attachments/assets/c4c8c8e0-470f-4076-b399-9f695f62aab2">

Here’s a suggestion: The first results are the filters, and at the end, the searched keyword with a magnifying glass icon.
The first result should always be pre-selected so that the user can directly press "Enter."

👇

<img width="670" alt="Capture d’écran 2024-11-19 à 13 56 23" src="https://github.com/user-attachments/assets/4a63244d-c60f-4276-b7a8-2d0c4791d172">

----------------------

### **Buttons**
- [ ] The buttons next to the search bar on the right add complexity to the readability.

> - [ ] I would position the "Save" button in the bar only when filters are selected.
> - [ ] I would add a "Clear All" button when filters are selected in the search bar.
> - [ ] I would separate the search bar from the two refresh buttons.
> - [ ] I'm a bit unsure about the "Show Chart" button, maybe move it with the refresh buttons and use a chart icon.

<img width="529" alt="Capture d’écran 2024-11-19 à 13 59 56" src="https://github.com/user-attachments/assets/5466fc32-2524-48e2-97de-2cd4737391e6">

👇

<img width="1767" alt="Capture d’écran 2024-11-19 à 14 07 44" src="https://github.com/user-attachments/assets/c4ca8ca9-66df-4e54-b1cd-b5c21de4c445">

------------------------------------------------------------------------------------------------------------

### **Design refinement.**

- [x] Tag filter: Is it possible to add a separation between the elements and remove the purple? The desired result would be in a different shade of gray.

<img width="319" alt="Capture d’écran 2024-11-19 à 14 10 19" src="https://github.com/user-attachments/assets/41605f31-9db6-4777-99cf-2fc379e7fc60">

👇

<img width="369" alt="Capture d’écran 2024-11-19 à 14 10 20" src="https://github.com/user-attachments/assets/02e54ef2-9404-4afa-a61a-ab089605ecf2">

----------------------

- [ ] Color border when i use the search:  In purple

<img width="468" alt="Capture d’écran 2024-11-19 à 14 14 00" src="https://github.com/user-attachments/assets/1881613a-620f-4614-9432-acdf8d3577d0">

👇

<img width="1653" alt="Capture d’écran 2024-11-19 à 14 12 23" src="https://github.com/user-attachments/assets/31cf3b70-3117-4297-ae55-212311fd8a92">

**Comment by anna-geller** [comment]
search is done
![image](https://github.com/user-attachments/assets/695a9adf-0d02-4660-8197-8de8b3ed9cc8)

Ludo did tags

only buttons part is open - can be done in 0.21

**Comment by MilosPaunovic** [comment]
Moved remaining two things to separate issues, for them to be tackled by contributors.
