### ISSUE TITLE
Debug outputs, pebble expression issue

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5991]
If you have a task with an id that contains dashes, when moving to the Outputs tab, you get this incorrect example:
![image](https://github.com/user-attachments/assets/a5515e97-6f69-4a76-bfd6-0d76800405ce)

It should be `{{ outputs['fetch-and-validate-ticket-data'] }}`.

**Comment by MilosPaunovic** [comment]
Another one related to `Outputs`, are you willing to handle this one also @ManojTauro?

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic 

Can it be assigned to me ?

**Comment by ManojTauro** [comment]
Yes @MilosPaunovic. I can work on the issue this weekend. I hope that's okay.

Also, could you please share an example flow to reproduce this?

Thank you

**Comment by MilosPaunovic** [comment]
@Ben8t Could you provide the example flow here?

@Piyush-r-bhaskar As @ManojTauro already close few issues closely related to this topic, it just makes more sense for him to tackle it. You can take your pick from the backlog if you're willing to help us! 🙂

**Comment by Ben8t** [comment]
@ManojTauro here is a sample flow

```yaml
id: test-dash
namespace: kestra.test

tasks:
  - id: return-dash
    type: io.kestra.plugin.core.debug.Return
    format: "Hello"
```

The outputs format should be `{{ outputs["return-dash"] }}` in this case (and not `{{ outputs.return-dash }}`)

**Comment by ManojTauro** [comment]
Hi @MilosPaunovic I have created a PR for this issue. Please review.

Thank you

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @ManojTauro! 🚀
