### ISSUE TITLE
Not possible to Set Labels — Illegal argument: System labels can only be set by Kestra itself, offending label: system.app=xxx

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5992]
Adding execution labels returns, after refresh they disappear
![image](https://github.com/user-attachments/assets/722ed234-a0c9-422d-a339-c9c6835d06ab)

Demo: https://share.descript.com/view/FVaLVn8UMvY

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
Related to https://github.com/kestra-io/kestra-ee/issues/2001.

**Comment by loicmathieu** [comment]
This is a UI issue, existing labels are now sent to the backend which should not happen

**Comment by MilosPaunovic** [comment]
After a brief discussion we've came to a conclusion current behavior is definitely not ideal. We need to find a way to either ignore `system` labels using the existing endpoint or to create separate endpoints for adding and for removing labels.

**Comment by anna-geller** [comment]
@MilosPaunovic are you on it or should we ask Bart or Yann? this one seems critical to get before 0.20

**Comment by MilosPaunovic** [comment]
I am not on it, had a discussion on Slack with @loicmathieu, he said he'll look at it from BE side.
