### ISSUE TITLE
Kestra slack invite has expiered

### ISSUE THREAD

**Issue by grammicus** [kestra-io/kestra#5994]
### Describe the issue

The slack invite on https://github.com/kestra-io/kestra/issues/new/choose and https://github.com/kestra-io/kestra?tab=readme-ov-file#-join-the-community has expired

![image](https://github.com/user-attachments/assets/2a06cc4d-e1b2-4479-a647-bb4e0c9f334b)

### Environment

- Kestra Version: N/A

**Comment by anna-geller** [comment]
I couldn't reproduce it — can you please refresh your browser, delete cookies, try in incognito mode or try in a different browser?

![image](https://github.com/user-attachments/assets/282bab5e-a061-439c-99f7-b5394fe11757)

**Comment by tchiotludo** [comment]
Ok found it, we have randomly a wrong link, should be fixed! Thanks @grammicus for the report
