### ISSUE TITLE
Option to restart/replay multi selected tasks but using latest revision 

### ISSUE THREAD

**Issue by syepes** [kestra-io/kestra#5996]
### Feature description

It would be great if we could have the possibility of restarting and replaying executions of multiple selected items, but with the **latest revision of the flow code**.
Sometimes we just need to replay a long list of failed flows because of a minor code issue and as of right now this has to be done individually on each item :-(

![CleanShot 2024-11-19 at 6  17 43@2x](https://github.com/user-attachments/assets/7fc55470-08ca-49ed-a24a-e4f867837368)

**Comment by Ben8t** [comment]
@syepes that's exactly what's the team is working on for the next release :) (out in two weeks)
https://github.com/kestra-io/kestra/issues/5740

closing this one as duplicate
