### ISSUE TITLE
Add support for allowfailed also on io.kestra.plugin.core.http.Download

### ISSUE THREAD

**Issue by syepes** [kestra-io/kestra#6025]
### Feature description

It would also be very useful to have this option in the [core.http.download](https://kestra.io/plugins/core/tasks/http/io.kestra.plugin.core.http.download) plugin also like its possible with the [Request](https://kestra.io/plugins/core/tasks/http/io.kestra.plugin.core.http.request#allowfailed)

![CleanShot 2024-11-20 at 9  17 29](https://github.com/user-attachments/assets/630fef62-e25b-4bb6-83c8-0af73100e636)

**Comment by syepes** [comment]
@tchiotludo Great, so with this implemented now are we also going to be able to use the output (status code) just like with the [Request](https://kestra.io/plugins/core/tasks/http/io.kestra.plugin.core.http.request#allowfailed)?

```
- id: api_down
    type: io.kestra.plugin.core.http.Download
    allowfailed: true
    ...
  - id: ifError401
    type: io.kestra.plugin.core.flow.If
    condition: "{{ outputs.api_down.code == 401}}"
    ...
```

**Comment by tchiotludo** [comment]
yes :gift: 

https://github.com/kestra-io/kestra/blob/78f5ff2b7b085a9ad117e701ae0c59e1c9e7b27e/core/src/test/java/io/kestra/plugin/core/http/DownloadTest.java#L159
