### ISSUE TITLE
Aligning Title and Tag on Blueprint table

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6033]
Aligne title and Tag
<img width="692" alt="Capture d’écran 2024-11-21 à 14 24 15" src="https://github.com/user-attachments/assets/8bd53b2d-0cfb-44f5-9198-3beb4489170c">

![image](https://github.com/user-attachments/assets/f6bd655e-88b0-4f5a-949c-323bf1d3d18c)

**Comment by celin07** [comment]
Could I grab this task?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @celin07! 🚀

**Comment by anna-geller** [comment]
@celin07 how is it going? let us know if you need help

**Comment by celin07** [comment]
I encountered some problems running the project due to Docker, but I’ve started working on a solution for the issue. I’ll keep you updated on the progress

**Comment by MilosPaunovic** [comment]
Have you followed [this](https://kestra.io/docs/getting-started/contributing#setup-to-work-without-building-the-backend-from-the-source-code) guide @celin07?

**Comment by aabhas-sao** [comment]
Is this issue available to be taken up. I would like to work on it.

**Comment by Piyush-r-bhaskar** [comment]
Hey @MilosPaunovic & @anna-geller 

I have fixed this in https://github.com/kestra-io/kestra/pull/6191 when I observed the same while doing Blueprint section of Editor.

You may review and let's discuss the expectation.

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic 

Since, we have done a change in how title and tags should look as Nicolas suggested `(particularly adding ps-0 for title for this issue)` https://github.com/kestra-io/kestra/pull/6229

I believe this has been solved here https://github.com/kestra-io/kestra/pull/6229 and https://github.com/kestra-io/kestra/pull/6191

**Comment by MilosPaunovic** [comment]
You're absolutely right @Piyush-r-bhaskar, closing this.
