### ISSUE TITLE
Reduce the font size of the sidebar

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6040]
### Feature description

![image](https://github.com/user-attachments/assets/2792be31-261c-474b-84a4-4fc86b32dc0e)

**Comment by meAnkit18** [comment]
can you suggest me how much would be better size

**Comment by MilosPaunovic** [comment]
Hi @meAnkit18, it seems like there is already a PR opened for this issue, but you can take your pick from our [curated list of good first issues](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and chose something else that seems interesting from there?
