### ISSUE TITLE
Adjust the import functionality to accept zipped `.yaml` files (rather than only `.yml`)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6042]
### Describe the issue

It seems that current export/import functionality relies on files being `.yml ` — trying to import a zip file of flows with `.yaml` extension gives error: 

> At yaml: special characters are not allowed at [Source: (StringReader); line: 1, column: 1] Caused by: special characters are not allowed

![image](https://github.com/user-attachments/assets/4864d148-adaa-43ab-b477-246b5c0d92ed)

### Environment

- Kestra Version: develop

**Comment by kratosmy** [comment]
I tried with some `.yaml` files archived to a `.zip` but no error is found. Could you provide the test file?

**Comment by Skraye** [comment]
The real issue is that Mac compression add some meta files that will be handled by Kestra and throw an error : 
![image](https://github.com/user-attachments/assets/d80b442d-8c13-4127-8b75-713b246e9802)
