### ISSUE TITLE
Horizontal scroll of the the context docs

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#6047]
On the new feature of context docs, when we open `news` section, there is an unwanted horizontal scroll appear out of nowhere. That should not happen.

![image](https://github.com/user-attachments/assets/244656e0-29dc-4198-915b-0e1bf9f6065e)

**Comment by elevatebart** [comment]
Is it still an issue?

**Comment by MilosPaunovic** [comment]
Doesn't seem to be anymore, fixed by https://github.com/kestra-io/kestra/commit/db219825041d7eb15526f2971a071ccd3be54fad.
