### ISSUE TITLE
Improve the Welcome Page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6056]
With the new sidebar, the old welcome page no longer fits. 

![image](https://github.com/user-attachments/assets/666c1eb5-fc43-436a-ac32-29a1b2bfcc8e)

The button "Watch video" should point to this video https://www.youtube.com/watch?v=a2BZ7vOihjg 

Here is a new design:

![Dashboard-Welcome](https://github.com/user-attachments/assets/1ebc28ca-a208-4338-8bbf-7a731e25dcc7)

![Dashboard-Welcome-1](https://github.com/user-attachments/assets/de70cb57-59b7-4c80-8a82-b3bed9fcbb5c)

![Dashboard-Welcome-2](https://github.com/user-attachments/assets/fb2287bc-ca61-4b84-b986-38bf59e8193c)

**Comment by Piyush-r-bhaskar** [comment]
Hi @anna-geller 

May I take this & work ?

Thanks

**Comment by anna-geller** [comment]
sure @Piyush-r-bhaskar 🙏 in case it helps, here are SVG exports:

![Kestra](https://github.com/user-attachments/assets/2908d7d3-d226-4dd5-8e62-becfe864a2f8)

![Frame 10](https://github.com/user-attachments/assets/a8320637-6ea5-4c78-88c2-3f06db96f010)


![Rectangle 30](https://github.com/user-attachments/assets/194df9d4-bf4f-4bb3-a0ae-62cc7cf4cdcf)

**Comment by minukusunilkumar1910** [comment]
Hi  @anna-geller  
May I take this opportunity and start working on it?

**Comment by Piyush-r-bhaskar** [comment]
> Hi @anna-geller May I take this opportunity and start working on it?

Thanks for the interest @minukusunilkumar1910  but I am working on it.

**Comment by MilosPaunovic** [comment]
Hi @minukusunilkumar1910 , may I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by minukusunilkumar1910** [comment]
Sure sir.
