### ISSUE TITLE
Adjust the Plugins page to match the same new design as on the Blueprints page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6060]
The plugins page doesn't look good with the new right sidebar:

![image](https://github.com/user-attachments/assets/f3604cd8-b048-496d-b755-5d9a3768bda3)

We want to add this new design that will be similar to the current Blueprints UI page (note for contributors: feel free to use the Blueprints page as a template): 

![image](https://github.com/user-attachments/assets/428f9918-77d7-4e64-a14b-eb42bd675c71)

[Internal Figma link](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=1114-8020&t=sUFLnowptb1XqmaT-4)

**Comment by RudhraBharathy** [comment]
@anna-geller, I would like to take on this task. Could you please update the description? The image seems to be broken. Additionally, if possible, embedding the Figma design image would be very helpful

**Comment by anna-geller** [comment]
can you say what's not clear in the description?

updated SVG:
![Plugins](https://github.com/user-attachments/assets/cd48aec0-415a-4ef5-9c05-62591574fdf5)

![Frame 15524](https://github.com/user-attachments/assets/5f3f73de-750b-4314-bacd-11f029b985fd)

**Comment by smart-hit** [comment]
Actually the second image in the first comment is broken and figma link requires access to view

**Comment by anna-geller** [comment]
what is broken? here again SVGs (figma access is internal only):
![Icon_Category](https://github.com/user-attachments/assets/d8fac3a7-bbc6-44be-9a2d-75269748c413)
![Frame 15524 (1)](https://github.com/user-attachments/assets/8cb41db3-1d2a-40cd-90fe-b5d78a32c06a)
![Plugins (1)](https://github.com/user-attachments/assets/656c2b7c-00aa-459f-bf51-d6733958fac9)

**Comment by smart-hit** [comment]
now it is fine

**Comment by RudhraBharathy** [comment]
@anna-geller, @Skraye 
Can you assign this to me? I would like to solve it.

**Comment by MilosPaunovic** [comment]
This issue has already been assigned @RudhraBharathy.

May I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by elevatebart** [comment]
Hello @smart-hit, 

I think you will have a hard time finishing this ticket without the proper assets:
- Icons in SVG format
- Layout in light mode

Do you mind terribly if I take it on?
Sorry again for the confusion

**Comment by smart-hit** [comment]
Sure u can 👍
