### ISSUE TITLE
Inconsistent usage of `instanceof` patterns

### ISSUE THREAD

**Issue by ori0o0p** [kestra-io/kestra#6064]
## Description
The codebase currently has mixed usage of instanceof patterns:

- The modern pattern matching style (s instanceof String str) 
- The traditional style (s instanceof String) which requires explicit casting.

This inconsistency can lead to reduced code readability and potential confusion among contributors.

<details>
  <summary> Existing Code 1</summary>
  <img width="632" alt="image" src="https://github.com/user-attachments/assets/3110fc19-1021-457e-b46d-405b7258764d">
</details>

<details>
  <summary> Existing Code 2</summary>
  <img width="1339" alt="image" src="https://github.com/user-attachments/assets/de66c88c-7a79-48e9-996b-cbfc8d27ea37">
</details>

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
@ori0o0p PRs are always welcome 🙂
