### ISSUE TITLE
Remove the warning from cURL command, or at least make this an Information note, not a Warning

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6066]
### Feature description

It's annoying to see this warning every time you want to get a cURL command; also, the information shown here is fairly obvious (_that the user would need to fill in a SECRET placeholder with a real secret or point to their local file with FILE type input_). It seems best to remove this warning entirely:
![image](https://github.com/user-attachments/assets/740292ab-407b-400a-a696-c741e6c10592)

If you prefer to keep it, let's change it to Info note with text `"For SECRET and FILE-type inputs, adjust the command to match the actual value."`

**Comment by rd-99** [comment]
can take this up! @anna-geller

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @rd-99! 🚀
