### ISSUE TITLE
When hover, documentation scrollbar disappear

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#6082]
### Describe the issue

Visible on flows editor > documentations
![image](https://github.com/user-attachments/assets/1a62968a-1794-4ab9-801e-f15b55c27b31)

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
I believe I can no longer reproduce -- please reopen if this is still an issue https://share.descript.com/view/pFjjxI4NbeD
