### ISSUE TITLE
 new filters  log on page don't work 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6092]
We used the new filters page on the log page : 
![image](https://github.com/user-attachments/assets/043f0859-1cf5-4762-bf68-95eac031cc05)

- By default, we don't display what log level is used (no level is TRACE) 
- Typing the log level to TRACE don't display any log level (no request is sent back to the server) 
- we lose the search feature existing before: 
  ![image](https://github.com/user-attachments/assets/f7426908-4e47-4f04-86fe-0dbcb116ce43)

Really wonder if it make sense on this page to have the new filter, @anna-geller

**Comment by anna-geller** [comment]
You're totally right! 👍 

Can we bring back the old version? It looked better here under Logs as we really have only 1 log-level filter, the full filter/search bar makes no sense here:

![image](https://github.com/user-attachments/assets/9a4ee445-dcb3-42de-bbbf-3a9ae871e816)

**Comment by anna-geller** [comment]
btw I was first to spot that bug 😄 

closes https://github.com/kestra-io/kestra/issues/6085

**Comment by tchiotludo** [comment]
reverted only on the executions > logs page, all others logs page are relevant since we have a log of filters inside the page
