### ISSUE TITLE
Log Level filter can overflow the button

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6093]
on executions > logs page, when you have more than 2 digits, the close cross is outside of the box: 
![image](https://github.com/user-attachments/assets/098fb0fa-8a78-4276-a545-219ed19393f3)

**Comment by joaomateusmunuera** [comment]
Hello, I would like to work in this issue if possible

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @joaomateusmunuera! 🚀

**Comment by MilosPaunovic** [comment]
Hi, is there any progress on this @joaomateusmunuera?

**Comment by Piyush-r-bhaskar** [comment]
Hey @MilosPaunovic 
I believe this has been fixed in https://github.com/kestra-io/kestra/issues/6218 it's a duplicate of https://github.com/kestra-io/kestra/issues/6093

**Comment by MilosPaunovic** [comment]
You're absolutely right @Piyush-r-bhaskar, this issue is solved via https://github.com/kestra-io/kestra/pull/6224.
