### ISSUE TITLE
Table header is not visible enough compared to rows + dashboard elements seem misaligned

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6097]
### Describe the issue

empty space when no data instead of table within the "Next Scheduled Executions"
![image](https://github.com/user-attachments/assets/d71917ea-e4c8-409c-a26d-86261ccf4fe4)

+ table header may need a look - @Nico-Kestra can you have a look?

The previous table looked better here as the header was highlighted much stronger compared to rows:

![image](https://github.com/user-attachments/assets/fb6e7f2c-408b-404b-8c90-58d3f5e08656)

### Environment

- Kestra Version: develop

**Comment by Nico-Kestra** [comment]
https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=2411-26518&t=KOJ6WYV8IchATO4L-1

**Comment by MilosPaunovic** [comment]
For any external contributors willing to take on this issue, this is how it should look like.

![image](https://github.com/user-attachments/assets/107e189f-9e98-4364-aed5-ffc1d720833d)

**Comment by rd-99** [comment]
i can take this up @MilosPaunovic

**Comment by MilosPaunovic** [comment]
If @tchiotludo is not currently working on it, you definitely can, but he'll assign you if that's the case.

**Comment by anna-geller** [comment]
@rd-99 go for it, Ludo has too many things this week already 👍
