### ISSUE TITLE
Update a flow and changing id or namespace failed

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#61]
Changing the namespace or the id will led to a 404 on the update from the webui.
It's a normal behaviour on the `FlowControler` we ask and update on a flow that don't exists. 

This led to 2 issues : 
* 404 are not catch and loading bar keep growing, this must be capture and displayed as error. 
* How can we rename a flow ? is this a possible action ? 

Since there is a lot of "foreign keys" (see #60), we need to disabled the edition of namespace and flow id for now (waiting #60)

**Comment by eregnier** [comment]
The ui logic must follow backen constraints. So we have to define the appropriate behavior.

For this issue we can :
* Allo  id change ( which is obviously not what is possible and desired now)
* Clone flow with new name ans ns on clone operation
* Clone and delete flow
* Manage virtual flows or allow id change on revision update which seems complicated and looks like a trap

I think the best way to do this is clone only. Ask new id when operation is in progress.
This prevent existing flow and it's exexution to be deleted. conservative approach is often good ans we may *disable* some unwanted flows.
We should avoid complex user data management to keep sustem ux as kiss as possible.

Also I really think description in flow should be quite mandatory : it forces self documentation and legacy flow easier to manage.

**Comment by tchiotludo** [comment]
Maybe I'm not clear but the idea is to forbid the edition of namespace and Id.
On the #60, we are going on further
