### ISSUE TITLE
Endpoint to delete namespace_file is not working

### ISSUE THREAD

**Issue by aballiet** [kestra-io/kestra#6118]
### Describe the issue

To reproduce:
- Create a namespace file in Kestra UI
- Try to delete it using API call

Here is a short loom video showcasing the issue: https://www.loom.com/share/dc3f26d764e04f36873721af02580102

The endpoint `http://localhost:8080/api/v1/namespaces/prod.automation/files?path=my_file.py` seems not responding.

Current fix is to add leading `/` in the path like : `http://localhost:8080/api/v1/namespaces/prod.automation/files?path=/my_file.py`.

In the TF resource it's hacky to define it as "/my_name"

### Environment

- Kestra Version: 0.19.8

**Comment by japerry911** [comment]
+1

**Comment by anna-geller** [comment]
thx for the issue, seems related to https://github.com/kestra-io/terraform-provider-kestra/issues/131 

for transparency, we weren't able to look into this in 0.20 so might be postponed to a bugfix release

**Comment by anna-geller** [comment]
internal issue which is also related https://github.com/kestra-io/cloud/issues/20
