### ISSUE TITLE
Allow to capture output from bash task even on failed tasks

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#613]
in this case: 
```yaml
Kestra.outputs({'status': r.status_code, 'text': r.headers['X-Warp10-Error-Message']})
raise Exception(r.headers['X-Warp10-Error-Message'])
```
the output seems to be not captured if there is any exception (not saved on the execution).

It prevent to use this output on the `errors` block to send a notification with error message.

**Comment by fhussonnois** [comment]
@tchiotludo, is this issue still relevant as the `Bash` task is now deprecated. Also seems to be linked to : https://github.com/kestra-io/kestra/issues/2407

**Comment by tchiotludo** [comment]
same than the one https://github.com/kestra-io/kestra/issues/2407, closing
