### ISSUE TITLE
Allow to use system-site-packages for python venv creation

### ISSUE THREAD

**Issue by nsteinmetz** [kestra-io/kestra#615]
### Feature description

Hi,

When running python task in Docker a fresh virtual environment is built for each execution. This can slow execution time in my case (a 1s operation leads to a 15/30s operation on my Mac) 

So I thought I would create a custom docker image with my requirements and it would fix the issue but no.

```
FROM python:3.10
RUN python -m pip install --no-cache-dir --upgrade pip \
  && python -m pip install --no-cache-dir pendulum requests
```

But when the venv is created, it does not take site-packages as well so the requests/pendulum packages will still miss.

```
Image pulled [docker.io/nsteinmetz/kestra-python:latest]
DEBUG    2022-05-25 11:55:10.264 Starting command with container id 3511921400b54961e4056754853cb81f77d357585cc4079bcac5a8d7e5124661 [/bin/sh -c set -o errexit
python -m venv /tmp/kestra-wd/tmp/12YFQYVHNYo5DtGMqIqYsW > /dev/null
./bin/pip install pip --upgrade > /dev/null
./bin/python main.py]
```

Would it be possible to add a flag to get site-packages as well ?

So that we have:

```
python -m venv --system-site-packages /path/to/venv
```

Thanks

**Comment by robomotic** [comment]
Plus one on this, I have the same problem!

**Comment by nsteinmetz** [comment]
As said on slack: in my case, it cuts by 50% the operation time from 25/30 to 13/15s

Nice improvement but not as fast as the version with the HTTP plugin which is around 1s 😎
