### ISSUE TITLE
View for namespaced flows is buggy. 

### ISSUE THREAD

**Issue by kundeng** [kestra-io/kestra#6153]
### Describe the issue

The view for namespace flows is highly problematic:
- It fails to filter for flows contained solely within the namespace.
- The dropdown menu for selecting a namespace is non-functional.
- Sorting by namespace does not effectively organize the list.

### Environment

- Kestra Version: 0.19.2

**Comment by anna-geller** [comment]
Hi @kundeng, thanks for the feedback. We've addressed the issue of the filtering in kestra 0.20 coming out on Tuesday, December 3rd. Check out the changes: https://share.descript.com/view/xKP7ClZYcYS 

Additionally, in OSS, namespaces don't really exist, in EE version, we provide namespaced-based organization for flows. Feel free to book a demo to learn more https://kestra.io/demo or join our Slack to discuss your use case https://kestra.io/slack
