### ISSUE TITLE
Time type issue for Flow Trigger timeWindow `DAILY_TIME_WINDOW`

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6158]
### Describe the issue

It's not clear what time type is expeced in `startTime` and `endTime` props within the `DAILY_TIME_WINDOW` sla type 🤔 

As per the warning it expect RFC3339 time type, but doing so raise an error in flow definition

![Screenshot 2024-11-28 at 10 27 20](https://github.com/user-attachments/assets/ae72fb03-e934-42af-9c59-ea93d4d55b88)

![Screenshot 2024-11-28 at 10 27 36](https://github.com/user-attachments/assets/503b7751-33fb-40ae-a3ef-cf1c61dcac3d)

related to https://github.com/kestra-io/kestra/issues/6156

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
can you try with timezone offset? if it works, let's clarify in plugin docs and close 👍

**Comment by loicmathieu** [comment]
Yes, it's offset like for deadline.

**Comment by anna-geller** [comment]
added https://github.com/kestra-io/kestra/commit/8d12451f2fbc47686f02047c9d68d265e5efc9e1
