### ISSUE TITLE
PAUSED state is not readable

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6174]
### Describe the issue

![image](https://github.com/user-attachments/assets/936fd479-1302-48b9-b14e-a2c05676871b)
![image](https://github.com/user-attachments/assets/b97c9de1-9231-4d06-8802-fb30b25fa17d)

on light theme it looks good but not centered?

![image](https://github.com/user-attachments/assets/c9e0411c-91b7-4b0b-bf52-be83edf21746)

### Environment

- Kestra Version: develop

**Comment by Nico-Kestra** [comment]
<img width="368" alt="Capture d’écran 2024-11-28 à 16 31 42" src="https://github.com/user-attachments/assets/32f0d3a3-e3ac-42c5-9316-a81cfe4e75da">

https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=2625-28770&t=glSEjhYQjhM2wTUP-1
