### ISSUE TITLE
Triggers: Align the toggle to the left with the backfill title.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6176]
### Describe the issue

<img width="1260" alt="Capture d’écran 2024-11-28 à 16 43 21" src="https://github.com/user-attachments/assets/2edac6e3-630f-412e-ab32-50ff02fd1b0c">

### Environment

- Kestra Version: develop

**Comment by JoeCelaster** [comment]
I can do this, Please assign this to me .

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @JoeCelaster! 🚀

**Comment by MilosPaunovic** [comment]
Hi @JoeCelaster, is there any progress on this?

**Comment by JoeCelaster** [comment]
@MilosPaunovic  YES, I am working on this issue, will complete it very sooner .

**Comment by MilosPaunovic** [comment]
@JoeCelaster As there was no progress, I've unassigned you from the issue. If you decide to open a PR for it, I'll assign you back to it.

In the meantime, if someone else from the community wants to take this issue, it's up for grabs!

**Comment by Piyush-r-bhaskar** [comment]
Hi @Nico-Kestra 

If it's about `switch` alignment then it is a different column (_with no header label_) than Backfill.
I have added the column label just to differentiate.
![image](https://github.com/user-attachments/assets/7d9397ed-6070-40f2-9b8b-7a19b0d13b4d)

**Comment by MilosPaunovic** [comment]
I'd say that's it @Piyush-r-bhaskar, can you open a PR with the change, just use `Action` column header and we can close this one.

**Comment by Piyush-r-bhaskar** [comment]
> I'd say that's it @Piyush-r-bhaskar, can you open a PR with the change, just use `Action` column header and we can close this one.

Sure Milos , I will open it in a few hrs today.
