### ISSUE TITLE
Triggers: The expanded button displays an empty area.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6178]
### Describe the issue

Triggers: The expanded button displays an empty area.

<img width="1313" alt="Capture d’écran 2024-11-28 à 16 47 48" src="https://github.com/user-attachments/assets/fd0ad0f0-decd-4e18-ae4b-099108ed067f">

If there's no information to display, I suggest disabling the arrow and greying it out.

### Environment

- Kestra Version: develop

**Comment by rd-99** [comment]
Hey @Nico-Kestra, i can take this up!

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @rd-99! 🚀

**Comment by MilosPaunovic** [comment]
Whoever get to solving this issuet, the component that needs changing is `kestra/ui/src/components/admin/Triggers.vue`, and we need to prevent expanding the table row if there is no content to be shown.

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic 

Please assign this to me.
