### ISSUE TITLE
Plugins page: Remove the background behind the search input.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6180]
### Describe the issue

Remove the background behind the search input.

<img width="1030" alt="Capture d’écran 2024-11-28 à 16 52 58" src="https://github.com/user-attachments/assets/0da74408-281c-4614-8e1f-b302e93bd6df">

### Environment

- Kestra Version: develop

**Comment by JoeCelaster** [comment]
I can work with this issue, you can assign this to me

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @JoeCelaster! 🚀

**Comment by Ankush1oo8** [comment]
how you suggest how can i solve this

**Comment by MilosPaunovic** [comment]
Hey @Ankush1oo8,

This issue already has an assignee.

May I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by Ankush1oo8** [comment]
> Hey @Ankush1oo8,
> 
> This issue already has an assignee.
> 
> May I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

okey

**Comment by MilosPaunovic** [comment]
Thanks for this @JoeCelaster! 🚀
