### ISSUE TITLE
Blueprints: Change tags design

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6181]
### Describe the issue
<img width="1224" alt="Capture d’écran 2024-11-28 à 17 04 41" src="https://github.com/user-attachments/assets/b6a6454c-c670-4e27-8e9e-541d84349cc7">

<img width="1080" alt="Capture d’écran 2024-11-28 à 17 04 57" src="https://github.com/user-attachments/assets/f97217ad-9f72-4a07-8236-3b9f7c9d1e8e">

- Change the pink tags to tags with a grey background and clearly separate them.
- Place the tags to the right of the blueprint title.
- Change the tags on the detail page as well.
- Use Button can be purple (primary button)

👇

<img width="1375" alt="Capture d’écran 2024-11-28 à 16 59 20" src="https://github.com/user-attachments/assets/e2c3759c-fe2e-47a2-ac57-409f966d5e5b">

<img width="1210" alt="Capture d’écran 2024-11-28 à 17 02 30" src="https://github.com/user-attachments/assets/6a4165c5-b22f-4125-81e4-df442144d781">

[Figma](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=1446-12393&t=glSEjhYQjhM2wTUP-1)

### Environment

- Kestra Version: develop

**Comment by Piyush-r-bhaskar** [comment]
Hey @MilosPaunovic 

I would like to check this.

**Comment by MilosPaunovic** [comment]
Go for it! 🚀

**Comment by Piyush-r-bhaskar** [comment]
Hi @Nico-Kestra 

How do you want to handle large sentences because even if I implement a separate div for tags width for long sentence of title seems concerning for me. like here

![image](https://github.com/user-attachments/assets/92f87edc-137e-4c9d-b0bc-aaacc9a0a547)

Do you want to wrap the title if it's longer. 
Or should I just work on designing the tag , Use button and length will be taken up by doing modification while reviewing ?

**Comment by MilosPaunovic** [comment]
Great job, as it always is @Piyush-r-bhaskar! 🚀 

@Nico-Kestra, once this is deployed, you can check it, and if need tweaking, please open another issue.

**Comment by Nico-Kestra** [comment]
<img width="1678" alt="Capture d’écran 2024-12-04 à 13 40 55" src="https://github.com/user-attachments/assets/9f92d4d1-6564-4a33-bf47-2c4ab301bb88">
n the case where the text is really too long, we could split it into two lines.

For this issue:

Don't forget to set the tags to gray and remove uppercase letters.
Make the "use" button purple.
Try to align the tags in a single column.

Thx @Piyush-r-bhaskar !
