### ISSUE TITLE
Add top spacing in the editor area

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6182]
### Describe the issue

The first line of code is too close to the edge. If possible, add a 32px space.
This issue applies to all code areas.

<img width="1079" alt="Capture d’écran 2024-11-28 à 17 08 33" src="https://github.com/user-attachments/assets/3a34b837-8ece-44e0-922c-5b71d1c8cf99">

👇

<img width="1365" alt="Capture d’écran 2024-11-28 à 17 11 01" src="https://github.com/user-attachments/assets/85abae3a-6856-4398-a4dd-ae6a37b070f5">

### Environment

- Kestra Version: develop

**Comment by Piyush-r-bhaskar** [comment]
Hi @Nico-Kestra 

Can I take this ?

**Comment by MilosPaunovic** [comment]
Yup @Piyush-r-bhaskar!

**Comment by MilosPaunovic** [comment]
Great job, as always. Thanks for this @Piyush-r-bhaskar! 🚀
