### ISSUE TITLE
Logs page: Place the secondary buttons to the right of the search bar

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6183]
### Describe the issue

<img width="1711" alt="Capture d’écran 2024-11-28 à 17 23 01" src="https://github.com/user-attachments/assets/8f3b83c8-dd44-47e7-a89f-e5f21113290b">

👇

<img width="1668" alt="Capture d’écran 2024-11-28 à 17 23 21" src="https://github.com/user-attachments/assets/e4ececb6-fe21-4ca6-939b-5668c7f0cd5a">

### Environment

- Kestra Version: develop

**Comment by MichaScant** [comment]
Hey, can I be assigned this issue please?

**Comment by anna-geller** [comment]
hey, this is no longer an issue as we brought back the previous UX for Flow Execution's Logs tab:

![image](https://github.com/user-attachments/assets/b57fe10f-4dc6-4a4c-b80e-a4ccfd7fa47a)
