### ISSUE TITLE
Logs page: Issue with "More actions" &  "Expanded/collapsed" button

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6184]
### Describe the issue

<img width="1021" alt="Capture d’écran 2024-11-28 à 17 31 32" src="https://github.com/user-attachments/assets/c1a2fd55-1efc-442a-a313-2affd4ac417d">

- Align the height of the "Expanded/Collapsed" button with the others.
- Standardize the color of the "More Actions" button to match the others.

👇
<img width="510" alt="Capture d’écran 2024-11-28 à 17 28 30" src="https://github.com/user-attachments/assets/d5f6b625-1975-4eb8-9c61-ea209d8a8bfc">

### Environment

- Kestra Version: develop

**Comment by aabhas-sao** [comment]
Hi @MilosPaunovic 👋 , 
I would like to work on this issue. Can you please assign me

**Comment by aabhas-sao** [comment]
Hi @MilosPaunovic,

I have raised a PR to close the issue. Please check it out once 🌻

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @aabhas-sao! 🚀
