### ISSUE TITLE
Align the size of the "Executions In Progress" and "Next Scheduled Executions" cards.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6192]
### Describe the issue

Both cards should have the same height.

<img width="1375" alt="Capture d’écran 2024-11-29 à 09 45 48" src="https://github.com/user-attachments/assets/c845d4ac-e364-488a-a419-4d984827eb79">

### Environment

- Kestra Version: develop

**Comment by abhishekpawar1060** [comment]
I would like to work on this issue.

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @abhishekpawar1060! 🚀

**Comment by abhishekpawar1060** [comment]
@MilosPaunovic  I run this UI on local machine, but the height of this two card component look similar, then  how to approach this issue.

**Comment by MilosPaunovic** [comment]
Mock some rows into one of the tables.

**Comment by anna-geller** [comment]
when there is data, it works:

![image](https://github.com/user-attachments/assets/41353446-c837-4089-bde2-ad54b2cba9d2)

but the issue Nico reported happens when one of the tables has no data:

![image](https://github.com/user-attachments/assets/01e62ac1-2c61-4f21-a834-dad28f9537b8)

**Comment by abhishekpawar1060** [comment]
Ok, I got it. I send fix PR for that

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @abhishekpawar1060! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/6213.
