### ISSUE TITLE
Review spacing on Plugin page

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6196]
### Describe the issue

<img width="1226" alt="Capture d’écran 2024-11-29 à 11 53 43" src="https://github.com/user-attachments/assets/9ab9ea31-7654-418a-91f9-4d475d0a8f27">

Is it possible to have plugin buttons that stretch based on the resolution so that there are no large gaps depending on the resolution, while always maintaining a 16px spacing?

Example:
<img width="1523" alt="Capture d’écran 2024-11-29 à 11 54 23" src="https://github.com/user-attachments/assets/ae6b07f6-9195-47aa-84b9-ad87f836f8b1">

### Environment

- Kestra Version: develop

**Comment by nitsbat** [comment]
Hi @Nico-Kestra  @anna-geller @MilosPaunovic. I am certain that i will be able to work on this issue. Could you please assign me.?

**Comment by anna-geller** [comment]
For sure, thanks for the PR @nitsbat 👍

**Comment by MilosPaunovic** [comment]
Thanks for this @nitsbat! 🚀
