### ISSUE TITLE
User dashboard filters "User dashboard" instead of  "User executions"

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#6198]
### Describe the issue

User dashboard filters "User dashboard" instead of  "User executions"

![image](https://github.com/user-attachments/assets/739adb4f-7b7e-4a3e-9822-eccde28dbab5)

### Environment

- Kestra Version: develop

**Comment by nipunh** [comment]
Hi @smunteankestra can you please assign this to me?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @nipunh! 🚀

**Comment by MilosPaunovic** [comment]
Hi @nipunh, is there any progress on this?

**Comment by nipunh** [comment]
Hi @MilosPaunovic, i am getting started it with. Will get it done over the weekend.

**Comment by nipunh** [comment]
I am running the system locally, and i can see "User Data" and "System Data" filter in here. And the filter bar seems a bit different from the screenshot attached.

<img width="1512" alt="Screenshot 2024-12-07 at 4 41 19 PM" src="https://github.com/user-attachments/assets/d8b3108d-df1c-4ee9-8e8d-f1265581348c">

**Comment by MilosPaunovic** [comment]
You're not running latest version @nipunh.
