### ISSUE TITLE
Add a Pebble function to generate a random number

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6207]
### Feature description

sth like in Python:

```Python
import random

random_value = random.randint(0, 1)
```

**Comment by kyradjis** [comment]
Hey, i think i could work on this issue. Can you please explain where you want me to implement the function? @anna-geller

**Comment by loicmathieu** [comment]
Hi, thanks to volunteer to implement this.

Pebble functions are implemented here: https://github.com/kestra-io/kestra/tree/develop/core/src/main/java/io/kestra/core/runners/pebble/functions

You need to add a new class and configure it here: https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/runners/pebble/Extension.java#L123

Don't forget to add a new test for the function.

**Comment by coderkill** [comment]
Hi,

Please assign this to me

**Comment by MilosPaunovic** [comment]
Why don't we give a chance to @kyradjis to see if he's still willing to try and solve this issue. If not, @coderkill you can take over.

**Comment by coderkill** [comment]
@MilosPaunovic Since I see that it was unassigned after 4 days of inactivity from Kyradjis, I assumed I can take it. May I know how long after do you want me to wait before I start?

**Comment by MilosPaunovic** [comment]
Let's wait until tomorrow, if there is no response, ping me here again and I'll assign it to you.

**Comment by anna-geller** [comment]
@coderkill please take it if you want 🙏@kyradjis DMed me via Slack saying he can't do it so was unassigned
