### ISSUE TITLE
Add a Pebble function to generate a UUID

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6208]
### Feature description

`uuid()` or an `id` in the kestra format (i.e., a UUID encoded in Url62)

**Comment by kyradjis** [comment]
I am pretty sure i would be able to work on this issue as well. But I would need some more information about it first. @anna-geller

**Comment by anna-geller** [comment]
@kyradjis big thanks in advance! 🙏

**Comment by coderkill** [comment]
Hi, Please assign this to me

**Comment by MilosPaunovic** [comment]
Same here @coderkill , let's give a chance to @kyradjis to see if he's still willing to try and solve this issue. If not, you can take over.

In the meantime, may I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by coderkill** [comment]
@MilosPaunovic Since I see that it was unassigned after 4 days of inactivity from Kyradjis, I assumed I can take it. May I know how long after do you want me to wait before I start?

**Comment by MilosPaunovic** [comment]
Let's wait until tomorrow, if there is no response, ping me here again and I'll assign it to you.

**Comment by anna-geller** [comment]
Also here, @coderkill please take it, the other person was explicitly unassigned upon request
