### ISSUE TITLE
Docker image with version number and latest don't have the same digest 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#621]
We push the latest & the version tag in to separate github actions runs, we may need to push the version and the latest at the same time to have the same digest

**Comment by loicmathieu** [comment]
These two images are created in different CI build: one on master and one for the version tag.
What we can do is:
- Make our build reproducible (hard) so the same hash would be calculated
- Remove publishing the latest tag from master and use manually the retag action, we cannot use it automatically as we cannot be sure that the version tag is already published.

**Comment by loicmathieu** [comment]
Decision: building on tag will be manually with a checkbox (false by default) to publish the latest or not.

**Comment by loicmathieu** [comment]
Done by using a new CI and release process
