### ISSUE TITLE
Add a validation popup before removing a bookmark

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#6211]
### Feature description

Add a validation popup before removing a bookmark from the bookmark section in the left menu.

**Comment by ManojTauro** [comment]
Hi @loicmathieu, I would like to work on this issue. Could you please assign this to me? Also, it would be great if you can give me some more information.

Thanks

**Comment by MilosPaunovic** [comment]
Hey @ManojTauro, so, now, in the left menu, we have the option to set something as bookmark by clicking on the star icon in the header. That will add a new menu section at the top, and we need confirmation dialog when removing items from that section.

![image](https://github.com/user-attachments/assets/92d40c14-260c-4abe-a596-1479655e8b66)

**Comment by ManojTauro** [comment]
Got it @MilosPaunovic. I'll keep you posted on the progress.

Thank you.

**Comment by MilosPaunovic** [comment]
Hey @ManojTauro, we actually had a PR for this opened a day before you asked to work on it (https://github.com/kestra-io/kestra/pull/6217), so it would be fair to merge that one.

We definitely appreciate all your hard work and I'd like to encourage you to take your pick of whatever you'd like from the backlog, if you're still up for closing some more issues.

**Comment by MilosPaunovic** [comment]
Thanks for this, @morri12! 🚀 

If you can add a comment here, I'll add you as an assignee to this issue, because without one I am not able to.
