### ISSUE TITLE
Cross Icon Bug when Executing the  flow 

### ISSUE THREAD

**Issue by anuj846k** [kestra-io/kestra#6218]
### Describe the issue

When I execute the flow in the info filter when the number goes up after 100 the cross icon goes out of that relative div  I have attached an image below
![image](https://github.com/user-attachments/assets/4c72af6f-da8e-4748-a675-31232cf93d1d)

### Environment

- Kestra Version: develop

**Comment by abhishekpawar1060** [comment]
I would like to work on this issue

**Comment by anuj846k** [comment]
/assign 
me

**Comment by MilosPaunovic** [comment]
As @abhishekpawar1060 was first, he can have the first go at it.

@anuj846k, may I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by anuj846k** [comment]
This is so wrong I pointed out the issue so I should be assigned

**Comment by MilosPaunovic** [comment]
Hi @anuj846k, as you've never expressed any desire to solve this issue when initially opening it, and someone else was first to ask, it's only fair that other person attacks the problem first.

If @abhishekpawar1060 is alright with choosing some other issue from our backlog, I'm perfectly fine with assigning yourself to this one.

**Comment by anuj846k** [comment]
No problem I wasn't aware of this thing I will keep in mind from now on m

**Comment by anuj846k** [comment]
No problem I wasn't aware of this thing I will keep in mind from now on

**Comment by abhishekpawar1060** [comment]
Sorry @anuj846k,  I have solve this issue.
I was send the PR for this issue, I want to review my PR.

**Comment by anuj846k** [comment]
@abhishekpawar1060 are  you working on this ? Did you make the Pull request?

**Comment by abhishekpawar1060** [comment]
Yes

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @abhishekpawar1060, and thank you for the review @Piyush-r-bhaskar! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/6224.
