### ISSUE TITLE
System namespace description's color makes text illegible on dark mode

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6221]
![image](https://github.com/user-attachments/assets/e4045d4c-6dab-4c3e-a0a7-88b55320ce01)

on light mode it's OK
![image](https://github.com/user-attachments/assets/84b26483-9b94-4b3b-8407-48d835b6e594)

**Comment by Vamshi-Reddy-16** [comment]
Hi

**Comment by callybton** [comment]
Hi! I'd love to work on this issue if available!

**Comment by htami1717** [comment]
‎##- الرجاء كتابة ردك أعلى هذا السطر -##
‎مرحبًا يا من هناك،

‎لسوء الحظ، نواجه مشكلة في معالجة هذا الطلب. إذا كانت المشكلة لا تزال مستمرة، فيرجى الاطلاع على الروابط أدناه أو زيارة موقع الدعم الخاص بنا لتقديم طلب جديد.

‎إذا كنت ترغب في الإبلاغ عن إساءة أو مشكلة تتعلق بالخصوصية أو السلامة أو البريد العشوائي على Snapchat، فيرجى النقر هنا ، وزيارة مركز الأمان الخاص بنا للحصول على مزيد من المعلومات.

‎إذا كنت تواجه مشكلة في تسجيل الدخول إلى حسابك، فيرجى إلقاء نظرة على هذه المقالة لمراجعة بعض خطوات استكشاف الأخطاء وإصلاحها المفيدة. يمكنك أيضًا العثور على مساعدة بشأن أشياء مثل: إعادة تعيين كلمة المرور والحسابات المخترقة.

‎يرجى ملاحظة أن الردود على هذه الرسالة لن تتم مراقبتها. إذا كنت لا تزال بحاجة إلى المساعدة، يرجى إرسال تذكرة جديدة من خلال زيارة موقع الدعم الخاص بنا.

‎- - [ ] -فريق سناب ****

**Comment by htami1717** [comment]
> Hi

‎##- الرجاء كتابة ردك أعلى هذا السطر -##
‎مرحبًا يا من هناك،

‎لسوء الحظ، نواجه مشكلة في معالجة هذا الطلب. إذا كانت المشكلة لا تزال مستمرة، فيرجى الاطلاع على الروابط أدناه أو زيارة موقع الدعم الخاص بنا لتقديم طلب جديد.

‎إذا كنت ترغب في الإبلاغ عن إساءة أو مشكلة تتعلق بالخصوصية أو السلامة أو البريد العشوائي على Snapchat، فيرجى النقر هنا ، وزيارة مركز الأمان الخاص بنا للحصول على مزيد من المعلومات.

‎إذا كنت تواجه مشكلة في تسجيل الدخول إلى حسابك، فيرجى إلقاء نظرة على هذه المقالة لمراجعة بعض خطوات استكشاف الأخطاء وإصلاحها المفيدة. يمكنك أيضًا العثور على مساعدة بشأن أشياء مثل: إعادة تعيين كلمة المرور والحسابات المخترقة.

‎يرجى ملاحظة أن الردود على هذه الرسالة لن تتم مراقبتها. إذا كنت لا تزال بحاجة إلى المساعدة، يرجى إرسال تذكرة جديدة من خلال زيارة موقع الدعم الخاص بنا.

‎- - [ ] -فريق سناب ****

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @callybton! 🚀

Hi @Vamshi-Reddy-16!

**Comment by Nico-Kestra** [comment]
Hello, thank you for your contribution.
Regarding what needs to be done, it's just a matter of changing the color for content-secondary:

- Dark mode: #E3DBFF
- Light mode: #475569

<img width="1958" alt="Capture d’écran 2024-12-02 à 10 10 48" src="https://github.com/user-attachments/assets/a867ca5d-4b94-47ad-9df8-e8c9eea72e3a">
<img width="1951" alt="Capture d’écran 2024-12-02 à 10 10 33" src="https://github.com/user-attachments/assets/ac9344e7-088a-47e4-ad62-c60c9a9e05e4">

**Comment by anna-geller** [comment]
@callybton do you work on it? it's a matter of changing colors so LMK if you can't take it, will be a matter of minutes for Milos

**Comment by htami1717** [comment]
VPN
