### ISSUE TITLE
Add new filters to Flows -> Metrics tab

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6233]
### Feature description

![image](https://github.com/user-attachments/assets/fe1eaa87-a4a4-44c8-b700-9ec74261a8d1)

**Comment by MichaScant** [comment]
Hi, could I work on this issue?

**Comment by MichaScant** [comment]
thank you, to clarify, what filters should I add to the flows -> metric tab?

**Comment by anna-geller** [comment]
We want to include a new `KestraFilters` component, as we did, for example, on the Executions or Flows page, so you can use those as guidelines.

Also, we want to have all the filters which are present now.

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @MichaScant! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/6409 & https://github.com/kestra-io/kestra/pull/6305.
