### ISSUE TITLE
Add new filters to Administration -> Triggers page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6234]
### Feature description

![image](https://github.com/user-attachments/assets/8c2172f9-7ecb-484a-8f96-29129761625d)

**Comment by sikehish** [comment]
Hi, what kind of filters would you like to have implemented?

**Comment by MilosPaunovic** [comment]
Hi @sikehish, we want to include new `KestraFilters` component, as we did for example on Executions or Flows page, so you can use those as guidelines.

Also, we want to have all the filters which are present now.

**Comment by Piyush-r-bhaskar** [comment]
Hey @MilosPaunovic 

Please assign it to me. I have linked a PR for this.
