### ISSUE TITLE
Handle recent functionality better due to filters being triggered automatically now

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6235]
### Feature description

Given that now we search automatically anytime user types, this creates too many recent searches.

Milos suggests to remove the Recents section and only keep the Saved section -- OK IMO 👍

**Comment by MilosPaunovic** [comment]
@Ben8t @tchiotludo 

Do you maybe have some creative ideas on how we can handle the recent searches in this new setup where we apply filters as soon as we select them?

**Comment by Ben8t** [comment]
Keeping Saved section is enough to me 👍

Other idea: deduplicate Recent searches as I believe user would keep searching the same things over an over without real differences (hence the Recent searches would be smaller...). Still something to validate so I'm not sure it's worth the time for now

**Comment by tchiotludo** [comment]
Quick idea overwrite the latest search as soon as the user stay on the same page (the route didn't change)? 
But not optimal one, so I think we could delete the recent search
