### ISSUE TITLE
ForceRun button must be disabled when execution is in a terminated-state

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#6241]
### Describe the issue

Currently, the execution view, a user can click on `ForceRun` button. But, this action is only relevant if the execution has a non-terminated state. Thus, that button must be disabled when the execution is in a terminated-state.

![kestra-force-run](https://github.com/user-attachments/assets/9e65751f-67e6-4c5a-943e-6ef3fb6e9323)

### Environment

- Kestra Version: develop

**Comment by loicmathieu** [comment]
I'm already on it ;)
