### ISSUE TITLE
Vertically center the content in a table

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6246]
### Describe the issue

When we display the execution statistics, the content of the row is not vertically centered.
<img width="1947" alt="Capture d’écran 2024-12-02 à 15 56 18" src="https://github.com/user-attachments/assets/62b37243-bf3c-4e97-b607-1920a81d0ba4">

### Environment

- Kestra Version: develop

**Comment by nitinkumarpals** [comment]
can i work on this issue

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @nitinkumarpals ! 🚀

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @nitinkumarpals! 🚀

**Comment by nitinkumarpals** [comment]
Thank you so much for the opportunity, @MilosPaunovic! It was a valuable learning experience for me, especially since I'm a React developer and Vue is new to me. I'm glad I could contribute and look forward to taking on more challenges in the future! 🚀
