### ISSUE TITLE
On single flow, add `flowId` as artificial filter parameter

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#6257]
Add it for user to see what is being filtered.

**Comment by aabhas-sao** [comment]
Hi @MilosPaunovic,
I would like to work on this issue. Can you please assign me this issue ✨.

If I am understanding correctly are you suggesting about adding flowid in filter the flows page below for selected flow.

<img width="1440" alt="Screenshot 2024-12-09 at 11 13 33 PM" src="https://github.com/user-attachments/assets/6e34deb7-4160-493d-aa51-b3676107c3ad">

**Comment by MilosPaunovic** [comment]
That's basically it, yes, only on single flow page, add `flowId i VALUE` filter.

**Comment by aabhas-sao** [comment]
Hi @MilosPaunovic,

I have added the filter but the title of the filter need to be added to the 1i8n for different languages. That I'm not sure what values to put in diff languages. Can you please help me out here.

![image](https://github.com/user-attachments/assets/3a662b81-b23c-40e2-a5d3-28a0d143dd2c)

**Comment by MilosPaunovic** [comment]
Hey @aabhas-sao, we have automation which will cover all the languages other than English, so you'd need to add new key only to `en.json` file, search for `filters` key there, where we have all other keys for this new filter bar, and you can open a PR for me to take a look at it.
