### ISSUE TITLE
On single namespace, add the namespace as filter parameter

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#6258]
Add it for user to see what is being filtered.

**Comment by rishamraj-17** [comment]
Hey, I want to work on this issue.  Can Iget some more clarification about the issue??

**Comment by MilosPaunovic** [comment]
Hi @rishamraj-17, so, when you open Namespace listing, and the open single Namespace, you'll get this screen:
![image](https://github.com/user-attachments/assets/6f8d6ba3-ad9e-403a-afa7-4544dd465963)

We should automatically add the selected namespace filter into the `KestraFilter` component, so the user know which namespace data is being shown on first glance.

**Comment by Skraye** [comment]
Adding more detailed base on [this slack message](https://kestra-io.slack.com/archives/C03FQKXRK3K/p1734238976573279?thread_ts=1734238976.573279&cid=C03FQKXRK3K)

Above the graphs on the screen that @MilosPaunovic sent, there is a filter bar. On a Namespace page, we want the filter bar to have the Namespace filter included ( and read only )

**Comment by MilosPaunovic** [comment]
This is already done, section of the code is starting here: https://github.com/kestra-io/kestra/blob/008c03ce2d051370bc750d1c6f7d2fde08c7ac67/ui/src/components/filter/KestraFilter.vue#L485

We are now artificially adding `namespace` parameter on a single flow page and also on a single namespace one.
