### ISSUE TITLE
Improve buttons on new filter bar

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#6260]
The buttons next to the search bar on the right add complexity to the readability.

- [ ] Position the `Save` button in the bar only when filters are selected.
- [x] Separate the search bar from the two refresh buttons.
- [x] Move `Show Chart` button with the refresh buttons and use a chart icon.
- [X] Add a `Clear All` button when filters are selected in the search bar. https://github.com/kestra-io/kestra/issues/5954

<img width="529" alt="Capture d’écran 2024-11-19 à 13 59 56" src="https://github.com/user-attachments/assets/5466fc32-2524-48e2-97de-2cd4737391e6">

👇

<img width="1767" alt="Capture d’écran 2024-11-19 à 14 07 44" src="https://github.com/user-attachments/assets/c4ca8ca9-66df-4e54-b1cd-b5c21de4c445">

**Comment by luciastefankova** [comment]
Hi, I would like to work on this issue

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @luciastefankova! 🚀
