### ISSUE TITLE
Change filter color border

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#6261]
### Feature description

- [ ] Color border when i use the search:  In purple

<img width="468" alt="Capture d’écran 2024-11-19 à 14 14 00" src="https://github.com/user-attachments/assets/1881613a-620f-4614-9432-acdf8d3577d0">

👇

<img width="1653" alt="Capture d’écran 2024-11-19 à 14 12 23" src="https://github.com/user-attachments/assets/31cf3b70-3117-4297-ae55-212311fd8a92">

**Comment by abhishekpawar1060** [comment]
I want to work on this issue

**Comment by MilosPaunovic** [comment]
Go for it, @abhishekpawar1060! 🚀

**Comment by sriyansh18** [comment]
i wanna work on it

**Comment by kalpesh0487** [comment]
@abhishekpawar1060 heyy are you working on this issue? @MilosPaunovic Can i work on the issue at the same time

**Comment by MilosPaunovic** [comment]
Sure, go ahead. Who submits the first PR, it will be merged (if it does what it's supposed to).

**Comment by rajatsingh23** [comment]
We have to make visible the border color?

**Comment by MilosPaunovic** [comment]
@rajatsingh23 this issue is already assigned. May I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/kestra/pull/6364, @Piyush-r-bhaskar can you add a comment here for me to be able to assign this issue to you? And thanks for fixing it! 🚀

**Comment by MilosPaunovic** [comment]
Temporarily disabled the highlighting in e9be7894748edf0fa78a7314d97ff3cc5b09a43e. @Piyush-r-bhaskar you can tackle it when you get the chance.

**Comment by Piyush-r-bhaskar** [comment]
> Closed via https://github.com/kestra-io/kestra/pull/6364, @Piyush-r-bhaskar can you add a comment here for me to be able to assign this issue to you? And thanks for fixing it! 🚀 

Apologies! I didn't know there was an issue for this 🤔.

Sorry @abhishekpawar1060 @kalpesh0487 . Next time whatever you pick I will help you in reviewing if you want. 🙂

**Comment by Piyush-r-bhaskar** [comment]
> Temporarily disabled the highlighting in e9be7894748edf0fa78a7314d97ff3cc5b09a43e. @Piyush-r-bhaskar you can tackle it when you get the chance.

Okie @MilosPaunovic 

Just to be sure. You have disabled it  for now just for me to enable it and link a new PR to close this in particular?

**Comment by Piyush-r-bhaskar** [comment]
> Closed via https://github.com/kestra-io/kestra/pull/6364, @Piyush-r-bhaskar can you add a comment here for me to be able to assign this issue to you? And thanks for fixing it! 🚀 


Yeah you may assign it to me.

**Comment by MilosPaunovic** [comment]
Because we don't have border initially, and add one on hover, this feels a bit jumpy. I'll close it for now and we'll try to rethink it a bit first, before trying to tackle it again.

Thanks for the efforts to everyone involved! 🚀
