### ISSUE TITLE
Check used npm dependecies

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#6286]
We're using the `shiki` package, along with `@shikijs/markdown-it`. Check if the second one is necessary if we have the first one.

**Comment by satvik2131** [comment]
yes , we are using the second package for highlighter in md .

**Comment by MilosPaunovic** [comment]
@satvik2131 Meaning the second package is not included in the first one?

**Comment by satvik2131** [comment]
yes , they are different , the second one is another package and `shiki` doesn't have functions we are using , it's in the other package `@shikijs/markdown-it`

**Comment by MilosPaunovic** [comment]
Thanks for the investigation @satvik2131!
