### ISSUE TITLE
Default NameSpace - io

### ISSUE THREAD

**Issue by Yuri-Lima** [kestra-io/kestra#630]
### Expected Behavior

Once we Select de Default NameSpace to IO and go to the Template, it should not show any error.

### Actual Behaviour

Once we go to the Templates it show ->
![NameSpace error](https://user-images.githubusercontent.com/9964218/175502382-15a7d000-9889-4d5c-9179-9ad4f72a0457.png)

### Steps To Reproduce

1. ![1](https://user-images.githubusercontent.com/9964218/175502754-07a6de4a-b1e6-45e8-91a6-afc3a49d6b4d.png)
2.![new 2](https://user-images.githubusercontent.com/9964218/175503878-329a8293-a837-4414-bcb4-faecc90594c0.jpeg)
3. ![3](https://user-images.githubusercontent.com/9964218/175502837-75580e14-4d19-4678-b5b7-872cefbf166b.png)

### Environment Information

- Kestra Version:0.5.0-SNAPSHOT

- Operating System (OS / Docker / Kubernetes): Ubuntu 20.04.4 LTS(Py3.7.9)

**Comment by Yuri-Lima** [comment]
Sorry, @tchiotludo by my mistake I hit the button before typing the issue. I'm still writing.

**Comment by tchiotludo** [comment]
ok :) 
If you want interactive exchange, please go to our [Slack](https://api.kestra.io/v1/communities/slack/redirect)

**Comment by tchiotludo** [comment]
fix after the build :) 

THanks for the report @Yuri-Lima :+1:
