### ISSUE TITLE
Navigating to User IAM in Admin causes UI to Freeze/Lose Response

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#6307]
### Describe the issue

- navigate to Admin
- Navigate to IAM
- Navigate to any User
- freezes

*example URL - https://us.kestra.cloud/ui/xxxxxx-prod/admin/iam/users/edit/xxxxxx 

### Environment

- Kestra Version: `0.20.1`

**Comment by Ben8t** [comment]
Able to reproduce on cloud (05/12) https://share.descript.com/view/JbjRaIOAq1h

**Comment by Ben8t** [comment]
Actually not something related to Cloud directly: as a superAdmin everything works fine, but Admin only will get a frozen tab whenever checking a user page
