### ISSUE TITLE
Two date columns in the Triggers table lack sorting option

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6317]
### Describe the issue

![image](https://github.com/user-attachments/assets/8c45aa41-f437-4778-ad2e-8b78467c9856)

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
Added sorting by `nextExecutionDate` field. Other fields would require BE work (and by looking at the DB structure, not really sure it's easy feasible).

Is this one field enough for this issue or are we going to tackle the implementation for the other one @anna-geller ?

**Comment by anna-geller** [comment]
Looks enough yup! Thanks Milos 👍

**Comment by MilosPaunovic** [comment]
Cool, then, closing this via https://github.com/kestra-io/kestra/pull/6318.
