### ISSUE TITLE
Overflow of states in the Donut chart on the main Dashboard

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6319]
### Describe the issue

You can reproduce e.g. in Cloud 
![image](https://github.com/user-attachments/assets/038ad043-f808-4cc8-8c85-b52bfde8217e)

### Environment

- Kestra Version: latest

**Comment by MilosPaunovic** [comment]
Does this solution https://github.com/kestra-io/kestra/pull/5971 seem alright @anna-geller, or would you prefer to have scroll after some point (to show e.g. 5 labels all the time but scroll that container if there are more.

**Comment by anna-geller** [comment]
LGTM! Given we have a PR from a contributor, seems best to merge it and afterwards maybe check with Nico if it's good for him? 👍

**Comment by MilosPaunovic** [comment]
The other solution was not technically done in a proper way, so I've tweaked it to now show 4 labels and scrollbar if there are more than that. It solves the problem for now, if there is a need, we can revisit.
