### ISSUE TITLE
[UI] Search component fails to handle empty result from the backend

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#6326]
### Describe the issue

When searching executions with some filters, if the API returns no result (i.e., `{"total":0}`),  then the component fails to properly handle the response :

`TypeError: Cannot read properties of undefined (reading 'length')`

Which leads to an empty page:

![kestra-issue-search-execs](https://github.com/user-attachments/assets/c9fafa5c-22d6-4dc4-9c95-9164dcb41b99)

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
Hey @fhussonnois, could you provide some more details about this, as I'm unable to reproduce locally.

![image](https://github.com/user-attachments/assets/ec9acabd-e04f-4997-b19c-14ed924e438a)

**Comment by smunteankestra** [comment]
@fhussonnois not reproducing on my side either 
![image](https://github.com/user-attachments/assets/dd2a2d5b-cdb0-4843-8134-8c4163a50451)

**Comment by MilosPaunovic** [comment]
Closing, as nobody except Florian can reproduce. Please reopen if If necessary.
