### ISSUE TITLE
Deleted flow should be not prevent to see past execution 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6333]
A regression is done, in the past, you were able to see an execution from a flow that was deleted, now we have this error page not found: 
![image](https://github.com/user-attachments/assets/5fe424a2-1bbe-4f10-88f2-3f6fd1aa4994)

We need to be able to see the execution of deleted flow and we can see the flow at the revision it was triggered

**Comment by MilosPaunovic** [comment]
Can you provide more details @tchiotludo, as I've tried reproducing by following these steps and it works as expected:
Or @smunteankestra, can you try to reproduce the issue somehow?

1. Create new flow and execute it
2. Check it's execution
3. Go back to flows listing and delete the flow
4. Go to the executions listing, and the execution of the flow is there
5. Open the execution and see its details

![image](https://github.com/user-attachments/assets/2598c01f-1813-41ed-818f-791aec4e7db7)

**Comment by smunteankestra** [comment]
not reproducing on develop
what I understood - if you delete a flow - past executions should be present (not deleted)
@tchiotludo can you check again and close if it's not reproducing?

**Comment by Ben8t** [comment]
Cannot reproduce on 0.20 Postgres but can reproduce on Kafka backend (https://preview-ee-kafka.kestra.io/ui/executions/kestra.bpimpaud/myflow/6kowtgaAw9N2RIofoYrpsP)

**Comment by MilosPaunovic** [comment]
If that's the case, it seems like a BE problem then.

**Comment by tchiotludo** [comment]
seems a front end one, look at this : 
![image](https://github.com/user-attachments/assets/e387c29d-215f-45f4-aa4c-f65d87b818d5)
the revision is not passed, so trying to get the latest revision, that will failed.
