### ISSUE TITLE
UI - Should tweak the hitboxes while double clicking inside trigger boxes 

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#6344]
### Describe the issue

![Flow_Trigger_expansion_bug](https://github.com/user-attachments/assets/e075deef-60a6-45e0-9162-517ef592b58d)
While double clicking inside the trigger box (anywhere) it displays the details of the trigger, yet, it should be deactivated on area like the collapse/expand button or any other one.

### Environment

- Kestra Version: 0.20.2
- OSS
- Docker compose debian
- Web access :
  - Firefox
  - Windows 10

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @tejas2292! 🚀

**Comment by tejas2292** [comment]
@MilosPaunovic Thank you, can you please assign me this task. 

I have fixed this bug. Should i put the PR once you assign me or should i directly push it?

**Comment by MilosPaunovic** [comment]
Open a PR please, I will assign you.

**Comment by tejas2292** [comment]
Done, Thank you for clear guidance

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @tejas2292! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/6354.
