### ISSUE TITLE
Improve Gantt page 

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6346]
### Feature description

<img width="1457" alt="Capture d’écran 2024-12-06 à 12 15 48" src="https://github.com/user-attachments/assets/0fcee7be-ae0a-4f53-8d3e-267659b39903">

- [x] Add a line for separation between tasks
- [x] Name of task in white
- [x] Add a arrow on the left of task
- [x] Increase the row height
- [x] When task is expended, add spacing on left and right and radius

[Figma](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3622-32458&t=LlVtYYisOKsNljAL-1)

**Comment by Piyush-r-bhaskar** [comment]
Hey @MilosPaunovic 

It's looks almost similar to the Logs one. 
I would love to do this if it's to proceed with one PR open.
