### ISSUE TITLE
Change arrow and colors tasks on Executions logs tab

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6347]
### Feature description

- [x] The arrow on the right is not visible; I suggest placing it to the left of the task name.
- [x] Change color font and icon task for white

<img width="1835" alt="Capture d’écran 2024-12-06 à 13 27 35" src="https://github.com/user-attachments/assets/51d98cc8-e5bd-4225-93b3-c5ffce142593">

👇

<img width="1699" alt="Capture d’écran 2024-12-06 à 13 28 46" src="https://github.com/user-attachments/assets/d6286d6d-4a44-49a8-ac75-bf6c294746ef">

[FIGMA](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=1446-11615&t=LlVtYYisOKsNljAL-1)

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic 

Please assign this to me. I will link a PR for this.
