### ISSUE TITLE
Swagger specs  are generated on the bad path

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6353]
in the past, swagger specs was generated on the `/META-INF/swagger/kestra.yml`. 
Now it's `/META-INF/swagger/kestra-1.0.0.yml`. probably due to a change on micronaut side. 
I think it's using the specification [here](https://micronaut-projects.github.io/micronaut-openapi/snapshot/guide/index.html#propertiesFileConfiguration).
We should revert to old path (it's a breaking change) and add a unit test to prevent this change.

**Comment by yuri1969** [comment]
Can you assign the issue to me, please?

**Comment by tchiotludo** [comment]
yes for sure, thanks ! 
I've started to look quickly previous week, it seems that default configuration from micronaut had [changed](https://micronaut-projects.github.io/micronaut-openapi/snapshot/guide/index.html#availableOptions) especially `micronaut.openapi.filename` but maybe I'm wrong on the first analysis! 

EDIT: seen the PR, I restarted the build
