### ISSUE TITLE
KVs with system namespace don't work

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6367]
### Describe the issue

`{{ kv(key='SMTP_HOST', namespace='system', errorOnMissing=true) }}` raises `io.pebbletemplates.pebble.error.PebbleException: Cannot access the KV store. The namespace 'system' does not exist. ({{ kv(key='SMTP_HOST', namespace='system', errorOnMissing=true) }}:1)` 

FYI, current workaround as a Enterprise Edition user: add a description to the system name (still not a good solution)
### Environment

- Kestra Version: develop

**Comment by loicmathieu** [comment]
Can you check if it could happen with any other namespaces that didn't exist (that didn't have any KV).

It may be just that the kv function fail when the namespace didn't already exist, we may decide to ignore such case and return null as if the kv didn't exist.

**Comment by loicmathieu** [comment]
This is the case for any namespace which have a KV but not flows as, in OSS, we check the existence of a namespace by checking if a flow exist for it.
I'll also check if a KV exist.
