### ISSUE TITLE
Bug - UI Main Dashboard Total Executions overflow

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#6375]
### Describe the issue

Total Executions on Main Dashboard is overflowing on 14 inch laptop screen normal resolution/zoom.

<img width="471" alt="Screenshot 2024-12-09 at 8 31 33 PM" src="https://github.com/user-attachments/assets/da451c61-9abf-4eb0-bc2b-e35c995e03c4">

### Environment

- Kestra Version: 0.20.4

**Comment by MilosPaunovic** [comment]
Amended in https://github.com/kestra-io/kestra/pull/5971. Will be part of maintenance release planned for later today.
