### ISSUE TITLE
Disabling a trigger while it is evaluating will re-enable it when the evaluation is done.

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#6378]
### Describe the issue

To reproduce, better to have a trigger which took some time to evaluate.
When the trigger is evaluating, go to the trigger page and disable it.
When the trigger ends its evaluation, it triggers and execution then  update itself, re-enabling itself.

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
Is this related to https://github.com/kestra-io/kestra/issues/3705?

**Comment by loicmathieu** [comment]
Maybe, I'm investiguating
