### ISSUE TITLE
Do a CSS sweep to align with latest version of Sass

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#6390]
Cooldown period might be a good time to do a full sweep of CSS to align with latest version of Sass, which produces warnings when we remove the artificial silencing of the logger from `vite.config.js` file:

```js
preprocessorOptions: {
   scss: {
      logger: sass.Logger.silent
   },
}
```

This should be done in EE repository also.

**Comment by elevatebart** [comment]
A lot of issues come straight from bootstrap. 

https://github.com/twbs/bootstrap/issues/40962#issuecomment-2448214806

They don't want to fix the deprecations. It would remove compatibility with `node-sass`.
I think we should postpone until they have fixed it.

Let's change one thing though: "only silence the needed warning"

**Comment by MilosPaunovic** [comment]
Yup, agreed.
