### ISSUE TITLE
Kestra Schedule not executing on time

### ISSUE THREAD

**Issue by Drishti-rawal** [kestra-io/kestra#6406]
Hi All,

I'm facing an issue in Kestra while using triggers. None of the flows are running on their scheduled time. It shows the correct next execution time when the flow is created. But it doesn't executes on the scheduled time and the next execution date is not updated after that time is passed.

I've checked logs of all pods in k8s. couldn't find any error. Postgres db is also available for connecting.

How do I debug/resolve this?

[Slack Message](https://kestra-io.slack.com/archives/C03FQKXRK3K/p1733912019951129)

**Comment by Ben8t** [comment]
Hello,

Can you share more informations about your flows (which task, triggers, etc.)?
What's your Kestra version?
Is it a new error happening here, or it's the first time you're using Kestra?

**Comment by Drishti-rawal** [comment]
Following is my flow.


id: trigger-test
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: This will execute only on Thursday!

triggers:
  - id: trigger-0
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "12 9 * * *"


Kestra version is - **0.18.3**

We faced similar issue earlier. It worked after I flushed the old DB and created a new one.

None of the flows are executing on scheduled time.

**Comment by Ben8t** [comment]
It's not easy to reproduce without more information 🤔 I understand that all the Kestra services are running well correct ?
Are you able to reproduce in some way locally ?

**Comment by Drishti-rawal** [comment]
This is the scheduled time.
![image](https://github.com/user-attachments/assets/4fc8824c-9c42-46f4-9a2e-bb32e013cbdd)

But there's no execution at that time.
![image](https://github.com/user-attachments/assets/5defd898-2205-4fbc-be18-aad7e847c442)


Same is happening with all other triggers. This is happening only on this particular instance of kestra.
What could be the potential issue?

**Comment by Ben8t** [comment]
> This is happening only on this particular instance of kestra.

Can you check if all services are running properly. If it's only on this instance, you might have to deep dive into your installation.

I'm closing for now, do not hesitate to reopen if oyu find out it's an actual issue on Kestra components

**Comment by Drishti-rawal** [comment]
I have verified that all services are up and running fine. We have deployed multiple instances using the same helmchart.
Scheduling was working fine on this instance for around 3 months and it has suddenly stopped working with no errors.
