### ISSUE TITLE
Topology view throws an error for unsaved flows: An issue occurred while generating the graph which prevents the topology to be displayed.

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6408]
### Describe the issue

![image](https://github.com/user-attachments/assets/0de24de9-211d-4d0f-b34f-c3bf0bc76dcf)

Once you save the flow, everything works again:

![image](https://github.com/user-attachments/assets/b8333daa-8905-449a-92af-ac71b8f02f8c)

### Environment

- Kestra Version: latest 0.20.4

**Comment by MilosPaunovic** [comment]
Think @brian-mulier-p solved this yesterday?

**Comment by brian-mulier-p** [comment]
Yes https://github.com/kestra-io/kestra/commit/99227a64437f66259c4e302108cf2a40b639b66a
