### ISSUE TITLE
Add a Pebble function to convert timestamp to date and date string

### ISSUE THREAD

**Issue by mozhu1024** [kestra-io/kestra#6416]
### Feature description

Add a Pebble function to convert timestamp to date and date string

**Comment by Ben8t** [comment]
Hello @mozhu1024 , did you try with some of the expressions listed here https://kestra.io/docs/expressions#temporal-filters ?

**Comment by mozhu1024** [comment]
> Hello @mozhu1024 , did you try with some of the expressions listed here https://kestra.io/docs/expressions#temporal-filters ?

Sorry, I tried it yesterday, but show me could not be parsed. 

I found it, my timestamp field is a string.

It work!

'timestamp' | number('LONG') | date('yyyy-MM-dd')
