### ISSUE TITLE
Add a Pebble function [uniq] to deduplice array

### ISSUE THREAD

**Issue by mozhu1024** [kestra-io/kestra#6417]
### Feature description

Add a Pebble function [uniq] to deduplice array

[1,2,2,3] | uniq -> [1,2,3]

OR

Adding a bool parameter to merge with uniq

[1,2] | merge([2,3],true) -> [1,2,3]

**Comment by Rajarajan985** [comment]
Hi @mozhu1024,
I would like to work on the issue.
Can you assign the issue to me.

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @Rajarajan985! 🚀

**Comment by Rajarajan985** [comment]
Hi @MilosPaunovic , @mozhu1024,

Added the new change for the below mentioned feature.

Can you check once the code, the code is commited in the branch and created the merge request for waiting for approval.
I'm new to this project, Can you guide how to test changes which I have modified on the branch for this feature.

feature:
--------
Add a Pebble function [uniq] to deduplice array
[1,2,2,3] | uniq -> [1,2,3]
