### ISSUE TITLE
Make the entire row of tasks clickable on the Gants page

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6448]
### Describe the issue

Since the arrow was added on the left, the gauge is no longer clickable.
I suggest making the entire area clickable.

<img width="1500" alt="Capture d’écran 2024-12-13 à 10 55 10" src="https://github.com/user-attachments/assets/cb920a18-eaf9-4eb9-ad81-ca8a98aba246" />

### Environment

- Kestra Version: develop

**Comment by Piyush-r-bhaskar** [comment]
whoever takes it need to make a little change here in this component `ui/src/components/executions/Gantt.vue`

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic 

please assign it to me. I will link a PR for this.

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @Piyush-r-bhaskar! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/6539.
