### ISSUE TITLE
Review the error component on the Overview Executions page

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6449]
### Describe the issue

<img width="1596" alt="Capture d’écran 2024-12-13 à 11 03 16" src="https://github.com/user-attachments/assets/db1c94ea-fb6e-4faa-8653-2b24328dc440" />

- IUse the same style as the announcement shades (background opacity, text color, border color, etc.).
- Change the arrow icons.
- Change the error icon.
- Change the Errors Logs button.

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
@Piyush-r-bhaskar Thanks for the contribution on this one! 🚀

If you add a simple comment here, I'll be able to assign it to you.

**Comment by Piyush-r-bhaskar** [comment]
> @Piyush-r-bhaskar Thanks for the contribution on this one! 🚀
> 
> If you add a simple comment here, I'll be able to assign it to you.

Sure @MilosPaunovic 
Please assign this to me.
