### ISSUE TITLE
Language and Timezone Selections Not Retained After Reopening Settings (unless Save Changes is Clicked)

### ISSUE THREAD

**Issue by ghost** [kestra-io/kestra#6460]
### Describe the issue

When changing both the language and timezone in Kestra, the changes are applied correctly throughout the interface. However, if the "Save Changes" button is not explicitly clicked, these settings (language and timezone) are not retained upon reopening the Settings page. The language dropdown reverts to showing "English" as selected, and the timezone resets to the default value, even though the application retains the previously selected language and timezone.

In contrast, features like changing the theme to Dark/Light are properly retained without needing to click "Save Changes."

**Steps to Reproduce:**

1. Change the language to a non-English language (e.g., French or Japanese) and set the desired timezone.
2. Do not click "Save Changes" and navigate away from the Settings page.
3. Reopen the Settings page.
4. Observe that the language dropdown shows "English" as selected, and the timezone is set to the default value, even though the application continues to use the previously selected language and timezone.

**Expected Behavior:** 

Both the language and timezone dropdowns should retain the last selected values without requiring the "Save Changes" button to be clicked, just like the theme dropdown.

**Actual Behavior:**

The language dropdown incorrectly displays "English" as selected, and the timezone defaults to the original value when the Settings page is reopened.

![kestra-bug](https://github.com/user-attachments/assets/26e859df-7fda-470a-bd85-aab13df5f0f4)

### Environment

- Kestra Version: develop
- Version: 0.20.6

**Comment by arpitgupta-it** [comment]
`const {t} = useI18n();`

Looks like useI18n instance is not tied to the global scope for this issue.

**Comment by MilosPaunovic** [comment]
This is indeed a bug.

But, we would like to change behavior so that nothing is changed/saved until user explicitly clicks on the `Save Changes` button in the top right corner.

If any contributor wants to tackle this, the file in question is `kestra/ui/src/components/settings/BasicSettings.vue`

**Comment by MilosPaunovic** [comment]
This was some awesome work @shreeup, thanks for the contribution! 🚀 

Also, if you add a comment to this issue, I'll be able to assign it to you, otherwise, I can not.

**Comment by shreeup** [comment]
Thank you for reviewing my PR. Can you please assign the task to me?
