### ISSUE TITLE
UI - 2 'Cancelled' Options

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#6461]
### Describe the issue

2 cancelled options in executions state filter

<img width="424" alt="Screenshot 2024-12-13 at 1 30 31 PM" src="https://github.com/user-attachments/assets/e82bd335-75c8-4ebb-a65c-f163f8285515" />

### Environment

- Kestra Version: 0.20.6

**Comment by MilosPaunovic** [comment]
Right now, we have:

```js
 CANCELLED: {
   name: "CANCELLED"
   // ...
},
SKIPPED: {
   name: "CANCELLED",
   // ...
}
```

So `Skipped` status is labeled `Cancelled`. Was there any decision behind it @anna-geller or should I just rename it back to `Skipped`?

**Comment by anna-geller** [comment]
Rename it of course, no idea how this happened 😅 should definitely be SKIPPED

**Comment by ghost** [comment]
I've opened a PR. Please review!

**Comment by MilosPaunovic** [comment]
Re-opening this as now, when we send `SKIPPED` as parameter get the error below:
![image](https://github.com/user-attachments/assets/eeb39155-2c68-4dc4-8f66-209ae3e5c4a1)

Maybe @Skraye remembers why we labeled it `CANCELLED` in the first place?
