### ISSUE TITLE
MUltiple filters can be added on second try

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#6476]
### Describe the issue

https://github.com/user-attachments/assets/d9e235a8-f6d0-41dc-a656-1b7646c40a06

### Environment

- Kestra Version: develop

**Comment by rajatsingh23** [comment]
Can this issue be assigned to me?

**Comment by MilosPaunovic** [comment]
Great work, thanks for this @rajatsingh23! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/6573.
