### ISSUE TITLE
[Feature] add a core plugin to store string to local file

### ISSUE THREAD

**Issue by qui458** [kestra-io/kestra#6524]
### Feature description

in Slack, me an @tchiotludo had a discussion about how to store messages that come as a string to files that could be later passed on as uri further down the flow. Ludovic suggested to add a core plugin to mitigate this.

Ludovic's example:
```
- id: put
     type: io.kestra.plugin.core.storage.Put
     from: "{{ trigger.data }}"
     name: "data.xml" 
```

initial question in Slack:

> hey! is there a way in Kestra to store STRING variables to local storage as URI? I wanted to use AMQP RealtimeTrigger and then use received data in the flow to convert messages (my flow is to fetch xml messages from RabbitMQ and convert them to Ion for further processing), but I did not find a way to use that message as a string to process it down the line. unless AMQP trigger could use fetchType parameter, perhaps?

**Comment by tchiotludo** [comment]
https://github.com/kestra-io/kestra/pull/1009/files

**Comment by anna-geller** [comment]
just a note that the naming + plugin category might be misleading - this is intended as sth just to return Output in a given format, not sth to be forever stored in internal storage, so we should explore:
- `io.kestra.plugin.serdes` seems like the right place as all conversion/serialization tasks are there
- it's not Put, more Output = output data in format XYZ, maybe a direction like `StringToIon`

**Comment by aj-emerich** [comment]
Added description in https://github.com/kestra-io/kestra/pull/6710
