### ISSUE TITLE
Change the “Editor” name by “Edit”

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6533]
### Feature description

![image](https://github.com/user-attachments/assets/c19c5ef7-bbff-45c5-a8d8-f48c628bbb16)

**Comment by sampath24-ss** [comment]
Hi @Ben8t 

Could you point me to the relevant file(folder) where the changes need to be made?

**Comment by sampath24-ss** [comment]
Hi @Ben8t 

I will check on this issue

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @sampath24-ss! 🚀
