### ISSUE TITLE
UI: improvement to Blueprints inside Flows (Source and blueprints).

### ISSUE THREAD

**Issue by Piyush-r-bhaskar** [kestra-io/kestra#6547]
### Describe the issue

We are having tags without border and 'Copy' button doesn't have the styling from Blueprints main page.

![image](https://github.com/user-attachments/assets/f68d8833-a045-4618-adad-ab2e16cf2da1)
![image](https://github.com/user-attachments/assets/9016d6c0-6f70-4747-9dbf-10d708a090d5)

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
Great catch @Piyush-r-bhaskar, thanks for this! 🚀
