### ISSUE TITLE
Add a revision column to Executions 

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#6593]
### Feature description

It would be useful to know what the revision of the flow is for each execution on the Executions page. I think it should be added as a default column to be shown on this page :

![image](https://github.com/user-attachments/assets/a1c43aef-3818-4958-847c-de9c77c760da)

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/kestra/commit/807a44d1875ff648f67d424cb71728b28881e225.
