### ISSUE TITLE
UI - Execution Inputs Info visual does not read full inputs

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#6594]
### Describe the issue

Hello,

I am running into issues seeing full inputs in Execution-specific Inputs Info visual at the bottom.

For example - Customer IDs is.. 
```
6730734544,9934289301,6927244203,6862101609,6902190782,2151934093,5738910368,7300513944,2085536403,3057343133,9659038954,2351835650,8626880633,7765982366,1673318092,4572672133,8146813680,6657990211,5976051882,2990476500,5463801233,1049429842,1491350872,1066749599,5697024080,7816406113,5837163448,1628354727
```

and this image is what I see, despite clicking on it

![Screenshot 2024-12-26 at 9 34 13 AM](https://github.com/user-attachments/assets/b82b96f3-4519-4898-a1cf-dd24e2aa5e31)

### Environment

- Kestra Version: 0.20.7

**Comment by japerry911** [comment]
![Screenshot 2024-12-26 at 9 35 25 AM](https://github.com/user-attachments/assets/1f07904b-34ce-4a4f-8041-ebdb806ab6db)


here's another screenshot, showing empty space

**Comment by MilosPaunovic** [comment]
Solved via https://github.com/kestra-io/kestra/commit/96d8239b5964f26e3f18afa9edef5620704b7538. Will be available on next cloud deployment.
