### ISSUE TITLE
Ability to create 1+ tasks through a For Loop in Pebble

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#6599]
### Feature description

I think if there was some sort of way to create multiple tasks in pebble for loop, that would be really cool and help make our code base super DRY.

- example:

```
      - id: parallel
        type: io.kestra.plugin.core.flow.Parallel
        concurrent: 5
        tasks:
          {% for job in variables.possible_jobs %}
            insert task
          {% endfor %}
```

I understand this breaks basic YAML conventions, so I think it would have to be creative, and maybe a special type of task where this is allowed.

Let me know your thoughts and/or questions.

Thank you!

**Comment by Ben8t** [comment]
Hello Jack! Interesting case, can you details a bit more your needs please ?

What about using ForEach with Subflows ?
What about using Terraform like proposed [here](https://kestra.io/docs/how-to-guides/terraform-templating) ?

**Comment by japerry911** [comment]
Hello @Ben8t 😄 !

I think [this](https://kestra.io/docs/how-to-guides/terraform-templating#tasksyml-will-contain-the-flow-definition-in-yaml-format-we-can-leverage-jinja-as-supported-by-terraform-templatefile), what you pointed to, is the solution.

We currently use Kestra Deploy CLI for deploying Namespace Flows, but Terraform makes more sense with that templating. So I think I am going to take advantage of Terraform integration and the Terraform templating language.

Thank you for sharing that with me, feel free to close this, it's no longer needed with Terraform :D  🙏

**Comment by Ben8t** [comment]
Great !! Let us know how it goes, we're always curious about such integration with Terraform.

cc @aballiet as he's one of the contributor of this guide and definitely a big user of such Terraform integration 😉
