### ISSUE TITLE
theme uri invalid with extra "/"

### ISSUE THREAD

**Issue by mengzhuo** [kestra-io/kestra#660]
### Expected Behavior

Access /ui/flows get all extra resources.

### Actual Behaviour

Can't get theme-light.js and theme-light.css, here is actual URI, Please note there is an extra "/" after ui/

```
<link rel="stylesheet" href="/ui//css/theme-light.00305fce.css" data-theme="theme-light">
```
https://github.com/kestra-io/kestra/blob/0886e50d7fd828bafbea67e268f95665bd59616e/ui/public/index.html#L23-L26

https://github.com/kestra-io/kestra/blob/d9f02017a5f23b6581ca1b35d96392351a45a93f/ui/src/App.vue#L96-L110

Might be the culprit.

### Steps To Reproduce

1. Install istio and using oauth2-proxy for authentication.

### Environment Information

- Kestra Version: 0.5.0-BETA

**Comment by tchiotludo** [comment]
Thanks for the report 
Maybe you can add create a PR with trim last `/` on `basePath` ?
