### ISSUE TITLE
Killed task remains active

### ISSUE THREAD

**Issue by nsteinmetz** [kestra-io/kestra#664]
### Expected Behavior

Killed task should be killed and marked as failed

### Actual Behaviour

Killed task keeps running

We can see the kill call

```
kestra-kestra-1  | 2022-07-21 07:09:42,297 INFO  default-nioEventLoopGroup-1-4 io.kestra.webserver.access [Date: 2022-07-21T07:09:42.275975Z] [Duration: 21 ms] [Method: DELETE] [Url: /api/v1/executions/6jOT5hnUvGIfODoyYI1r5f/kill] [Status: 204] [Length: 0] [Ip: 109.190.249.185] [Port: 8080]
```

but nothing happens, no more logs on kestra side nor on postgres side that could provide more info on this.

Task is active for more than a day now and I have no way to kill it afaik.

### Environment Information

- Kestra Version: 0.5.0-snapshot - lite mode
- Operating System (OS / Docker / Kubernetes): docker
- Java Version (If not docker):

**Comment by tchiotludo** [comment]
It's the same issue than https://github.com/kestra-io/kestra/issues/309. But for the JDBC executor. 
When we kill an execution, we ask all the workers to find a task to kill, if no one handle this one, this lead to infinite kill and keep it running.
Do you have an easy reproduction?

**Comment by nsteinmetz** [comment]
I still have my waitiing to be killed flow for days. Except that I don't really know how to reproduce it. I noticed the issue as the job no longer runs for next occurences of the schedule...

**Comment by loicmathieu** [comment]
Kill has been totally reworked a few release ago and on 0.17 it will be transmitted to script tasks.
I considered this old issue as fixed by those changes made on several releases.
