### ISSUE TITLE
[UI] Add a global search bar — at first only allowing to jump to specific sections (Flows, Logs, Executions, ...)

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#706]
Like Slack / Github / Notion / Atlan , add a global search in Kestra in order to find anythings: 
- Flow 
- Template
- Execution Id 
- (TaskRun Id) (don't think it's possible)

**Comment by Ben8t** [comment]
@Nico-Kestra probably some design needed here 🤔  I will keep in you in touch if we prioritize this one

**Comment by Nico-Kestra** [comment]
can we look in the documentation too?

**Comment by anna-geller** [comment]
first iteration of a global search bar will only allow to jump to menus:
![Capture d’écran 2023-10-11 à 16 37 23](https://github.com/kestra-io/kestra/assets/86264395/1efb4998-52e4-4fb6-94f6-88dfd51f0b0f)

**Comment by Ben8t** [comment]
lovely 👏
