### ISSUE TITLE
Allow multiple usage of a template inside the same flow

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#719]
When using multiple template inside the same flow, the task id from the template will be duplicated and prevent the execution. 

We must support this and maybe you can do a quick hack using the taskrun.value to deduplicate the task Id.

**Comment by mlaigre** [comment]
Hello,

I often run into this problem e.g. when I want to trigger several AirByte tasks in the same flow.

Am I the only one or is there a pattern to avoid it?

**Comment by tchiotludo** [comment]
My advice is to used [SubFlow](https://kestra.io/docs/developer-guide/triggers/flow) instead of Template that will remove all limitation. 
Does you really need to have a Template? If yes, why?

**Comment by tchiotludo** [comment]
close in favor of kestra-io/kestra#1907
