### ISSUE TITLE
Add startOf / endOf filter for dates

### ISSUE THREAD

**Issue by nsteinmetz** [kestra-io/kestra#763]
### Feature description

To compute a date (like start of day, start of month, etc), it would be nice to have:

```
{{ schedule.date | startOf('DAYS') }}
```

It would return `YYYY-MM-DDT00:00:00Z`

Same with `endOf()`

**Comment by anna-geller** [comment]
sorry for responding to this so late

this can be accomplished using: 
- `{{ execution.startDate | date("yyyy-MM-dd") }}`
- `{{ (trigger.date ?? execution.startDate) | date("yyyy-MM-dd") }}`

See more https://kestra.io/docs/concepts/expression/filter/temporal
