### ISSUE TITLE
Enhance UI representation of subflows from a flow topology

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#774]
### Feature description

Use-case: when dealing with several subflows or a few number of subflows with a lot of tasks, it's quite complicated to follow the execution or understand the topology when looking at the parent flow.

Suggested solutions:
- set-up a breadcrumb in order to "go back" to the calling flow, when we dived into the topology of a subflow
- create a "expand" button on a subflow node when looking at the topology of a flow in order to unpack it

Thanks :)

**Comment by Ben8t** [comment]
epic at #1670
