### ISSUE TITLE
Speed-up copying of inputFiles at the beginning of a task execution

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#789]
### Feature description

Staging local files from Kestra storage to the temporary one takes a lot of time and ends up to be quite costly when executing on cloud environments.

For example, it currently takes roughly 5 minutes to stage 30GB on a VM with fast I/O (several CPUs and SSD).

Is there a way to speed it up ?

Thanks :)

**Comment by anna-geller** [comment]
given we added `inputFiles` and `outputFiles` properties, it seems easier now to add custom files in a much faster way (even first downloading via another plugin and passing it to downstream tasks)

if this is critical and doesn't work yet, feel free to reopen or ping me and I'll reopen
