### ISSUE TITLE
Docs:  Adding Restack as a way to deploy Kestra on Kubernetes

### ISSUE THREAD

**Issue by kuberaspeaking** [kestra-io/kestra#812]
### Issue description

This contribution will add [Restack](https://www.restack.io/) as a way to deploy Kestra on k8s in your own AWS infrastructure.
I will be adding this under Administrator Guide/Installation guide next to [Deployment on Kubernetes](https://kestra.io/docs/administrator-guide/deployment/kubernetes/)
I have gone through the contribution guide.
Do let me know if you have any preferences like screenshots or no screenshots.

**Comment by tchiotludo** [comment]
Hey, You can add screenshot, it's even better
