### ISSUE TITLE
Flow page: empty page on nav click 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#84]
Switching between tabs on flow page lead to an empty page : 
![image](https://user-images.githubusercontent.com/2064609/76195687-2688df80-61e9-11ea-87e3-cacecdbb3088.png)
We need to press F5 to have the current page displayed well

**Comment by eregnier** [comment]
we should have automatic tests for this in CI. I will fix this and produce tests.

**Comment by tchiotludo** [comment]
:+1:
