### ISSUE TITLE
Input files via URL as a proper input (inputURLS feature)

### ISSUE THREAD

**Issue by priamai** [kestra-io/kestra#849]
### Feature description

Would be super useful to add a feature to input files via urls.
Maybe we can call this as an inputURL feature?
For now what I do is a bash task that calls wget/curl to download a file then pipe it through an output to another file.

**Comment by anna-geller** [comment]
We support URL-type input now, so the use case seems possible. 

if the URL-type input doesn't solve the issue, please add a comment here or ping us on Slack and we'll look into it
