### ISSUE TITLE
UI improvements suggestions

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#878]
### Feature description

Several UI improvement suggestions following my first tests:

- When creating a new flow, the textarea could already contains what is mandatory for a flow: id, namespace, tasks, ...
- Add a button "Support" or "Help" or whatever button to redirect to ways to contact the team (Github / slack / ...). It is currently possible via Documentation but it's not the same.
- Flow Outputs column is not outputs but all variables. It would be greate to only shows output and have a separate tab for all variables (or a detail button on the output page).
- Flows -> select a namespace -> click on a flow -> click on the 'namespace breadcrumb': the namespace is lost
- Outputs should allow to easily filter on the Value column
- There is no direct link to the Github repo (there is a link to the issue but it's not the same)
- When you create a flow then create another, the previous flow content is still in the textarea and when you hit create you have a 404. Refreshing the page fix the issue.
- Add a "Copy logs" button in the Logs tab and in the Gantt tab when accessing the detail of a task.
- After the creation of a Flow, it would be great to redirect to the Topology tab
- Provide an "Export" button on the flow source to download the source YAML

**Comment by anna-geller** [comment]
@loicmathieu was it created when you started at Kestra? :) we should create a dedicated issue for each of those points that are still true

**Comment by loicmathieu** [comment]
Yes, it was created when I first test Kestra, most of them has already been covered over the months.

The ones that I think deserve a separate issue as they have some interest are:
- Outputs should allow to easily filter on the Value column => in fact also on the name. This may be a broader issue with sort and filtering on output names and variables
- Add a "Copy logs" button in the Logs tab and in the Gantt tab when accessing the detail of a task.
- Provide an "Export" button on the flow source to download the source YAML

**Comment by anna-geller** [comment]
Regarding `copy logs`: do you want to download a single log message or all logs for a given task? Are there no performance implications of allowing to copy all logs per task (e.g. a task with thousands of lines of logs)?


For others, I opened dedicated issues:
- https://github.com/kestra-io/kestra/issues/2067
- https://github.com/kestra-io/kestra/issues/2065

**Comment by loicmathieu** [comment]
> Regarding copy logs: do you want to download a single log message or all logs for a given task? Are there no performance implications of allowing to copy all logs per task (e.g. a task with thousands of lines of logs)?

All logs for a task or a flow, this has less performance impact than from the UI as we can stream a text file (like GitHub does when your action logs are too big).

**Comment by anna-geller** [comment]
https://github.com/kestra-io/kestra/issues/2074
