### ISSUE TITLE
Contributing.md frontend config out of date

### ISSUE THREAD

**Issue by simonpic** [kestra-io/kestra#894]
### Issue description

Hey, while setting the project locally I've noticed some of the configuration steps for the frontend were out of date.
- VUE_APP_API_URL -> VITE_APP_API_URL
- npm run serve -> npm run dev

I can submit a PR if you're ok with it.

**Comment by tchiotludo** [comment]
Yes for sure PR will be appreciate! 
We move to vite few days ago and forgot this part 😬
