### ISSUE TITLE
[0.6+] Existing template return 404

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#912]
### Expected Behavior

When I go to my template list, I should be able to select one and access it.

### Actual Behaviour

When I go to my template list, I select one and it return me 404 not found

### Steps To Reproduce

On demo.kestra.io
Access to the template examples
Get 404

### Environment Information

- Kestra Version: 0.6.1-Snapshot
Tested on the kestra demo

**Comment by tchiotludo** [comment]
duplicate https://github.com/kestra-io/kestra/issues/911
