### ISSUE TITLE
JsonSchema expose static properties

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#919]
![image](https://user-images.githubusercontent.com/2064609/213941894-f3e55e18-cb5a-4f6f-a882-dad841175c64.png)

**Comment by loicmathieu** [comment]
@tchiotludo can you validate that the issue still occurs on the latest version of Kestra and the plugin ? As I cannot reproduce it locally;

**Comment by tchiotludo** [comment]
can't reproduce
