### ISSUE TITLE
Task edit : ide disappear

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#926]
Seems that remove part of the type, then part of the id, it remove the ide from the dom 

https://user-images.githubusercontent.com/2064609/214426422-55bcdb46-cf1c-4da5-af6c-eae849bf8fc3.mp4

**Comment by Melkaz** [comment]
What is that `Form` tab 🧐 ?

:-)

**Comment by tchiotludo** [comment]
done in b4fa047e77458d2f958502b98d3d566b5a829f52
