### ISSUE TITLE
Pattern annotation not detected in Interface

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#931]
### Expected Behavior

When using @Pattern in an interface property, the annotation is not detected by the PluginSchemaGenerator.

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by loicmathieu** [comment]
Unfortunatly the javax.validation annotations are not inherited so it's not easy (but always possible) to discover them.

**Comment by loicmathieu** [comment]
https://github.com/victools/jsonschema-generator/pull/299 may fix this issue.

**Comment by loicmathieu** [comment]
This is fixed by https://github.com/victools/jsonschema-generator/pull/344

**Comment by loicmathieu** [comment]
It will be fixed by https://github.com/kestra-io/kestra/pull/1185 I think we can close this issue as soon as we merge the dependabot PR
