### ISSUE TITLE
Allow continuously pushing changes to flow YAML files added locally outside of Kestra UI - CLI `--watch` flag on kestra server commands 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#939]
It can be convenient to have similar way to develop flow as front web developer: `kestra server local --watch /mydir`. 

- We watch at file systems and update all flow automatically on the ui 
- This one may also work also with a remote server

**Comment by leonlowitzki** [comment]
would be great to have this!

**Comment by Skraye** [comment]
Done, preview documentation is available here : https://github.com/kestra-io/docs/pull/1842/files#diff-ed98dd9084949a882c0d5bf29a5ea56690bf1e48f3cff4d05830b8f11bf4b1af
