### ISSUE TITLE
Documentation of property of type AbstractRetry is not correct

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#962]
### Expected Behavior

`AbstractRetry` class should generates valid documentation.

### Actual Behaviour

When using `AbstractRetry` on a plugin property, for ex in https://kestra.io/plugins/plugin-gcp/tasks/bigquery/io.kestra.plugin.gcp.bigquery.Copy.html#retryauto, the generated documentation is not correct 

![image](https://user-images.githubusercontent.com/1819009/217007740-9ebe30cd-9547-40b4-ae6e-d995b7ecd5df.png)

We can see that the `dynamic` attribute is not read correctly and the `type` is not correct.

### Environment Information

- Kestra Version: 0.6.1-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by smunteankestra** [comment]
look ok now 

![Image](https://github.com/kestra-io/kestra/assets/171780240/acd0ea47-3e8a-48a4-a606-324587c3ca77)
