### ISSUE TITLE
Docker with a timeout don't kill the container

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#973]
If a set a `timeout` on any Bash or Python with `runner: DOCKER`, if the timeout is reached, the task will be killed properly but the docker container is not killed and will continue the processus in the background. 
We should propagate the signal in order to kill properly the container

**Comment by anna-geller** [comment]
done in https://github.com/kestra-io/kestra/pull/3570

**Comment by loicmathieu** [comment]
@anna-geller on https://github.com/kestra-io/kestra/pull/3570 we pass the task timeout to "remote" taks runners that have a `waitForCompletion` property, but for the Docker task runner we did nothing.

I think this one is dependant of https://github.com/kestra-io/kestra/issues/1498 and task lifecycle method that we plan to add.
