### ISSUE TITLE
Adjust log handling in JDBC backend to be written in bulk/async rather than in real-time

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#988]
Currently, each log line is inserted in a transaction. 

The logs should be inserted in bulk & async rather than true real-time

## Problem

Currently, it's possible for some plugins e.g. Terraform CLI task, or other Script based plugins like e.g. Python, to generate a large volume of logs in the range of e.g 150k line of logs in a single task — issue reported by @aballiet: 173460 logs generated for a single execution ID (`select count(*) from logs where execution_id = 'xxx'`)

sample query to troubleshoot: 
 ```sql
SELECT JSONB_EXTRACT_PATH(value, 'message')
FROM logs
WHERE execution_id = '3pxDZcgpTx3pUBfGmjo5aI'
ORDER BY timestamp ASC
```

## Possible solutions

- Asynchronous/Batch write of logs, especially for Script tasks
- Introduce some rate limits and retries for such operations

## Workaround until then

Set the log storage to a lower level `logLevel: ERROR` to only store error logs

**Comment by anna-geller** [comment]
on ES we already batch-write

on OSS, we'll need improved indexing
