### ISSUE TITLE
Add a function to process json object

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#993]
### Feature description

Could we add a function (e.g. `startsWith`) to transform this syntax:

`"{{ outputs['my-task'].outputFiles | jq('with_entries(select(.key | startswith(\"my-folder/\")))') | first }}"`

into:
`"{{ outputs['my-task'].outputFiles | startsWith('my-folder/') | first }}"`

Thanks 🌈

**Comment by anna-geller** [comment]
done in 0.17.0 that will be released today https://develop.kestra.io/docs/concepts/expression/filter/string#startswith
